default/objects/pq_Influence__c/pq_Influence__c.object-meta.xml
<CustomObject>
    <label>Influence</label>
    <nameField>
        <label>Influence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Influence_And_Support_Matrix__c/pq_Influence_And_Support_Matrix__c.object-meta.xml
<CustomObject>
    <label>Influence And Support Matrix</label>
    <nameField>
        <label>Influence And Support Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence And Support Matrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Influence_Matrix_Association__c/pq_Influence_Matrix_Association__c.object-meta.xml
<CustomObject>
    <label>Influence value for this matrix</label>
    <nameField>
        <displayFormat>pqIM-{0000}</displayFormat>
        <label>Influence Matrix Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influence values for this matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Influence_Matrix_Association__c/fields/Influence__c.field-meta.xml
<CustomField>
    <fullName>Influence__c</fullName>
    <label>Influence</label>
    <referenceTo>pq_Influence__c</referenceTo>
    <relationshipName>Influence_Matrix_Association</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/pq_Influence_Matrix_Association__c/fields/Influence_And_Support_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Influence_And_Support_Matrix__c</fullName>
    <label>Influence And Support Matrix</label>
    <referenceTo>pq_Influence_And_Support_Matrix__c</referenceTo>
    <relationshipName>Influence_Matrix_Association</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/classes/InfluenceMatrixAssociationSelectorTest.cls
@isTest
private class InfluenceMatrixAssociationSelectorTest {
    @isTest
    static void newInstanceTest() {
        InfluenceMatrixAssociationSelector selector = InfluenceMatrixAssociationSelector.newInstance();
        System.assertNotEquals(null, selector);
    }

    @isTest
    static void selectByMatrixIdTest() {
        pq_Influence__c s1 = new pq_Influence__c(Name = 'high', Label__c = 'highlabel');
        insert s1;
        pq_Influence_And_Support_Matrix__c m1 = new pq_Influence_And_Support_Matrix__c(Name = 'one');
        insert m1;
        pq_Influence_Matrix_Association__c input1 = new pq_Influence_Matrix_Association__c(
            Order__c = 1,
            Influence__c = s1.Id,
            Influence_And_Support_Matrix__c = m1.Id
        );
        insert input1;

        Set<Id> inputSet = new Set<Id>{ m1.Id };

        Test.startTest();
        List<pq_Influence_Matrix_Association__c> result = new InfluenceMatrixAssociationSelector()
            .selectByMatrixId(inputSet);
        Test.stopTest();

        System.assertEquals(1, result.size());
        System.assertEquals(m1.Id, result[0].Influence_And_Support_Matrix__c);
        System.assertEquals(s1.Id, result[0].Influence__c);
        System.assertEquals('high', result[0].Influence__r.Name);
        System.assertEquals('highlabel', result[0].Influence__r.Label__c);
    }
}