default/objects/Account_Map_Member__c/Account_Map_Member__c.object-meta.xml
<CustomObject>
    <label>Account Map Member</label>
    <nameField>
        <displayFormat>CHM-{0000}</displayFormat>
        <label>Account Map Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Map Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Account_Map_Member__c/fields/Account_Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Account_Relationship_Map__c</fullName>
    <label>Account Relationship Map</label>
    <referenceTo>Account_Relationship_Map__c</referenceTo>
    <relationshipLabel>Account Map Members</relationshipLabel>
    <relationshipName>Account_Map_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Account_Relationship_Map__c/Account_Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Account Relationship Map</label>
    <nameField>
        <label>Account Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/AccountRelationshipMapServiceImpl.cls
public with sharing class AccountRelationshipMapServiceImpl {
    
    public List<Account_Map_Member__c> addAccountToRelationshipMap(Id relationshipMapId, Set<Id> accountIdSet) {
        System.debug('==addAccountToRelationshipMap implementataion==called');
        System.debug('==accountIdSet=='+accountIdSet);
        System.debug('==relationshipMapId=='+relationshipMapId);
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        List<Account_Map_Member__c> mapMembers = new List<Account_Map_Member__c>();

        for (Id accountId : accountIdSet) {
            Account_Map_Member__c member = new Account_Map_Member__c(
                Account_Relationship_Map__c = relationshipMapId,
                pqcrush__Account__c = accountId
            );
            System.debug('===member account=='+member);
            mapMembers.add(member);
            uow.registerNew(member);
        }
        System.debug('===mapMembers=='+mapMembers);

        uow.commitWork();

        return mapMembers;
    }
}