default/objects/Mapping_Condition__c/Mapping_Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Mapping Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Mapping_Condition__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/MappingConditionWrapper.cls
public with sharing class MappingConditionWrapper {
    @AuraEnabled
    public Boolean isFieldCreateable { get; set; }

    @AuraEnabled
    public Mapping_Condition__c singleCondition { get; set; }

    public MappingConditionWrapper() {
        this.isFieldCreateable = false;
        this.singleCondition = null;
    }

    public MappingConditionWrapper(Mapping_Condition__c singleCondition, String parentObject) {
        this.singleCondition = singleCondition;
        FieldMetadata fmd = new FieldMetadata(parentObject, singleCondition.Field__c);
        this.isFieldCreateable = fmd.isCreateable;
    }
}