default/objects/Mapping_Condition__c/Mapping_Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Mapping Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Mapping_Condition__c/fields/Condition_Group__c.field-meta.xml
<CustomField>
    <fullName>Condition_Group__c</fullName>
    <label>Condition Group</label>
    <referenceTo>Mapping_Condition_Group__c</referenceTo>
    <relationshipLabel>Conditions</relationshipLabel>
    <relationshipName>Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Mapping_Condition__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Mapping_Condition__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/MappingConditionSelector.cls
public with sharing class MappingConditionSelector extends fflib_SObjectSelector {
    public static MappingConditionSelector newInstance() {
        return (MappingConditionSelector) Application.Selector.newInstance(Mapping_Condition__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Mapping_Condition__c.Id,
            Mapping_Condition__c.Field__c,
            Mapping_Condition__c.Operator__c,
            Mapping_Condition__c.Value__c,
            Mapping_Condition__c.Condition_Group__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Mapping_Condition__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<Mapping_Condition__c> selectById(Set<ID> idSet) {
        return (List<Mapping_Condition__c>) selectSObjectsById(idSet);
    }

    public List<Mapping_Condition__c> selectByConditionGroupId(Set<ID> idSet) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        return Database.query(queryFactory.setCondition('Condition_Group__c IN :idSet').toSOQL());
    }
}