default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Auto_Layout__c.field-meta.xml
<CustomField>
    <fullName>Auto_Layout__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to have the Relationship Map automatically lay out the nodes.  Uncheck to do this manually.</description>
    <inlineHelpText>Check this to have the Relationship Map automatically lay out the nodes.  Uncheck to do this manually.</inlineHelpText>
    <label>Auto Layout</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Card_Style__c.field-meta.xml
<CustomField>
    <fullName>Card_Style__c</fullName>
    <inlineHelpText>Select the detail level of the card.</inlineHelpText>
    <label>Card Style</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detail</fullName>
            </value>
            <value>
                <fullName>Compact</fullName>
            </value>
            <value>
                <fullName>FixedSize</fullName>
                <default>true</default>
                <label>FixedSize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Display_Style__c.field-meta.xml
<CustomField>
    <fullName>Display_Style__c</fullName>
    <inlineHelpText>Select the chart display styles.  For charts that are wide, choose last parents arranging children vertically.</inlineHelpText>
    <label>Main Map Display Style</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horizontal</fullName>
                <default>true</default>
                <label>Horizontal</label>
            </value>
            <value>
                <fullName>Leaf_Vertical</fullName>
                <label>Vertical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Enable_Drag_Select__c.field-meta.xml
<CustomField>
    <fullName>Enable_Drag_Select__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option to enable drag select. To drag select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</description>
    <inlineHelpText>Check this option to enable drag select. To drag select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</inlineHelpText>
    <label>Enable Drag Select</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Badge_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Badge_Global_Scope__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When this is check, badges on contacts will persist wherever the contact is on the maps.  If unchecked, the badge will only be present for that particular map</description>
    <inlineHelpText>When this is check, badges on contacts will persist wherever the contact is on the maps.  If unchecked, the badge will only be present for that particular map</inlineHelpText>
    <label>Use Global Badges</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Group_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Group_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to create groups that are global, i.e. they will exists for any map (if the maps have the group members)</description>
    <inlineHelpText>Check this to use groups that are global (They can show up in other Relationship Maps). Leaving this uncheck will use local groups (These groups will only be visible in this Relationship Map).</inlineHelpText>
    <label>Use Global Groups</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Influence_Support_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Influence_Support_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Global Influence and Support Values</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Relationship_Line_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Relationship_Line_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to use Global Relationship Lines.  Leave this unchecked to create and use lines that are visible only in this Relationship Map</description>
    <inlineHelpText>Check this to use Global Relationship Lines.  Leave this unchecked to create and use lines that are visible only in this Relationship Map</inlineHelpText>
    <label>Use Global Relationship Lines</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Reports_To_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Reports_To_Global_Scope__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this option to use the Salesforce &apos;Reports To&apos; field.  Uncheck this and this relationship map will maintain this data locally to the chart.</description>
    <inlineHelpText>Check this option to use the Salesforce &apos;Reports To&apos; field.  Uncheck this and this relationship map will maintain this data locally to the chart.</inlineHelpText>
    <label>Use Global Reports To Field</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Line_Opacity__c</fullName>
    <description>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Relationship Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Reports_To_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Reports_To_Line_Opacity__c</fullName>
    <description>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Reports To Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Show_Empty_Fields__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want fields that have no value to show up.  For example, if users don&apos;t have an email it will show [email].  Uncheck this if you want fields that have no value to not show up.</description>
    <label>Show Empty Fields</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Show_Parents__c.field-meta.xml
<CustomField>
    <fullName>Show_Parents__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to include a node&apos;s parent node (if they have a parent)</description>
    <inlineHelpText>Check this to include a node&apos;s parent node (if they have a parent)</inlineHelpText>
    <label>Show Parents</label>
    <type>Checkbox</type>
</CustomField>

default/classes/RMChartSettingServiceTest.cls
@isTest
private class RMChartSettingServiceTest {
    @isTest
    static void getRelationshipMapSettingForObjectAccountPlanTest() {
        testMockData md = new testMockData();
        RMChartSettingSelector mockRMChartSettingSelector = md.mockRMChartSettingSelector;
        fflib_ISObjectUnitOfWork mockUow = md.mockUow; //NOPMD - Needs to be called in order for it to be mocked in the test

        md.mocks.startStubbing();
        md.mocks.when(mockRMChartSettingSelector.selectByObjectId(new Set<Id>{ md.mockAccountPlanId }))
            .thenReturn(new List<RM_Chart_Setting__c>{ md.mockRMChartSettingForAccountPlan });
        md.mocks.stopStubbing();

        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(md.mockAccountPlanId);

        System.assertEquals(md.mockRMChartSettingForAccountPlanId, setting.Id);
    }

    @isTest
    static void getRelationshipMapSettingForObjectRelationshipMapTest() {
        testMockData md = new testMockData();
        RMChartSettingSelector mockRMChartSettingSelector = md.mockRMChartSettingSelector;
        fflib_ISObjectUnitOfWork mockUow = md.mockUow; //NOPMD - Needs to be called in order for it to be mocked in the test

        md.mocks.startStubbing();
        md.mocks.when(mockRMChartSettingSelector.selectByObjectId(new Set<Id>{ md.mockRelationshipMapId }))
            .thenReturn(new List<RM_Chart_Setting__c>{ md.mockRMChartSettingForRelationshipMap });
        md.mocks.stopStubbing();

        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(
            md.mockRelationshipMapId
        );

        System.assertEquals(md.mockRMChartSettingForRelationshipMapId, setting.Id);
    }

    @isTest
    static void getRelationshipMapSettingForObjectNewSettingTest() {
        testMockData md = new testMockData();
        RMChartSettingSelector mockRMChartSettingSelector = md.mockRMChartSettingSelector;
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;

        md.mocks.startStubbing();
        md.mocks.when(
                mockRMChartSettingSelector.selectByObjectId(new Set<Id>{ md.mockRMChartSettingForRelationshipMapId })
            )
            .thenReturn(new List<RM_Chart_Setting__c>());
        md.mocks.stopStubbing();

        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(
            md.mockRMChartSettingForRelationshipMapId
        );

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 0))
            .registerNew(fflib_Match.sObjectOfType(RM_Chart_Setting__c.SObjectType));
        System.assertEquals(
            RM_Chart_Setting__c.Show_Parents__c.getDescribe().getDefaultValue(),
            setting.Show_Parents__c
        );
        System.assertEquals(
            RM_Chart_Setting__c.Show_Overview__c.getDescribe().getDefaultValue(),
            setting.Show_Overview__c
        );
    }

    @isTest
    static void getRelationshipMapSettingForObjectCreateIfNeededNewSettingTest() {
        testMockData md = new testMockData();
        RMChartSettingSelector mockRMChartSettingSelector = md.mockRMChartSettingSelector;
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;

        md.mocks.startStubbing();
        md.mocks.when(
                mockRMChartSettingSelector.selectByObjectId(new Set<Id>{ md.mockRMChartSettingForRelationshipMapId })
            )
            .thenReturn(new List<RM_Chart_Setting__c>());
        md.mocks.stopStubbing();

        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObjectCreateIfNeeded(
            md.mockRMChartSettingForRelationshipMapId
        );

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1))
            .registerNew(fflib_Match.sObjectOfType(RM_Chart_Setting__c.SObjectType));
        System.assertEquals(
            RM_Chart_Setting__c.Show_Parents__c.getDescribe().getDefaultValue(),
            setting.Show_Parents__c
        );
        System.assertEquals(
            RM_Chart_Setting__c.Show_Overview__c.getDescribe().getDefaultValue(),
            setting.Show_Overview__c
        );
    }

    @isTest
    static void getRelationshipMapSettingForObjectNewSettingFromOrgDefaultTest() {
        testMockData md = new testMockData();
        RMChartSettingSelector mockRMChartSettingSelector = md.mockRMChartSettingSelector;
        RMOrgSettingServiceImpl mockRMOrgSettingService = md.mockRMOrgSettingService;
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;

        md.mockRMOrgSettingForRM.Auto_Layout__c = false;
        md.mockRMOrgSettingForRM.Card_Style__c = 'Compact';
        md.mockRMOrgSettingForRM.Enable_Drag_Select__c = true;
        md.mockRMOrgSettingForRM.Display_Style__c = 'Leaf_Vertical';
        md.mockRMOrgSettingForRM.Relationship_Line_Opacity__c = 23;
        md.mockRMOrgSettingForRM.Reports_To_Line_Opacity__c = 46;
        md.mockRMOrgSettingForRM.Show_Empty_Fields__c = true;
        md.mockRMOrgSettingForRM.Show_Overview__c = true;
        md.mockRMOrgSettingForRM.Show_Parents__c = true;
        md.mockRMOrgSettingForRM.Is_Group_Global_Scope__c = true;
        md.mockRMOrgSettingForRM.Is_Badge_Global_Scope__c = true;
        md.mockRMOrgSettingForRM.Is_Relationship_Line_Global_Scope__c = true;
        md.mockRMOrgSettingForRM.Is_Influence_Support_Global_Scope__c = true;
        md.mockRMOrgSettingForRM.Is_Reports_To_Global_Scope__c = true;

        md.mocks.startStubbing();
        md.mocks.when(mockRMOrgSettingService.getRMOrgSetting(md.mockRelationshipMapId))
            .thenReturn(md.mockRMOrgSettingForRM);
        md.mocks.when(mockRMChartSettingSelector.selectByObjectId(new Set<Id>{ md.mockRelationshipMapId }))
            .thenReturn(new List<RM_Chart_Setting__c>());
        md.mocks.stopStubbing();

        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(
            md.mockRelationshipMapId
        );

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 0))
            .registerNew(fflib_Match.sObjectOfType(RM_Chart_Setting__c.SObjectType));

        System.assertEquals(md.mockRMOrgSettingForRM.Auto_Layout__c, setting.Auto_Layout__c);
        System.assertEquals(md.mockRMOrgSettingForRM.Card_Style__c, setting.Card_Style__c);
        System.assertEquals(md.mockRMOrgSettingForRM.Enable_Drag_Select__c, setting.Enable_Drag_Select__c);
        System.assertEquals(md.mockRMOrgSettingForRM.Display_Style__c, setting.Display_Style__c);
        System.assertEquals(
            md.mockRMOrgSettingForRM.Relationship_Line_Opacity__c,
            setting.Relationship_Line_Opacity__c
        );
        System.assertEquals(md.mockRMOrgSettingForRM.Reports_To_Line_Opacity__c, setting.Reports_To_Line_Opacity__c);
        System.assertEquals(md.mockRMOrgSettingForRM.Show_Empty_Fields__c, setting.Show_Empty_Fields__c);
        System.assertEquals(md.mockRMOrgSettingForRM.Show_Overview__c, setting.Show_Overview__c);
        System.assertEquals(md.mockRMOrgSettingForRM.Show_Parents__c, setting.Show_Parents__c);
        System.assertEquals(md.mockRMOrgSettingForRM.Is_Group_Global_Scope__c, setting.Is_Group_Global_Scope__c);
        System.assertEquals(md.mockRMOrgSettingForRM.Is_Badge_Global_Scope__c, setting.Is_Badge_Global_Scope__c);
        System.assertEquals(
            md.mockRMOrgSettingForRM.Is_Influence_Support_Global_Scope__c,
            setting.Is_Influence_Support_Global_Scope__c
        );
        System.assertEquals(
            md.mockRMOrgSettingForRM.Is_Relationship_Line_Global_Scope__c,
            setting.Is_Relationship_Line_Global_Scope__c
        );
        System.assertEquals(
            md.mockRMOrgSettingForRM.Is_Reports_To_Global_Scope__c,
            setting.Is_Reports_To_Global_Scope__c
        );
    }
}