default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Auto_Layout__c.field-meta.xml
<CustomField>
    <fullName>Auto_Layout__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to have the Relationship Map automatically lay out the nodes.  Uncheck to do this manually.</description>
    <inlineHelpText>Check this to have the Relationship Map automatically lay out the nodes.  Uncheck to do this manually.</inlineHelpText>
    <label>Auto Layout</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Card_Style__c.field-meta.xml
<CustomField>
    <fullName>Card_Style__c</fullName>
    <inlineHelpText>Select the detail level of the card.</inlineHelpText>
    <label>Card Style</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detail</fullName>
            </value>
            <value>
                <fullName>Compact</fullName>
            </value>
            <value>
                <fullName>FixedSize</fullName>
                <default>true</default>
                <label>FixedSize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Display_Style__c.field-meta.xml
<CustomField>
    <fullName>Display_Style__c</fullName>
    <inlineHelpText>Select the chart display styles.  For charts that are wide, choose last parents arranging children vertically.</inlineHelpText>
    <label>Main Map Display Style</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horizontal</fullName>
                <default>true</default>
                <label>Horizontal</label>
            </value>
            <value>
                <fullName>Leaf_Vertical</fullName>
                <label>Vertical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Enable_Drag_Select__c.field-meta.xml
<CustomField>
    <fullName>Enable_Drag_Select__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option to enable drag select. To drag select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</description>
    <inlineHelpText>Check this option to enable drag select. To drag select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</inlineHelpText>
    <label>Enable Drag Select</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Influence_Support_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Influence_Support_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Global Influence and Support Values</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This read-only field restricts any modifications or updates to the chart, effectively freezing it in its current state.</description>
    <inlineHelpText>This read-only field restricts any modifications or updates to the chart, effectively freezing it in its current state.</inlineHelpText>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Line_Opacity__c</fullName>
    <description>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Relationship Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Reports_To_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Reports_To_Line_Opacity__c</fullName>
    <description>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Reports To Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Show_Empty_Fields__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want fields that have no value to show up.  For example, if users don&apos;t have an email it will show [email].  Uncheck this if you want fields that have no value to not show up.</description>
    <label>Show Empty Fields</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Show_Parents__c.field-meta.xml
<CustomField>
    <fullName>Show_Parents__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to include a node&apos;s parent node (if they have a parent)</description>
    <inlineHelpText>Check this to include a node&apos;s parent node (if they have a parent)</inlineHelpText>
    <label>Show Parents</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/RM_Org_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Org Setting</label>
    <nameField>
        <label>RM_Org_Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM_Org_Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Org_Setting__c/fields/Auto_Layout__c.field-meta.xml
<CustomField>
    <fullName>Auto_Layout__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to have the Relationship Map automatically layout the nodes. Uncheck to do this manually.</description>
    <inlineHelpText>Check this to have the Relationship Map automatically layout the nodes. Uncheck to do this manually.</inlineHelpText>
    <label>Auto Layout</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Card_Style__c.field-meta.xml
<CustomField>
    <fullName>Card_Style__c</fullName>
    <description>Select the detail level of the card.</description>
    <inlineHelpText>Select the detail level of the card.</inlineHelpText>
    <label>Card Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detail</fullName>
            </value>
            <value>
                <fullName>Compact</fullName>
            </value>
            <value>
                <fullName>FixedSize</fullName>
                <default>true</default>
                <label>FixedSize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Create_New_Contact__c.field-meta.xml
<CustomField>
    <fullName>Create_New_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Create New Contact</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Display_Style__c.field-meta.xml
<CustomField>
    <fullName>Display_Style__c</fullName>
    <description>Select the chart display styles. For charts that are wide, choose the last parents arranging children vertically.</description>
    <inlineHelpText>Select the chart display styles. For charts that are wide, choose the last parents arranging children vertically.</inlineHelpText>
    <label>Display Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horizontal</fullName>
                <default>true</default>
                <label>Horizontal</label>
            </value>
            <value>
                <fullName>Leaf_Vertical</fullName>
                <label>Vertical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Drag_Select__c.field-meta.xml
<CustomField>
    <fullName>Enable_Drag_Select__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option to enable drag-select. To drag-select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</description>
    <inlineHelpText>Check this option to enable drag-select. To drag-select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</inlineHelpText>
    <label>Enable Drag Select</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Is_Influence_Support_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Influence_Support_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Influence Support Global Scope</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Relationship_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Line_Opacity__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Relationship Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Reports_To_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Reports_To_Line_Opacity__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Reports To Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Chart_Settings__c.field-meta.xml
<CustomField>
    <fullName>Show_Chart_Settings__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked then the settings button in the dropdown menu of key stakeholder/relationship maps will show based on user permissions.  If unchecked this will hide the button regardless of any permissions for users to see the settings button.</description>
    <inlineHelpText>If this is unchecked then no users in the org will see the settings button in the key stakeholder/relationship map dropdown menu regardless of what permissions they have set for showing the button.  This is org wide.</inlineHelpText>
    <label>Show Chart Settings</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Clone_Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Show_Clone_Relationship_Map__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked then the clone button in the dropdown menu of relationship maps will show based on user permissions.  If unchecked this will hide the button regardless of any permissions for users to see the clone button.</description>
    <inlineHelpText>If this is unchecked then no users in the org will see the clone button in the relationship map dropdown menu regardless of what permissions they have set for showing the button.  This is org wide.</inlineHelpText>
    <label>Show Clone Relationship Map</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Empty_Fields__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want fields that have no value to show up. For example, if users don&apos;t have an email it will show [email]. Uncheck this if you want fields that have no value to not show up.</description>
    <inlineHelpText>Check this if you want fields that have no value to show up. For example, if users don&apos;t have an email it will show [email]. Uncheck this if you want fields that have no value to not show up.</inlineHelpText>
    <label>Show Empty Fields</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Overview__c.field-meta.xml
<CustomField>
    <fullName>Show_Overview__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to display an overview that users can pan around to see the whole relationship map</description>
    <inlineHelpText>Check this to display an overview that users can pan around to see the whole relationship map</inlineHelpText>
    <label>Show Overview</label>
    <type>Checkbox</type>
</CustomField>

default/classes/RMChartSettingsWrapper.cls
@SuppressWarnings('PMD.CyclomaticComplexity,PMD.ExcessivePublicCount,PMD.TooManyFields')
public with sharing class RMChartSettingsWrapper {
    @AuraEnabled
    public String id;
    @AuraEnabled
    public Boolean showOverview;
    @AuraEnabled
    public String cardStyle;
    @AuraEnabled
    public String displayStyle;
    @AuraEnabled
    public Boolean showParent;
    @AuraEnabled
    public Boolean enableDragSelect;
    @AuraEnabled
    public Boolean autoLayout;
    @AuraEnabled
    public Boolean readOnly;
    @AuraEnabled
    public Boolean showEmptyFields;
    @AuraEnabled
    public Double relationshipLineOpacity;
    @AuraEnabled
    public Double reportsToLineOpacity;
    @AuraEnabled
    public Boolean createNewContact;
    @AuraEnabled
    public Boolean isInfluenceSupportGlobal;
    @AuraEnabled
    public Boolean isCloneEnabled;
    @AuraEnabled
    public Boolean isSettingsEnabled;
    @AuraEnabled
    public Boolean userCanClone;
    @AuraEnabled
    public Boolean userCanAccessSettings;

    private RM_Chart_Setting__c baseChartSettings;
    private RM_Org_Setting__c baseOrgSettings;

    public RMChartSettingsWrapper() {
        this(null, null);
    }

    public RMChartSettingsWrapper(RM_Chart_Setting__c setting, RM_Org_Setting__c orgSetting) {
        this.id = setting?.Id;
        this.showOverview = setting?.Show_Overview__c == null ? false : setting.Show_Overview__c;
        this.cardStyle = setting?.Card_Style__c == null ? 'Detail' : setting.Card_Style__c;
        this.displayStyle = setting?.Display_Style__c == null ? 'Horizontal' : setting.Display_Style__c;
        this.showParent = setting?.Show_Parents__c == null ? false : setting.Show_Parents__c;
        this.enableDragSelect = setting?.Enable_Drag_Select__c == null ? false : setting.Enable_Drag_Select__c;
        this.autoLayout = setting?.Auto_Layout__c == null ? true : setting.Auto_Layout__c;
        this.readOnly = setting?.Read_Only__c == null ? true : setting.Read_Only__c;
        this.showEmptyFields = setting?.Show_Empty_Fields__c == null ? false : setting.Show_Empty_Fields__c;
        this.relationshipLineOpacity = setting?.Relationship_Line_Opacity__c == null
            ? 1
            : setting.Relationship_Line_Opacity__c / 100;
        this.reportsToLineOpacity = setting?.Reports_To_Line_Opacity__c == null
            ? 1
            : setting.Reports_To_Line_Opacity__c / 100;
        this.createNewContact = orgSetting?.Create_New_Contact__c == null ? true : orgSetting.Create_New_Contact__c;
        this.isInfluenceSupportGlobal = setting?.Is_Influence_Support_Global_Scope__c == null
            ? false
            : setting.Is_Influence_Support_Global_Scope__c;
        this.isCloneEnabled = orgSetting?.Show_Clone_Relationship_Map__c == null
            ? true
            : orgSetting.Show_Clone_Relationship_Map__c;
        this.isSettingsEnabled = orgSetting?.Show_Chart_Settings__c == null ? true : orgSetting.Show_Chart_Settings__c;
        this.baseChartSettings = setting;
        this.baseOrgSettings = orgSetting;
        this.userCanClone = FeatureManagement.checkPermission('pqcrush__Can_See_Chart_Clone_Button');
        this.userCanAccessSettings = FeatureManagement.checkPermission('pqcrush__Can_See_Chart_Settings');
    }

    public RM_Chart_Setting__c toChartSettings() {
        if (baseChartSettings == null) {
            baseChartSettings = new RM_Chart_Setting__c();
        }
        baseChartSettings.Show_Overview__c = showOverview;
        baseChartSettings.Card_Style__c = cardStyle;
        baseChartSettings.Display_Style__c = displayStyle;
        baseChartSettings.Show_Parents__c = showParent;
        baseChartSettings.Enable_Drag_Select__c = enableDragSelect;
        baseChartSettings.Auto_Layout__c = autoLayout;
        baseChartSettings.Show_Empty_Fields__c = showEmptyFields;
        baseChartSettings.Relationship_Line_Opacity__c = relationshipLineOpacity * 100;
        baseChartSettings.Reports_To_Line_Opacity__c = reportsToLineOpacity * 100;
        return baseChartSettings;
    }

    public RM_Org_Setting__c toOrgSettings() {
        if (baseOrgSettings == null) {
            baseOrgSettings = new RM_Org_Setting__c();
        }
        baseOrgSettings.Create_New_Contact__c = createNewContact;
        baseOrgSettings.Show_Clone_Relationship_Map__c = isCloneEnabled;
        baseOrgSettings.Show_Chart_Settings__c = isSettingsEnabled;
        return baseOrgSettings;
    }
}