default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Card_Style__c.field-meta.xml
<CustomField>
    <fullName>Card_Style__c</fullName>
    <inlineHelpText>Select the detail level of the card.</inlineHelpText>
    <label>Card Style</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detail</fullName>
            </value>
            <value>
                <fullName>Compact</fullName>
            </value>
            <value>
                <fullName>FixedSize</fullName>
                <default>true</default>
                <label>FixedSize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Display_Style__c.field-meta.xml
<CustomField>
    <fullName>Display_Style__c</fullName>
    <inlineHelpText>Select the chart display styles.  For charts that are wide, choose last parents arranging children vertically.</inlineHelpText>
    <label>Main Map Display Style</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horizontal</fullName>
                <default>true</default>
                <label>Horizontal</label>
            </value>
            <value>
                <fullName>Leaf_Vertical</fullName>
                <label>Vertical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Enable_Drag_Select__c.field-meta.xml
<CustomField>
    <fullName>Enable_Drag_Select__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option to enable drag select. To drag select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</description>
    <inlineHelpText>Check this option to enable drag select. To drag select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</inlineHelpText>
    <label>Enable Drag Select</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Badge_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Badge_Global_Scope__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When this is check, badges on contacts will persist wherever the contact is on the maps.  If unchecked, the badge will only be present for that particular map</description>
    <inlineHelpText>When this is check, badges on contacts will persist wherever the contact is on the maps.  If unchecked, the badge will only be present for that particular map</inlineHelpText>
    <label>Use Global Badges</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Group_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Group_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to create groups that are global, i.e. they will exists for any map (if the maps have the group members)</description>
    <inlineHelpText>Check this to use groups that are global (They can show up in other Relationship Maps). Leaving this uncheck will use local groups (These groups will only be visible in this Relationship Map).</inlineHelpText>
    <label>Use Global Groups</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Relationship_Line_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Relationship_Line_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to use Global Relationship Lines.  Leave this unchecked to create and use lines that are visible only in this Relationship Map</description>
    <inlineHelpText>Check this to use Global Relationship Lines.  Leave this unchecked to create and use lines that are visible only in this Relationship Map</inlineHelpText>
    <label>Use Global Relationship Lines</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Line_Opacity__c</fullName>
    <description>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Relationship Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Reports_To_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Reports_To_Line_Opacity__c</fullName>
    <description>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Reports To Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Show_Empty_Fields__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want fields that have no value to show up.  For example, if users don&apos;t have an email it will show [email].  Uncheck this if you want fields that have no value to not show up.</description>
    <label>Show Empty Fields</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Show_Parents__c.field-meta.xml
<CustomField>
    <fullName>Show_Parents__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to include a node&apos;s parent node (if they have a parent)</description>
    <inlineHelpText>Check this to include a node&apos;s parent node (if they have a parent)</inlineHelpText>
    <label>Show Parents</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/RM_Org_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Org Setting</label>
    <nameField>
        <label>RM_Org_Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM_Org_Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Org_Setting__c/fields/Display_Style__c.field-meta.xml
<CustomField>
    <fullName>Display_Style__c</fullName>
    <description>Select the chart display styles. For charts that are wide, choose the last parents arranging children vertically.</description>
    <inlineHelpText>Select the chart display styles. For charts that are wide, choose the last parents arranging children vertically.</inlineHelpText>
    <label>Display Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horizontal</fullName>
                <default>true</default>
                <label>Horizontal</label>
            </value>
            <value>
                <fullName>Leaf_Vertical</fullName>
                <label>Vertical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Drag_Select__c.field-meta.xml
<CustomField>
    <fullName>Enable_Drag_Select__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option to enable drag-select. To drag-select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</description>
    <inlineHelpText>Check this option to enable drag-select. To drag-select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</inlineHelpText>
    <label>Enable Drag Select</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Is_Badge_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Badge_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check to associate a badge with the contact regardless of which map the contact is on</description>
    <inlineHelpText>Check to associate a badge with the contact regardless of which map the contact is on.</inlineHelpText>
    <label>Is Badge Global Scope</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Is_Group_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Group_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to use groups that are global (They can show up in other Relationship Maps). Leaving this unchecked will use local groups (These groups will only be visible in this Relationship Map).</description>
    <inlineHelpText>Check this to use groups that are global (They can show up in other Relationship Maps). Leaving this unchecked will use local groups (These groups will only be visible in this Relationship Map).</inlineHelpText>
    <label>Is Group Global Scope</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Is_Relationship_Line_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Relationship_Line_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to use Global Relationship Lines. Leave this unchecked to create and use lines that are visible only in this Relationship Map</description>
    <inlineHelpText>Check this to use Global Relationship Lines. Leave this unchecked to create and use lines that are visible only in this Relationship Map</inlineHelpText>
    <label>Is Relationship Line Global Scope</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Relationship_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Line_Opacity__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Relationship Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Reports_To_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Reports_To_Line_Opacity__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Reports To Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Empty_Fields__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want fields that have no value to show up. For example, if users don&apos;t have an email it will show [email]. Uncheck this if you want fields that have no value to not show up.</description>
    <inlineHelpText>Check this if you want fields that have no value to show up. For example, if users don&apos;t have an email it will show [email]. Uncheck this if you want fields that have no value to not show up.</inlineHelpText>
    <label>Show Empty Fields</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Overview__c.field-meta.xml
<CustomField>
    <fullName>Show_Overview__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to display an overview that users can pan around to see the whole relationship map</description>
    <inlineHelpText>Check this to display an overview that users can pan around to see the whole relationship map</inlineHelpText>
    <label>Show Overview</label>
    <type>Checkbox</type>
</CustomField>

default/classes/RMChartSettingServiceImpl.cls
@SuppressWarnings('PMD.CyclomaticComplexity')
public with sharing class RMChartSettingServiceImpl {
    private static Map<Id, RM_Chart_Setting__c> settingsCache = new Map<Id, RM_Chart_Setting__c>();
    /******************************
     *      PUBLIC METHODS
     ******************************/

    public RM_Chart_Setting__c getRelationshipMapSettingForObject(Id objectId) {
        if (settingsCache.containsKey(objectId)) {
            return settingsCache.get(objectId);
        }
        Map<Id, RM_Chart_Setting__c> settings = getRelationshipMapSettingForObjects(new Set<Id>{ objectId }, false);
        RM_Chart_Setting__c setting = settings.get(objectId);
        settingsCache.put(objectId, setting);
        return setting;
    }

    public RM_Chart_Setting__c getRelationshipMapSettingForObjectCreateIfNeeded(Id objectId) {
        if (settingsCache.containsKey(objectId)) {
            return settingsCache.get(objectId);
        }
        Map<Id, RM_Chart_Setting__c> settings = getRelationshipMapSettingForObjects(new Set<Id>{ objectId }, true);
        RM_Chart_Setting__c setting = settings.get(objectId);
        settingsCache.put(objectId, setting);
        return setting;
    }

    public Map<Id, RM_Chart_Setting__c> getRelationshipMapSettingForObjects(Set<Id> objectIds, Boolean insertOnCreate) {
        List<RM_Chart_Setting__c> settings = RMChartSettingSelector.newInstance().selectByObjectId(objectIds);

        Map<Id, RM_Chart_Setting__c> result = new Map<Id, RM_Chart_Setting__c>();

        for (RM_Chart_Setting__c setting : settings) {
            if (setting.Relationship_Map__c != null) {
                result.put(setting.Relationship_Map__c, setting);
            } else if (setting.Account_Plan__c != null) {
                result.put(setting.Account_Plan__c, setting);
            }
        }

        for (Id objId : objectIds) {
            if (!result.containsKey(objId)) {
                result.put(objId, createSettingForObject(objId, insertOnCreate));
            }
        }

        return result;
    }

    private RM_Chart_Setting__c createSettingForObject(Id objectId, Boolean shouldInsert) {
        // IF SETTINGS DOESN'T EXISTS, CREATE ONE
        Id accountPlanId = null;
        Id relationshipMapId = null;

        if (objectId != null) {
            if (objectId.getSobjectType() == Account_Plan__c.SObjectType) {
                accountPlanId = objectId;
            } else if (objectId.getSobjectType() == Relationship_Map__c.SObjectType) {
                relationshipMapId = objectId;
            }
        }

        // Get Crush Settings (default values for creating new settings)
        RM_Org_Setting__c orgSettings = RMOrgSettingService.getRMOrgSetting(objectId);

        RM_Chart_Setting__c setting = (RM_Chart_Setting__c) RM_Chart_Setting__c.sObjectType.newSObject(null, true);

        setting.Account_Plan__c = accountPlanId;
        setting.Relationship_Map__c = relationshipMapId;
        setting.Description__c = System.Label.Relationship_Map_Chart_Description;

        setting = this.populateDefaultValues(setting, orgSettings);

        if (shouldInsert) {
            fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
            uow.registerNew(setting);
            uow.commitWork();
        }

        return setting;
    }

    private RM_Chart_Setting__c populateDefaultValues(RM_Chart_Setting__c setting, RM_Org_Setting__c orgSettings) {
        if (orgSettings == null) {
            return setting;
        }

        setting.Relationship_Line_Opacity__c = (orgSettings.Relationship_Line_Opacity__c != null)
            ? orgSettings.Relationship_Line_Opacity__c
            : setting.Relationship_Line_Opacity__c;
        setting.Reports_To_Line_Opacity__c = (orgSettings.Reports_To_Line_Opacity__c != null)
            ? orgSettings.Reports_To_Line_Opacity__c
            : setting.Reports_To_Line_Opacity__c;
        setting.Show_Empty_Fields__c = (orgSettings.Show_Empty_Fields__c != null)
            ? orgSettings.Show_Empty_Fields__c
            : setting.Show_Empty_Fields__c;
        setting.Show_Overview__c = (orgSettings.Show_Overview__c != null)
            ? orgSettings.Show_Overview__c
            : setting.Show_Overview__c;
        setting.Show_Parents__c = (orgSettings.Show_Parents__c != null)
            ? orgSettings.Show_Parents__c
            : setting.Show_Parents__c;
        setting.Is_Group_Global_Scope__c = (orgSettings.Is_Group_Global_Scope__c != null)
            ? orgSettings.Is_Group_Global_Scope__c
            : setting.Is_Group_Global_Scope__c;
        setting.Is_Badge_Global_Scope__c = (orgSettings.Is_Badge_Global_Scope__c != null)
            ? orgSettings.Is_Badge_Global_Scope__c
            : setting.Is_Badge_Global_Scope__c;
        setting.Is_Relationship_Line_Global_Scope__c = (orgSettings.Is_Relationship_Line_Global_Scope__c != null)
            ? orgSettings.Is_Relationship_Line_Global_Scope__c
            : setting.Is_Relationship_Line_Global_Scope__c;
        setting.Display_Style__c = (orgSettings.Display_Style__c != null)
            ? orgSettings.Display_Style__c
            : setting.Display_Style__c;
        setting.Enable_Drag_Select__c = (orgSettings.Enable_Drag_Select__c != null)
            ? orgSettings.Enable_Drag_Select__c
            : setting.Enable_Drag_Select__c;
        setting.Card_Style__c = (orgSettings.Card_Style__c != null) ? orgSettings.Card_Style__c : setting.Card_Style__c;
        setting.Auto_Layout__c = (orgSettings.Auto_Layout__c != null)
            ? orgSettings.Auto_Layout__c
            : setting.Auto_Layout__c;
        setting.Is_Influence_Support_Global_Scope__c = (orgSettings.Is_Influence_Support_Global_Scope__c != null)
            ? orgSettings.Is_Influence_Support_Global_Scope__c
            : setting.Is_Influence_Support_Global_Scope__c;
        setting.Is_Reports_To_Global_Scope__c = (orgSettings.Is_Reports_To_Global_Scope__c != null)
            ? orgSettings.Is_Reports_To_Global_Scope__c
            : setting.Is_Reports_To_Global_Scope__c;
        return setting;
    }
}