default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Auto_Layout__c.field-meta.xml
<CustomField>
    <fullName>Auto_Layout__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to have the Relationship Map automatically lay out the nodes.  Uncheck to do this manually.</description>
    <inlineHelpText>Check this to have the Relationship Map automatically lay out the nodes.  Uncheck to do this manually.</inlineHelpText>
    <label>Auto Layout</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Card_Style__c.field-meta.xml
<CustomField>
    <fullName>Card_Style__c</fullName>
    <inlineHelpText>Select the detail level of the card.</inlineHelpText>
    <label>Card Style</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detail</fullName>
            </value>
            <value>
                <fullName>Compact</fullName>
            </value>
            <value>
                <fullName>FixedSize</fullName>
                <default>true</default>
                <label>FixedSize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Display_Style__c.field-meta.xml
<CustomField>
    <fullName>Display_Style__c</fullName>
    <inlineHelpText>Select the chart display styles.  For charts that are wide, choose last parents arranging children vertically.</inlineHelpText>
    <label>Main Map Display Style</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horizontal</fullName>
                <default>true</default>
                <label>Horizontal</label>
            </value>
            <value>
                <fullName>Leaf_Vertical</fullName>
                <label>Vertical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Enable_Drag_Select__c.field-meta.xml
<CustomField>
    <fullName>Enable_Drag_Select__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option to enable drag select. To drag select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</description>
    <inlineHelpText>Check this option to enable drag select. To drag select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</inlineHelpText>
    <label>Enable Drag Select</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Influence_Support_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Influence_Support_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Global Influence and Support Values</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Line_Opacity__c</fullName>
    <description>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Relationship Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Reports_To_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Reports_To_Line_Opacity__c</fullName>
    <description>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Reports To Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Show_Empty_Fields__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want fields that have no value to show up.  For example, if users don&apos;t have an email it will show [email].  Uncheck this if you want fields that have no value to not show up.</description>
    <label>Show Empty Fields</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Show_Parents__c.field-meta.xml
<CustomField>
    <fullName>Show_Parents__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to include a node&apos;s parent node (if they have a parent)</description>
    <inlineHelpText>Check this to include a node&apos;s parent node (if they have a parent)</inlineHelpText>
    <label>Show Parents</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/RM_Org_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Org Setting</label>
    <nameField>
        <label>RM_Org_Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM_Org_Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Org_Setting__c/fields/Auto_Layout__c.field-meta.xml
<CustomField>
    <fullName>Auto_Layout__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to have the Relationship Map automatically layout the nodes. Uncheck to do this manually.</description>
    <inlineHelpText>Check this to have the Relationship Map automatically layout the nodes. Uncheck to do this manually.</inlineHelpText>
    <label>Auto Layout</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Card_Style__c.field-meta.xml
<CustomField>
    <fullName>Card_Style__c</fullName>
    <description>Select the detail level of the card.</description>
    <inlineHelpText>Select the detail level of the card.</inlineHelpText>
    <label>Card Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detail</fullName>
            </value>
            <value>
                <fullName>Compact</fullName>
            </value>
            <value>
                <fullName>FixedSize</fullName>
                <default>true</default>
                <label>FixedSize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Create_New_Contact__c.field-meta.xml
<CustomField>
    <fullName>Create_New_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Create New Contact</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Display_Style__c.field-meta.xml
<CustomField>
    <fullName>Display_Style__c</fullName>
    <description>Select the chart display styles. For charts that are wide, choose the last parents arranging children vertically.</description>
    <inlineHelpText>Select the chart display styles. For charts that are wide, choose the last parents arranging children vertically.</inlineHelpText>
    <label>Display Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horizontal</fullName>
                <default>true</default>
                <label>Horizontal</label>
            </value>
            <value>
                <fullName>Leaf_Vertical</fullName>
                <label>Vertical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Drag_Select__c.field-meta.xml
<CustomField>
    <fullName>Enable_Drag_Select__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option to enable drag-select. To drag-select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</description>
    <inlineHelpText>Check this option to enable drag-select. To drag-select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</inlineHelpText>
    <label>Enable Drag Select</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Is_Influence_Support_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Influence_Support_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Influence Support Global Scope</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Relationship_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Line_Opacity__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Relationship Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Reports_To_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Reports_To_Line_Opacity__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Reports To Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Chart_Settings__c.field-meta.xml
<CustomField>
    <fullName>Show_Chart_Settings__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked then the settings button in the dropdown menu of key stakeholder/relationship maps will show based on user permissions.  If unchecked this will hide the button regardless of any permissions for users to see the settings button.</description>
    <inlineHelpText>If this is unchecked then no users in the org will see the settings button in the key stakeholder/relationship map dropdown menu regardless of what permissions they have set for showing the button.  This is org wide.</inlineHelpText>
    <label>Show Chart Settings</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Clone_Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Show_Clone_Relationship_Map__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked then the clone button in the dropdown menu of relationship maps will show based on user permissions.  If unchecked this will hide the button regardless of any permissions for users to see the clone button.</description>
    <inlineHelpText>If this is unchecked then no users in the org will see the clone button in the relationship map dropdown menu regardless of what permissions they have set for showing the button.  This is org wide.</inlineHelpText>
    <label>Show Clone Relationship Map</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Empty_Fields__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want fields that have no value to show up. For example, if users don&apos;t have an email it will show [email]. Uncheck this if you want fields that have no value to not show up.</description>
    <inlineHelpText>Check this if you want fields that have no value to show up. For example, if users don&apos;t have an email it will show [email]. Uncheck this if you want fields that have no value to not show up.</inlineHelpText>
    <label>Show Empty Fields</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Overview__c.field-meta.xml
<CustomField>
    <fullName>Show_Overview__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to display an overview that users can pan around to see the whole relationship map</description>
    <inlineHelpText>Check this to display an overview that users can pan around to see the whole relationship map</inlineHelpText>
    <label>Show Overview</label>
    <type>Checkbox</type>
</CustomField>

default/classes/RMChartSettingsWrapperTest.cls
@isTest
private class RMChartSettingsWrapperTest {
    @isTest
    static void basicInitTest() {
        RMChartSettingsWrapper wrapper = new RMChartSettingsWrapper();
        System.assertEquals(false, wrapper.showOverview);
        System.assertEquals('Detail', wrapper.cardStyle);
        System.assertEquals('Horizontal', wrapper.displayStyle);
        System.assertEquals(false, wrapper.showParent);
        System.assertEquals(false, wrapper.enableDragSelect);
        System.assertEquals(true, wrapper.autoLayout);
        System.assertEquals(false, wrapper.showEmptyFields);
        System.assertEquals(1, wrapper.relationshipLineOpacity);
        System.assertEquals(1, wrapper.reportsToLineOpacity);
        System.assertEquals(true, wrapper.createNewContact);
        System.assertEquals(false, wrapper.isInfluenceSupportGlobal);
        System.assertEquals(true, wrapper.isCloneEnabled);
        System.assertEquals(true, wrapper.isSettingsEnabled);
    }

    @isTest
    static void initNullObjectsTest() {
        RMChartSettingsWrapper wrapper = new RMChartSettingsWrapper(null, null);
        System.assertEquals(false, wrapper.showOverview);
        System.assertEquals('Detail', wrapper.cardStyle);
        System.assertEquals('Horizontal', wrapper.displayStyle);
        System.assertEquals(false, wrapper.showParent);
        System.assertEquals(false, wrapper.enableDragSelect);
        System.assertEquals(true, wrapper.autoLayout);
        System.assertEquals(false, wrapper.showEmptyFields);
        System.assertEquals(1, wrapper.relationshipLineOpacity);
        System.assertEquals(1, wrapper.reportsToLineOpacity);
        System.assertEquals(true, wrapper.createNewContact);
        System.assertEquals(false, wrapper.isInfluenceSupportGlobal);
        System.assertEquals(true, wrapper.isCloneEnabled);
        System.assertEquals(true, wrapper.isSettingsEnabled);
    }

    @isTest
    static void initEmptyObjectsTest() {
        RMChartSettingsWrapper wrapper = new RMChartSettingsWrapper(new RM_Chart_Setting__c(), new RM_Org_Setting__c());
        System.assertEquals(false, wrapper.showOverview);
        System.assertEquals('Detail', wrapper.cardStyle);
        System.assertEquals('Horizontal', wrapper.displayStyle);
        System.assertEquals(false, wrapper.showParent);
        System.assertEquals(false, wrapper.enableDragSelect);
        System.assertEquals(false, wrapper.autoLayout); //Object initializes with false not null
        System.assertEquals(false, wrapper.showEmptyFields);
        System.assertEquals(1, wrapper.relationshipLineOpacity);
        System.assertEquals(1, wrapper.reportsToLineOpacity);
        System.assertEquals(false, wrapper.createNewContact); //Object initializes with false not null
        System.assertEquals(false, wrapper.isInfluenceSupportGlobal);
        System.assertEquals(false, wrapper.isCloneEnabled); //Object empty initializes with false not true
        System.assertEquals(false, wrapper.isSettingsEnabled); //Object empty initializes with false not true
    }

    @isTest
    static void initValidObjectsTest() {
        TestMockData md = new TestMockData();
        md.mockRMChartSettingForAccountPlan.Show_Overview__c = true;
        md.mockRMChartSettingForAccountPlan.Card_Style__c = 'Expanded';
        md.mockRMChartSettingForAccountPlan.Display_Style__c = 'Vertical';
        md.mockRMChartSettingForAccountPlan.Show_Parents__c = true;
        md.mockRMChartSettingForAccountPlan.Enable_Drag_Select__c = true;
        md.mockRMChartSettingForAccountPlan.Auto_Layout__c = false;
        md.mockRMChartSettingForAccountPlan.Show_Empty_Fields__c = true;
        md.mockRMChartSettingForAccountPlan.Relationship_Line_Opacity__c = .5;
        md.mockRMChartSettingForAccountPlan.Reports_To_Line_Opacity__c = .5;
        md.mockRMChartSettingForAccountPlan.Is_Influence_Support_Global_Scope__c = true;

        md.mockRMOrgSettingForAccountPlan.Create_New_Contact__c = false;
        md.mockRMOrgSettingForAccountPlan.Show_Clone_Relationship_Map__c = true;
        md.mockRMOrgSettingForAccountPlan.Show_Chart_Settings__c = false;

        RMChartSettingsWrapper wrapper = new RMChartSettingsWrapper(
            md.mockRMChartSettingForAccountPlan,
            md.mockRMOrgSettingForAccountPlan
        );
        System.assertEquals(md.mockRMChartSettingForAccountPlan.Show_Overview__c, wrapper.showOverview);
        System.assertEquals(md.mockRMChartSettingForAccountPlan.Card_Style__c, wrapper.cardStyle);
        System.assertEquals(md.mockRMChartSettingForAccountPlan.Display_Style__c, wrapper.displayStyle);
        System.assertEquals(md.mockRMChartSettingForAccountPlan.Show_Parents__c, wrapper.showParent);
        System.assertEquals(md.mockRMChartSettingForAccountPlan.Enable_Drag_Select__c, wrapper.enableDragSelect);
        System.assertEquals(md.mockRMChartSettingForAccountPlan.Auto_Layout__c, wrapper.autoLayout);
        System.assertEquals(md.mockRMChartSettingForAccountPlan.Show_Empty_Fields__c, wrapper.showEmptyFields);
        System.assertEquals(
            md.mockRMChartSettingForAccountPlan.Relationship_Line_Opacity__c / 100,
            wrapper.relationshipLineOpacity
        );
        System.assertEquals(
            md.mockRMChartSettingForAccountPlan.Reports_To_Line_Opacity__c / 100,
            wrapper.reportsToLineOpacity
        );
        System.assertEquals(md.mockRMOrgSettingForAccountPlan.Create_New_Contact__c, wrapper.createNewContact);
        System.assertEquals(
            md.mockRMChartSettingForAccountPlan.Is_Influence_Support_Global_Scope__c,
            wrapper.isInfluenceSupportGlobal
        );
        System.assertEquals(md.mockRMOrgSettingForAccountPlan.Show_Clone_Relationship_Map__c, wrapper.isCloneEnabled);
        System.assertEquals(md.mockRMOrgSettingForAccountPlan.Show_Chart_Settings__c, wrapper.isSettingsEnabled);
    }

    @isTest
    static void toChartSettingsNullChartObjTest() {
        RMChartSettingsWrapper wrapper = new RMChartSettingsWrapper();
        wrapper.showOverview = true;
        wrapper.cardStyle = 'Expanded';
        wrapper.displayStyle = 'Vertical';
        wrapper.showParent = true;
        wrapper.enableDragSelect = true;
        wrapper.autoLayout = false;
        wrapper.showEmptyFields = true;
        wrapper.relationshipLineOpacity = .5;
        wrapper.reportsToLineOpacity = .5;

        RM_Chart_Setting__c chartSetting = wrapper.toChartSettings();
        System.assertEquals(true, chartSetting.Show_Overview__c);
        System.assertEquals('Expanded', chartSetting.Card_Style__c);
        System.assertEquals('Vertical', chartSetting.Display_Style__c);
        System.assertEquals(true, chartSetting.Show_Parents__c);
        System.assertEquals(true, chartSetting.Enable_Drag_Select__c);
        System.assertEquals(false, chartSetting.Auto_Layout__c);
        System.assertEquals(true, chartSetting.Show_Empty_Fields__c);
        System.assertEquals(50, chartSetting.Relationship_Line_Opacity__c);
        System.assertEquals(50, chartSetting.Reports_To_Line_Opacity__c);
        System.assertEquals(null, chartSetting.Id);
    }

    @isTest
    static void toChartSettingsTest() {
        TestMockData md = new TestMockData();

        md.mockRMChartSettingForAccountPlan.Show_Overview__c = true;
        md.mockRMChartSettingForAccountPlan.Card_Style__c = 'Expanded';
        md.mockRMChartSettingForAccountPlan.Display_Style__c = 'Vertical';
        md.mockRMChartSettingForAccountPlan.Show_Parents__c = true;
        md.mockRMChartSettingForAccountPlan.Enable_Drag_Select__c = true;
        md.mockRMChartSettingForAccountPlan.Auto_Layout__c = false;
        md.mockRMChartSettingForAccountPlan.Show_Empty_Fields__c = true;
        md.mockRMChartSettingForAccountPlan.Relationship_Line_Opacity__c = .5;
        md.mockRMChartSettingForAccountPlan.Reports_To_Line_Opacity__c = .5;

        RMChartSettingsWrapper wrapper = new RMChartSettingsWrapper(
            md.mockRMChartSettingForAccountPlan,
            md.mockRMOrgSettingForAccountPlan
        );

        RM_Chart_Setting__c returnedSettings = wrapper.toChartSettings();
        System.assertEquals(md.mockRMChartSettingForAccountPlan, returnedSettings);
    }

    @isTest
    static void toOrgSettingsNullOrgObjTest() {
        RMChartSettingsWrapper wrapper = new RMChartSettingsWrapper();
        wrapper.createNewContact = false;
        wrapper.isCloneEnabled = true;
        wrapper.isSettingsEnabled = false;

        RM_Org_Setting__c orgSetting = wrapper.toOrgSettings();
        System.assertEquals(false, orgSetting.Create_New_Contact__c);
        System.assertEquals(wrapper.isCloneEnabled, orgSetting.Show_Clone_Relationship_Map__c);
        System.assertEquals(wrapper.isSettingsEnabled, orgSetting.Show_Chart_Settings__c);
        System.assertEquals(null, orgSetting.Id);
    }

    @isTest
    static void toOrgSettingsTest() {
        TestMockData md = new TestMockData();

        md.mockRMOrgSettingForAccountPlan.Create_New_Contact__c = false;
        md.mockRMOrgSettingForAccountPlan.Show_Clone_Relationship_Map__c = true;
        md.mockRMOrgSettingForAccountPlan.Show_Chart_Settings__c = false;

        RMChartSettingsWrapper wrapper = new RMChartSettingsWrapper(
            md.mockRMChartSettingForAccountPlan,
            md.mockRMOrgSettingForAccountPlan
        );

        RM_Org_Setting__c returnedSettings = wrapper.toOrgSettings();
        System.assertEquals(md.mockRMOrgSettingForAccountPlan, returnedSettings);
    }
}