default/objects/RM_Svg__c/RM_Svg__c.object-meta.xml
<CustomObject>
    <label>Relationship Map Badge</label>
    <nameField>
        <label>Relationship Map Badge Names</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Map Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Svg__c/fields/Contact_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Field_API_Name__c</fullName>
    <description>The api name of the field on the Contact Object.  This Contact field must be a checkbox.  By populating this field name, whenever the contact field is checked, the badge appears on the contact card.</description>
    <inlineHelpText>The api name of the field on the Contact Object.  This Contact field must be a checkbox.  By populating this field name, whenever the contact field is checked, the badge appears on the contact card.</inlineHelpText>
    <label>Contact Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/RMSvgHelperServiceImpl.cls
public with sharing class RMSvgHelperServiceImpl {
    public List<GraphNodeData> injectBoundBadges(List<RM_Svg__c> svgs, List<GraphNodeData> graphNodeDataList) {
        for (RM_Svg__c svg : svgs) {
            if (String.isBlank(svg.Contact_Field_API_Name__c)) {
                continue;
            }
            updateGraphNodeDataListForSvg(svg, graphNodeDataList);
        }
        return graphNodeDataList;
    }

    private void updateGraphNodeDataListForSvg(RM_Svg__c svg, List<GraphNodeData> graphNodeDataList) {
        for (GraphNodeData gnd : graphNodeDataList) {
            if (nodeContainsBoundField(gnd, svg.Contact_Field_API_Name__c)) {
                if (gnd.badges == null) {
                    gnd.badges = new List<Badge>();
                }
                gnd.badges.add(new Badge((String) svg.Id, '', '', true));
            }
            gnd.additionalFields = removeField(gnd.additionalFields, svg.Contact_Field_API_Name__c);
        }
    }

    private Boolean nodeContainsBoundField(GraphNodeData node, String apiName) {
        if (node.additionalFields != null && node.additionalFields.size() > 0) {
            for (OrgAdditionalField f : node.additionalFields) {
                if (f.apiName == apiName && f.value.toLowerCase() == 'true') {
                    return true;
                }
            }
        }
        return false;
    }

    private List<OrgAdditionalField> removeField(List<OrgAdditionalField> fields, String apiName) {
        List<OrgAdditionalField> newFields = new List<OrgAdditionalField>();
        if (fields != null && fields.size() > 0) {
            for (OrgAdditionalField f : fields) {
                if (f.apiName != apiName) {
                    newFields.add(f);
                }
            }
        }
        return newFields;
    }
}