default/objects/RM_Svg__c/RM_Svg__c.object-meta.xml
<CustomObject>
    <label>Relationship Map Badge</label>
    <nameField>
        <label>Relationship Map Badge Names</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Map Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Svg__c/fields/Contact_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Field_API_Name__c</fullName>
    <description>The api name of the field on the Contact Object.  This Contact field must be a checkbox.  By populating this field name, whenever the contact field is checked, the badge appears on the contact card.</description>
    <inlineHelpText>The api name of the field on the Contact Object.  This Contact field must be a checkbox.  By populating this field name, whenever the contact field is checked, the badge appears on the contact card.</inlineHelpText>
    <label>Contact Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/RMSvgHelperServiceTest.cls
@isTest
private class RMSvgHelperServiceTest {
    @isTest
    static void injectBoundBadgesTest() {
        Id id1 = fflib_IDGenerator.generate(RM_Svg__c.SObjectType);
        Id id2 = fflib_IDGenerator.generate(RM_Svg__c.SObjectType);

        RM_Svg__c svg1 = new RM_Svg__c(Id = id1, Contact_Field_API_Name__c = 'foo');
        RM_Svg__c svg2 = new RM_Svg__c(Id = id2, Contact_Field_API_Name__c = 'something else');

        List<RM_Svg__c> svgs = new List<RM_Svg__c>{ svg1, svg2 };

        List<GraphNodeData> graphNodeDataList = new List<GraphNodeData>();

        String value = 'true';
        String apiName = 'foo';
        OrgAdditionalField f1 = new OrgAdditionalField(apiName, 'foo', value, false, '');
        OrgAdditionalField f2 = new OrgAdditionalField('title', 'title', 'Mr', false, '');

        Id cId = fflib_IDGenerator.generate(Contact.SObjectType);
        GraphNodeData graphData1 = new GraphNodeData(cId, 'groupKey', 'label', 'horizontal');
        graphData1.additionalFields = new List<OrgAdditionalField>{ f1, f2 };

        graphNodeDataList.add(graphData1);

        List<GraphNodeData> result = RMSvgHelperService.injectBoundBadges(svgs, graphNodeDataList);

        System.assertEquals(1, result.size());
        System.assertEquals(1, result[0].additionalFields.size());
        System.assertEquals('title', result[0].additionalFields[0].apiName);
        System.assertEquals(id1, result[0].badges[0].id);
    }
}