default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_User_Setting__c/WS_User_Setting__c.object-meta.xml
<CustomObject>
    <label>WS User Setting</label>
    <nameField>
        <displayFormat>WSUserSetting-{0000}</displayFormat>
        <label>WS User Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WS User Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_User_Setting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>WS_User_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>WS User Settings</relationshipLabel>
    <relationshipName>WS_User_Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/WS_User_Setting__c/fields/Zoom_Index__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Index__c</fullName>
    <label>Zoom Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/WSUserSettingServiceTest.cls
@isTest
private class WSUserSettingServiceTest {
    @isTest
    static void getUserSettingTest() {
        // mocks
        TestMockData md = new TestMockData();
        WSUserSettingSelector mockWSUserSettingSelector = md.mockWSUserSettingSelector;

        md.mocks.startStubbing();
        md.mocks.when(mockWSUserSettingSelector.selectByWhitespaceId(md.mockWhiteSpaceId))
            .thenReturn(new List<WS_User_Setting__c>{ md.mockWSUserSetting });
        md.mocks.stopStubbing();

        // When
        Test.startTest();
        WS_User_Setting__c setting = WSUserSettingService.getUserSetting(md.mockWhiteSpaceId);
        Test.stopTest();

        System.assert(setting != null);
    }

    @isTest
    static void getUserSettingTest2() {
        // mocks
        TestMockData md = new TestMockData();
        fflib_ISObjectUnitOfWork mockUoW = md.mockUow; //NOPMD - Needs to be called in order for it to be mocked in the test
        WSUserSettingSelector mockWSUserSettingSelector = md.mockWSUserSettingSelector;

        md.mocks.startStubbing();
        md.mocks.when(mockWSUserSettingSelector.selectByWhitespaceId(md.mockWhiteSpaceId)).thenReturn(null);
        md.mocks.stopStubbing();

        // When
        Test.startTest();
        WS_User_Setting__c setting = WSUserSettingService.getUserSetting(md.mockWhiteSpaceId);
        Test.stopTest();

        System.assertNotEquals(setting, null);
        System.assertEquals(md.mockWhiteSpaceId, setting.White_Space__c);
        System.assertEquals(UserInfo.getUserId(), setting.User__c);
        System.assertEquals(null, setting.Id);
    }

    @isTest
    static void updateUserSettingTest() {
        // mocks
        TestMockData md = new TestMockData();
        fflib_ISObjectUnitOfWork mockUoW = md.mockUow;

        // When
        Test.startTest();
        WSUserSettingService.updateUserSetting(new List<WS_User_Setting__c>{ md.mockWSUserSetting });
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDirty(md.mockWSUserSetting);
        System.assert(true, 'Assert by verifing mock data');
    }

    @isTest
    static void updateUserSettingTest2() {
        // mocks
        TestMockData md = new TestMockData();
        fflib_ISObjectUnitOfWork mockUoW = md.mockUow;
        WS_User_Setting__c mockWSUserSetting = md.mockWSUserSetting;
        mockWSUserSetting.Id = null;

        // When
        Test.startTest();
        WSUserSettingService.updateUserSetting(new List<WS_User_Setting__c>{ md.mockWSUserSetting });
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerNew(md.mockWSUserSetting);
        System.assert(true, 'Assert by verifing mock data');
    }

    @isTest
    static void updateZoomIndexTest() {
        // mocks
        TestMockData md = new TestMockData();
        fflib_ISObjectUnitOfWork mockUoW = md.mockUow;
        WSUserSettingSelector mockWSUserSettingSelector = md.mockWSUserSettingSelector;

        Integer zoomIndex = 5;

        md.mocks.startStubbing();
        md.mocks.when(mockWSUserSettingSelector.selectById(new Set<Id>{ md.mockWSUserSettingId }))
            .thenReturn(new List<WS_User_Setting__c>{ md.mockWSUserSetting });
        md.mocks.stopStubbing();

        // When
        Test.startTest();
        WSUserSettingService.updateZoomIndex(md.mockWSUserSettingId, zoomIndex);
        Test.stopTest();

        md.mockWSUserSetting.Zoom_Index__c = zoomIndex;

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDirty(md.mockWSUserSetting);
        System.assert(true, 'Assert by verifing mock data');
    }
}