default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Row__c/White_Space_Row__c.object-meta.xml
<CustomObject>
    <label>Row</label>
    <nameField>
        <label>Row Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Row__c/fields/Related_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Id__c</fullName>
    <label>Related Object Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Row__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>Rows</relationshipLabel>
    <relationshipName>White_Space_Rows</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/WhiteSpaceRowSelector.cls
public with sharing class WhiteSpaceRowSelector extends fflib_SObjectSelector {
    public static WhiteSpaceRowSelector newInstance() {
        return (WhiteSpaceRowSelector) Application.Selector.newInstance(White_Space_Row__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            White_Space_Row__c.Id,
            White_Space_Row__c.Name,
            White_Space_Row__c.Order__c,
            White_Space_Row__c.Related_Object_Id__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return White_Space_Row__c.sObjectType;
    }

    public override String getOrderBy() {
        return White_Space_Row__c.Order__c.getDescribe().getName();
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<White_Space_Row__c> selectById(Set<ID> recordIds) {
        return (List<White_Space_Row__c>) selectSObjectsById(recordIds);
    }

    public List<White_Space_Row__c> selectByWhiteSpaceId(Set<Id> whiteSpaceIds) {
        return Database.query(newQueryFactory().setCondition('White_Space__c IN :whiteSpaceIds').toSOQL());
    }
}