default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_User_Setting__c/WS_User_Setting__c.object-meta.xml
<CustomObject>
    <label>WS User Setting</label>
    <nameField>
        <displayFormat>WSUserSetting-{0000}</displayFormat>
        <label>WS User Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WS User Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_User_Setting__c/fields/Amount_Type_Filters__c.field-meta.xml
<CustomField>
    <fullName>Amount_Type_Filters__c</fullName>
    <label>Amount Type Filters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/Column_Filters__c.field-meta.xml
<CustomField>
    <fullName>Column_Filters__c</fullName>
    <label>Column Filters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/Highlight_Filters__c.field-meta.xml
<CustomField>
    <fullName>Highlight_Filters__c</fullName>
    <description>List of highlight id&apos;s used to hide highlights from view</description>
    <label>Highlight Filters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/Row_Filters__c.field-meta.xml
<CustomField>
    <fullName>Row_Filters__c</fullName>
    <label>Row Filters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/Show_Empty_Columns__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Columns__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether or not to show columns that do not have data in any of their cells</description>
    <label>Show columns without data</label>
    <type>Checkbox</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/Show_Empty_Rows__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Rows__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether or not to show rows that do not have any cells with data</description>
    <label>Show rows without data</label>
    <type>Checkbox</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/Show_Populated_Columns__c.field-meta.xml
<CustomField>
    <fullName>Show_Populated_Columns__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether or not to show columns that have at least one cell with data</description>
    <label>Show columns with data</label>
    <type>Checkbox</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/Show_Populated_Rows__c.field-meta.xml
<CustomField>
    <fullName>Show_Populated_Rows__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether or not to show rows in the cross sell that have data in at least one cell</description>
    <label>Show rows with data</label>
    <type>Checkbox</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/Show_Unhighlighted__c.field-meta.xml
<CustomField>
    <fullName>Show_Unhighlighted__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Unhighlighted</label>
    <type>Checkbox</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>WS_User_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>WS User Settings</relationshipLabel>
    <relationshipName>WS_User_Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/WS_User_Setting__c/fields/Zoom_Index__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Index__c</fullName>
    <label>Zoom Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/WSUserSettingSelector.cls
public with sharing class WSUserSettingSelector extends fflib_SObjectSelector {
    public static WSUserSettingSelector newInstance() {
        return (WSUserSettingSelector) Application.Selector.newInstance(WS_User_Setting__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            WS_User_Setting__c.Id,
            WS_User_Setting__c.Row_Filters__c,
            WS_User_Setting__c.Column_Filters__c,
            WS_User_Setting__c.Amount_Type_Filters__c,
            WS_User_Setting__c.White_Space__c,
            WS_User_Setting__c.User__c,
            WS_User_Setting__c.Highlight_Filters__c,
            WS_User_Setting__c.Show_Empty_Columns__c,
            WS_User_Setting__c.Show_Empty_Rows__c,
            WS_User_Setting__c.Show_Populated_Columns__c,
            WS_User_Setting__c.Show_Populated_Rows__c,
            WS_User_Setting__c.Show_Unhighlighted__c,
            WS_User_Setting__c.Zoom_Index__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return WS_User_Setting__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<WS_User_Setting__c> selectById(Set<ID> idSet) {
        return (List<WS_User_Setting__c>) selectSObjectsById(idSet);
    }

    public List<WS_User_Setting__c> selectByWhitespaceId(Id whitespaceId) {
        Id userId = UserInfo.getUserId(); //NOPMD - False positive, used in query condition below
        fflib_QueryFactory query = newQueryFactory();
        return Database.query(query.setCondition('White_Space__c = :whitespaceId AND User__c = :userId').toSOQL());
    }
}