default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Column__c/White_Space_Column__c.object-meta.xml
<CustomObject>
    <label>Column</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Column__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>Columns</relationshipLabel>
    <relationshipName>White_Space_Columns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/WhiteSpaceColumnSelector.cls
public with sharing class WhiteSpaceColumnSelector extends fflib_SObjectSelector {
    public static WhiteSpaceColumnSelector newInstance() {
        return (WhiteSpaceColumnSelector) Application.Selector.newInstance(White_Space_Column__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            White_Space_Column__c.Id,
            White_Space_Column__c.Name,
            White_Space_Column__c.Order__c,
            White_Space_Column__c.Related_Object_Id__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return White_Space_Column__c.sObjectType;
    }

    public override String getOrderBy() {
        return White_Space_Column__c.Order__c.getDescribe().getName();
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<White_Space_Column__c> selectById(Set<ID> idSet) {
        return (List<White_Space_Column__c>) selectSObjectsById(idSet);
    }

    public List<White_Space_Column__c> selectByWhiteSpaceId(Set<Id> whiteSpaceIds) {
        return Database.query(newQueryFactory().setCondition('White_Space__c IN :whiteSpaceIds').toSOQL());
    }
}