default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space__c/fields/White_Space_Template__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cross-Sell Template</label>
    <referenceTo>White_Space_Template__c</referenceTo>
    <relationshipLabel>Cross-Sell Maps</relationshipLabel>
    <relationshipName>White_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Template__c/White_Space_Template__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Template</label>
    <nameField>
        <label>Cross-Sell Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/WhiteSpaceFactory.cls
public with sharing class WhiteSpaceFactory {
    public WhiteSpaceAbstract makeWhiteSpaceAbstract(White_Space__c whiteSpaceInfo, White_Space_Template__c template) {
        WhiteSpaceTypeEnum type = WhiteSpaceTypeEnumHelper.getTypeFrom(whiteSpaceInfo, template);
        WhiteSpaceAbstract newWhiteSpaceResult = null;

        if (type.equals(WhiteSpaceTypeEnum.TEMPLATE)) {
            newWhiteSpaceResult = new WhiteSpaceFromTemplate(whiteSpaceInfo, template);
        } else if (type.equals(WhiteSpaceTypeEnum.FREE_FORM)) {
            newWhiteSpaceResult = new WhiteSpaceFreeForm(whiteSpaceInfo);
        } else if (type.equals(WhiteSpaceTypeEnum.LEGACY_TEMPLATE)) {
            newWhiteSpaceResult = new WhiteSpaceFromLegacyTemplate(whiteSpaceInfo, template);
        } else if (type.equals(WhiteSpaceTypeEnum.DEPENDENT_PICKLIST)) {
            newWhiteSpaceResult = new WhiteSpaceFromDependentPicklistTemplate(whiteSpaceInfo, template);
        }

        return newWhiteSpaceResult.build();
    }
}