default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Amount_Type__c/White_Space_Amount_Type__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Amount Type</label>
    <nameField>
        <label>Cross-Sell Amount Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Amount Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/White_Space_Amount_Type_Association__c/White_Space_Amount_Type_Association__c.object-meta.xml
<CustomObject>
    <label>White Space Amount Type Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>White Space Amount Type Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>White Space Amount Type Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Amount_Type_Association__c/fields/White_Space_Amount_Type__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Amount_Type__c</fullName>
    <label>Cross-Sell Amount Type</label>
    <referenceTo>White_Space_Amount_Type__c</referenceTo>
    <relationshipLabel>White Space Amount Type Associations</relationshipLabel>
    <relationshipName>White_Space_Amount_Type_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/White_Space_Amount_Type_Association__c/fields/White_Space_Cell__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Cell__c</fullName>
    <label>White Space Cell</label>
    <referenceTo>White_Space_Cell__c</referenceTo>
    <relationshipLabel>White Space Amount Type Associations</relationshipLabel>
    <relationshipName>White_Space_Amount_Type_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/White_Space_Cell__c/White_Space_Cell__c.object-meta.xml
<CustomObject>
    <label>White Space Cell</label>
    <nameField>
        <label>White Space Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Space Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Cell__c/fields/Highlight__c.field-meta.xml
<CustomField>
    <fullName>Highlight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Highlight</label>
    <referenceTo>WS_Highlight__c</referenceTo>
    <relationshipLabel>White Space Cells</relationshipLabel>
    <relationshipName>White_Space_Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Cell__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <description>Generic Information about a cell</description>
    <label>Info</label>
    <type>TextArea</type>
</CustomField>

default/objects/White_Space_Cell__c/fields/Primary_Amount_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Amount_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Amount Type</label>
    <referenceTo>White_Space_Amount_Type__c</referenceTo>
    <relationshipLabel>White Space Cells</relationshipLabel>
    <relationshipName>White_Space_Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Cell__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>White Space Cells</relationshipLabel>
    <relationshipName>White_Space_Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/White_Space_Cell__c/fields/White_Space_Column__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Column__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Column</label>
    <referenceTo>White_Space_Column__c</referenceTo>
    <relationshipLabel>White Space Cells</relationshipLabel>
    <relationshipName>White_Space_Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Cell__c/fields/White_Space_Row__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Row__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Row</label>
    <referenceTo>White_Space_Row__c</referenceTo>
    <relationshipLabel>White Space Cells</relationshipLabel>
    <relationshipName>White_Space_Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Column__c/White_Space_Column__c.object-meta.xml
<CustomObject>
    <label>Column</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Column__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>Columns</relationshipLabel>
    <relationshipName>White_Space_Columns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/White_Space_Row__c/White_Space_Row__c.object-meta.xml
<CustomObject>
    <label>Row</label>
    <nameField>
        <label>Row Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Row__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>Rows</relationshipLabel>
    <relationshipName>White_Space_Rows</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/WS_Data_Type__c/WS_Data_Type__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Data Type</label>
    <nameField>
        <displayFormat>WSDT-{0000}</displayFormat>
        <label>WS Data Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Data Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/WS_Data_Type__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color in the form of #RRGGBB (example: #FF0000 for red)</description>
    <inlineHelpText>Color in the form of #RRGGBB (example: #FF0000 for red)</inlineHelpText>
    <label>Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/WS_Data_Type__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>Cross-Sell Data Types</relationshipLabel>
    <relationshipName>Cross_Sell_Data_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/WS_Data_Type_Association__c/WS_Data_Type_Association__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Data Type Association</label>
    <nameField>
        <displayFormat>WSDTA-{0000}</displayFormat>
        <label>Cross-Sell Data Type Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Data Type Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_Data_Type_Association__c/fields/White_Space_Cell__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Cell__c</fullName>
    <label>White Space Cell</label>
    <referenceTo>White_Space_Cell__c</referenceTo>
    <relationshipLabel>Cross-Sell Data Type Associations</relationshipLabel>
    <relationshipName>Cross_Sell_Data_Type_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/WS_Data_Type_Association__c/fields/WS_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>WS_Data_Type__c</fullName>
    <label>WS Data Type</label>
    <referenceTo>WS_Data_Type__c</referenceTo>
    <relationshipLabel>Cross-Sell Data Type Associations</relationshipLabel>
    <relationshipName>Cross_Sell_Data_Type_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/WS_Highlight__c/WS_Highlight__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Highlight</label>
    <nameField>
        <displayFormat>WSH-{0000}</displayFormat>
        <label>WS Highlight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Highlights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/WS_Highlight__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color RGB in the form of #rrggbb</description>
    <label>Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

default/classes/WhiteSpaceCellSelector.cls
public with sharing class WhiteSpaceCellSelector extends fflib_SObjectSelector {
    public static WhiteSpaceCellSelector newInstance() {
        return (WhiteSpaceCellSelector) Application.Selector.newInstance(White_Space_Cell__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            White_Space_Cell__c.Id,
            White_Space_Cell__c.Name,
            White_Space_Cell__c.CreatedDate,
            White_Space_Cell__c.White_Space__c,
            White_Space_Cell__c.White_Space_Column__c,
            White_Space_Cell__c.White_Space_Row__c,
            White_Space_Cell__c.Info__c,
            White_Space_Cell__c.Primary_Amount_Type__c,
            White_Space_Cell__c.Highlight__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return White_Space_Cell__c.sObjectType;
    }

    public override String getOrderBy() {
        return White_Space_Cell__c.CreatedDate.getDescribe().getName() + ' ASC';
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<White_Space_Cell__c> selectById(Set<ID> idSet) {
        return (List<White_Space_Cell__c>) selectSObjectsById(idSet);
    }

    public List<White_Space_Cell__c> selectByRowId(Set<Id> rowIds) {
        return Database.query(newQueryFactory().setCondition('White_Space_Row__c IN :rowIds').toSOQL());
    }

    public List<White_Space_Cell__c> selectByColumnId(Set<Id> columnIds) {
        return Database.query(newQueryFactory().setCondition('White_Space_Column__c IN :columnIds').toSOQL());
    }

    public List<White_Space_Cell__c> selectByWhiteSpaceIdWithAmountTypeAssociations(Id wsId) {
        fflib_QueryFactory query = newQueryFactory();

        new WhiteSpaceAmountTypeSelector()
            .configureQueryFactoryFields(
                query,
                White_Space_Cell__c.Primary_Amount_Type__c.getDescribe().getRelationshipName()
            );

        new WSHighlightSelector()
            .configureQueryFactoryFields(query, White_Space_Cell__c.Highlight__c.getDescribe().getRelationshipName());

        fflib_QueryFactory associationsQueryFactory = new WhiteSpaceAmountTypeAssociationSelector()
            .addQueryFactorySubselect(query);

        new WhiteSpaceAmountTypeSelector()
            .configureQueryFactoryFields(
                associationsQueryFactory,
                White_Space_Amount_Type_Association__c.White_Space_Amount_Type__c.getDescribe().getRelationshipName()
            );

        // ADD DATA TYPE TO QUERY
        fflib_QueryFactory dataTypeAssociationsQueryFactory = new WSDataTypeAssociationSelector()
            .addQueryFactorySubselect(query);

        new WSDataTypeSelector()
            .configureQueryFactoryFields(
                dataTypeAssociationsQueryFactory,
                WS_Data_Type_Association__c.WS_Data_Type__c.getDescribe().getRelationshipName()
            );

        return Database.query(
            query
                .selectField('Highlight__r.Id')
                .selectField('Highlight__r.Color__c')
                .selectField('Highlight__r.Label__c')
                .setCondition('White_Space__c = :wsId')
                .toSOQL()
        );
    }
}