default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space__c/fields/White_Space_Template__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cross-Sell Template</label>
    <referenceTo>White_Space_Template__c</referenceTo>
    <relationshipLabel>Cross-Sell Maps</relationshipLabel>
    <relationshipName>White_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Template__c/White_Space_Template__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Template</label>
    <nameField>
        <label>Cross-Sell Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/White_Space_Template__c/fields/hasDependentPicklistColumns__c.field-meta.xml
<CustomField>
    <fullName>hasDependentPicklistColumns__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Column values are generated based on possible picklist values from the records mapped to cell data and the picklist field&apos;s controlling field.</description>
    <label>Has Dependent Picklist Columns</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space_Template__c/fields/hasDependentPicklistRows__c.field-meta.xml
<CustomField>
    <fullName>hasDependentPicklistRows__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Row values are generated based on possible picklist values from the records mapped to cell data and the picklist field&apos;s controlling field.</description>
    <label>Has Dependent Picklist Rows</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space_Template__c/fields/isLegacy__c.field-meta.xml
<CustomField>
    <fullName>isLegacy__c</fullName>
    <formula>AND(ISBLANK(ColumnMapping__c),ISBLANK(RowMapping__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isLegacy</label>
    <type>Checkbox</type>
</CustomField>

default/classes/WhiteSpaceTypeEnumHelper.cls
public with sharing class WhiteSpaceTypeEnumHelper {
    public static WhiteSpaceTypeEnum getTypeFrom(White_Space__c whiteSpace, White_Space_Template__c template) {
        return whiteSpace.White_Space_Template__c == null ? WhiteSpaceTypeEnum.FREE_FORM : getTypeFrom(template);
    }

    public static WhiteSpaceTypeEnum getTypeFrom(White_Space_Template__c template) {
        WhiteSpaceTypeEnum type = null;
        if (template != null) {
            if (template.isLegacy__c) {
                type = WhiteSpaceTypeEnum.LEGACY_TEMPLATE;
            } else if (template.hasDependentPicklistColumns__c || template.hasDependentPicklistRows__c) {
                type = WhiteSpaceTypeEnum.DEPENDENT_PICKLIST;
            } else {
                type = WhiteSpaceTypeEnum.TEMPLATE;
            }
        }
        return type;
    }
}