default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_Summary_Formula__c/WS_Summary_Formula__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Summary Formula</label>
    <nameField>
        <displayFormat>WSSummaryFormula-{0000}</displayFormat>
        <label>WS Summary Formula Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Summary Formulas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_Summary_Formula__c/fields/Apply_To_All_Cross_Sell_Maps__c.field-meta.xml
<CustomField>
    <fullName>Apply_To_All_Cross_Sell_Maps__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to apply this formula to all Cross-Sell maps</description>
    <inlineHelpText>Check this to apply this formula to all Cross-Sell maps</inlineHelpText>
    <label>Apply To All Cross-Sell Maps</label>
    <type>Checkbox</type>
</CustomField>

default/objects/WS_Summary_Formula__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color RBG in the form of #rrggbb</description>
    <inlineHelpText>Color RBG in the form of #rrggbb</inlineHelpText>
    <label>Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

default/objects/WS_Summary_Formula__c/fields/Display_Type__c.field-meta.xml
<CustomField>
    <fullName>Display_Type__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/WS_Summary_Formula__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <inlineHelpText>Formulas are comprised of different amount types and math symbols.  The amount type variable is defined by using the name of the amount type surrounded by curly braces.  Example formula: {Amount Type 1} + {Amount Type 2}</inlineHelpText>
    <label>Formula</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/WS_Summary_Formula__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>Cross-Sell Summary Formulas</relationshipLabel>
    <relationshipName>Cross_Sell_Summary_Formulas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/WSSummaryFormulaSelector.cls
public with sharing class WSSummaryFormulaSelector extends fflib_SObjectSelector {
    public static WSSummaryFormulaSelector newInstance() {
        return (WSSummaryFormulaSelector) Application.Selector.newInstance(WS_Summary_Formula__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            WS_Summary_Formula__c.Id,
            WS_Summary_Formula__c.Name,
            WS_Summary_Formula__c.Label__c,
            WS_Summary_Formula__c.Display_Type__c,
            WS_Summary_Formula__c.Formula__c,
            WS_Summary_Formula__c.Color__c,
            WS_Summary_Formula__c.White_Space__c,
            WS_Summary_Formula__c.Apply_To_All_Cross_Sell_Maps__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return WS_Summary_Formula__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<WS_Summary_Formula__c> selectById(Set<ID> idSet) {
        return (List<WS_Summary_Formula__c>) selectSObjectsById(idSet);
    }

    public List<WS_Summary_Formula__c> selectByWhiteSpaceId(Id whiteSpaceId) {
        fflib_QueryFactory query = newQueryFactory();
        return Database.query(
            query.setCondition('White_Space__c = :whiteSpaceId OR Apply_To_All_Cross_Sell_Maps__c = true').toSOQL()
        );
    }
}