default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space__c/fields/White_Space_Template__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cross-Sell Template</label>
    <referenceTo>White_Space_Template__c</referenceTo>
    <relationshipLabel>Cross-Sell Maps</relationshipLabel>
    <relationshipName>White_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Template__c/White_Space_Template__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Template</label>
    <nameField>
        <label>Cross-Sell Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/White_Space_Template__c/fields/hasDependentPicklistColumns__c.field-meta.xml
<CustomField>
    <fullName>hasDependentPicklistColumns__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Column values are generated based on possible picklist values from the records mapped to cell data and the picklist field&apos;s controlling field.</description>
    <label>Has Dependent Picklist Columns</label>
    <type>Checkbox</type>
</CustomField>

default/classes/WhiteSpaceTypeEnumHelperTest.cls
@isTest
private class WhiteSpaceTypeEnumHelperTest {
    @isTest
    private static void getTypeFromTest1() {
        White_Space__c ws = new White_Space__c(White_Space_Template__c = null);

        WhiteSpaceTypeEnum wsenum = WhiteSpaceTypeEnumHelper.getTypeFrom(ws, null);
        System.assertEquals(WhiteSpaceTypeEnum.FREE_FORM, wsenum);
    }

    @isTest
    private static void getTypeFromTest2() {
        White_Space_Template__c wst = new White_Space_Template__c(
            Id = fflib_IDGenerator.generate(White_Space_Template__c.SObjectType)
        );
        White_Space__c ws = new White_Space__c();
        ws.White_Space_Template__c = wst.Id;

        WhiteSpaceTypeEnum wsenum = WhiteSpaceTypeEnumHelper.getTypeFrom(ws, wst);
        System.assertEquals(WhiteSpaceTypeEnum.TEMPLATE, wsenum);
    }

    @isTest
    private static void getTypeFromTest3() {
        White_Space_Template__c wst = new White_Space_Template__c(
            Id = fflib_IDGenerator.generate(White_Space_Template__c.SObjectType)
        );
        wst.hasDependentPicklistColumns__c = true;
        White_Space__c ws = new White_Space__c();
        ws.White_Space_Template__c = wst.Id;

        WhiteSpaceTypeEnum wsenum = WhiteSpaceTypeEnumHelper.getTypeFrom(ws, wst);
        System.assertEquals(WhiteSpaceTypeEnum.DEPENDENT_PICKLIST, wsenum);
    }
}