default/objects/Cell_Relationship_Configuration__c/Cell_Relationship_Configuration__c.object-meta.xml
<CustomObject>
    <description>Configuration data for records related to cells in a Cross Sell</description>
    <label>Cell Relationship Configuration</label>
    <nameField>
        <displayFormat>CRC-{0000}</displayFormat>
        <label>Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cell Relationship Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Cell_Relationship_Configuration__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;#556677&quot;</defaultValue>
    <description>Hexadecimal color code value</description>
    <inlineHelpText>Color code in the form of #RRGGBB or #RGB (example: #FF0000 for red)</inlineHelpText>
    <label>Color</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Cell_Relationship_Configuration__c/fields/Display_Field__c.field-meta.xml
<CustomField>
    <fullName>Display_Field__c</fullName>
    <description>The API Name of the field you want to display in the cell that is on the object specified in this configuration</description>
    <inlineHelpText>If this field does not exist on the object or this field is left blank then the object&apos;s default name field will be used instead</inlineHelpText>
    <label>Display Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Cell_Relationship_Configuration__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>The API name for the object you want to configure which has a relationship to the pqcrush__White_Space_Cell__c object</description>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Amount_Type_Association__c/White_Space_Amount_Type_Association__c.object-meta.xml
<CustomObject>
    <label>White Space Amount Type Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>White Space Amount Type Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>White Space Amount Type Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Amount_Type_Association__c/fields/White_Space_Cell__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Cell__c</fullName>
    <label>White Space Cell</label>
    <referenceTo>White_Space_Cell__c</referenceTo>
    <relationshipLabel>White Space Amount Type Associations</relationshipLabel>
    <relationshipName>White_Space_Amount_Type_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/White_Space_Cell__c/White_Space_Cell__c.object-meta.xml
<CustomObject>
    <label>White Space Cell</label>
    <nameField>
        <label>White Space Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Space Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/classes/WSRelatedObjectWrapperTest.cls
@isTest
private with sharing class WSRelatedObjectWrapperTest {
    @isTest
    static void emptyInitializerTest() {
        WSRelatedObjectWrapper result = new WSRelatedObjectWrapper();
        System.assertEquals(null, result.objDesc);
        System.assertEquals(null, result.labelFieldName);
        System.assertEquals(null, result.fieldList);
        System.assertEquals(null, result.relationshipField);
        System.assertEquals('#556677', result.color);
    }
    @isTest
    static void initializerWithoutConfigTest() {
        WSRelatedObjectWrapper result = new WSRelatedObjectWrapper(
            Account.sObjectType.getDescribe(),
            Schema.SObjectType.Account.fields.OwnerId
        );
        System.assertEquals(Schema.SObjectType.Account.fields.Name.getName(), result.labelFieldName);
        System.assertEquals(2, result.fieldList.size());
        System.assertEquals(Schema.SObjectType.Account.fields.Name.getName(), result.fieldList[0]);
        System.assertEquals(Schema.SObjectType.Account.fields.Id.getName(), result.fieldList[1]);
    }

    @isTest
    static void initializerNullConfigTest() {
        WSRelatedObjectWrapper result = new WSRelatedObjectWrapper(
            Account.sObjectType.getDescribe(),
            Schema.SObjectType.Account.fields.OwnerId,
            null
        );
        System.assertEquals(Schema.SObjectType.Account.fields.Name.getName(), result.labelFieldName);
        System.assertEquals(2, result.fieldList.size());
        System.assertEquals(Schema.SObjectType.Account.fields.Name.getName(), result.fieldList[0]);
        System.assertEquals(Schema.SObjectType.Account.fields.Id.getName(), result.fieldList[1]);
    }

    @isTest
    static void initializerBadConfigObjectTest() {
        Cell_Relationship_Configuration__c config = new Cell_Relationship_Configuration__c();
        config.Object_API_Name__c = 'Contact';
        config.Color__c = '#FFF';
        config.Display_Field__c = 'Name';
        WSRelatedObjectWrapper result = new WSRelatedObjectWrapper(
            Account.sObjectType.getDescribe(),
            Schema.SObjectType.Account.fields.OwnerId,
            config
        );
        System.assertEquals(Schema.SObjectType.Account.fields.Name.getName(), result.labelFieldName);
        System.assertEquals(2, result.fieldList.size());
        System.assertEquals(Schema.SObjectType.Account.fields.Name.getName(), result.fieldList[0]);
        System.assertEquals(Schema.SObjectType.Account.fields.Id.getName(), result.fieldList[1]);
    }

    @isTest
    static void initializerBadConfigDisplayFieldTest() {
        Cell_Relationship_Configuration__c config = new Cell_Relationship_Configuration__c();
        config.Object_API_Name__c = 'Account';
        config.Color__c = '#FFF';
        config.Display_Field__c = 'wsrow_FakeField';
        WSRelatedObjectWrapper result = new WSRelatedObjectWrapper(
            Account.sObjectType.getDescribe(),
            Schema.SObjectType.Account.fields.OwnerId,
            config
        );
        System.assertEquals(Schema.SObjectType.Account.fields.Name.getName(), result.labelFieldName);
        System.assertEquals(2, result.fieldList.size());
        System.assertEquals(Schema.SObjectType.Account.fields.Name.getName(), result.fieldList[0]);
        System.assertEquals(Schema.SObjectType.Account.fields.Id.getName(), result.fieldList[1]);
    }

    @isTest
    static void initializerEmptyConfigDisplayFieldTest() {
        Cell_Relationship_Configuration__c config = new Cell_Relationship_Configuration__c();
        config.Object_API_Name__c = 'Account';
        config.Color__c = '#FFF';
        config.Display_Field__c = '';
        WSRelatedObjectWrapper result = new WSRelatedObjectWrapper(
            Account.sObjectType.getDescribe(),
            Schema.SObjectType.Account.fields.OwnerId,
            config
        );
        System.assertEquals(Schema.SObjectType.Account.fields.Name.getName(), result.labelFieldName);
        System.assertEquals(2, result.fieldList.size());
        System.assertEquals(Schema.SObjectType.Account.fields.Name.getName(), result.fieldList[0]);
        System.assertEquals(Schema.SObjectType.Account.fields.Id.getName(), result.fieldList[1]);
    }

    @isTest
    static void initializerWithConfigHappyPathTest() {
        Cell_Relationship_Configuration__c config = new Cell_Relationship_Configuration__c();
        config.Object_API_Name__c = 'Account';
        config.Color__c = '#FFF';
        config.Display_Field__c = 'Type';
        WSRelatedObjectWrapper result = new WSRelatedObjectWrapper(
            Account.sObjectType.getDescribe(),
            Schema.SObjectType.Account.fields.OwnerId,
            config
        );
        System.assertEquals(Schema.SObjectType.Account.fields.Type.getName(), result.labelFieldName);
        System.assertEquals(2, result.fieldList.size());
        System.assertEquals(Schema.SObjectType.Account.fields.Type.getName(), result.fieldList[0]);
        System.assertEquals(Schema.SObjectType.Account.fields.Id.getName(), result.fieldList[1]);
        System.assertEquals(config.Color__c, result.color);
    }

    @isTest
    static void initializerWithConfigCompoundBadPathTest() {
        Cell_Relationship_Configuration__c config = new Cell_Relationship_Configuration__c();
        config.Object_API_Name__c = 'pqcrush__White_Space_Amount_Type_Association__c';
        config.Color__c = '#FFF';
        config.Display_Field__c = 'pqcrush__White_Space_Amount_Type__r.pqcrush__Not_Real__c';
        WSRelatedObjectWrapper result = new WSRelatedObjectWrapper(
            pqcrush__White_Space_Amount_Type_Association__c.sObjectType.getDescribe(),
            Schema.SObjectType.pqcrush__White_Space_Amount_Type_Association__c.fields.White_Space_Cell__c,
            config
        );
        System.assertEquals(
            Schema.SObjectType.White_Space_Amount_Type_Association__c.fields.Name.getName(),
            result.labelFieldName
        );
        System.assertEquals(2, result.fieldList.size());
        System.assertEquals(
            Schema.SObjectType.White_Space_Amount_Type_Association__c.fields.Name.getName(),
            result.fieldList[0]
        );
        System.assertEquals(
            Schema.SObjectType.White_Space_Amount_Type_Association__c.fields.Id.getName(),
            result.fieldList[1]
        );
        System.assertEquals(config.Color__c, result.color);
    }

    @isTest
    static void initializerWithConfigCompoundGoodPathTest() {
        Cell_Relationship_Configuration__c config = new Cell_Relationship_Configuration__c();
        config.Object_API_Name__c = 'pqcrush__White_Space_Amount_Type_Association__c';
        config.Color__c = '#FFF';
        config.Display_Field__c = 'pqcrush__White_Space_Amount_Type__r.pqcrush__Color_RGB__c';
        WSRelatedObjectWrapper result = new WSRelatedObjectWrapper(
            pqcrush__White_Space_Amount_Type_Association__c.sObjectType.getDescribe(),
            Schema.SObjectType.pqcrush__White_Space_Amount_Type_Association__c.fields.White_Space_Cell__c,
            config
        );
        System.assertEquals('pqcrush__White_Space_Amount_Type__r.pqcrush__Color_RGB__c', result.labelFieldName);
        System.assertEquals(2, result.fieldList.size());
        System.assertEquals('pqcrush__White_Space_Amount_Type__r.pqcrush__Color_RGB__c', result.fieldList[0]);
        System.assertEquals('pqcrush__White_Space_Amount_Type__r.Id', result.fieldList[1]);
        System.assertEquals(config.Color__c, result.color);
    }
}