default/objects/Cell_Relationship_Configuration__c/Cell_Relationship_Configuration__c.object-meta.xml
<CustomObject>
    <description>Configuration data for records related to cells in a Cross Sell</description>
    <label>Cell Relationship Configuration</label>
    <nameField>
        <displayFormat>CRC-{0000}</displayFormat>
        <label>Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cell Relationship Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Cell_Relationship_Configuration__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;#556677&quot;</defaultValue>
    <description>Hexadecimal color code value</description>
    <inlineHelpText>Color code in the form of #RRGGBB or #RGB (example: #FF0000 for red)</inlineHelpText>
    <label>Color</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Cell_Relationship_Configuration__c/fields/Display_Field__c.field-meta.xml
<CustomField>
    <fullName>Display_Field__c</fullName>
    <description>The API Name of the field you want to display in the cell that is on the object specified in this configuration</description>
    <inlineHelpText>If this field does not exist on the object or this field is left blank then the object&apos;s default name field will be used instead</inlineHelpText>
    <label>Display Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Cell_Relationship_Configuration__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>The API name for the object you want to configure which has a relationship to the pqcrush__White_Space_Cell__c object</description>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/WSRelatedObjectWrapper.cls
public with sharing class WSRelatedObjectWrapper {
    public Schema.DescribeSObjectResult objDesc;
    public Schema.DescribeFieldResult relationshipField;
    public Schema.DescribeFieldResult labelFieldDesc;
    public String labelFieldName;
    public List<String> fieldList;
    public String color = '#556677';

    public WSRelatedObjectWrapper() {
        this.objDesc = null;
        this.relationshipField = null;
        this.labelFieldName = null;
        this.fieldList = null;
    }

    public WSRelatedObjectWrapper(Schema.DescribeSObjectResult obj, Schema.DescribeFieldResult rel) {
        this(obj, rel, null);
    }

    public WSRelatedObjectWrapper(
        Schema.DescribeSObjectResult obj,
        Schema.DescribeFieldResult rel,
        Cell_Relationship_Configuration__c config
    ) {
        if (config?.Object_API_Name__c != obj.getName()) {
            config = null;
        }
        this.objDesc = obj;
        this.relationshipField = rel;
        setupDisplayFieldsFromConfig(config);
        if (!String.isBlank(config?.Color__c)) {
            this.color = config.Color__c;
        }
    }

    private void setupDisplayFieldsFromConfig(Cell_Relationship_Configuration__c config) {
        if (String.isBlank(config?.Display_Field__c)) {
            findAndSetDisplayFields();
            return;
        }
        List<String> parts = config.Display_Field__c.split('\\.');
        String fieldName = (String) UtilityForList.last(parts);
        String idName = config.Display_Field__c.replace(fieldName, 'Id');
        Schema.DescribeSObjectResult currentObj = this.objDesc;
        //verify that displayField path fully exists, if not use Name field via findAndSetDisplayFields method
        for (String part : parts) {
            Boolean found = false;
            for (Schema.SObjectField sof : currentObj.fields.getMap().values()) {
                try {
                    Schema.DescribeFieldResult field = sof.getDescribe();
                    if (field.getRelationshipName() == part || field.getName() == part) {
                        found = true;
                        if (field.getReferenceTo().size() > 0) {
                            currentObj = field.getReferenceTo()[0].getDescribe();
                        }
                        this.labelFieldDesc = field;
                        break;
                    }
                } catch (Exception e) {
                    continue;
                }
            }
            if (!found) {
                findAndSetDisplayFields();
                return;
            }
        }
        this.labelFieldName = config.Display_Field__c;
        this.fieldList = new List<String>{ config.Display_Field__c, idName };
    }

    private void findAndSetDisplayFields() {
        for (Schema.SObjectField childField : this.objDesc.fields.getMap().values()) {
            try {
                if (childField.getDescribe().isNameField()) {
                    this.labelFieldDesc = childField.getDescribe();
                    String name = this.labelFieldDesc.getName();
                    this.labelFieldName = name;
                    this.fieldList = new List<String>{ name, 'Id' };
                }
            } catch (Exception e) {
                continue;
            }
        }
    }
}