default/objects/White_Space_Template__c/White_Space_Template__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Template</label>
    <nameField>
        <label>Cross-Sell Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/White_Space_Template__c/fields/Column_Label_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Label_Field_Name__c</fullName>
    <label>Column Label Field Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/fields/Column_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Object_Name__c</fullName>
    <label>Column Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/fields/ColumnMapping__c.field-meta.xml
<CustomField>
    <fullName>ColumnMapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to mapping object to dynamically create columns</description>
    <label>Column Mapping</label>
    <referenceTo>Mapping__c</referenceTo>
    <relationshipLabel>White Space Templates (Column Mapping)</relationshipLabel>
    <relationshipName>White_Space_Templates_Column</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Template__c/fields/hasDependentPicklistColumns__c.field-meta.xml
<CustomField>
    <fullName>hasDependentPicklistColumns__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Column values are generated based on possible picklist values from the records mapped to cell data and the picklist field&apos;s controlling field.</description>
    <label>Has Dependent Picklist Columns</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space_Template__c/fields/hasDependentPicklistRows__c.field-meta.xml
<CustomField>
    <fullName>hasDependentPicklistRows__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Row values are generated based on possible picklist values from the records mapped to cell data and the picklist field&apos;s controlling field.</description>
    <label>Has Dependent Picklist Rows</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space_Template__c/fields/isLegacy__c.field-meta.xml
<CustomField>
    <fullName>isLegacy__c</fullName>
    <formula>AND(ISBLANK(ColumnMapping__c),ISBLANK(RowMapping__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isLegacy</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space_Template__c/fields/Row_Label_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Row_Label_Field_Name__c</fullName>
    <label>Row Label Field Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/fields/Row_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Row_Object_Name__c</fullName>
    <label>Row Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/fields/RowMapping__c.field-meta.xml
<CustomField>
    <fullName>RowMapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to mapping object to dynamically create rows</description>
    <label>Row Mapping</label>
    <referenceTo>Mapping__c</referenceTo>
    <relationshipLabel>White Space Templates (Row Mapping)</relationshipLabel>
    <relationshipName>White_Space_Templates_Row</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/WhiteSpaceTemplateSelector.cls
public with sharing class WhiteSpaceTemplateSelector extends fflib_SObjectSelector {
    public static WhiteSpaceTemplateSelector newInstance() {
        return (WhiteSpaceTemplateSelector) Application.Selector.newInstance(White_Space_Template__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            White_Space_Template__c.Id,
            White_Space_Template__c.Name,
            White_Space_Template__c.isLegacy__c,
            White_Space_Template__c.hasDependentPicklistColumns__c,
            White_Space_Template__c.hasDependentPicklistRows__c,
            White_Space_Template__c.Column_Object_Name__c,
            White_Space_Template__c.Column_Label_Field_Name__c,
            White_Space_Template__c.ColumnMapping__c,
            White_Space_Template__c.Row_Object_Name__c,
            White_Space_Template__c.Row_Label_Field_Name__c,
            White_Space_Template__c.RowMapping__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return White_Space_Template__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<White_Space_Template__c> selectById(Set<ID> idSet) {
        return new SystemSelector().selectById(this, idSet);
    }

    public List<White_Space_Template__c> selectAll() {
        return new SystemSelector().selectAll(this);
    }

    public List<White_Space_Template__c> selectAllWithRowColumnMappings() {
        fflib_QueryFactory templateQueryFactory = newQueryFactory();

        new MappingSelector()
            .configureQueryFactoryFields(
                templateQueryFactory,
                White_Space_Template__c.ColumnMapping__c.getDescribe().getRelationshipName()
            );
        new MappingSelector()
            .configureQueryFactoryFields(
                templateQueryFactory,
                White_Space_Template__c.RowMapping__c.getDescribe().getRelationshipName()
            );

        return Database.query(templateQueryFactory.toSOQL());
    }

    /******************************
     *       INNER CLASSES
     ******************************/
    private with sharing class SystemSelector {
        public List<White_Space_Template__c> selectById(WhiteSpaceTemplateSelector selector, Set<Id> ids) {
            return Database.query(selector.newQueryFactory(false, false, true).setCondition('id in :ids').toSOQL());
        }

        public List<White_Space_Template__c> selectAll(WhiteSpaceTemplateSelector selector) {
            return Database.query(selector.newQueryFactory(false, false, true).toSOQL());
        }
    }
}