default/objects/Relationship_Map_Member_Auto_History__c/Relationship_Map_Member_Auto_History__c.object-meta.xml
<CustomObject>
    <description>History of contacts that were automatically added to relationship maps by our app.</description>
    <label>Relationship Map Member Auto History</label>
    <nameField>
        <displayFormat>MMAH-{0000}</displayFormat>
        <label>Member History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Member Auto Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Relationship_Map_Member_Auto_History__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Id of the contact that our app has already related to the relationship map.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Plan Member Histories</relationshipLabel>
    <relationshipName>Opportunity_Plan_Member_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map_Member_Auto_History__c/fields/RelationshipMapId__c.field-meta.xml
<CustomField>
    <fullName>RelationshipMapId__c</fullName>
    <description>The Relationship Map where the contact was added by the system</description>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Relationship Map Member Auto Histories</relationshipLabel>
    <relationshipName>Relationship_Map_Member_Auto_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/RMMAutoHistorySelector.cls
public with sharing class RMMAutoHistorySelector extends fflib_SObjectSelector {
    public static RMMAutoHistorySelector newInstance() {
        return (RMMAutoHistorySelector) Application.Selector.newInstance(
            Relationship_Map_Member_Auto_History__c.SObjectType
        );
    }

    /******************************
     *      QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Relationship_Map_Member_Auto_History__c.Id,
            Relationship_Map_Member_Auto_History__c.ContactId__c,
            Relationship_Map_Member_Auto_History__c.RelationshipMapId__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Relationship_Map_Member_Auto_History__c.sObjectType;
    }

    /******************************
     *      SELECT METHODS
     ******************************/

    public List<Relationship_Map_Member_Auto_History__c> selectByMapIds(Set<Id> mapIdSet) {
        if (mapIdSet == null || mapIdSet.isEmpty()) {
            return new List<Relationship_Map_Member_Auto_History__c>();
        }
        return Database.query(newQueryFactory().setCondition('RelationshipMapId__c IN :mapIdSet').toSOQL());
    }
}