default/objects/CRUSH_Settings_Obj__c/CRUSH_Settings_Obj__c.object-meta.xml
<CustomObject>
    <description>The object that holds the organization wide and user specific settings for CRUSH.</description>
    <label>CRUSH Settings</label>
    <nameField>
        <displayFormat>CRUSH-{0000}</displayFormat>
        <label>CRUSH Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRUSH Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/CRUSH_Settings_Obj__c/fields/Account_Plan_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Transfer__c</fullName>
    <label>Account Plan Transfer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TEAM_MEMBER</fullName>
                <label>Assign to oldest team member</label>
            </value>
            <value>
                <fullName>USER</fullName>
                <label>Assign to specific user</label>
            </value>
            <value>
                <fullName>NONE</fullName>
                <default>true</default>
                <label>Do nothing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Account_Plan_Transfer_User__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Transfer_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan Transfer User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CRUSH_Settings_Plan_Transfer</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Allow_Add_Tasks_From_Objective_Component__c.field-meta.xml
<CustomField>
    <fullName>Allow_Add_Tasks_From_Objective_Component__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to allow users to add tasks from the Objective Component</description>
    <inlineHelpText>Check this box to allow users to add tasks from the Objective Component</inlineHelpText>
    <label>Allow Add Tasks From Objective Component</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Auto_Create_Relationship_Maps__c.field-meta.xml
<CustomField>
    <fullName>Auto_Create_Relationship_Maps__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked will allow the system to auto create a map if one isn&apos;t found (and user has permissions) when accessing the Relationship Map component</description>
    <label>Auto Create Relationship Maps</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Auto_Create_Stakeholder_Maps__c.field-meta.xml
<CustomField>
    <fullName>Auto_Create_Stakeholder_Maps__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Should auto create relationship maps for CRUSH Account Plans</description>
    <inlineHelpText>If checked, then it will auto create relationship maps for account plans, if unchecked it will not.  (Note that there are currently no ways to manually create a map from inside the plan, so only uncheck if you are creating through some sort of automation, or just don&apos;t want relationship maps on your account plans)</inlineHelpText>
    <label>Auto Create Stakeholder Maps</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Can_Create_Objects_In_Cross_Sell__c.field-meta.xml
<CustomField>
    <fullName>Can_Create_Objects_In_Cross_Sell__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Toggle this to true to give users the option to create new objects in the Cross-Sell map</description>
    <inlineHelpText>Toggle this to true to give users the option to create new objects in the Cross-Sell map</inlineHelpText>
    <label>Can Create Objects In Cross-Sell</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Contacts_Ancestry_Levels__c.field-meta.xml
<CustomField>
    <fullName>Contacts_Ancestry_Levels__c</fullName>
    <defaultValue>2</defaultValue>
    <description>The number of levels to query when displaying the Hierarchy Chart of Contacts</description>
    <label>Contacts Ancestry Levels</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Enable_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Enable_Notifications__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Notifications</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Enable_Objective_Stage_Based_On_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Enable_Objective_Stage_Based_On_Tasks__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to enable objective stage based on tasks</description>
    <inlineHelpText>Check this box to enable objective stage based on tasks</inlineHelpText>
    <label>Enable objective stage based on tasks</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Goal_Updated__c.field-meta.xml
<CustomField>
    <fullName>Goal_Updated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Goal Updated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Objective_High_Color__c.field-meta.xml
<CustomField>
    <fullName>Objective_High_Color__c</fullName>
    <description>The RGB color when the number of objectives completed is High (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the number of objectives completed is in High (in format #aabbcc)</inlineHelpText>
    <label>Objective High Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Objective_Low_Color__c.field-meta.xml
<CustomField>
    <fullName>Objective_Low_Color__c</fullName>
    <description>The RGB color when the number of objectives completed is low (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the number of objectives completed is low (in format #aabbcc)</inlineHelpText>
    <label>Objective Low Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Objective_Low_Middle_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Objective_Low_Middle_Boundary__c</fullName>
    <description>The boundary between low &amp; middle.  Anything below this value is considered low.</description>
    <inlineHelpText>The boundary between low &amp; middle.  Anything below this value is considered low.</inlineHelpText>
    <label>Objective Low Middle Boundary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Objective_Middle_Color__c.field-meta.xml
<CustomField>
    <fullName>Objective_Middle_Color__c</fullName>
    <description>The RGB color when the number of objectives completed is in the middle (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the number of objectives completed is in the middle (in format #aabbcc)</inlineHelpText>
    <label>Objective Middle Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Objective_Middle_High_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Objective_Middle_High_Boundary__c</fullName>
    <description>The boundary between middle &amp; high.  Anything equal or above this value is considered high.</description>
    <inlineHelpText>The boundary between middle &amp; high.  Anything equal or above this value is considered high.</inlineHelpText>
    <label>Objective Middle High Boundary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Objective_Task_High_Color__c.field-meta.xml
<CustomField>
    <fullName>Objective_Task_High_Color__c</fullName>
    <description>The RGB color when the number of objective tasks completed is high (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the number of objective tasks completed is high (in format #aabbcc)</inlineHelpText>
    <label>Objective Task High Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Objective_Task_Low_Color__c.field-meta.xml
<CustomField>
    <fullName>Objective_Task_Low_Color__c</fullName>
    <description>The RGB color when the number of objective tasks completed is low (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the number of objectives tasks completed is low (in format #aabbcc)</inlineHelpText>
    <label>Objective Task Low Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Objective_Task_Low_Middle_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Objective_Task_Low_Middle_Boundary__c</fullName>
    <description>The boundary between low &amp; middle.  Anything below this value is considered low.</description>
    <inlineHelpText>The boundary between low &amp; middle.  Anything below this value is considered low.</inlineHelpText>
    <label>Objective Task Low Middle Boundary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Objective_Task_Middle_Color__c.field-meta.xml
<CustomField>
    <fullName>Objective_Task_Middle_Color__c</fullName>
    <description>The RGB color when the number of objective tasks completed is in the middle (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the number of objective tasks completed is in the middle (in format #aabbcc)</inlineHelpText>
    <label>Objective Task Middle Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Objective_Task_Middle_High_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Objective_Task_Middle_High_Boundary__c</fullName>
    <description>The boundary between middle &amp; high.  Anything equal or above this value is considered high.</description>
    <inlineHelpText>The boundary between middle &amp; high.  Anything equal or above this value is considered high.</inlineHelpText>
    <label>Objective Task Middle High Boundary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Org_Chart_Default_Fields__c.field-meta.xml
<CustomField>
    <fullName>Org_Chart_Default_Fields__c</fullName>
    <defaultValue>&quot;Contact.Name.Required,Contact.Title,Contact.Email,Key_Stakeholder__c.Influence__c.Required,Key_Stakeholder__c.Support__c.Required&quot;</defaultValue>
    <description>Determines the default fields for the Org Chart display</description>
    <label>Org Chart Default Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Relationship_Map_Default_Fields__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map_Default_Fields__c</fullName>
    <defaultValue>&quot;Contact.Name.Required,Contact.Title,Contact.Email,Relationship_Map_Member__c.Influence__c.Required,Relationship_Map_Member__c.Support__c.Required&quot;</defaultValue>
    <description>Determines the default fields for the Relationship Map display</description>
    <label>Relationship Map Default Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Score_High_Color__c.field-meta.xml
<CustomField>
    <fullName>Score_High_Color__c</fullName>
    <description>The RGB color when the score is high (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the score is high (in format #aabbcc)</inlineHelpText>
    <label>Score High Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Score_Low_Color__c.field-meta.xml
<CustomField>
    <fullName>Score_Low_Color__c</fullName>
    <description>The RGB color when the score is low (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the score is low (in format #aabbcc)</inlineHelpText>
    <label>Score Low Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Score_Low_Mid_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Score_Low_Mid_Boundary__c</fullName>
    <description>The boundary between low &amp; middle.  Anything below this value is considered low.</description>
    <inlineHelpText>The boundary between low &amp; middle.  Anything below this value is considered low.</inlineHelpText>
    <label>Score Low Middle Boundary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Score_Mid_Color__c.field-meta.xml
<CustomField>
    <fullName>Score_Mid_Color__c</fullName>
    <description>The RGB color when the score is in the middle (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the score is in the middle (in format #aabbcc)</inlineHelpText>
    <label>Score Middle Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Score_Mid_High_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Score_Mid_High_Boundary__c</fullName>
    <description>The boundary between middle &amp; high.  Anything equal or above this value is considered high.</description>
    <inlineHelpText>The boundary between middle &amp; high.  Anything equal or above this value is considered high.</inlineHelpText>
    <label>Score Middle High Boundary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Support_Colors_Long__c.field-meta.xml
<CustomField>
    <fullName>Support_Colors_Long__c</fullName>
    <defaultValue>&quot;Blocker:#FF0000;Supporter:#FFC741;Floater:#E5E1E6;Champion:#97D700;&quot;</defaultValue>
    <label>Support Colors</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Team_Member_Permission_Updated__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Permission_Updated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Team Member Permission Updated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Org</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Determines the user these settings are for in the case of user level settings</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CRUSH_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/CrushSettingsObjSelector.cls
public with sharing class CrushSettingsObjSelector extends fflib_SObjectSelector {
    public static CrushSettingsObjSelector newInstance() {
        return (CrushSettingsObjSelector) Application.Selector.newInstance(Crush_Settings_Obj__c.sObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Crush_Settings_Obj__c.Id,
            Crush_Settings_Obj__c.Name,
            Crush_Settings_Obj__c.LastModifiedDate,
            Crush_Settings_Obj__c.Account_Plan_Transfer__c,
            Crush_Settings_Obj__c.Account_Plan_Transfer_User__c,
            Crush_Settings_Obj__c.Allow_Add_Tasks_From_Objective_Component__c,
            Crush_Settings_Obj__c.Enable_Objective_Stage_Based_On_Tasks__c,
            Crush_Settings_Obj__c.Auto_Create_Relationship_Maps__c,
            Crush_Settings_Obj__c.Auto_Create_Stakeholder_Maps__c,
            Crush_Settings_Obj__c.Can_Create_Objects_In_Cross_Sell__c,
            Crush_Settings_Obj__c.Contacts_Ancestry_Levels__c,
            Crush_Settings_Obj__c.Enable_Notifications__c,
            Crush_Settings_Obj__c.Goal_Updated__c,
            Crush_Settings_Obj__c.Key_Date_Updated__c,
            Crush_Settings_Obj__c.Key_Stakeholder_Updated__c,
            Crush_Settings_Obj__c.Objective_High_Color__c,
            Crush_Settings_Obj__c.Objective_Low_Color__c,
            Crush_Settings_Obj__c.Objective_Low_Middle_Boundary__c,
            Crush_Settings_Obj__c.Objective_Middle_Color__c,
            Crush_Settings_Obj__c.Objective_Middle_High_Boundary__c,
            Crush_Settings_Obj__c.Objective_Task_High_Color__c,
            Crush_Settings_Obj__c.Objective_Task_Low_Color__c,
            Crush_Settings_Obj__c.Objective_Task_Low_Middle_Boundary__c,
            Crush_Settings_Obj__c.Objective_Task_Middle_Color__c,
            Crush_Settings_Obj__c.Objective_Task_Middle_High_Boundary__c,
            Crush_Settings_Obj__c.Objectives_Updated__c,
            Crush_Settings_Obj__c.Opportunities_Added__c,
            Crush_Settings_Obj__c.Org_Chart_Default_Fields__c,
            Crush_Settings_Obj__c.Plan_Overview_Updated__c,
            Crush_Settings_Obj__c.Relationship_Map_Default_Fields__c,
            Crush_Settings_Obj__c.Score_High_Color__c,
            Crush_Settings_Obj__c.Score_Low_Color__c,
            Crush_Settings_Obj__c.Score_Low_Mid_Boundary__c,
            Crush_Settings_Obj__c.Score_Mid_Color__c,
            Crush_Settings_Obj__c.Score_Mid_High_Boundary__c,
            Crush_Settings_Obj__c.Status_Updated__c,
            Crush_Settings_Obj__c.Support_Colors_Long__c,
            Crush_Settings_Obj__c.SWOT_Analysis_Updated__c,
            Crush_Settings_Obj__c.Team_Member_Added_Removed__c,
            Crush_Settings_Obj__c.Team_Member_Permission_Updated__c,
            Crush_Settings_Obj__c.Type__c,
            Crush_Settings_Obj__c.Use_System_Create_Task_Modal__c,
            Crush_Settings_Obj__c.User__c,
            Crush_Settings_Obj__c.Use_Account_Team_Permissions__c,
            Crush_Settings_Obj__c.Use_Default_Account_Plan_Score__c,
            Crush_Settings_Obj__c.Use_Percentage_Account_Plan_Score__c,
            Crush_Settings_Obj__c.Task_Objects_Related_To_Account__c,
            Crush_Settings_Obj__c.Task_Objects_Related_To_Account_Plan__c,
            Crush_Settings_Obj__c.Task_Objects_Related_Exclusions__c,
            CRUSH_Settings_Obj__c.WS_Object_Filter__c,
            CRUSH_Settings_Obj__c.Disabled_Objective_Sort_Button__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Crush_Settings_Obj__c.sObjectType;
    }

    public override String getOrderBy() {
        return Crush_Settings_Obj__c.LastModifiedDate.getDescribe().getName() + ' DESC';
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<Crush_Settings_Obj__c> selectOrgSettingsObj() {
        return new SystemSelector().selectOrgSettingsObj(this);
    }

    public List<Crush_Settings_Obj__c> selectUserSettingsObj(Id userId) {
        return new SystemSelector().selectUserSettingsObj(this, userId);
    }

    /******************************
     *   PRIVATE SYSTEM SELECTOR
     ******************************/

    private with sharing class SystemSelector {
        public List<Crush_Settings_Obj__c> selectOrgSettingsObj(CrushSettingsObjSelector selector) {
            return Database.query(
                selector.newQueryFactory(false, false, true).setCondition('Type__c = \'Org\'').setLimit(1).toSOQL()
            );
        }

        public List<Crush_Settings_Obj__c> selectUserSettingsObj(CrushSettingsObjSelector selector, Id userId) {
            return Database.query(
                selector.newQueryFactory(false, false, true)
                    .setCondition('Type__c = \'User\' AND User__c = :userId')
                    .setLimit(1)
                    .toSOQL()
            );
        }
    }
}