default/objects/White_Space_Template_Cell_Field__c/White_Space_Template_Cell_Field__c.object-meta.xml
<CustomObject>
    <label>White Space Template Cell Field</label>
    <nameField>
        <label>White Space Template Cell Field</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Space Template Cell Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Template_Cell_Field__c/fields/DisplayFieldId__c.field-meta.xml
<CustomField>
    <fullName>DisplayFieldId__c</fullName>
    <description>Id of the associated whitespace display field</description>
    <label>Display Field Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template_Cell_Field__c/fields/ValueMapping__c.field-meta.xml
<CustomField>
    <fullName>ValueMapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to mapping object</description>
    <label>Value Mapping</label>
    <referenceTo>Mapping__c</referenceTo>
    <relationshipLabel>White Space Template Cell Fields</relationshipLabel>
    <relationshipName>White_Space_Template_Cell_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Template_Cell_Field__c/fields/WhitespaceTemplate__c.field-meta.xml
<CustomField>
    <fullName>WhitespaceTemplate__c</fullName>
    <label>Cross-Sell Template</label>
    <referenceTo>White_Space_Template__c</referenceTo>
    <relationshipLabel>Cross-Sell Template Cell Fields</relationshipLabel>
    <relationshipName>White_Space_Template_Cell_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/WhiteSpaceTemplateCellFieldSelector.cls
public with sharing class WhiteSpaceTemplateCellFieldSelector extends fflib_SObjectSelector {
    public static WhiteSpaceTemplateCellFieldSelector newInstance() {
        return (WhiteSpaceTemplateCellFieldSelector) Application.Selector.newInstance(
            White_Space_Template_Cell_Field__c.SObjectType
        );
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            White_Space_Template_Cell_Field__c.Id,
            White_Space_Template_Cell_Field__c.DisplayFieldId__c,
            White_Space_Template_Cell_Field__c.ValueMapping__c,
            White_Space_Template_Cell_Field__c.WhitespaceTemplate__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return White_Space_Template_Cell_Field__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<White_Space_Template_Cell_Field__c> selectById(Set<ID> idSet) {
        if (idSet == null) {
            return new List<White_Space_Template_Cell_Field__c>();
        }
        return (List<White_Space_Template_Cell_Field__c>) selectSObjectsById(idSet);
    }

    public List<White_Space_Template_Cell_Field__c> selectByWhiteSpaceTemplateId(Set<Id> templateIds) {
        if (templateIds == null) {
            return new List<White_Space_Template_Cell_Field__c>();
        }
        return Database.query(newQueryFactory().setCondition('WhitespaceTemplate__c IN :templateIds').toSOQL());
    }

    public List<White_Space_Template_Cell_Field__c> selectByWhiteSpaceTemplateIdAndDisplayFieldIds(
        Set<Id> templateIds,
        Set<Id> displayFieldIds
    ) {
        if (templateIds == null) {
            return new List<White_Space_Template_Cell_Field__c>();
        }
        return Database.query(
            newQueryFactory()
                .setCondition('WhitespaceTemplate__c IN :templateIds AND DisplayFieldId__c IN :displayFieldIds')
                .toSOQL()
        );
    }

    public List<White_Space_Template_Cell_Field__c> selectByWhiteSpaceTemplateIdExcludingDisplayFieldIds(
        Set<Id> templateIds,
        Set<Id> displayFieldIdsToExclude
    ) {
        if (templateIds == null) {
            return new List<White_Space_Template_Cell_Field__c>();
        }
        return Database.query(
            newQueryFactory()
                .setCondition(
                    'WhitespaceTemplate__c IN :templateIds AND DisplayFieldId__c  NOT IN :displayFieldIdsToExclude'
                )
                .toSOQL()
        );
    }
}