default/objects/pq_Opportunity_Effectiveness_Association__c/pq_Opportunity_Effectiveness_Association__c.object-meta.xml
<CustomObject>
    <label>Opportunity Effectiveness Association</label>
    <nameField>
        <displayFormat>OEA-{0000}</displayFormat>
        <label>Opportunity Effectiveness Association Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Effectiveness Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Opportunity_Effectiveness_Association__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Effectiveness Associations</relationshipLabel>
    <relationshipName>Opportunity_Effectiveness_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Association__c/fields/Opportunity_Effectiveness_Index__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Effectiveness_Index__c</fullName>
    <label>Opportunity Effectiveness Index</label>
    <referenceTo>pq_Opportunity_Effectiveness_Index__c</referenceTo>
    <relationshipLabel>Opportunity Effectiveness Associations</relationshipLabel>
    <relationshipName>Opportunity_Effectiveness_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/pq_Opportunity_Effectiveness_Index__c.object-meta.xml
<CustomObject>
    <label>Opportunity Effectiveness Index</label>
    <nameField>
        <displayFormat>OEI-{0000}</displayFormat>
        <label>Opportunity Effectiveness Index Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Effectiveness Indexes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Serialized_Lost_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Lost_Data__c</fullName>
    <label>Serialized Lost Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Serialized_Won_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Won_Data__c</fullName>
    <label>Serialized Won Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Lost__c.field-meta.xml
<CustomField>
    <fullName>Total_Lost__c</fullName>
    <label>Total Lost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Lost_With_Contact__c.field-meta.xml
<CustomField>
    <fullName>Total_Lost_With_Contact__c</fullName>
    <label>Total Lost With Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Won__c.field-meta.xml
<CustomField>
    <fullName>Total_Won__c</fullName>
    <label>Total Won</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Won_With_Contact__c.field-meta.xml
<CustomField>
    <fullName>Total_Won_With_Contact__c</fullName>
    <label>Total Won With Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/OpportunityEIAssociationSelectorTest.cls
@isTest
private class OpportunityEIAssociationSelectorTest {
    @isTest
    static void newInstanceTest() {
        OpportunityEIAssociationSelector selector = OpportunityEIAssociationSelector.newInstance();
        System.assertNotEquals(null, selector);
    }

    @isTest
    static void selectByOpportunitiesTest() {

        Opportunity opp1 = new Opportunity(
            Name = 'Opp1',
            CloseDate = Date.today(),
            StageName = 'Prospecting'
        );
        Opportunity opp2 = new Opportunity(
            Name = 'Opp2',
            CloseDate = Date.today(),
            StageName = 'Prospecting'
        );
        insert new List<Opportunity>{ opp1, opp2 };
        
        pq_Opportunity_Effectiveness_Index__c index1 = new pq_Opportunity_Effectiveness_Index__c(
            Serialized_Lost_Data__c = '',
            Serialized_Won_Data__c = '',
            Total_Lost__c = 1,
            Total_Won__c = 2,
            Total_Won_With_Contact__c = 3,
            Total_Lost_With_Contact__c = 4
        );

        pq_Opportunity_Effectiveness_Index__c index2 = new pq_Opportunity_Effectiveness_Index__c(
            Serialized_Lost_Data__c = '',
            Serialized_Won_Data__c = '',
            Total_Lost__c = 12,
            Total_Won__c = 18,
            Total_Won_With_Contact__c = 20,
            Total_Lost_With_Contact__c = 24
        );

        insert new List<pq_Opportunity_Effectiveness_Index__c>{ index1, index2 };

        pq_Opportunity_Effectiveness_Association__c assoc1 = new pq_Opportunity_Effectiveness_Association__c(
            Opportunity_Effectiveness_Index__c = index1.Id,
            Opportunity__c = opp1.Id
        );

        pq_Opportunity_Effectiveness_Association__c assoc2 = new pq_Opportunity_Effectiveness_Association__c(
            Opportunity_Effectiveness_Index__c = index2.Id,
            Opportunity__c = opp2.Id
        );

        insert new List<pq_Opportunity_Effectiveness_Association__c>{ assoc1, assoc2 };


        List<pq_Opportunity_Effectiveness_Association__c> result =  OpportunityEIAssociationSelector.newInstance().selectByOpportunities(new Set<Id>{ opp1.Id });
        System.assertEquals(1, result.size());
        System.assertEquals(opp1.Id, result[0].Opportunity__c);
        System.assertEquals(index1.Id, result[0].Opportunity_Effectiveness_Index__c);
    }

    @isTest
    static void selectByOEITest() {

        Opportunity opp1 = new Opportunity(
            Name = 'Opp1',
            CloseDate = Date.today(),
            StageName = 'Prospecting'
        );
        Opportunity opp2 = new Opportunity(
            Name = 'Opp2',
            CloseDate = Date.today(),
            StageName = 'Prospecting'
        );
        insert new List<Opportunity>{ opp1, opp2 };
        
        pq_Opportunity_Effectiveness_Index__c index1 = new pq_Opportunity_Effectiveness_Index__c(
            Serialized_Lost_Data__c = '',
            Serialized_Won_Data__c = '',
            Total_Lost__c = 1,
            Total_Won__c = 2,
            Total_Won_With_Contact__c = 3,
            Total_Lost_With_Contact__c = 4
        );

        pq_Opportunity_Effectiveness_Index__c index2 = new pq_Opportunity_Effectiveness_Index__c(
            Serialized_Lost_Data__c = '',
            Serialized_Won_Data__c = '',
            Total_Lost__c = 12,
            Total_Won__c = 18,
            Total_Won_With_Contact__c = 20,
            Total_Lost_With_Contact__c = 24
        );

        insert new List<pq_Opportunity_Effectiveness_Index__c>{ index1, index2 };

        pq_Opportunity_Effectiveness_Association__c assoc1 = new pq_Opportunity_Effectiveness_Association__c(
            Opportunity_Effectiveness_Index__c = index1.Id,
            Opportunity__c = opp1.Id
        );

        pq_Opportunity_Effectiveness_Association__c assoc2 = new pq_Opportunity_Effectiveness_Association__c(
            Opportunity_Effectiveness_Index__c = index2.Id,
            Opportunity__c = opp2.Id
        );

        insert new List<pq_Opportunity_Effectiveness_Association__c>{ assoc1, assoc2 };


        List<pq_Opportunity_Effectiveness_Association__c> result =  OpportunityEIAssociationSelector.newInstance().selectByOEI(new Set<Id>{ index2.Id });
        System.assertEquals(1, result.size());
        System.assertEquals(opp2.Id, result[0].Opportunity__c);
        System.assertEquals(index2.Id, result[0].Opportunity_Effectiveness_Index__c);
    }
}