default/objects/pq_CRUSH_Plan_Overview__c/pq_CRUSH_Plan_Overview__c.object-meta.xml
<CustomObject>
    <label>CRUSH Plan Overview</label>
    <nameField>
        <label>Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRUSH Plan Overviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_CRUSH_Plan_Overview__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <label>Background Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/PlanOverviewWrapper.cls
public with sharing class PlanOverviewWrapper {
    @AuraEnabled
    public Id id;

    @AuraEnabled
    public string title;

    @AuraEnabled
    public string backgroundColor;

    @AuraEnabled
    public string description;

    @AuraEnabled
    public Boolean updateable { get; set; }

    @AuraEnabled
    public Boolean deleteable { get; set; }

    public PlanOverviewWrapper(pq_CRUSH_Plan_Overview__c planOverview, Boolean updateable, Boolean deleteable) {
        this.id = planOverview.Id;
        this.title = planOverview.Title__c;
        this.backgroundColor = planOverview.Background_Color__c != null ? planOverview.Background_Color__c : '#cccccc';
        this.description = planOverview.Description__c;
        this.updateable = updateable;
        this.deleteable = deleteable;
    }
}