default/objects/Mapping__c/Mapping__c.object-meta.xml
<CustomObject>
    <description>Polymorphic Relationship Mapping Object</description>
    <label>Mapping</label>
    <nameField>
        <label>Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Mapping__c/fields/DisplayLabelField__c.field-meta.xml
<CustomField>
    <fullName>DisplayLabelField__c</fullName>
    <description>Fully qualified API name used as the display label</description>
    <label>Label Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Mapping__c/fields/GroupResults__c.field-meta.xml
<CustomField>
    <fullName>GroupResults__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Group the records matching this mapping</description>
    <inlineHelpText>Records fetched for this mapping will be grouped together if they have the same label (used for row/column template)</inlineHelpText>
    <label>Group Results</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Mapping__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <description>Fully qualified object type name</description>
    <label>Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Mapping__c/fields/ParentField__c.field-meta.xml
<CustomField>
    <fullName>ParentField__c</fullName>
    <label>Parent Relationship Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Mapping__c/fields/ValueField__c.field-meta.xml
<CustomField>
    <fullName>ValueField__c</fullName>
    <description>Fully qualified API name of field to lookup for a value</description>
    <label>Value Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Mapping_Condition__c/Mapping_Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Mapping Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Mapping_Condition__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Mapping_Condition_Group__c/Mapping_Condition_Group__c.object-meta.xml
<CustomObject>
    <label>Condition Group</label>
    <nameField>
        <displayFormat>MCG-{0000}</displayFormat>
        <label>Mapping Condition Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Mapping_Condition_Group__c/fields/Mapping__c.field-meta.xml
<CustomField>
    <fullName>Mapping__c</fullName>
    <label>Mapping</label>
    <referenceTo>Mapping__c</referenceTo>
    <relationshipLabel>Condition Groups</relationshipLabel>
    <relationshipName>Condition_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Mapping_Condition_Group__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>Logical operator for conditions within the group. Valid values are &apos;AND&apos;, &apos;OR&apos;.</description>
    <label>Operator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Mapping_Condition_Group__c/fields/Parent_Condition_Group__c.field-meta.xml
<CustomField>
    <fullName>Parent_Condition_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Condition Group</label>
    <referenceTo>Mapping_Condition_Group__c</referenceTo>
    <relationshipLabel>Condition Groups</relationshipLabel>
    <relationshipName>Condition_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/WhiteSpaceTemplateMappingWrapper.cls
@SuppressWarnings('PMD.ExcessivePublicCount')
public with sharing class WhiteSpaceTemplateMappingWrapper {
    @AuraEnabled
    public Id id { get; set; }
    @AuraEnabled
    public String name { get; set; }
    @AuraEnabled
    public String objectName { get; set; }
    @AuraEnabled
    public String objectLabel { get; private set; }
    @AuraEnabled
    public String objectLabelPlural { get; private set; }
    @AuraEnabled
    public String labelFieldName { get; set; }
    @AuraEnabled
    public String valueFieldName { get; set; }
    @AuraEnabled
    public String parentIdFieldName { get; set; }
    @AuraEnabled
    public Boolean groupResults { get; set; }
    @AuraEnabled
    public ConditionModel conditions { get; set; }
    @AuraEnabled
    public Boolean isObjectCreateable { get; set; }

    @AuraEnabled
    public FieldMetaData valueFieldInfo { get; private set; }

    @AuraEnabled
    public FieldMetaData labelFieldInfo { get; private set; }

    public DescribeSObjectResult description { get; private set; }

    public WhiteSpaceTemplateMappingWrapper() {
        this(null, null);
    }

    public WhiteSpaceTemplateMappingWrapper(String objectName, String labelField, String valueField) {
        if (objectName == null) {
            return;
        }
        this.objectName = objectName;
        this.labelFieldName = labelField;
        this.valueFieldName = valueField;
        this.groupResults = false;
        setupAutomaticFields();
    }

    public WhiteSpaceTemplateMappingWrapper(Mapping__c mapping) {
        this(
            mapping,
            mapping.Condition_Groups__r != null
                ? mapping.Condition_Groups__r
                : MappingConditionGroupSelector.newInstance().selectByMappingId(new Set<Id>{ mapping.Id })
        );
    }

    public WhiteSpaceTemplateMappingWrapper(Mapping__c mapping, List<Mapping_Condition_Group__c> conditionGroups) {
        if (mapping == null) {
            return;
        }
        this.id = mapping.id;
        this.name = mapping.Name;
        this.objectName = mapping.ObjectType__c;
        this.labelFieldName = mapping.DisplayLabelField__c;
        this.valueFieldName = mapping.ValueField__c;
        this.parentIdFieldName = mapping.ParentField__c;
        this.groupResults = mapping.GroupResults__c;
        this.conditions = buildConditions(mapping, conditionGroups);
        setupAutomaticFields();
    }

    public WhiteSpaceTemplateMappingWrapper(WSRelatedObjectWrapper relationshipWrapper) {
        this.objectName = relationshipWrapper.objDesc.getName();
        this.labelFieldName = relationshipWrapper.labelFieldName;
        this.valueFieldName = relationshipWrapper.labelFieldName;
        setupAutomaticFields(relationshipWrapper);
        this.labelFieldInfo = this.valueFieldInfo;
    }

    private void setupAutomaticFields() {
        this.description = UTIL_Describe.getObjectDescribe(this.objectName);
        this.objectLabel = UTIL_Describe.getObjectLabel(this.objectName);
        this.objectLabelPlural = UTIL_Describe.getObjectLabelPlural(this.objectName);
        this.isObjectCreateable = this.description.isCreateable();

        if (String.isNotBlank(this.valueFieldName)) {
            if (this.valueFieldName.contains('.')) {
                String subObjName = this.valueFieldName.substringBefore('.');
                String subFieldName = this.valueFieldName.substringAfter('.');
                this.valueFieldInfo = new FieldMetadata(subObjName, subFieldName);
            } else {
                this.valueFieldInfo = new FieldMetadata(this.objectName, this.valueFieldName);
            }
        }
        if (String.isNotBlank(this.labelFieldName)) {
            if (this.labelFieldName.contains('.')) {
                String subObjName = this.labelFieldName.substringBefore('.');
                String subFieldName = this.labelFieldName.substringAfter('.');
                this.labelFieldInfo = new FieldMetadata(subObjName, subFieldName);
            } else {
                this.labelFieldInfo = new FieldMetadata(this.objectName, this.labelFieldName);
            }
        }
    }

    private void setupAutomaticFields(WSRelatedObjectWrapper relationshipWrapper) {
        this.description = relationshipWrapper.objDesc;
        this.objectLabel = relationshipWrapper.objDesc.getLabel();
        this.objectLabelPlural = relationshipWrapper.objDesc.getLabelPlural();
        this.isObjectCreateable = this.description.isCreateable();

        if (relationshipWrapper.objDesc != null && relationshipWrapper.labelFieldDesc != null) {
            this.valueFieldInfo = new FieldMetadata(
                relationshipWrapper.objDesc.getSObjectType(),
                relationshipWrapper.labelFieldDesc.getSobjectField()
            );
        }
    }

    private static ConditionModel buildConditions(
        Mapping__c mapping,
        List<Mapping_Condition_Group__c> conditionGroups
    ) {
        if (!conditionGroups.isEmpty()) {
            Mapping_Condition_Group__c root = (Mapping_Condition_Group__c) new Collection(conditionGroups)
                .find(Mapping_Condition_Group__c.Parent_Condition_Group__c, '==', null);
            root = root != null ? root : conditionGroups[0];
            ConditionModel model = new ConditionModel();
            model.singleConditions = new List<MappingConditionWrapper>();
            model.operator = root.Operator__c;
            List<Mapping_Condition__c> mappingConditions = MappingConditionSelector.newInstance()
                .selectByConditionGroupId(new Set<Id>{ root.id });
            for (Mapping_Condition__c mappingCondition : mappingConditions) {
                model.singleConditions.add(new MappingConditionWrapper(mappingCondition, mapping.ObjectType__c));
            }

            return model;
        }
        return null;
    }

    public List<String> getQueryFields() {
        List<String> queryFields = new List<String>();
        if (String.isNotBlank(this.labelFieldName) && !this.labelFieldName.startsWith('OpportunityLineItem.')) {
            queryFields.add(this.labelFieldName);
        }
        if (String.isNotBlank(this.valueFieldName) && !this.valueFieldName.startsWith('OpportunityLineItem.')) {
            queryFields.add(this.valueFieldName);
        }
        if (String.isNotBlank(this.parentIdFieldName) && !this.parentIdFieldName.startsWith('OpportunityLineItem.')) {
            queryFields.add(this.parentIdFieldName);
        }
        return queryFields;
    }

    public List<String> getOLIQueryFields() {
        List<String> queryFields = new List<String>();
        if (String.isNotBlank(this.labelFieldName) && this.labelFieldName.startsWith('OpportunityLineItem.')) {
            queryFields.add(this.labelFieldName);
        }
        if (String.isNotBlank(this.valueFieldName) && this.valueFieldName.startsWith('OpportunityLineItem.')) {
            queryFields.add(this.valueFieldName);
        }
        if (String.isNotBlank(this.parentIdFieldName) && this.parentIdFieldName.startsWith('OpportunityLineItem.')) {
            queryFields.add(this.parentIdFieldName);
        }
        return queryFields;
    }
}