default/objects/Mapping__c/Mapping__c.object-meta.xml
<CustomObject>
    <description>Polymorphic Relationship Mapping Object</description>
    <label>Mapping</label>
    <nameField>
        <label>Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Mapping__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <description>Fully qualified object type name</description>
    <label>Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Mapping__c/fields/ValueField__c.field-meta.xml
<CustomField>
    <fullName>ValueField__c</fullName>
    <description>Fully qualified API name of field to lookup for a value</description>
    <label>Value Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/White_Space_Template__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Template</label>
    <nameField>
        <label>Cross-Sell Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/White_Space_Template__c/fields/Column_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Object_Name__c</fullName>
    <label>Column Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/fields/ColumnMapping__c.field-meta.xml
<CustomField>
    <fullName>ColumnMapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to mapping object to dynamically create columns</description>
    <label>Column Mapping</label>
    <referenceTo>Mapping__c</referenceTo>
    <relationshipLabel>White Space Templates (Column Mapping)</relationshipLabel>
    <relationshipName>White_Space_Templates_Column</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Template__c/fields/Row_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Row_Object_Name__c</fullName>
    <label>Row Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/fields/RowMapping__c.field-meta.xml
<CustomField>
    <fullName>RowMapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to mapping object to dynamically create rows</description>
    <label>Row Mapping</label>
    <referenceTo>Mapping__c</referenceTo>
    <relationshipLabel>White Space Templates (Row Mapping)</relationshipLabel>
    <relationshipName>White_Space_Templates_Row</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/WhiteSpaceTemplatePickerController.cls
public with sharing class WhiteSpaceTemplatePickerController {
    @AuraEnabled
    public static List<TemplateInfo> getTemplateList() {
        List<TemplateInfo> templates = new List<TemplateInfo>();
        for (White_Space_Template__c temp : WhiteSpaceTemplateSelector.newInstance().selectAllWithRowColumnMappings()) {
            try {
                TemplateInfo templateInfo = new TemplateInfo(temp);
                templates.add(templateInfo);
            } catch (Exception e) {
                continue;
            }
        }
        return templates;
    }

    @AuraEnabled
    public static WhiteSpaceTemplateWrapper getTemplateWrapper(Id templateId) {
        try {
            White_Space_Template__c template = WhiteSpaceTemplateSelector.newInstance()
                .selectById(new Set<Id>{ templateId })[0];
            return new WhiteSpaceTemplateWrapper(template);
        } catch (Exception e) {
            Application.throwAuraHandledException(e);
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Integer> getHeaderTotals(
        WhiteSpaceTemplateMappingWrapper columnMapping,
        WhiteSpaceTemplateMappingWrapper rowMapping
    ) {
        return new Map<String, Integer>{
            'columnTotal' => WhiteSpaceUtils.getTotalCount(columnMapping),
            'rowTotal' => WhiteSpaceUtils.getTotalCount(rowMapping)
        };
    }

    public class TemplateInfo {
        @AuraEnabled
        public Id id;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String columnName;
        @AuraEnabled
        public String rowName;

        @TestVisible
        private TemplateInfo(White_Space_Template__c template) {
            this.id = template.id;
            this.name = template.name;
            this.columnName = String.isBlank(template.Column_Object_Name__c)
                ? getHeaderDisplayValueForMapping(template.ColumnMapping__r)
                : UTIL_Describe.getObjectLabelPlural(template.Column_Object_Name__c);
            this.rowName = String.isBlank(template.Row_Object_Name__c)
                ? getHeaderDisplayValueForMapping(template.RowMapping__r)
                : UTIL_Describe.getObjectLabelPlural(template.Row_Object_Name__c);
        }
    }

    private static String getHeaderDisplayValueForMapping(Mapping__c mapping) {
        String returnValue = '';
        if (WhiteSpaceUtils.isPicklistMappingType(mapping)) {
            returnValue = UTIL_Describe.getFieldLabelSafe(mapping.ObjectType__c, mapping.ValueField__c);
        } else {
            returnValue = UTIL_Describe.getObjectLabelPlural(mapping.ObjectType__c);
        }
        return returnValue;
    }
}