default/objects/Mapping__c/Mapping__c.object-meta.xml
<CustomObject>
    <description>Polymorphic Relationship Mapping Object</description>
    <label>Mapping</label>
    <nameField>
        <label>Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Mapping__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <description>Fully qualified object type name</description>
    <label>Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Mapping__c/fields/ValueField__c.field-meta.xml
<CustomField>
    <fullName>ValueField__c</fullName>
    <description>Fully qualified API name of field to lookup for a value</description>
    <label>Value Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Amount_Type__c/White_Space_Amount_Type__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Amount Type</label>
    <nameField>
        <label>Cross-Sell Amount Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Amount Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/White_Space_Template__c/White_Space_Template__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Template</label>
    <nameField>
        <label>Cross-Sell Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/White_Space_Template__c/fields/Column_Label_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Label_Field_Name__c</fullName>
    <label>Column Label Field Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/fields/Column_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Object_Name__c</fullName>
    <label>Column Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/fields/ColumnMapping__c.field-meta.xml
<CustomField>
    <fullName>ColumnMapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to mapping object to dynamically create columns</description>
    <label>Column Mapping</label>
    <referenceTo>Mapping__c</referenceTo>
    <relationshipLabel>White Space Templates (Column Mapping)</relationshipLabel>
    <relationshipName>White_Space_Templates_Column</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Template__c/fields/hasDependentPicklistColumns__c.field-meta.xml
<CustomField>
    <fullName>hasDependentPicklistColumns__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Column values are generated based on possible picklist values from the records mapped to cell data and the picklist field&apos;s controlling field.</description>
    <label>Has Dependent Picklist Columns</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space_Template__c/fields/hasDependentPicklistRows__c.field-meta.xml
<CustomField>
    <fullName>hasDependentPicklistRows__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Row values are generated based on possible picklist values from the records mapped to cell data and the picklist field&apos;s controlling field.</description>
    <label>Has Dependent Picklist Rows</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space_Template__c/fields/isLegacy__c.field-meta.xml
<CustomField>
    <fullName>isLegacy__c</fullName>
    <formula>AND(ISBLANK(ColumnMapping__c),ISBLANK(RowMapping__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isLegacy</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space_Template__c/fields/Row_Label_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Row_Label_Field_Name__c</fullName>
    <label>Row Label Field Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/fields/Row_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Row_Object_Name__c</fullName>
    <label>Row Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Template__c/fields/RowMapping__c.field-meta.xml
<CustomField>
    <fullName>RowMapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to mapping object to dynamically create rows</description>
    <label>Row Mapping</label>
    <referenceTo>Mapping__c</referenceTo>
    <relationshipLabel>White Space Templates (Row Mapping)</relationshipLabel>
    <relationshipName>White_Space_Templates_Row</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Template_Cell_Field__c/White_Space_Template_Cell_Field__c.object-meta.xml
<CustomObject>
    <label>White Space Template Cell Field</label>
    <nameField>
        <label>White Space Template Cell Field</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Space Template Cell Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/classes/WhiteSpaceTemplateWrapperTest.cls
@isTest
private class WhiteSpaceTemplateWrapperTest {
    @isTest
    private static void basicInitializerTest() {
        WhiteSpaceTemplateWrapper wrapper = new WhiteSpaceTemplateWrapper();

        System.assertEquals(null, wrapper.id);
        System.assertEquals(null, wrapper.name);
        System.assertEquals(null, wrapper.rowConfiguration);
        System.assertEquals(null, wrapper.columnConfiguration);
        System.assertEquals(null, wrapper.amountTypeFields);
        System.assertEquals(null, wrapper.basicFields);
    }

    @isTest
    private static void initializerWithTemplateTest() {
        TestMockData md = new TestMockData();
        WhiteSpaceAmountTypeSelector mockAtSelector = md.mockWhiteSpaceAmountTypeSelector;
        WhiteSpaceTemplateCellFieldSelector mockCFSelector = md.mockWSTCellFieldSelector;
        MappingSelector mockMappingSelector = md.mockMappingSelector;
        White_Space_Amount_Type__c mockAT = md.mockWhiteSpaceAmountType; //NOPMD - Needs to be called in order for it to be mocked in the test

        md.mocks.startStubbing();
        md.mocks.when(mockAtSelector.selectInactive()).thenReturn(new List<White_Space_Amount_Type__c>());
        md.mocks.when(
                mockCFSelector.selectByWhiteSpaceTemplateIdExcludingDisplayFieldIds(
                    new Set<Id>{ md.mockWhiteSpaceTemplateId },
                    new Set<Id>()
                )
            )
            .thenReturn(new List<White_Space_Template_Cell_Field__c>{ md.mockCellField });
        md.mocks.when(
                mockMappingSelector.selectByIdWithConditionGroups(
                    new Set<Id>{ md.mockAssetMappingId, md.mockProductMappingId, md.mockAccountMappingId }
                )
            )
            .thenReturn(new List<Mapping__c>{ md.mockAssetMapping, md.mockProductMapping, md.mockAccountMapping });
        md.mocks.stopStubbing();

        WhiteSpaceTemplateWrapper wrapper = new WhiteSpaceTemplateWrapper(md.mockWhiteSpaceTemplate);

        System.assertEquals(md.mockWhiteSpaceTemplateId, wrapper.id);
        System.assertEquals(md.mockWhiteSpaceTemplate.Name, wrapper.name);
        System.assertEquals(md.mockAccountMapping.ObjectType__c, wrapper.rowConfiguration.mapping.objectName);
        System.assertEquals(md.mockProductMapping.ObjectType__c, wrapper.columnConfiguration.mapping.objectName);
        System.assertEquals(1, wrapper.amountTypeFields.size());
        System.assertNotEquals(null, wrapper.amountTypeFields.get(md.mockWhiteSpaceAmountTypeId));
    }

    @isTest
    private static void initializerWithTemplateNoCellFieldTest() {
        TestMockData md = new TestMockData();
        WhiteSpaceAmountTypeSelector mockAtSelector = md.mockWhiteSpaceAmountTypeSelector;
        WhiteSpaceTemplateCellFieldSelector mockCFSelector = md.mockWSTCellFieldSelector;
        MappingSelector mockMappingSelector = md.mockMappingSelector;
        White_Space_Amount_Type__c mockAT = md.mockWhiteSpaceAmountType; //NOPMD - Needs to be called in order for it to be mocked in the test

        md.mocks.startStubbing();
        md.mocks.when(mockAtSelector.selectInactive()).thenReturn(new List<White_Space_Amount_Type__c>());
        md.mocks.when(
                mockCFSelector.selectByWhiteSpaceTemplateIdExcludingDisplayFieldIds(
                    new Set<Id>{ md.mockWhiteSpaceTemplateId },
                    new Set<Id>()
                )
            )
            .thenReturn(new List<White_Space_Template_Cell_Field__c>());
        md.mocks.when(
                mockMappingSelector.selectByIdWithConditionGroups(
                    new Set<Id>{ md.mockProductMappingId, md.mockAccountMappingId }
                )
            )
            .thenReturn(new List<Mapping__c>{ md.mockProductMapping, md.mockAccountMapping });
        md.mocks.stopStubbing();

        WhiteSpaceTemplateWrapper wrapper = new WhiteSpaceTemplateWrapper(md.mockWhiteSpaceTemplate);

        System.assertEquals(md.mockWhiteSpaceTemplateId, wrapper.id);
        System.assertEquals(md.mockWhiteSpaceTemplate.Name, wrapper.name);
        System.assertEquals(md.mockAccountMapping.ObjectType__c, wrapper.rowConfiguration.mapping.objectName);
        System.assertEquals(md.mockProductMapping.ObjectType__c, wrapper.columnConfiguration.mapping.objectName);
        System.assertEquals(0, wrapper.amountTypeFields.size());
    }

    @isTest
    private static void initializerWithLegacyTemplateTest() {
        TestMockData md = new TestMockData();

        White_Space_Template__c mockLegacyWhiteSpaceTemplate = md.mockLegacyWhiteSpaceTemplate;
        mockLegacyWhiteSpaceTemplate.id = null;
        insert md.mockLegacyWhiteSpaceTemplate;
        White_Space_Template__c template = getTemplate(mockLegacyWhiteSpaceTemplate.Name);

        WhiteSpaceTemplateWrapper wrapper = new WhiteSpaceTemplateWrapper(template);

        System.assertEquals(true, wrapper.isLegacyTemplate);
        System.assertEquals(mockLegacyWhiteSpaceTemplate.Id, wrapper.id);
        System.assertEquals(mockLegacyWhiteSpaceTemplate.Name, wrapper.name);
        System.assertEquals(
            mockLegacyWhiteSpaceTemplate.Row_Object_Name__c,
            wrapper.rowConfiguration.mapping.objectName
        );
        System.assertEquals(
            mockLegacyWhiteSpaceTemplate.Column_Object_Name__c,
            wrapper.columnConfiguration.mapping.objectName
        );
        System.assertEquals(0, wrapper.amountTypeFields.size());
    }

    private static White_Space_Template__c getTemplate(String templateName) {
        return [
            SELECT
                Id,
                Name,
                Column_Object_Name__c,
                Column_Label_Field_Name__c,
                ColumnMapping__c,
                ColumnMapping__r.ObjectType__c,
                ColumnMapping__r.ValueField__c,
                Row_Object_Name__c,
                Row_Label_Field_Name__c,
                RowMapping__c,
                RowMapping__r.ObjectType__c,
                RowMapping__r.ValueField__c,
                hasDependentPicklistColumns__c,
                hasDependentPicklistRows__c,
                isLegacy__c
            FROM White_Space_Template__c
            WHERE Name = :templateName
            LIMIT 1
        ];
    }
}