default/objects/pq_Support__c/pq_Support__c.object-meta.xml
<CustomObject>
    <label>Support</label>
    <nameField>
        <label>Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Support__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color RGB value in the form of #FF0011</description>
    <inlineHelpText>Enter color RGB value in the form of #FF0011</inlineHelpText>
    <label>Color</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/SupportWrapperTest.cls
@isTest
private class SupportWrapperTest {
    @isTest
    static void initializeTest() {

        pq_Support__c s1 = new pq_Support__c(Name = 'Low', Color__c = '#122123', Label__c = 'lowlabel');
        insert s1;

        SupportWrapper sw1 = new SupportWrapper('test1');
        SupportWrapper sw2 = new SupportWrapper(s1);
        System.assertEquals('test1', sw1.value);
        System.assertEquals(s1.Label__c, sw2.value);
        System.assertEquals(s1.Color__c, sw2.color);
    }

}