default/objects/pq_Support__c/pq_Support__c.object-meta.xml
<CustomObject>
    <label>Support</label>
    <nameField>
        <label>Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Support__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color RGB value in the form of #FF0011</description>
    <inlineHelpText>Enter color RGB value in the form of #FF0011</inlineHelpText>
    <label>Color</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/SupportWrapper.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class SupportWrapper {
    @AuraEnabled
    public Id id;

    @AuraEnabled
    public String name;

    @AuraEnabled
    public String value;

    @AuraEnabled
    public String color;

    public SupportWrapper(String value) {
        this.value = value;
        this.color = '#aaaaaa';
    }

    public SupportWrapper(pq_Support__c supp) {
        this.id = supp.Id;
        this.name = supp.Name;
        this.value = supp.Label__c;
        this.color = supp.Color__c;
    }
}