default/objects/RM_Org_Setting__c/RM_Org_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Org Setting</label>
    <nameField>
        <label>RM_Org_Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM_Org_Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Org_Setting__c/fields/Auto_Layout__c.field-meta.xml
<CustomField>
    <fullName>Auto_Layout__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to have the Relationship Map automatically layout the nodes. Uncheck to do this manually.</description>
    <inlineHelpText>Check this to have the Relationship Map automatically layout the nodes. Uncheck to do this manually.</inlineHelpText>
    <label>Auto Layout</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Card_Style__c.field-meta.xml
<CustomField>
    <fullName>Card_Style__c</fullName>
    <description>Select the detail level of the card.</description>
    <inlineHelpText>Select the detail level of the card.</inlineHelpText>
    <label>Card Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detail</fullName>
            </value>
            <value>
                <fullName>Compact</fullName>
            </value>
            <value>
                <fullName>FixedSize</fullName>
                <default>true</default>
                <label>FixedSize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Create_New_Contact__c.field-meta.xml
<CustomField>
    <fullName>Create_New_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Create New Contact</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Display_Style__c.field-meta.xml
<CustomField>
    <fullName>Display_Style__c</fullName>
    <description>Select the chart display styles. For charts that are wide, choose the last parents arranging children vertically.</description>
    <inlineHelpText>Select the chart display styles. For charts that are wide, choose the last parents arranging children vertically.</inlineHelpText>
    <label>Display Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horizontal</fullName>
                <default>true</default>
                <label>Horizontal</label>
            </value>
            <value>
                <fullName>Leaf_Vertical</fullName>
                <label>Vertical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Contact_Context_Menu__c.field-meta.xml
<CustomField>
    <fullName>Enable_Contact_Context_Menu__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to show and let users click on Contact to view the Salesforce contact modal</description>
    <inlineHelpText>Check this to show and let users click on Contact to view the Salesforce contact modal</inlineHelpText>
    <label>Enable Contact Context Menu</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Drag_Select__c.field-meta.xml
<CustomField>
    <fullName>Enable_Drag_Select__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option to enable drag-select. To drag-select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</description>
    <inlineHelpText>Check this option to enable drag-select. To drag-select, click &amp; hold the mouse button for 2 seconds, then drag around objects to select them. Disable this option if you are experiencing issues with panning.</inlineHelpText>
    <label>Enable Drag Select</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Group_Selection_Context_Menu__c.field-meta.xml
<CustomField>
    <fullName>Enable_Group_Selection_Context_Menu__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag for the abilty to create and adjust groups in the Relationship Map</description>
    <inlineHelpText>Check this to allow creating deleting and editing groups in Relationship Maps</inlineHelpText>
    <label>Enable Grouping</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Map_Member_Context_Menu__c.field-meta.xml
<CustomField>
    <fullName>Enable_Map_Member_Context_Menu__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to enable the context menu for Map Members or Key Stakeholder in the Relationship Map</description>
    <inlineHelpText>Check this to enable the context menu for Map Members or Key Stakeholder in the Relationship Map</inlineHelpText>
    <label>Enable Map Member Context Menu</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Omni_Viewer_Context_Menu__c.field-meta.xml
<CustomField>
    <fullName>Enable_Omni_Viewer_Context_Menu__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to enable the OmniViewer context menu in the Relationship Map</description>
    <inlineHelpText>Check this to enable the OmniViewer context menu in the Relationship Map</inlineHelpText>
    <label>Enable OmniViewer context Menu</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Sugg_Con_For_RMSettings__c.field-meta.xml
<CustomField>
    <fullName>Enable_Sugg_Con_For_RMSettings__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to allow users to see suggested contacts for the relationship map settings.</description>
    <inlineHelpText>Check this box to allow users to see suggested contacts for the relationship map settings.</inlineHelpText>
    <label>Enable Suggested Contacts For RMSetting</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Suggested_Contacts_For_RM__c.field-meta.xml
<CustomField>
    <fullName>Enable_Suggested_Contacts_For_RM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to allow users to see suggested contacts for the relationship map.</description>
    <inlineHelpText>Check this box to allow users to see suggested contacts for the relationship map.</inlineHelpText>
    <label>Enable Suggested Contacts For RM</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Is_Badge_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Badge_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check to associate a badge with the contact regardless of which map the contact is on</description>
    <inlineHelpText>Check to associate a badge with the contact regardless of which map the contact is on.</inlineHelpText>
    <label>Is Badge Global Scope</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Is_Group_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Group_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to use groups that are global (They can show up in other Relationship Maps). Leaving this unchecked will use local groups (These groups will only be visible in this Relationship Map).</description>
    <inlineHelpText>Check this to use groups that are global (They can show up in other Relationship Maps). Leaving this unchecked will use local groups (These groups will only be visible in this Relationship Map).</inlineHelpText>
    <label>Is Group Global Scope</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Is_Influence_Support_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Influence_Support_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Influence Support Global Scope</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Is_Relationship_Line_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Relationship_Line_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to use Global Relationship Lines. Leave this unchecked to create and use lines that are visible only in this Relationship Map</description>
    <inlineHelpText>Check this to use Global Relationship Lines. Leave this unchecked to create and use lines that are visible only in this Relationship Map</inlineHelpText>
    <label>Is Relationship Line Global Scope</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Is_Reports_To_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Reports_To_Global_Scope__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Reports To Global Scope</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Lead_Tab__c.field-meta.xml
<CustomField>
    <fullName>Lead_Tab__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lead Tab</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Prolifiq_Extended_Tools_URL__c.field-meta.xml
<CustomField>
    <fullName>Prolifiq_Extended_Tools_URL__c</fullName>
    <description>External URL for extended features.</description>
    <inlineHelpText>External URL for extended features.</inlineHelpText>
    <label>Prolifiq Extended Tools URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Relationship_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Line_Opacity__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the custom relationship lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Relationship Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Reports_To_Line_Opacity__c.field-meta.xml
<CustomField>
    <fullName>Reports_To_Line_Opacity__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</description>
    <inlineHelpText>The opacity of the Contact &apos;Reports To&apos; hierarchy lines.  Set a percentage value between 0% to make the lines hidden and 100% for full visibility.</inlineHelpText>
    <label>Reports To Line Opacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Auto_Manual_Toggle__c.field-meta.xml
<CustomField>
    <fullName>Show_Auto_Manual_Toggle__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Auto Manual Toggle</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Chart_Settings__c.field-meta.xml
<CustomField>
    <fullName>Show_Chart_Settings__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked then the settings button in the dropdown menu of key stakeholder/relationship maps will show based on user permissions.  If unchecked this will hide the button regardless of any permissions for users to see the settings button.</description>
    <inlineHelpText>If this is unchecked then no users in the org will see the settings button in the key stakeholder/relationship map dropdown menu regardless of what permissions they have set for showing the button.  This is org wide.</inlineHelpText>
    <label>Show Chart Settings</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Clone_Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Show_Clone_Relationship_Map__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked then the clone button in the dropdown menu of relationship maps will show based on user permissions.  If unchecked this will hide the button regardless of any permissions for users to see the clone button.</description>
    <inlineHelpText>If this is unchecked then no users in the org will see the clone button in the relationship map dropdown menu regardless of what permissions they have set for showing the button.  This is org wide.</inlineHelpText>
    <label>Show Clone Relationship Map</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Empty_Fields__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want fields that have no value to show up. For example, if users don&apos;t have an email it will show [email]. Uncheck this if you want fields that have no value to not show up.</description>
    <inlineHelpText>Check this if you want fields that have no value to show up. For example, if users don&apos;t have an email it will show [email]. Uncheck this if you want fields that have no value to not show up.</inlineHelpText>
    <label>Show Empty Fields</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Overview__c.field-meta.xml
<CustomField>
    <fullName>Show_Overview__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to display an overview that users can pan around to see the whole relationship map</description>
    <inlineHelpText>Check this to display an overview that users can pan around to see the whole relationship map</inlineHelpText>
    <label>Show Overview</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>keystakeholder</fullName>
            </value>
            <value>
                <fullName>rm</fullName>
            </value>
            <value>
                <fullName>om</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/RM_Org_Setting__c/fields/User_Tab__c.field-meta.xml
<CustomField>
    <fullName>User_Tab__c</fullName>
    <defaultValue>true</defaultValue>
    <label>User Tab</label>
    <type>Checkbox</type>
</CustomField>

default/classes/RMOrgSettingServiceImpl.cls
public with sharing class RMOrgSettingServiceImpl {
    private static Map<String, RM_Org_Setting__c> settingsCache = new Map<String, RM_Org_Setting__c>();
    /******************************
     *      PUBLIC METHODS
     ******************************/

    public RM_Org_Setting__c getRMOrgSetting(Id recordId) {
        String type;
        if (recordId != null && RelationshipMapService.hasAccountPlanSetting(recordId)) {
            type = 'keystakeholder';
        } else if (recordId != null && OpportunityPlanService.hasOpportunityPlanSetting(recordId)) {
            type = 'om';
        } else if (recordID != null) {
            RM_Org_Setting__c rmOrgSettings = getRMOrgSettingForID(recordId);
            if (rmOrgSettings != null) {
                return rmOrgSettings;
            } else {
                type = 'rm';
            }
        } else {
            type = 'rm';
        }

        return getRMOrgSettingForType(type);
    }

    public RM_Org_Setting__c getRMOrgSettingForID(id recordId) {
        if (recordId == null) {
            return null;
        }

        List<RM_Org_Setting__c> settings = RMOrgSettingSelector.newInstance().selectById(new Set<Id>{ recordId });

        if (settings == null || settings.isempty()) {
            return null;
        } else {
            return settings[0];
        }
    }

    public RM_Org_Setting__c getRMOrgSettingForType(String type) {
        if (settingsCache.containsKey(type)) {
            return settingsCache.get(type);
        }

        List<RM_Org_Setting__c> settings = RMOrgSettingSelector.newInstance().selectByType(type);

        if (settings.size() < 1) {
            return createNewSetting(type);
        }

        if (settings[0].Lead_Tab__c == null) {
            settings[0].Lead_Tab__c = true;
        }

        if (settings[0].User_Tab__c == null) {
            settings[0].User_Tab__c = true;
        }

        if (settings[0].Show_Auto_Manual_Toggle__c == null) {
            settings[0].Show_Auto_Manual_Toggle__c = true;
        }

        settingsCache.put(type, settings[0]);

        return settings[0];
    }

    public void setRMOrgSetting(RM_Org_Setting__c settings) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        if (settings.id != null) {
            uow.registerDirty(settings);
        } else {
            uow.registerNew(settings);
        }

        uow.commitWork();
    }

    public void setAdvancedOrgSetting(RM_Org_Setting__c settings) {
        RM_Org_Setting__c rmSetting = getRMOrgSettingForType(settings.Type__c);

        rmSetting.Prolifiq_Extended_Tools_URL__c = settings.Prolifiq_Extended_Tools_URL__c;

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        uow.registerDirty(rmSetting);
        uow.commitWork();
    }

    public void setDefaultChartSetting(RM_Org_Setting__c settings) {
        RM_Org_Setting__c rmSetting = getRMOrgSettingForType(settings.Type__c);
        rmSetting.Auto_Layout__c = settings.Auto_Layout__c;
        rmSetting.Enable_Drag_Select__c = settings.Enable_Drag_Select__c;
        rmSetting.Is_Group_Global_Scope__c = settings.Is_Group_Global_Scope__c;
        rmSetting.Is_Relationship_Line_Global_Scope__c = settings.Is_Relationship_Line_Global_Scope__c;
        rmSetting.Is_Badge_Global_Scope__c = settings.Is_Badge_Global_Scope__c;
        rmSetting.Is_Influence_Support_Global_Scope__c = settings.Is_Influence_Support_Global_Scope__c;
        rmSetting.Is_Reports_To_Global_Scope__c = settings.Is_Reports_To_Global_Scope__c;
        rmSetting.Show_Empty_Fields__c = settings.Show_Empty_Fields__c;
        rmSetting.Show_Overview__c = settings.Show_Overview__c;
        rmSetting.Show_Parents__c = settings.Show_Parents__c;
        rmSetting.Relationship_Line_Opacity__c = settings.Relationship_Line_Opacity__c;
        rmSetting.Reports_To_Line_Opacity__c = settings.Reports_To_Line_Opacity__c;
        rmSetting.Prolifiq_Extended_Tools_URL__c = settings.Prolifiq_Extended_Tools_URL__c;
        rmSetting.Card_Style__c = settings.Card_Style__c;
        rmSetting.Display_Style__c = settings.Display_Style__c;

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        uow.registerDirty(rmSetting);
        uow.commitWork();
    }

    public void setTabsSetting(
        String type,
        Boolean leadTab,
        Boolean userTab,
        Boolean createNewContact,
        Boolean showAutoManualToggle,
        Boolean enableContactContextMenu,
        Boolean enableMapMemberContextMenu,
        Boolean enableOmniViewerContextMenu,
        Boolean enableGroupSelectionContextMenu,
        Boolean showCloneButton,
        Boolean showSettingsButton
    ) {
        RM_Org_Setting__c rmSetting = getRMOrgSettingForType(type);

        if (leadTab != null) {
            rmSetting.Lead_Tab__c = leadTab;
        }

        if (userTab != null) {
            rmSetting.User_Tab__c = userTab;
        }

        if (createNewContact != null) {
            rmSetting.Create_New_Contact__c = createNewContact;
        }
        if (createNewContact != null) {
            rmSetting.pqcrush__Create_New_Account__c = createNewContact;
        }

        if (showAutoManualToggle != null) {
            rmSetting.Show_Auto_Manual_Toggle__c = showAutoManualToggle;
        }

        if (enableContactContextMenu != null) {
            rmSetting.Enable_Contact_Context_Menu__c = enableContactContextMenu;
        }

        if (enableMapMemberContextMenu != null) {
            rmSetting.Enable_Map_Member_Context_Menu__c = enableMapMemberContextMenu;
        }

        if (enableOmniViewerContextMenu != null) {
            rmSetting.Enable_Omni_Viewer_Context_Menu__c = enableOmniViewerContextMenu;
        }

        if (enableGroupSelectionContextMenu != null) {
            rmSetting.Enable_Group_Selection_Context_Menu__c = enableGroupSelectionContextMenu;
        }

        if (showCloneButton != null) {
            rmSetting.Show_Clone_Relationship_Map__c = showCloneButton;
        }

        if (showSettingsButton != null) {
            rmSetting.Show_Chart_Settings__c = showSettingsButton;
        }

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        uow.registerDirty(rmSetting);
        uow.commitWork();
    }

    public List<NameValuePair> getPickListValues(String fieldName) {
        List<NameValuePair> nvp = new List<NameValuePair>();
        Schema.SObjectType s = RM_Org_Setting__c.SObjectType;
        Schema.DescribeSObjectResult r = s.getDescribe();
        Map<String, Schema.SObjectField> fields = r.fields.getMap();
        Schema.DescribeFieldResult fieldResult = fields.get(fieldName).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry pickListVal : ple) {
            nvp.add(new NameValuePair(pickListVal.getLabel(), pickListVal.getValue()));
        }
        return nvp;
    }

    public void updateEnableSuggestedContactsForRM(Id settingId, Boolean showSuggestedContacts) {
        if (showSuggestedContacts == null) {
            return;
        }
        string type = 'keystakeholder';

        RM_Org_Setting__c orgSettings = getRMOrgSettingForType(type);
        orgSettings.Enable_Suggested_Contacts_For_RM__c = showSuggestedContacts;
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(new fflib_SObjectUnitOfWork.SimpleDML());
        uow.registerDirty(orgSettings);
        SystemContext systemContext = new SystemContext();
        systemContext.commitWork(uow);
    }

    public void updateEnableSuggestedContactsForRMSettings(Id settingId, Boolean showSuggestedContacts) {
        if (showSuggestedContacts == null) {
            return;
        }

        RM_Org_Setting__c orgSettings = RMOrgSettingService.getRMOrgSetting(settingId);
        orgSettings.Enable_Sugg_Con_For_RMSettings__c = showSuggestedContacts;
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(new fflib_SObjectUnitOfWork.SimpleDML());
        uow.registerDirty(orgSettings);
        SystemContext systemContext = new SystemContext();
        systemContext.commitWork(uow);
    }

    public void updateRMOrgSettingOperator(Id rmOrgSettingId, String rmOrgSettingOperator) {
        if (rmOrgSettingOperator == null) {
            return;
        }

        RM_Org_Setting__c orgSettings = RMOrgSettingService.getRMOrgSetting(rmOrgSettingId);
        orgSettings.Operator__c = rmOrgSettingOperator;
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(new fflib_SObjectUnitOfWork.SimpleDML());
        uow.registerDirty(orgSettings);
        //suggest contact restricted
        uow.commitWork();
        //SystemContext systemContext = new SystemContext();
        //systemContext.commitWork(uow);
    }

    private RM_Org_Setting__c createNewSetting(String type) {
        RM_Org_Setting__c newSetting = new RM_Org_Setting__c(
            Type__c = type,
            Auto_Layout__c = true,
            Card_Style__c = 'Detail',
            Display_Style__c = 'Horizontal',
            Enable_Drag_Select__c = false,
            Lead_Tab__c = true,
            Is_Group_Global_Scope__c = false,
            Is_Relationship_Line_Global_Scope__c = false,
            Relationship_Line_Opacity__c = 100.0,
            Reports_To_Line_Opacity__c = 100.0,
            Prolifiq_Extended_Tools_URL__c = '',
            Show_Empty_Fields__c = false,
            Show_Overview__c = false,
            Show_Parents__c = true,
            User_Tab__c = true,
            Is_Influence_Support_Global_Scope__c = false,
            Is_Reports_To_Global_Scope__c = true,
            Show_Auto_Manual_Toggle__c = true,
            Enable_Contact_Context_Menu__c = true,
            Enable_Map_Member_Context_Menu__c = true,
            Enable_Omni_Viewer_Context_Menu__c = true,
            Enable_Group_Selection_Context_Menu__c = true
        );

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(new fflib_SObjectUnitOfWork.SimpleDML());
        uow.registerNew(newSetting);
        new SystemContext().commitWork(uow);

        return newSetting;
    }

    public void updateContactLimit(Id settingId, String contactLimitValue) {
        if (contactLimitValue == null) {
            return;
        }
        string type = 'keystakeholder';

        RM_Org_Setting__c orgSettings = getRMOrgSettingForType(type);
        orgSettings.pqcrush__contact_limit__c = contactLimitValue;
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(new fflib_SObjectUnitOfWork.SimpleDML());
        uow.registerDirty(orgSettings);
        SystemContext systemContext = new SystemContext();
        systemContext.commitWork(uow);
    }

    public void updateRMContactLimit(Id settingId, String contactLimitValue) {
        if (contactLimitValue == null) {
            return;
        }

        RM_Org_Setting__c orgSettings = RMOrgSettingService.getRMOrgSetting(settingId);
        orgSettings.pqcrush__rm_contact_limit__c = contactLimitValue;
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(new fflib_SObjectUnitOfWork.SimpleDML());
        uow.registerDirty(orgSettings);
        SystemContext systemContext = new SystemContext();
        systemContext.commitWork(uow);
    }

    private without sharing class SystemContext {
        private void commitWork(fflib_ISObjectUnitOfWork uow) {
            uow.commitWork();
        }
    }
}