default/objects/RM_Org_Setting__c/RM_Org_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Org Setting</label>
    <nameField>
        <label>RM_Org_Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM_Org_Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Org_Setting__c/fields/Create_New_Contact__c.field-meta.xml
<CustomField>
    <fullName>Create_New_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Create New Contact</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Contact_Context_Menu__c.field-meta.xml
<CustomField>
    <fullName>Enable_Contact_Context_Menu__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to show and let users click on Contact to view the Salesforce contact modal</description>
    <inlineHelpText>Check this to show and let users click on Contact to view the Salesforce contact modal</inlineHelpText>
    <label>Enable Contact Context Menu</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Group_Selection_Context_Menu__c.field-meta.xml
<CustomField>
    <fullName>Enable_Group_Selection_Context_Menu__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag for the abilty to create and adjust groups in the Relationship Map</description>
    <inlineHelpText>Check this to allow creating deleting and editing groups in Relationship Maps</inlineHelpText>
    <label>Enable Grouping</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Map_Member_Context_Menu__c.field-meta.xml
<CustomField>
    <fullName>Enable_Map_Member_Context_Menu__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to enable the context menu for Map Members or Key Stakeholder in the Relationship Map</description>
    <inlineHelpText>Check this to enable the context menu for Map Members or Key Stakeholder in the Relationship Map</inlineHelpText>
    <label>Enable Map Member Context Menu</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Enable_Omni_Viewer_Context_Menu__c.field-meta.xml
<CustomField>
    <fullName>Enable_Omni_Viewer_Context_Menu__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to enable the OmniViewer context menu in the Relationship Map</description>
    <inlineHelpText>Check this to enable the OmniViewer context menu in the Relationship Map</inlineHelpText>
    <label>Enable OmniViewer context Menu</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Lead_Tab__c.field-meta.xml
<CustomField>
    <fullName>Lead_Tab__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lead Tab</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Prolifiq_Extended_Tools_URL__c.field-meta.xml
<CustomField>
    <fullName>Prolifiq_Extended_Tools_URL__c</fullName>
    <description>External URL for extended features.</description>
    <inlineHelpText>External URL for extended features.</inlineHelpText>
    <label>Prolifiq Extended Tools URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Auto_Manual_Toggle__c.field-meta.xml
<CustomField>
    <fullName>Show_Auto_Manual_Toggle__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Auto Manual Toggle</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Chart_Settings__c.field-meta.xml
<CustomField>
    <fullName>Show_Chart_Settings__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked then the settings button in the dropdown menu of key stakeholder/relationship maps will show based on user permissions.  If unchecked this will hide the button regardless of any permissions for users to see the settings button.</description>
    <inlineHelpText>If this is unchecked then no users in the org will see the settings button in the key stakeholder/relationship map dropdown menu regardless of what permissions they have set for showing the button.  This is org wide.</inlineHelpText>
    <label>Show Chart Settings</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/Show_Clone_Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Show_Clone_Relationship_Map__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked then the clone button in the dropdown menu of relationship maps will show based on user permissions.  If unchecked this will hide the button regardless of any permissions for users to see the clone button.</description>
    <inlineHelpText>If this is unchecked then no users in the org will see the clone button in the relationship map dropdown menu regardless of what permissions they have set for showing the button.  This is org wide.</inlineHelpText>
    <label>Show Clone Relationship Map</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Org_Setting__c/fields/User_Tab__c.field-meta.xml
<CustomField>
    <fullName>User_Tab__c</fullName>
    <defaultValue>true</defaultValue>
    <label>User Tab</label>
    <type>Checkbox</type>
</CustomField>

default/classes/RMOrgSettingServiceTest.cls
@isTest
private class RMOrgSettingServiceTest {
    @testSetup
    static void testSetup() {
        testMockData md = new testMockData();
        RelationshipMapServiceImpl mockRelationshipMapService = md.mockRelationshipMapService;
        md.mocks.startStubbing();
        md.mocks.when(mockRelationshipMapService.hasAccountPlanSetting(md.mockRelationshipMapId)).thenReturn(false);
        md.mocks.stopStubbing();

        // Need to do this first so it creates the org setting.  Otherwise, test will create and then compare will be from teh query
        RMOrgSettingService.getRMOrgSetting(md.mockRelationshipMapId);
    }

    @isTest
    static void getRMOrgSettingTest() {
        testMockData md = new testMockData();
        RMOrgSettingSelector mockRMOrgSettingSelector = md.mockRMOrgSettingSelector;
        fflib_ISObjectUnitOfWork mockUow = md.mockUow; //NOPMD - Needs to be called in order for it to be mocked in the test
        RelationshipMapServiceImpl mockRelationshipMapService = md.mockRelationshipMapService;

        md.mocks.startStubbing();
        md.mocks.when(mockRelationshipMapService.hasAccountPlanSetting(md.mockRelationshipMapId)).thenReturn(false);
        md.mocks.when(mockRMOrgSettingSelector.selectByType('rm'))
            .thenReturn(new List<RM_Org_Setting__c>{ md.mockRMOrgSettingForRM });
        md.mocks.stopStubbing();

        RM_Org_Setting__c setting = RMOrgSettingService.getRMOrgSetting(md.mockRelationshipMapId);

        ((RMOrgSettingSelector) md.mocks.verify(mockRMOrgSettingSelector, 1)).selectByType('rm');

        System.assertNotEquals(null, setting);
    }

    @isTest
    static void setRMOrgSettingNewTest() {
        testMockData md = new testMockData();
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;

        md.mockRMOrgSettingForRM.id = null;

        RMOrgSettingService.setRMOrgSetting(md.mockRMOrgSettingForRM);

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerNew(md.mockRMOrgSettingForRM);
        System.assert(true, 'Assert from mock verify');
    }

    @isTest
    static void setRMOrgSettingDirtyTest() {
        testMockData md = new testMockData();
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;

        RMOrgSettingService.setRMOrgSetting(md.mockRMOrgSettingForRM);

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDirty(md.mockRMOrgSettingForRM);
        System.assert(true, 'Assert from mock verify');
    }

    @isTest
    static void setAdvancedOrgSettingTest() {
        testMockData md = new testMockData();
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;
        RelationshipMapServiceImpl mockRelationshipMapService = md.mockRelationshipMapService;

        md.mocks.startStubbing();
        md.mocks.when(mockRelationshipMapService.hasAccountPlanSetting(md.mockRelationshipMapId)).thenReturn(false);
        md.mocks.stopStubbing();

        RM_Org_Setting__c input = RMOrgSettingService.getRMOrgSetting(md.mockRelationshipMapId);
        input.Prolifiq_Extended_Tools_URL__c = 'https://example.com';
        RMOrgSettingService.setAdvancedOrgSetting(input);

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDirty(input);
        System.assert(true, 'Assert from mock verify');
    }

    @isTest
    static void setDefaultChartSettingTest() {
        testMockData md = new testMockData();
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;
        RelationshipMapServiceImpl mockRelationshipMapService = md.mockRelationshipMapService;

        md.mocks.startStubbing();
        md.mocks.when(mockRelationshipMapService.hasAccountPlanSetting(md.mockRelationshipMapId)).thenReturn(false);
        md.mocks.stopStubbing();

        RM_Org_Setting__c input = RMOrgSettingService.getRMOrgSetting(md.mockRelationshipMapId);
        input.Prolifiq_Extended_Tools_URL__c = 'https://example.com';
        RMOrgSettingService.setDefaultChartSetting(input);

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDirty(input);
        System.assert(true, 'Assert from mock verify');
    }

    @isTest
    static void setTabsSettingNullTest() {
        testMockData md = new testMockData();
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;
        RelationshipMapServiceImpl mockRelationshipMapService = md.mockRelationshipMapService;

        md.mocks.startStubbing();
        md.mocks.when(mockRelationshipMapService.hasAccountPlanSetting(md.mockRelationshipMapId)).thenReturn(false);
        md.mocks.stopStubbing();

        RM_Org_Setting__c result = RMOrgSettingService.getRMOrgSetting(md.mockRelationshipMapId);

        RMOrgSettingService.setTabsSetting('rm', null, null, null, null, null, null, null, null, null, null);

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDirty(result);
        System.assert(true, 'Assert from mock verify');
    }

    @isTest
    static void setTabsSettingTest() {
        testMockData md = new testMockData();
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;
        RelationshipMapServiceImpl mockRelationshipMapService = md.mockRelationshipMapService;

        md.mocks.startStubbing();
        md.mocks.when(mockRelationshipMapService.hasAccountPlanSetting(md.mockRelationshipMapId)).thenReturn(false);
        md.mocks.stopStubbing();

        RM_Org_Setting__c result = RMOrgSettingService.getRMOrgSetting(md.mockRelationshipMapId);

        RMOrgSettingService.setTabsSetting('rm', true, false, true, true, true, true, false, true, true, true);

        result.Lead_Tab__c = true;
        result.User_Tab__c = false;
        result.Create_New_Contact__c = true;
        result.Show_Auto_Manual_Toggle__c = true;
        result.Enable_Contact_Context_Menu__c = true;
        result.Enable_Map_Member_Context_Menu__c = true;
        result.Enable_Omni_Viewer_Context_Menu__c = false;
        result.Enable_Group_Selection_Context_Menu__c = true;
        result.Show_Chart_Settings__c = true;
        result.Show_Clone_Relationship_Map__c = true;

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDirty(result);
        System.assert(true, 'Assert from mock verify');
    }
}