default/objects/pq_Opportunity_Effectiveness_Index__c/pq_Opportunity_Effectiveness_Index__c.object-meta.xml
<CustomObject>
    <label>Opportunity Effectiveness Index</label>
    <nameField>
        <displayFormat>OEI-{0000}</displayFormat>
        <label>Opportunity Effectiveness Index Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Effectiveness Indexes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Serialized_Lost_Data__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Serialized_Lost_Data__c</fullName>
    <label>Rolling Serialized Lost Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Serialized_Won_Data__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Serialized_Won_Data__c</fullName>
    <label>Rolling Serialized Won Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Total_Lost__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Total_Lost__c</fullName>
    <label>Rolling Total Lost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Total_Lost_With_Contact__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Total_Lost_With_Contact__c</fullName>
    <label>Rolling Total Lost With Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Total_Won__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Total_Won__c</fullName>
    <label>Rolling Total Won</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Total_Won_With_Contact__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Total_Won_With_Contact__c</fullName>
    <label>Rolling Total Won With Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Serialized_Lost_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Lost_Data__c</fullName>
    <label>Serialized Lost Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Serialized_Won_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Won_Data__c</fullName>
    <label>Serialized Won Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Lost__c.field-meta.xml
<CustomField>
    <fullName>Total_Lost__c</fullName>
    <label>Total Lost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Lost_With_Contact__c.field-meta.xml
<CustomField>
    <fullName>Total_Lost_With_Contact__c</fullName>
    <label>Total Lost With Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Won__c.field-meta.xml
<CustomField>
    <fullName>Total_Won__c</fullName>
    <label>Total Won</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Won_With_Contact__c.field-meta.xml
<CustomField>
    <fullName>Total_Won_With_Contact__c</fullName>
    <label>Total Won With Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/OpportunityEffectivenessDataTest.cls
@isTest
private class OpportunityEffectivenessDataTest {
    @isTest
    static void instanceTest() {
        OpportunityEffectivenessData result = new OpportunityEffectivenessData();
        System.assertNotEquals(null, result);
    }

    @isTest
    static void convertNullTest() {
        pq_Opportunity_Effectiveness_Index__c input = null;
        OpportunityEffectivenessData result = OpportunityEffectivenessData.convert(input);
        System.assertNotEquals(null, result);
        System.assertNotEquals(null, result.lostMap);
        System.assertNotEquals(null, result.wonMap);
    }

    @isTest
    static void convertTest1() {
        pq_Opportunity_Effectiveness_Index__c input = new pq_Opportunity_Effectiveness_Index__c(
            Serialized_Lost_Data__c = '',
            Serialized_Won_Data__c = '',
            Total_Lost__c = 12,
            Total_Won__c = 18,
            Total_Won_With_Contact__c = 20,
            Total_Lost_With_Contact__c = 24
        );

        OpportunityEffectivenessData result = OpportunityEffectivenessData.convert(input);

        System.assertNotEquals(null, result);
        System.assertEquals(12, result.totalLost);
        System.assertEquals(18, result.totalWon);
        System.assertEquals(20, result.wonWithContact);
        System.assertEquals(24, result.lostWithContact);

        System.assertNotEquals(null, result.lostMap);
        System.assertNotEquals(null, result.wonMap);
    }

    @isTest
    static void convertTest2() {
        pq_Opportunity_Effectiveness_Index__c input = new pq_Opportunity_Effectiveness_Index__c(
            Serialized_Lost_Data__c = '{"Business User":27,"Decision Maker":10,"Influencer":32}',
            Serialized_Won_Data__c = '{"Decision Maker":43,"Influencer":36,"Business User":31}',
            Total_Lost__c = 12,
            Total_Won__c = 18,
            Total_Won_With_Contact__c = 20,
            Total_Lost_With_Contact__c = 24
        );

        OpportunityEffectivenessData result = OpportunityEffectivenessData.convert(input);

        System.assertNotEquals(null, result);
        System.assertEquals(12, result.totalLost);
        System.assertEquals(18, result.totalWon);
        System.assertEquals(20, result.wonWithContact);
        System.assertEquals(24, result.lostWithContact);

        System.assertNotEquals(null, result.lostMap);
        System.assertNotEquals(null, result.wonMap);

        System.assertEquals(27, result.lostMap.get('Business User'));
        System.assertEquals(10, result.lostMap.get('Decision Maker'));
        System.assertEquals(32, result.lostMap.get('Influencer'));
        System.assertEquals(43, result.wonMap.get('Decision Maker'));
        System.assertEquals(36, result.wonMap.get('Influencer'));
        System.assertEquals(31, result.wonMap.get('Business User'));
    }

    @isTest
    static void convertRollingNullTest() {
        pq_Opportunity_Effectiveness_Index__c input = null;
        OpportunityEffectivenessData result = OpportunityEffectivenessData.convertForRollingData(input);
        System.assertNotEquals(null, result);
        System.assertNotEquals(null, result.lostMap);
        System.assertNotEquals(null, result.wonMap);
    }

    @isTest
    static void convertForRollingDataTest() {
        pq_Opportunity_Effectiveness_Index__c input = new pq_Opportunity_Effectiveness_Index__c(
            Rolling_Serialized_Lost_Data__c = '{"Business User":27,"Decision Maker":10,"Influencer":32}',
            Rolling_Serialized_Won_Data__c = '{"Decision Maker":43,"Influencer":36,"Business User":31}',
            Rolling_Total_Lost__c = 12,
            Rolling_Total_Won__c = 18,
            Rolling_Total_Won_With_Contact__c = 20,
            Rolling_Total_Lost_With_Contact__c = 24
        );

        OpportunityEffectivenessData result = OpportunityEffectivenessData.convertForRollingData(input);

        System.assertNotEquals(null, result);
        System.assertEquals(12, result.totalLost);
        System.assertEquals(18, result.totalWon);
        System.assertEquals(20, result.wonWithContact);
        System.assertEquals(24, result.lostWithContact);

        System.assertNotEquals(null, result.lostMap);
        System.assertNotEquals(null, result.wonMap);

        System.assertEquals(27, result.lostMap.get('Business User'));
        System.assertEquals(10, result.lostMap.get('Decision Maker'));
        System.assertEquals(32, result.lostMap.get('Influencer'));
        System.assertEquals(43, result.wonMap.get('Decision Maker'));
        System.assertEquals(36, result.wonMap.get('Influencer'));
        System.assertEquals(31, result.wonMap.get('Business User'));
    }
}