default/objects/pq_Opportunity_Effectiveness_Index__c/pq_Opportunity_Effectiveness_Index__c.object-meta.xml
<CustomObject>
    <label>Opportunity Effectiveness Index</label>
    <nameField>
        <displayFormat>OEI-{0000}</displayFormat>
        <label>Opportunity Effectiveness Index Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Effectiveness Indexes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Date_of_Data__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Data__c</fullName>
    <description>Date of Data collected</description>
    <label>Date of Data</label>
    <type>Date</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Serialized_Lost_Data__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Serialized_Lost_Data__c</fullName>
    <label>Rolling Serialized Lost Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Serialized_Won_Data__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Serialized_Won_Data__c</fullName>
    <label>Rolling Serialized Won Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Total_Lost__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Total_Lost__c</fullName>
    <label>Rolling Total Lost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Total_Lost_With_Contact__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Total_Lost_With_Contact__c</fullName>
    <label>Rolling Total Lost With Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Total_Won__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Total_Won__c</fullName>
    <label>Rolling Total Won</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Rolling_Total_Won_With_Contact__c.field-meta.xml
<CustomField>
    <fullName>Rolling_Total_Won_With_Contact__c</fullName>
    <label>Rolling Total Won With Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Serialized_Lost_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Lost_Data__c</fullName>
    <label>Serialized Lost Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Serialized_Won_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Won_Data__c</fullName>
    <label>Serialized Won Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Lost__c.field-meta.xml
<CustomField>
    <fullName>Total_Lost__c</fullName>
    <label>Total Lost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Lost_With_Contact__c.field-meta.xml
<CustomField>
    <fullName>Total_Lost_With_Contact__c</fullName>
    <label>Total Lost With Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Won__c.field-meta.xml
<CustomField>
    <fullName>Total_Won__c</fullName>
    <label>Total Won</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Opportunity_Effectiveness_Index__c/fields/Total_Won_With_Contact__c.field-meta.xml
<CustomField>
    <fullName>Total_Won_With_Contact__c</fullName>
    <label>Total Won With Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/OpportunityEffectivenessIndexSelector.cls
public with sharing class OpportunityEffectivenessIndexSelector extends fflib_SObjectSelector {
    /******************************
     *      STATIC METHODS
     ******************************/

    public static OpportunityEffectivenessIndexSelector newInstance() {
        return (OpportunityEffectivenessIndexSelector) Application.Selector.newInstance(pq_Opportunity_Effectiveness_Index__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            pq_Opportunity_Effectiveness_Index__c.Id,
            pq_Opportunity_Effectiveness_Index__c.Date_of_Data__c,
            pq_Opportunity_Effectiveness_Index__c.Serialized_Lost_Data__c,
            pq_Opportunity_Effectiveness_Index__c.Serialized_Won_Data__c,
            pq_Opportunity_Effectiveness_Index__c.Total_Won__c,
            pq_Opportunity_Effectiveness_Index__c.Total_Lost__c,
            pq_Opportunity_Effectiveness_Index__c.Total_Won_With_Contact__c,
            pq_Opportunity_Effectiveness_Index__c.Total_Lost_With_Contact__c,
            pq_Opportunity_Effectiveness_Index__c.Rolling_Serialized_Lost_Data__c,
            pq_Opportunity_Effectiveness_Index__c.Rolling_Serialized_Won_Data__c,
            pq_Opportunity_Effectiveness_Index__c.Rolling_Total_Lost__c,
            pq_Opportunity_Effectiveness_Index__c.Rolling_Total_Won__c,
            pq_Opportunity_Effectiveness_Index__c.Rolling_Total_Lost_With_Contact__c,
            pq_Opportunity_Effectiveness_Index__c.Rolling_Total_Won_With_Contact__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return pq_Opportunity_Effectiveness_Index__c.sObjectType;
    }

    public override String getOrderBy() {
        return pq_Opportunity_Effectiveness_Index__c.Date_of_Data__c.getDescribe().getName() + ' DESC';
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<pq_Opportunity_Effectiveness_Index__c> selectById(Set<Id> ids) {
        return Database.query(newQueryFactory().setCondition('Id IN :ids').toSOQL());
    }

    public List<pq_Opportunity_Effectiveness_Index__c> selectByDate(Date day) {
        fflib_QueryFactory query = newQueryFactory().setCondition('Date_of_Data__c = :day').setLimit(1);
        return Database.query(query.toSOQL());
    }

    public List<pq_Opportunity_Effectiveness_Index__c> selectByStartDate(Date startDate) {
        fflib_QueryFactory query = newQueryFactory().setCondition('Date_of_Data__c >= :startDate');
        return Database.query(query.toSOQL());
    }

    // Getting 1 (the latest one, order by date desc above)
    public pq_Opportunity_Effectiveness_Index__c selectOne() {
        fflib_QueryFactory query = newQueryFactory().setLimit(1);
        List<pq_Opportunity_Effectiveness_Index__c> oeiList = Database.query(query.toSOQL());
        if (oeiList != null && oeiList.size() == 1) {
            return oeiList[0];
        }
        return null;
    }
}