default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/fields/pq_AccountPlanId__c.field-meta.xml
<CustomField>
    <fullName>pq_AccountPlanId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>pq_AccountPlanId</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Relationship Maps</relationshipLabel>
    <relationshipName>Relationship_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map__c/fields/Type_Setting__c.field-meta.xml
<CustomField>
    <fullName>Type_Setting__c</fullName>
    <description>The setting for which this map uses</description>
    <inlineHelpText>The setting for which this map uses</inlineHelpText>
    <label>Type Setting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Badge_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Badge_Global_Scope__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When this is check, badges on contacts will persist wherever the contact is on the maps.  If unchecked, the badge will only be present for that particular map</description>
    <inlineHelpText>When this is check, badges on contacts will persist wherever the contact is on the maps.  If unchecked, the badge will only be present for that particular map</inlineHelpText>
    <label>Use Global Badges</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Svg__c/RM_Svg__c.object-meta.xml
<CustomObject>
    <label>Relationship Map Badge</label>
    <nameField>
        <label>Relationship Map Badge Names</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Map Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Svg_Node_Association__c/RM_Svg_Node_Association__c.object-meta.xml
<CustomObject>
    <label>RM Svg Node Association</label>
    <nameField>
        <label>RM Svg Node Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM Svg Node Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/RM_Svg_Node_Association__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>RM Svg Node Associations</relationshipLabel>
    <relationshipName>RM_Svg_Node_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Svg_Node_Association__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Svg Node Associations</relationshipLabel>
    <relationshipName>RM_Svg_Node_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Svg_Node_Association__c/fields/RM_Svg__c.field-meta.xml
<CustomField>
    <fullName>RM_Svg__c</fullName>
    <label>RM Svg</label>
    <referenceTo>RM_Svg__c</referenceTo>
    <relationshipLabel>RM Svg Node Associations</relationshipLabel>
    <relationshipName>RM_Svg_Node_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/classes/RMSvgServiceImpl.cls
public with sharing class RMSvgServiceImpl {
    // This method gets the badges for each node and adds the data to the graph node data
    public GraphData injectBadges(Id mapId, GraphData gd, RM_Chart_Setting__C setting) {
        List<Relationship_Map__c> maps = RelationshipMapSelector.newInstance().selectByIds(new Set<Id>{ mapId });
        Boolean hasAccountPlanSetting = false;
        Id accountPlanId = null;
        if (maps != null && maps.size() > 0) {
            Relationship_Map__c rmMap = maps[0];
            if (rmMap?.Type_Setting__c == 'pqcrush__Account_Plan__c') {
                hasAccountPlanSetting = true;
            }

            accountPlanId = rmMap.pq_AccountPlanId__c;
        }

        List<RM_Svg__c> svgs = RMSvgSelector.newInstance()
            .selectByRelationshipMaps(new Set<Id>{ mapId }, hasAccountPlanSetting, accountPlanId);

        // Add badges that are data binds
        RMSvgHelperService.injectBoundBadges(svgs, gd.nodeDataArray);

        // Map Badges
        Map<String, GraphNodeData> mapNodes = new Map<String, GraphNodeData>();
        for (GraphNodeData node : gd.nodeDataArray) {
            mapNodes.put(node.key, node);
        }

        List<RM_Svg_Node_Association__c> nodeSvgs;
        if (setting.Is_Badge_Global_Scope__c) {
            nodeSvgs = RMSvgNodeAssociationSelector.newInstance().selectByKeysGlobalForSvgs(svgs, mapNodes.keySet());
        } else {
            nodeSvgs = RMSvgNodeAssociationSelector.newInstance()
                .selectByKeysLocalForSvgs(mapId, svgs, mapNodes.keySet());
        }

        for (RM_Svg_Node_Association__c nodeSvg : nodeSvgs) {
            GraphNodeData nData = mapNodes.get(nodeSvg.Key__c);
            if (nData == null) {
                continue;
            }
            if (nData.badges == null) {
                nData.badges = new List<Badge>{ new Badge(nodeSvg.RM_Svg__c, '', '', false) };
            } else {
                if (!containsBadge(nData.badges, nodeSvg.RM_Svg__c)) {
                    nData.badges.add(new Badge(nodeSvg.RM_Svg__c, '', '', false));
                }
            }

            mapNodes.put(nodeSvg.Key__c, nData);
        }

        gd.nodeDataArray = mapNodes.values();

        return gd;
    }

    private Boolean containsBadge(List<Badge> badgeList, String badgeId) {
        for (Badge b : badgeList) {
            if (b.Id == badgeId) {
                return true;
            }
        }
        return false;
    }

    public void associateBadge(Id mapOrAccountPlanId, String badgeId, List<String> nodeIds) {
        if (mapOrAccountPlanId == null) {
            return;
        }

        Set<String> idSet = new Set<String>(nodeIds);

        RM_Chart_Setting__C setting = RMChartSettingService.getRelationshipMapSettingForObject(mapOrAccountPlanId);

        // Look up current associations
        List<RM_Svg_Node_Association__c> nodeSvgs;
        if (setting.Is_Badge_Global_Scope__c) {
            nodeSvgs = RMSvgNodeAssociationSelector.newInstance().selectByKeysGlobal(idSet);
        } else {
            nodeSvgs = RMSvgNodeAssociationSelector.newInstance().selectByKeysLocal(mapOrAccountPlanId, idSet);
        }

        Set<String> keyBadgeSet = new Set<String>();
        for (RM_Svg_Node_Association__c nodeAssoc : nodeSvgs) {
            keyBadgeSet.add(nodeAssoc.Key__c + nodeAssoc.RM_Svg__c);
        }

        Id relationshipMapId = null;
        Id accountPlanId = null;
        if (mapOrAccountPlanId.getSobjectType() == Relationship_Map__c.getSObjectType()) {
            relationshipMapId = mapOrAccountPlanId;
        } else if (mapOrAccountPlanId.getSobjectType() == Account_Plan__c.getSObjectType()) {
            accountPlanId = mapOrAccountPlanId;
        }

        // Insert new associations
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        for (String nodeId : nodeIds) {
            if (keyBadgeSet.contains(nodeId + badgeId)) {
                // Already exists in database
                continue;
            }
            RM_Svg_Node_Association__c nodeAssoc = new RM_Svg_Node_Association__c(Key__c = nodeId, RM_Svg__c = badgeId);
            if (!setting.Is_Badge_Global_Scope__c) {
                nodeAssoc.Relationship_Map__c = relationshipMapId;
                nodeAssoc.Account_Plan__c = accountPlanId;
            }
            uow.registerNew(nodeAssoc);
        }
        uow.commitWork();
    }

    public void removeBadge(Id mapOrAccountPlanId, List<String> nodeIds) {
        if (mapOrAccountPlanId == null) {
            return;
        }

        Set<String> idSet = new Set<String>(nodeIds);

        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(mapOrAccountPlanId);

        // Remove old associations
        fflib_ISObjectUnitOfWork uow1 = Application.UnitOfWork.newInstance();
        List<RM_Svg_Node_Association__c> nodeSvgs;
        if (setting.Is_Badge_Global_Scope__c) {
            nodeSvgs = RMSvgNodeAssociationSelector.newInstance().selectByKeysGlobalWithAutomation(idSet, false);
        } else {
            nodeSvgs = RMSvgNodeAssociationSelector.newInstance()
                .selectByKeysLocalWithAutomation(mapOrAccountPlanId, idSet, false);
        }
        uow1.registerDeleted(nodeSvgs);
        uow1.commitWork();
    }
}