default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Relationship__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/Contact_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Type</label>
    <referenceTo>Contact_Relationship_Type__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/From_Contact__c.field-meta.xml
<CustomField>
    <fullName>From_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Relationships (From Contact)</relationshipLabel>
    <relationshipName>Contact_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/To_Contact__c.field-meta.xml
<CustomField>
    <fullName>To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Relationships (To Contact)</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship_Type__c/Contact_Relationship_Type__c.object-meta.xml
<CustomObject>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Relationship_Type__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>The color of the Relationship Line in the RGB format #AABBCC</description>
    <inlineHelpText>The color of the Relationship Line in the RGB format #AABBCC</inlineHelpText>
    <label>Line Color</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Contact_Relationship_Type__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Default Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Contact_Relationship_Type__c/fields/Label_Editable__c.field-meta.xml
<CustomField>
    <fullName>Label_Editable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want the users to be able to change the default label when they draw or edit a relationship of this Relationship Line Type</description>
    <inlineHelpText>Check this if you want the users to be able to change the default label when they draw or edit a relationship of this Relationship Line Type</inlineHelpText>
    <label>Label Editable</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/ContactRelationshipSelector.cls
public with sharing class ContactRelationshipSelector extends fflib_SObjectSelector {
    public ContactRelationshipSelector() {
        super(false, true, false);
    }

    public static ContactRelationshipSelector newInstance() {
        return (ContactRelationshipSelector) Application.Selector.newInstance(Contact_Relationship__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Contact_Relationship__c.Id,
            Contact_Relationship__c.Account_Plan__c,
            Contact_Relationship__c.Contact_Relationship_Type__c,
            Contact_Relationship__c.From_Contact__c,
            Contact_Relationship__c.To_Contact__c,
            Contact_Relationship__c.Label__c,
            Contact_Relationship__c.TempId__c,
            Contact_Relationship__c.Account_Plan__c,
            Contact_Relationship__c.Relationship_Map__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Contact_Relationship__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<Contact_Relationship__c> selectById(Set<Id> ids) {
        return (List<Contact_Relationship__c>) selectSObjectsById(ids);
    }

    public List<Contact_Relationship__c> selectByIdOrTempKey(Set<String> keys) {
        fflib_QueryFactory query = newQueryFactory().setCondition('Id IN :keys OR TempId__c IN :keys');
        return Database.query(query.toSOQL());
    }

    public List<Contact_Relationship__c> selectActiveCustomRelsByToOrFrom(Set<String> toOrFrom) {
        Set<String> queryFields = additionalQueryFields();
        fflib_QueryFactory query = newQueryFactory()
            .setCondition(
                'Contact_Relationship_Type__c != null AND Contact_Relationship_Type__r.pqcrush__IsActive__c = true AND (To_Contact__c IN :toOrFrom OR From_Contact__c IN :toOrFrom)'
            )
            .selectFields(queryFields);
        return Database.query(query.toSOQL());
    }

    public List<Contact_Relationship__c> selectLocalRelationshipsById(
        Set<Id> ids,
        Id mapOrAccountPlanId,
        Boolean hasAccountPlanSetting
    ) {
        if (mapOrAccountPlanId == null) {
            return new List<Contact_Relationship__c>();
        }

        String fieldCondition = '';
        String usedInString = 'pqcrush__Used_in_all_relationship_maps__c';
        if (hasAccountPlanSetting) {
            usedInString = 'pqcrush__Used_in_all_account_plans__c';
        }

        Set<Id> relTypeIds = ContactRelationshipTypeSelector.newInstance()
            .getRelationshipTypesFromJunction(mapOrAccountPlanId);
        if (relTypeIds.size() > 0) {
            fieldCondition =
                '(Contact_Relationship_Type__r.' +
                usedInString +
                ' = true OR Contact_Relationship_Type__c IN :relTypeIds)';
        } else {
            fieldCondition = 'Contact_Relationship_Type__r.' + usedInString + ' = true';
        }

        Set<String> queryFields = additionalQueryFields();

        String condition =
            'Contact_Relationship_Type__c != null AND Contact_Relationship_Type__r.pqcrush__IsActive__c = true AND ' +
            fieldCondition +
            ' AND (From_Contact__c IN :ids OR To_Contact__c IN :ids) AND ' +
            mapOrAccountPlanId.getSobjectType() +
            ' = :mapOrAccountPlanId';

        fflib_QueryFactory query = newQueryFactory().setCondition(condition).selectFields(queryFields);

        return Database.query(query.toSOQL());
    }

    public List<Contact_Relationship__c> selectGlobalRelationshipsById(
        Set<Id> ids,
        Id mapOrAccountPlanId,
        Boolean hasAccountPlanSetting
    ) {
        String fieldCondition = '';
        String usedInString = 'pqcrush__Used_in_all_relationship_maps__c';
        if (hasAccountPlanSetting) {
            usedInString = 'pqcrush__Used_in_all_account_plans__c';
        }

        Set<Id> relTypeIds = ContactRelationshipTypeSelector.newInstance()
            .getRelationshipTypesFromJunction(mapOrAccountPlanId);
        if (relTypeIds.size() > 0) {
            fieldCondition =
                '(Contact_Relationship_Type__r.' +
                usedInString +
                ' = true OR Contact_Relationship_Type__c IN :relTypeIds)';
        } else {
            fieldCondition = 'Contact_Relationship_Type__r.' + usedInString + ' = true';
        }

        String condition =
            'Contact_Relationship_Type__c != null AND Contact_Relationship_Type__r.pqcrush__IsActive__c = true AND ' +
            fieldCondition +
            ' AND (From_Contact__c IN :ids OR To_Contact__c IN :ids) AND pqcrush__Account_Plan__c = null AND pqcrush__Relationship_Map__c = null';

        Set<String> queryFields = additionalQueryFields();
        fflib_QueryFactory query = newQueryFactory().setCondition(condition).selectFields(queryFields);

        return Database.query(query.toSOQL());
    }

    private Set<String> additionalQueryFields() {
        Set<String> queryFields = new Set<String>();
        queryFields.add('Contact_Relationship_Type__c.Label_Editable__c');
        queryFields.add('Contact_Relationship_Type__c.Label__c');
        queryFields.add('Contact_Relationship_Type__c.Color__c');
        queryFields.add('Relationship_Map__c');
        queryFields.add('Account_Plan__c');
        queryFields.add('Relationship_Map__r.Name');
        queryFields.add('Account_Plan__r.Name');
        return queryFields;
    }
}