default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Contact_Relationship_Type__c/Contact_Relationship_Type__c.object-meta.xml
<CustomObject>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder_Relationship__c/Map_Member_Placeholder_Relationship__c.object-meta.xml
<CustomObject>
    <label>Map Member Placeholder Relationship</label>
    <nameField>
        <label>Map Member Placeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Member Placeholder Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Map Member Placeholder Relationships</relationshipLabel>
    <relationshipName>Map_Member_Placeholder_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Contact_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Type</label>
    <referenceTo>Contact_Relationship_Type__c</referenceTo>
    <relationshipLabel>Map Member Placeholder Relationships</relationshipLabel>
    <relationshipName>Map_Member_Placeholder_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Is_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Is_Hierarchy__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this is true, then the relationship line is a hierarchy line that identifies that node A reports to node B</description>
    <label>Is_Hierarchy</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Map Member Placeholder Relationships</relationshipLabel>
    <relationshipName>Map_Member_Placeholder_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/ReportStructureWrapperServiceTest.cls
@isTest
private class ReportStructureWrapperServiceTest {
    @isTest
    public static void organizeMemberListTest() {
        Map_Member_Placeholder_Relationship__c mmpr1 = new Map_Member_Placeholder_Relationship__c(
            To__c = fflib_IDGenerator.generate(Contact.SObjectType),
            From__c = fflib_IDGenerator.generate(Contact.SObjectType),
            Is_Hierarchy__c = true,
            Contact_Relationship_Type__c = null,
            Relationship_Map__c = null,
            Account_Plan__c = fflib_IDGenerator.generate(Account_Plan__c.SObjectType)
        );

        Map_Member_Placeholder_Relationship__c mmpr2 = new Map_Member_Placeholder_Relationship__c(
            To__c = fflib_IDGenerator.generate(Contact.SObjectType),
            From__c = fflib_IDGenerator.generate(Contact.SObjectType),
            Is_Hierarchy__c = true,
            Contact_Relationship_Type__c = null,
            Relationship_Map__c = fflib_IDGenerator.generate(Relationship_Map__c.SObjectType),
            Account_Plan__c = null
        );

        List<Map_Member_Placeholder_Relationship__c> mapMemberList = new List<Map_Member_Placeholder_Relationship__c>{
            mmpr1,
            mmpr2
        };

        Map<Id, List<Map_Member_Placeholder_Relationship__c>> result = ReportStructureWrapperService.organizeMemberList(
            mapMemberList
        );

        System.assertEquals(2, result.size());
        System.assert(result.keySet().contains(mmpr1.Account_Plan__c));
        System.assert(result.keySet().contains(mmpr2.Relationship_Map__c));
    }

    @isTest
    public static void getContactMapTest() {
        TestMockData md = new TestMockData();
        ContactSelector selector = md.mockContactSelector;

        Id c1 = fflib_IDGenerator.generate(Contact.SObjectType);
        Id c2 = fflib_IDGenerator.generate(Contact.SObjectType);
        Id c3 = fflib_IDGenerator.generate(Contact.SObjectType);

        Map_Member_Placeholder_Relationship__c mmpr1 = new Map_Member_Placeholder_Relationship__c(
            To__c = c1,
            From__c = c2,
            Is_Hierarchy__c = true,
            Contact_Relationship_Type__c = null,
            Relationship_Map__c = null,
            Account_Plan__c = fflib_IDGenerator.generate(Account_Plan__c.SObjectType)
        );

        Map_Member_Placeholder_Relationship__c mmpr2 = new Map_Member_Placeholder_Relationship__c(
            To__c = c3,
            From__c = c1,
            Is_Hierarchy__c = true,
            Contact_Relationship_Type__c = null,
            Relationship_Map__c = fflib_IDGenerator.generate(Relationship_Map__c.SObjectType),
            Account_Plan__c = null
        );

        Set<Id> contactIds = new Set<Id>{ c1, c2, c3 };

        md.mocks.startStubbing();
        md.mocks.when(selector.selectById(contactIds)).thenReturn(new List<Contact>{ md.mockContact });
        md.mocks.stopStubbing();

        List<Map_Member_Placeholder_Relationship__c> mapMemberList = new List<Map_Member_Placeholder_Relationship__c>{
            mmpr1,
            mmpr2
        };

        Map<Id, Contact> result = ReportStructureWrapperService.getContactMap(mapMemberList);

        System.assert(result.containsKey(md.mockContact.Id));
    }
}