default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/pq_CRUSH_Plan_Overview__c/pq_CRUSH_Plan_Overview__c.object-meta.xml
<CustomObject>
    <label>CRUSH Plan Overview</label>
    <nameField>
        <label>Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRUSH Plan Overviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_CRUSH_Plan_Overview__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>CRUSH Plan Overviews</relationshipLabel>
    <relationshipName>CRUSH_Plan_Overviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/pq_CRUSH_Plan_Overview__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <label>Background Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/pq_CRUSH_Plan_Overview__c/fields/Data_Key__c.field-meta.xml
<CustomField>
    <fullName>Data_Key__c</fullName>
    <description>Add a key to distinguish data between components added to the same Account Plan</description>
    <inlineHelpText>Add a key to distinguish data between components added to the same Account Plan</inlineHelpText>
    <label>Data Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/PlanOverviewSelector.cls
public with sharing class PlanOverviewSelector extends AccountPlanChildSelector {
    public static PlanOverviewSelector newInstance() {
        return (PlanOverviewSelector) Application.Selector.newInstance(pq_CRUSH_Plan_Overview__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            pq_CRUSH_Plan_Overview__c.Id,
            pq_CRUSH_Plan_Overview__c.Name,
            pq_CRUSH_Plan_Overview__c.Title__c,
            pq_CRUSH_Plan_Overview__c.Description__c,
            pq_CRUSH_Plan_Overview__c.Background_Color__c,
            pq_CRUSH_Plan_Overview__c.Account_Plan__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return pq_CRUSH_Plan_Overview__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<pq_CRUSH_Plan_Overview__c> selectById(Set<Id> idSet) {
        return (List<pq_CRUSH_Plan_Overview__c>) selectSObjectsById(idSet);
    }

    public List<pq_CRUSH_Plan_Overview__c> selectByAccountPlan(Set<Id> idSet, String dataKey, Boolean isGlobal) {
        fflib_QueryFactory queryFactory = newQueryFactory();

        if (isGlobal) {
            return Database.query(queryFactory.setCondition('Data_Key__c = :dataKey').toSOQL());
        }

        return Database.query(
            queryFactory.setCondition('Account_Plan__c IN :idSet AND Data_Key__c = :dataKey').toSOQL()
        );
    }
}