default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Anchor__c/RM_Anchor__c.object-meta.xml
<CustomObject>
    <label>RM Anchor</label>
    <nameField>
        <label>RM Anchors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM Anchors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Anchor__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>RM Anchors</relationshipLabel>
    <relationshipName>RM_Anchors</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Anchor__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Anchors</relationshipLabel>
    <relationshipName>RM_Anchors</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/RMAnchorSelector.cls
public with sharing class RMAnchorSelector extends fflib_SObjectSelector {
    public static RMAnchorSelector newInstance() {
        return (RMAnchorSelector) Application.Selector.newInstance(RM_Anchor__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{ RM_Anchor__c.Id, RM_Anchor__c.From__c, RM_Anchor__c.To__c };
    }

    public Schema.SObjectType getSObjectType() {
        return RM_Anchor__c.sObjectType;
    }

    public override String getOrderBy() {
        return RM_Anchor__c.LastModifiedDate.getDescribe().getName() + ' ASC';
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<RM_Anchor__c> selectByObjectId(Set<Id> objectId) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Account_Plan__c IN :objectId OR Relationship_Map__c IN :objectId');
        return Database.query(query.toSOQL());
    }

    public List<RM_Anchor__c> selectByObjectIdAndFromField(Id objectId, Set<String> fromField) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('(Account_Plan__c = :objectId OR Relationship_Map__c = :objectId) AND From__c IN :fromField');
        return Database.query(query.toSOQL());
    }
}