default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>White Spaces</relationshipLabel>
    <relationshipName>White_Spaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/White_Space__c/fields/AreCellsFiltered__c.field-meta.xml
<CustomField>
    <fullName>AreCellsFiltered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether cell data is populated based on having a parent relationship to the Account</description>
    <label>Filter Cells</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space__c/fields/AreColumnsFiltered__c.field-meta.xml
<CustomField>
    <fullName>AreColumnsFiltered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Filter Columns</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space__c/fields/AreRowsFiltered__c.field-meta.xml
<CustomField>
    <fullName>AreRowsFiltered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Filter Rows</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space__c/fields/AreUnrelatedCellsFiltered__c.field-meta.xml
<CustomField>
    <fullName>AreUnrelatedCellsFiltered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If filter cells is checked, then this checkbox determines if amount types using an object that has no relation to an account are also filtered out, or are still shown on the cross sell map.</description>
    <label>Filter Cells Without Relationships</label>
    <type>Checkbox</type>
</CustomField>

default/objects/White_Space__c/fields/White_Space_Template__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cross-Sell Template</label>
    <referenceTo>White_Space_Template__c</referenceTo>
    <relationshipLabel>Cross-Sell Maps</relationshipLabel>
    <relationshipName>White_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/White_Space_Template__c/White_Space_Template__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Template</label>
    <nameField>
        <label>Cross-Sell Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/WhiteSpaceSelector.cls
public with sharing class WhiteSpaceSelector extends fflib_SObjectSelector {
    public static WhiteSpaceSelector newInstance() {
        return (WhiteSpaceSelector) Application.Selector.newInstance(White_Space__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            White_Space__c.Id,
            White_Space__c.Name,
            White_Space__c.Account_Plan__c,
            White_Space__c.White_Space_Template__c,
            White_Space__c.AreColumnsFiltered__c,
            White_Space__c.AreRowsFiltered__c,
            White_Space__c.AreCellsFiltered__c,
            White_Space__c.AreUnrelatedCellsFiltered__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return White_Space__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<White_Space__c> selectById(Set<ID> idSet) {
        return (List<White_Space__c>) selectSObjectsById(idSet);
    }
    public List<White_Space__c> selectByTemplateId(Id templateId) {
        fflib_QueryFactory query = newQueryFactory();
        return Database.query(query.setCondition('White_Space_Template__c = :templateId').toSOQL());
    }

    public List<White_Space__c> selectWithGridDataById(Set<ID> idSet) {
        fflib_QueryFactory query = newWhitespaceQueryFactory();

        return Database.query(query.setCondition('Id IN :idSet').toSOQL());
    }

    public List<White_Space__c> selectWithGridDataByAccountPlanId(Set<ID> accountPlanIds) {
        fflib_QueryFactory query = newWhitespaceQueryFactory();

        return Database.query(query.setCondition('Account_Plan__c IN :accountPlanIds').toSOQL());
    }

    public White_Space__c selectFirstWithGridDataByAccountPlanId(Id accountPlanId) {
        fflib_QueryFactory query = newWhitespaceQueryFactory();
        query.setCondition('Account_Plan__c = :accountPlanId');
        query.setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        query.setLimit(1);

        List<White_Space__c> queryResults = Database.query(query.toSOQL());
        return (White_Space__c) UtilityForList.first(queryResults);
    }

    public List<White_Space__c> selectFirstByAccountPlanId(Id accountPlanId) {
        fflib_QueryFactory query = newQueryFactory();
        List<White_Space__c> queryResults = Database.query(
            query.setCondition('Account_Plan__c = :accountPlanId').toSOQL()
        );
        return queryResults;
    }

    public White_Space__c selectById(Id whiteSpaceId) {
        fflib_QueryFactory query = newWhitespaceQueryFactory();
        List<White_Space__c> queryResults = Database.query(
            query.setCondition('Id = :whiteSpaceId').setLimit(1).toSOQL()
        );
        return (White_Space__c) UtilityForList.first(queryResults);
    }

    private fflib_QueryFactory newWhitespaceQueryFactory() {
        fflib_QueryFactory query = newQueryFactory();
        new WhiteSpaceTemplateSelector()
            .configureQueryFactoryFields(
                query,
                White_Space__c.White_Space_Template__c.getDescribe().getRelationshipName()
            );
        new AccountPlanSelector()
            .configureQueryFactoryFields(query, White_Space__c.Account_Plan__c.getDescribe().getRelationshipName());

        new WhiteSpaceRowSelector().addQueryFactorySubselect(query);
        new WhiteSpaceColumnSelector().addQueryFactorySubselect(query);

        return query;
    }
}