default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Account_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/SWOT_Analysis__c/SWOT_Analysis__c.object-meta.xml
<CustomObject>
    <label>SWOT Analysis</label>
    <nameField>
        <label>SWOT Analysis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SWOT Analysis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/SWOT_Analysis__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>SWOT Analysis</relationshipLabel>
    <relationshipName>SWOT_Analysis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/SWOT_Analysis__c/fields/Description_Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Description_Rich_Text__c</fullName>
    <label>Description (Rich Text)</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

default/objects/SWOT_Analysis__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunities</label>
</RecordType>

default/objects/SWOT_Analysis__c/recordTypes/Strength.recordType-meta.xml
<RecordType>
    <fullName>Strength</fullName>
    <active>true</active>
    <label>Strengths</label>
</RecordType>

default/objects/SWOT_Analysis__c/recordTypes/Threat.recordType-meta.xml
<RecordType>
    <fullName>Threat</fullName>
    <active>true</active>
    <label>Threats</label>
</RecordType>

default/objects/SWOT_Analysis__c/recordTypes/Weakness.recordType-meta.xml
<RecordType>
    <fullName>Weakness</fullName>
    <active>true</active>
    <label>Weaknesses</label>
</RecordType>

default/classes/SWOTMatrixControllerTest.cls
@isTest
private class SWOTMatrixControllerTest {
    private static final String ACCOUNT_PLAN_NAME = 'Account Plan 1';

    @testSetup
    static void testSetup() {
        SWOTAnalysis.bypassEmailTrigger = true;
        AccountPlans.bypassEmailTrigger = true;

        Account a = new Account(Name = 'Account 1');
        insert a;

        Account_Plan__c ap = new Account_Plan__c(Name = ACCOUNT_PLAN_NAME, Account__c = a.Id);
        insert ap;

        Map<String, Schema.RecordTypeInfo> recordTypesByName = SWOT_Analysis__c.SObjectType.getDescribe()
            .getRecordTypeInfosByDeveloperName();
        Id strengthRTId = recordTypesByName.get('Strength').getRecordTypeId();
        Id weaknessRTId = recordTypesByName.get('Weakness').getRecordTypeId();
        Id opportunityRTId = recordTypesByName.get('Opportunity').getRecordTypeId();
        Id threatRTId = recordTypesByName.get('Threat').getRecordTypeId();

        SWOT_Analysis__c strength = new SWOT_Analysis__c(
            Name = 'Strength',
            Account_Plan__c = ap.Id,
            RecordTypeId = strengthRTId
        );
        SWOT_Analysis__c weakness = new SWOT_Analysis__c(
            Name = 'Weakness',
            Account_Plan__c = ap.Id,
            RecordTypeId = weaknessRTId
        );
        SWOT_Analysis__c opportunity = new SWOT_Analysis__c(
            Name = 'Opportunity',
            Account_Plan__c = ap.Id,
            RecordTypeId = opportunityRTId
        );
        SWOT_Analysis__c threat = new SWOT_Analysis__c(
            Name = 'Threat',
            Account_Plan__c = ap.Id,
            RecordTypeId = threatRTId
        );
        insert new List<SWOT_Analysis__c>{ strength, weakness, opportunity, threat };
    }

    @isTest
    static void getSWOTMatrixTest() {
        // Given
        Account_Plan__c accountPlan = [SELECT Id FROM Account_Plan__c WHERE Name = :ACCOUNT_PLAN_NAME];

        // When
        SWOTMatrix matrix = SWOTMatrixController.getSWOTMatrix(accountPlan.Id);

        // Then
        System.assertNotEquals(null, matrix);
        System.assertNotEquals(null, matrix.items);
        System.assertEquals(4, matrix.items.size());
    }

    @isTest
    static void createItemTest() {
        SWOTAnalysis.bypassEmailTrigger = true;

        // Given
        Map<String, Schema.RecordTypeInfo> recordTypesByName = SWOT_Analysis__c.SObjectType.getDescribe()
            .getRecordTypeInfosByDeveloperName();
        Account_Plan__c accountPlan = [SELECT Id FROM Account_Plan__c WHERE Name = :ACCOUNT_PLAN_NAME];

        // When
        SWOT_Analysis__c analysis = new SWOT_Analysis__c(
            Name = 'New Strength',
            Description_Rich_Text__c = 'super cool description',
            Account_Plan__c = accountPlan.Id,
            RecordTypeId = recordTypesByName.get('Strength').getRecordTypeId()
        );
        SWOT_Analysis__c result = SWOTMatrixController.createItem(analysis);

        // Then
        System.assertNotEquals(null, result.Id);
        System.assertEquals(analysis.Name, result.Name);
        System.assertEquals(analysis.Description_Rich_Text__c, result.Description_Rich_Text__c);
    }

    @isTest
    static void updateItemTest() {
        SWOTAnalysis.bypassEmailTrigger = true;

        // Given
        SWOT_Analysis__c analysis = [SELECT Id, Name, Description_Rich_Text__c FROM SWOT_Analysis__c LIMIT 1];

        // When
        analysis.Name = 'fantastic updated name';
        analysis.Description_Rich_Text__c = 'not the old, lame description';
        SWOT_Analysis__c result = SWOTMatrixController.updateItem(analysis);

        // Then
        System.assertEquals(analysis.Name, result.Name);
        System.assertEquals(analysis.Description_Rich_Text__c, result.Description_Rich_Text__c);
    }

    @isTest
    static void deleteItemTest() {
        // Given
        SWOT_Analysis__c analysis = [SELECT Id FROM SWOT_Analysis__c LIMIT 1];

        // When
        SWOTMatrixController.deleteItem(analysis);

        // Then
        List<SWOT_Analysis__c> queryResults = [SELECT Id FROM SWOT_Analysis__c WHERE Id = :analysis.Id];

        System.assertEquals(0, queryResults.size());
    }
}