default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Account Plan Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Team_Member__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/TeamMemberService.cls
public with sharing class TeamMemberService {
    public static Team_Member__c create(Team_Member__c teamMember) {
        return service().create(teamMember);
    }

    public static List<Team_Member__c> createOwnersForAccountPlans(List<Account_Plan__c> accountPlans) {
        return service().createOwnersForAccountPlans(accountPlans);
    }

    private static TeamMemberServiceImpl service() {
        return (TeamMemberServiceImpl) Application.Service.newInstance(TeamMemberServiceImpl.class);
    }
}