default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Account_Plan__c/fields/Account_Plan_Score__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Score__c</fullName>
    <formula>Intermediate_Score__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Plan Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Account_Plan_Score_History__c/pq_Account_Plan_Score_History__c.object-meta.xml
<CustomObject>
    <label>Account Plan Score History</label>
    <nameField>
        <displayFormat>APSH-{0000}</displayFormat>
        <label>Account Plan Score History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Score Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Account_Plan_Score_History__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Account Plan Score Histories</relationshipLabel>
    <relationshipName>Account_Plan_Score_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/pq_Account_Plan_Score_History__c/fields/Year_Week__c.field-meta.xml
<CustomField>
    <fullName>Year_Week__c</fullName>
    <description>Year week in the form of YYYYWW, example 202305 (fifth week of 2023)</description>
    <label>Year Week</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/ScheduleForAccountPlanScoreBatch.cls
@SuppressWarnings('PMD.AvoidGlobalModifier,PMD.EmptyStatementBlock')
global with sharing class ScheduleForAccountPlanScoreBatch implements Database.Batchable<Account_Plan__c>, Schedulable {
    /******************************
     *     Schedulable Methods
     ******************************/

    global void execute(SchedulableContext context) {
        Database.executeBatch(this);
    }

    /******************************
     *     Batchable Methods
     ******************************/

    global Iterable<Account_Plan__c> start(Database.BatchableContext context) {
        return AccountPlanSelector.newInstance().selectByStatus('Open');
    }

    global void execute(Database.BatchableContext context, List<Account_Plan__c> records) {
        List<pq_Account_Plan_Score_History__c> scoreHistories = new List<pq_Account_Plan_Score_History__c>();

        Date today = Date.Today();
        Date jan1 = Date.newInstance(today.Year(), 1, 1);
        Integer weeks = jan1.DaysBetween(today) / 7 + 1;

        Decimal yearweek = today.Year() * 100 + weeks;

        for (Account_Plan__c ap : records) {
            pq_Account_Plan_Score_History__c scoreHistory = new pq_Account_Plan_Score_History__c(
                Account_Plan__c = ap.Id,
                Year_Week__c = yearweek,
                Score__c = ap.Account_Plan_Score__c
            );
            scoreHistories.add(scoreHistory);
        }

        if (scoreHistories.size() > 0) {
            AccountPlanScoreHistoryService.insertScores(scoreHistories);
        }
    }

    global void finish(Database.BatchableContext context) {
    }
}