default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/CRUSH_Settings_Obj__c/CRUSH_Settings_Obj__c.object-meta.xml
<CustomObject>
    <description>The object that holds the organization wide and user specific settings for CRUSH.</description>
    <label>CRUSH Settings</label>
    <nameField>
        <displayFormat>CRUSH-{0000}</displayFormat>
        <label>CRUSH Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRUSH Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/CRUSH_Settings_Obj__c/fields/Score_High_Color__c.field-meta.xml
<CustomField>
    <fullName>Score_High_Color__c</fullName>
    <description>The RGB color when the score is high (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the score is high (in format #aabbcc)</inlineHelpText>
    <label>Score High Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Score_Low_Color__c.field-meta.xml
<CustomField>
    <fullName>Score_Low_Color__c</fullName>
    <description>The RGB color when the score is low (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the score is low (in format #aabbcc)</inlineHelpText>
    <label>Score Low Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Score_Low_Mid_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Score_Low_Mid_Boundary__c</fullName>
    <description>The boundary between low &amp; middle.  Anything below this value is considered low.</description>
    <inlineHelpText>The boundary between low &amp; middle.  Anything below this value is considered low.</inlineHelpText>
    <label>Score Low Middle Boundary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Score_Mid_Color__c.field-meta.xml
<CustomField>
    <fullName>Score_Mid_Color__c</fullName>
    <description>The RGB color when the score is in the middle (in format #aabbcc)</description>
    <inlineHelpText>The RGB color when the score is in the middle (in format #aabbcc)</inlineHelpText>
    <label>Score Middle Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Score_Mid_High_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Score_Mid_High_Boundary__c</fullName>
    <description>The boundary between middle &amp; high.  Anything equal or above this value is considered high.</description>
    <inlineHelpText>The boundary between middle &amp; high.  Anything equal or above this value is considered high.</inlineHelpText>
    <label>Score Middle High Boundary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/PQ_AP_Score__mdt.object-meta.xml
<CustomObject>
    <description>Settings used in the formulas used to calculate a score for an account plan</description>
    <label>Account Plan Score Settings</label>
    <pluralLabel>AP Score Settings</pluralLabel>
</CustomObject>

default/objects/PQ_AP_Score__mdt/fields/Category_Point_Total__c.field-meta.xml
<CustomField>
    <fullName>Category_Point_Total__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Category Point Total used in percent based component</description>
    <label>Category Point Total</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Count_BP_High__c.field-meta.xml
<CustomField>
    <fullName>Count_BP_High__c</fullName>
    <defaultValue>5</defaultValue>
    <description>The high breakpoint for the number of objects when calculating the score</description>
    <inlineHelpText>If the count is above this value it will have the high breakpoint score value for the score</inlineHelpText>
    <label>Count Breakpoint High</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Count_BP_Low__c.field-meta.xml
<CustomField>
    <fullName>Count_BP_Low__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The low breakpoint for the number of objects when calculating the score</description>
    <inlineHelpText>If the count is below this value it will have zero points for the score</inlineHelpText>
    <label>Count Breakpoint Low</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Count_BP_Mid__c.field-meta.xml
<CustomField>
    <fullName>Count_BP_Mid__c</fullName>
    <defaultValue>3</defaultValue>
    <description>The middle breakpoint for the number of objects when calculating the score</description>
    <inlineHelpText>If the count is below this value but above the low value the low breakpoint score will be used, if above this value but below the high value the mid breakpoint score will be used</inlineHelpText>
    <label>Count Breakpoint Mid</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Date_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Date_Field_API_Name__c</fullName>
    <description>The field on the account plan that holds the date value that is used for time decay of the score this metadata record represents</description>
    <inlineHelpText>If this field is not set or if &apos;Use Time Decay&apos; is not checked then time decay will not be used for the scoring of this object.  Time decay will also not work if the field entered is invalid or not a date or date time field on the Account Plan object.</inlineHelpText>
    <label>Date Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Score_BP_High__c.field-meta.xml
<CustomField>
    <fullName>Score_BP_High__c</fullName>
    <defaultValue>10</defaultValue>
    <description>The score used if the count is equal to or greater than the high breakpoint value</description>
    <label>Count Breakpoint Score High</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Score_BP_Low__c.field-meta.xml
<CustomField>
    <fullName>Score_BP_Low__c</fullName>
    <defaultValue>3</defaultValue>
    <description>The score used if the count is equal to the low breakpoint or between the low and mid breakpoint values</description>
    <label>Count Breakpoint Score Low</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Score_BP_Mid__c.field-meta.xml
<CustomField>
    <fullName>Score_BP_Mid__c</fullName>
    <defaultValue>5</defaultValue>
    <description>The score used if the count is equal to the middle breakpoint or between the middle and high breakpoint values</description>
    <label>Count Breakpoint Score Mid</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Score_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Score_Field_API_Name__c</fullName>
    <description>The field on the account plan that holds the score value that this metadata record represents</description>
    <inlineHelpText>This must be a field on the pqcrush__Account_Plan__c object and must be the API name.  Please make sure it&apos;s a valid API name for a field.</inlineHelpText>
    <label>Score Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Threshold_Limit__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Limit__c</fullName>
    <defaultValue>10</defaultValue>
    <description>The threshold Limit used to set a value that sets a limit or boundary</description>
    <label>Threshold Limit</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_High__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_High__c</fullName>
    <defaultValue>90</defaultValue>
    <description>The number of days used for the upper time breakpoint since any records of this type have been modified</description>
    <inlineHelpText>This is the final breakpoint for time decayed scoring</inlineHelpText>
    <label>Time Breakpoint High</label>
    <precision>7</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_Low__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_Low__c</fullName>
    <defaultValue>7</defaultValue>
    <description>The number of days used for the lower time breakpoint since any records of this type have been modified</description>
    <inlineHelpText>This is the first breakpoint after 0 days</inlineHelpText>
    <label>Time Breakpoint Low</label>
    <precision>7</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_Mid__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_Mid__c</fullName>
    <defaultValue>30</defaultValue>
    <description>The number of days used for the middle time breakpoint since any records of this type have been modified</description>
    <inlineHelpText>This is the second breakpoint in days that time decay can hit</inlineHelpText>
    <label>Time Breakpoint Mid</label>
    <precision>7</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_Mult_High__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_Mult_High__c</fullName>
    <defaultValue>0.25</defaultValue>
    <description>The multiplier if the number of days since any record was updated is greater than or equal to the high time breakpoint</description>
    <inlineHelpText>This value should be between 0.00 and 1.00</inlineHelpText>
    <label>Time Breakpoint Multiplier High</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_Mult_Low__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_Mult_Low__c</fullName>
    <defaultValue>0.75</defaultValue>
    <description>The multiplier if the number of days since any record was updated is greater than or equal to the low time breakpoint but less than the middle time breakpoint</description>
    <inlineHelpText>This value should be between 0.00 and 1.00</inlineHelpText>
    <label>Time Breakpoint Multiplier Low</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_Mult_Mid__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_Mult_Mid__c</fullName>
    <defaultValue>0.50</defaultValue>
    <description>The multiplier if the number of days since any record was updated is greater than or equal to the Middle time breakpoint but less than the high time breakpoint</description>
    <inlineHelpText>This value should be between 0.00 and 1.00</inlineHelpText>
    <label>Time Breakpoint Multiplier Mid</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Use_Time_Decay__c.field-meta.xml
<CustomField>
    <fullName>Use_Time_Decay__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If set then score will decrease by a multiplier based on how long since any records were modified</description>
    <inlineHelpText>This is only available for packaged score objects</inlineHelpText>
    <label>Use Time Decay</label>
    <type>Checkbox</type>
</CustomField>

default/classes/HealthScoreServiceImpl.cls
public with sharing class HealthScoreServiceImpl {
    public Double getTotalScoreForAccountPlan(Account_Plan__c accountPlan, List<PQ_AP_Score__mdt> allMetadata) {
        if (accountPlan == null || allMetadata == null) {
            return 0;
        }
        Double updatedScore = 0;
        for (PQ_AP_Score__mdt metadata : allMetadata) {
            Double points = getScoreFromPlanForMetadata(accountPlan, metadata);
            if (points != -1) {
                updatedScore += points;
            }
        }
        return updatedScore;
    }

    public Double getTotalScoreForAccountPlanPercent(Account_Plan__c accountPlan, List<PQ_AP_Score__mdt> allMetadata) {
        if (accountPlan == null || allMetadata == null) {
            return 0;
        }
        Double updatedScore = 0;
        for (PQ_AP_Score__mdt metadata : allMetadata) {
            Double points = getScoreFromPlanForMetadataPercent(accountPlan, metadata);

            Decimal thresholdLimit = (metadata.Threshold_Limit__c != null)
                ? metadata.Threshold_Limit__c
                : metadata.Score_BP_High__c;

            Decimal categoryPointTotal = (metadata.Category_Point_Total__c != null)
                ? metadata.Category_Point_Total__c
                : (metadata.Threshold_Limit__c != null) ? metadata.Threshold_Limit__c : metadata.Score_BP_High__c;

            points = points < thresholdLimit ? points : thresholdLimit;

            Double percentage = (points / thresholdLimit) * 100;

            Double pointsAwarded = (percentage / 100) * categoryPointTotal;

            if (points != -1) {
                updatedScore += pointsAwarded;
            }
        }

        return updatedScore;
    }

    public Double getMaxTotalScore() {
        List<PQ_AP_Score__mdt> allMetadata = HealthScoreMetadataSelector.newInstance().selectEnabled();
        Decimal maxPoints = 0;
        for (PQ_AP_Score__mdt metadata : allMetadata) {
            maxPoints += metadata.Score_BP_High__c;
        }
        return maxPoints;
    }

    public Double getMaxTotalScorePercent() {
        List<PQ_AP_Score__mdt> allMetadata = HealthScoreMetadataSelector.newInstance().selectEnabled();
        Decimal maxPoints = 0;
        for (PQ_AP_Score__mdt metadata : allMetadata) {
            maxPoints += (metadata.Category_Point_Total__c != null)
                ? metadata.Category_Point_Total__c
                : (metadata.Threshold_Limit__c != null) ? metadata.Threshold_Limit__c : metadata.Score_BP_High__c;
        }
        return maxPoints;
    }

    public Set<String> getAccountPlanFieldNamesForScoreMetadata(List<PQ_AP_Score__mdt> scoreMetadata) {
        if (scoreMetadata == null || scoreMetadata.size() == 0) {
            return new Set<String>();
        }
        Set<String> fieldNames = new Set<String>();
        for (PQ_AP_Score__mdt metadata : scoreMetadata) {
            if (
                UTIL_Describe.isValidField(
                    Schema.SObjectType.pqcrush__Account_Plan__c.getName(),
                    metadata.Score_Field_API_Name__c.toLowerCase()
                )
            ) {
                fieldNames.add(metadata.Score_Field_API_Name__c);
                if (
                    metadata.Date_Field_API_Name__c != null &&
                    UTIL_Describe.isValidField(
                        Schema.SObjectType.pqcrush__Account_Plan__c.getName(),
                        metadata.Date_Field_API_Name__c.toLowerCase()
                    )
                ) {
                    fieldNames.add(metadata.Date_Field_API_Name__c);
                }
            }
        }
        return fieldNames;
    }

    public List<PQ_AP_Score__mdt> getValidScoreMetadata() {
        List<PQ_AP_Score__mdt> allMetadata = HealthScoreMetadataSelector.newInstance().selectEnabled();
        List<PQ_AP_Score__mdt> validMetadata = new List<PQ_AP_Score__mdt>();
        for (PQ_AP_Score__mdt metadata : allMetadata) {
if (
                UTIL_Describe.isValidField(
                    Schema.SObjectType.pqcrush__Account_Plan__c.getName(),
                    metadata.Score_Field_API_Name__c.toLowerCase()
                )
            ) {
                validMetadata.add(metadata);
            }
        }
        return validMetadata;
    }

    public ColorBoundary getColorBoundaryFromSettings(CRUSH_Settings_Obj__c settings) {
        String lowColor = settings?.Score_Low_Color__c != null ? settings.Score_Low_Color__c : '#E1341E';
        String midColor = settings?.Score_Mid_Color__c != null ? settings.Score_Mid_Color__c : '#EB8214';
        String highColor = settings?.Score_High_Color__c != null ? settings.Score_High_Color__c : '#2DD24A';
        Decimal lowBound = settings?.Score_Low_Mid_Boundary__c != null ? settings.Score_Low_Mid_Boundary__c : .25;
        Decimal midBound = settings?.Score_Mid_High_Boundary__c != null ? settings.Score_Mid_High_Boundary__c : .75;
        return new ColorBoundary(lowColor, midColor, highColor, lowBound, midBound);
    }

    public Double getScoreFromPlanForMetadata(Account_Plan__c accountPlan, PQ_AP_Score__mdt metadata) {
        if (accountPlan == null || metadata == null) {
            return -1;
        }
        if (metadata.DeveloperName == 'Stakeholders') {
            return getMapMemberScoreFromPlanForMetadata(accountPlan, metadata);
        }
        Double count = getCountForPlanForMetadata(accountPlan, metadata);
        if (count == -1) {
            return -1;
        }
        Double points = getPointsForMetadata(metadata, count);
        Double multiplier = getMultiplierForPlanForMetadata(accountPlan, metadata);
        return points * multiplier;
    }

    public Double getScoreFromPlanForMetadataPercent(Account_Plan__c accountPlan, PQ_AP_Score__mdt metadata) {
        if (accountPlan == null || metadata == null) {
            return -1;
        }
        if (metadata.DeveloperName == 'Stakeholders') {
            return getMapMemberScoreFromPlanForMetadataPercent(accountPlan, metadata);
        }
        Double points = getCountForPlanForMetadata(accountPlan, metadata);
        if (points < 0) {
            return 0;
        }
        //return points;
        Double multiplier = 1;
        if (metadata.Use_Time_Decay__c) {
        	multiplier = getMultiplierForPlanForMetadata(accountPlan, metadata);
        }
        return points * multiplier;
    }

    public Double getMapMemberScoreFromPlanForMetadata(Account_Plan__c accountPlan, PQ_AP_Score__mdt metadata) {
        if (accountPlan == null || metadata == null || metadata.DeveloperName != 'Stakeholders') {
            return -1;
        }
        Double count = metadata.Score_Field_API_Name__c == 'pqcrush__Key_Stakeholder_Count__c'
            ? RelationshipMapService.getMapMemberCountForAccountPlan(new List<Account_Plan__c>{ accountPlan })
            : getCountForPlanForMetadata(accountPlan, metadata);
        if (count == -1) {
            return -1;
        }
        Double points = getPointsForMetadata(metadata, count);
        Double multiplier = 1;
        if (metadata.Use_Time_Decay__c) {
            multiplier = getMultiplierForPlanForScoreMetadata(accountPlan, metadata);
        }
        return points * multiplier;
    }

    public Double getMapMemberScoreFromPlanForMetadataPercent(Account_Plan__c accountPlan, PQ_AP_Score__mdt metadata) {
        if (accountPlan == null || metadata == null || metadata.DeveloperName != 'Stakeholders') {
            return -1;
        }
        Double points = metadata.Score_Field_API_Name__c == 'pqcrush__Key_Stakeholder_Count__c'
            ? RelationshipMapService.getMapMemberCountForAccountPlan(new List<Account_Plan__c>{ accountPlan })
            : getCountForPlanForMetadata(accountPlan, metadata);
        if (points < 0) {
            return 0;
        }

        Double multiplier = 1;
        if (metadata.Use_Time_Decay__c) {
             multiplier = getMultiplierForPlanForScoreMetadata(accountPlan, metadata);
         }
        return points * multiplier;
    }

    private Double getCountForPlanForMetadata(Account_Plan__c accountPlan, PQ_AP_Score__mdt metadata) {
        if (accountPlan == null || metadata == null) {
            return -1;
        }
        Double count = 0;
        try {
            Object value = accountPlan?.get(metadata.Score_Field_API_Name__c);
            count = Double.valueOf(value);
        } catch (Exception e) {
            return -1;
        }
        return count;
    }

    private Double getMultiplierForPlanForMetadata(Account_Plan__c accountPlan, PQ_AP_Score__mdt metadata) {
        if (accountPlan == null || metadata == null) {
            return 1;
        }
        Double multiplier = 1;
        Object dateObj = metadata.Date_Field_API_Name__c != null &&
            accountPlan.getPopulatedFieldsAsMap().containsKey(metadata.Date_Field_API_Name__c)
            ? accountPlan.get(metadata.Date_Field_API_Name__c)
            : null;
        if (metadata.Use_Time_Decay__c && dateObj != null) {
            try {
                Date decayDate = Date.valueOf(dateObj);
                Integer days = decayDate.daysBetween(Date.today());
                multiplier = getTimeDecayMultiplier(metadata, days);
            } catch (Exception e) {
                multiplier = 1;
            }
        }
        return multiplier;
    }

    private Double getMultiplierForPlanForScoreMetadata(Account_Plan__c accountPlan, PQ_AP_Score__mdt metadata) {
        if (accountPlan == null || metadata == null) {
            return 1;
        }
        Double multiplier = 1;
        if (metadata.Date_Field_API_Name__c == 'pqcrush__KS_Max_LMD__c') {
            Date lastModifiedDate = RelationshipMapService.getMapMemberLastUpdatedDateForAccountPlan(
                new List<Account_Plan__c>{ accountPlan }
            );
            if (lastModifiedDate != null) {
                Integer days = lastModifiedDate.daysBetween(Date.today());
                multiplier = getTimeDecayMultiplier(metadata, days);
            }
        } else {
            multiplier = getMultiplierForPlanForMetadata(accountPlan, metadata);
        }
        return multiplier;
    }

    private Double getPointsForMetadata(PQ_AP_Score__mdt metadata, Double count) {
        if (count < metadata.Count_BP_Low__c) {
            return 0;
        }
        if (count < metadata.Count_BP_Mid__c) {
            return metadata.Score_BP_Low__c;
        }
        if (count < metadata.Count_BP_High__c) {
            return metadata.Score_BP_Mid__c;
        }
        return metadata.Score_BP_High__c;
    }

    private Double getTimeDecayMultiplier(PQ_AP_Score__mdt metadata, Integer days) {
        if (days < metadata.Time_BP_Low__c) {
            return 1;
        }
        if (days < metadata.Time_BP_Mid__c) {
            return metadata.Time_BP_Mult_Low__c;
        }
        if (days < metadata.Time_BP_High__c) {
            return metadata.Time_BP_Mult_Mid__c;
        }
        return metadata.Time_BP_Mult_High__c;
    }
}