default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>White Spaces</relationshipLabel>
    <relationshipName>White_Spaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/WS_Data_Type__c/WS_Data_Type__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Data Type</label>
    <nameField>
        <displayFormat>WSDT-{0000}</displayFormat>
        <label>WS Data Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Data Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/WS_Data_Type__c/fields/Apply_To_All_Cross_Sell_Maps__c.field-meta.xml
<CustomField>
    <fullName>Apply_To_All_Cross_Sell_Maps__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked, All Cross-Sell Maps will have access to this Data Type</description>
    <inlineHelpText>If this is checked, All Cross-Sell Maps will have access to this Data Type</inlineHelpText>
    <label>Apply To All CROSS-SELL Maps</label>
    <type>Checkbox</type>
</CustomField>

default/objects/WS_Data_Type__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color in the form of #RRGGBB (example: #FF0000 for red)</description>
    <inlineHelpText>Color in the form of #RRGGBB (example: #FF0000 for red)</inlineHelpText>
    <label>Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/WS_Data_Type__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Picklist</fullName>
                <default>true</default>
                <label>Picklist</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/WS_Data_Type__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <description>Possible values for the picklist</description>
    <inlineHelpText>Enter values, with each value separated by a new line</inlineHelpText>
    <label>Picklist Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/WS_Data_Type__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>Cross-Sell Data Types</relationshipLabel>
    <relationshipName>Cross_Sell_Data_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/WSDataTypeSelectorTest.cls
@isTest
private class WSDataTypeSelectorTest {
    @isTest
    static void selectByIdTest() {
        // Given
        Account testAccount = new Account(Name = 'Account 1');
        insert testAccount;
        Account_Plan__c ap = TestDataFactory.createAccountPlan('PlanA', testAccount);
        White_Space__c ws = TestDataFactory.createWhiteSpace(ap, 'WS Name');
        White_Space__c ws2 = TestDataFactory.createWhiteSpace(ap, 'WS 2 Name');

        WS_Data_Type__c dt = new WS_Data_Type__c(
            Data_Type__c = 'Picklist',
            Picklist_Values__c = 'one',
            White_Space__c = ws.Id,
            Label__c = 'label1',
            Color__c = '#FFF'
        );
        insert dt;

        // Shouldn't return, not in queried data type set
        WS_Data_Type__c dt2 = new WS_Data_Type__c(
            Data_Type__c = 'Picklist',
            Picklist_Values__c = 'one',
            White_Space__c = ws2.Id,
            Label__c = 'label1',
            Color__c = '#FFF'
        );
        insert dt2;

        List<WS_Data_Type__c> dataTypes = new WSDataTypeSelector().selectById(new Set<Id>{ dt.Id });

        // Then
        System.assertEquals(1, dataTypes.size());
        System.assertEquals(dt.Id, dataTypes[0].Id);
    }

    @isTest
    static void selectByWhiteSpaceIdTest() {
        // Given
        Account testAccount = new Account(Name = 'Account 1');
        insert testAccount;
        Account_Plan__c ap = TestDataFactory.createAccountPlan('PlanA', testAccount);
        White_Space__c ws = TestDataFactory.createWhiteSpace(ap, 'WS Name');
        White_Space__c ws2 = TestDataFactory.createWhiteSpace(ap, 'WS 2  Name');

        WS_Data_Type__c dt1 = new WS_Data_Type__c(
            Data_Type__c = 'Picklist',
            Picklist_Values__c = 'one',
            White_Space__c = ws.Id,
            Label__c = 'label1',
            Color__c = '#FFF'
        );
        insert dt1;

        WS_Data_Type__c dt2 = new WS_Data_Type__c(
            Data_Type__c = 'Picklist',
            Picklist_Values__c = 'one',
            White_Space__c = null,
            Label__c = 'label1',
            Color__c = '#FFF',
            Apply_To_All_Cross_Sell_Maps__c = true
        );
        insert dt2;

        // Shouldn't return, not in queried WS
        WS_Data_Type__c dt3 = new WS_Data_Type__c(
            Data_Type__c = 'Picklist',
            Picklist_Values__c = 'one',
            White_Space__c = ws2.Id,
            Label__c = 'label1',
            Color__c = '#FFF'
        );
        insert dt3;

        List<WS_Data_Type__c> dataTypes = new WSDataTypeSelector().selectByWhiteSpaceId(ws.Id);

        // Then
        System.assertEquals(2, dataTypes.size());
    }
}