default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Node_Coordinate__c/RM_Node_Coordinate__c.object-meta.xml
<CustomObject>
    <label>RM Node Coordinate</label>
    <nameField>
        <displayFormat>RMNodeCoordinate-{0000}</displayFormat>
        <label>RM Node Coordinate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Node Coordinates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Node_Coordinate__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>RM Node Coordinates</relationshipLabel>
    <relationshipName>RM_Node_Coordinates</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Node_Coordinate__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Node Coordinates</relationshipLabel>
    <relationshipName>RM_Node_Coordinates</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Node_Coordinate__c/fields/X__c.field-meta.xml
<CustomField>
    <fullName>X__c</fullName>
    <description>X Coordinate</description>
    <inlineHelpText>X Coordinate</inlineHelpText>
    <label>X</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

default/objects/RM_Node_Coordinate__c/fields/Y__c.field-meta.xml
<CustomField>
    <fullName>Y__c</fullName>
    <label>Y</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

default/classes/RMNodeCoordinateSelector.cls
public with sharing class RMNodeCoordinateSelector extends fflib_SObjectSelector {
    public static RMNodeCoordinateSelector newInstance() {
        return (RMNodeCoordinateSelector) Application.Selector.newInstance(RM_Node_Coordinate__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            RM_Node_Coordinate__c.Id,
            RM_Node_Coordinate__c.Key__c,
            RM_Node_Coordinate__c.TempId__c,
            RM_Node_Coordinate__c.Account_Plan__c,
            RM_Node_Coordinate__c.Relationship_Map__c,
            RM_Node_Coordinate__c.X__c,
            RM_Node_Coordinate__c.Y__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return RM_Node_Coordinate__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<RM_Node_Coordinate__c> selectById(Set<Id> ids) {
        return (List<RM_Node_Coordinate__c>) selectSObjectsById(ids);
    }

    public List<RM_Node_Coordinate__c> selectByKeys(Set<String> keys) {
        fflib_QueryFactory query = newQueryFactory().setCondition('Key__c IN :keys');
        return Database.query(query.toSOQL());
    }

    public List<RM_Node_Coordinate__c> selectByObjectId(Id objectId) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Account_Plan__c = :objectId OR Relationship_Map__c = :objectId');
        return Database.query(query.toSOQL());
    }

    public List<RM_Node_Coordinate__c> selectByObjectIdAndKeys(Id objectId, Set<String> keys) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition(
                '(Account_Plan__c = :objectId OR Relationship_Map__c = :objectId) AND (Key__c in :keys OR TempId__c in :keys)'
            );
        return Database.query(query.toSOQL());
    }
}