default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/pq_Account_Plan_Score_History__c/pq_Account_Plan_Score_History__c.object-meta.xml
<CustomObject>
    <label>Account Plan Score History</label>
    <nameField>
        <displayFormat>APSH-{0000}</displayFormat>
        <label>Account Plan Score History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Score Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Account_Plan_Score_History__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Account Plan Score Histories</relationshipLabel>
    <relationshipName>Account_Plan_Score_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/pq_Account_Plan_Score_History__c/fields/Year_Week__c.field-meta.xml
<CustomField>
    <fullName>Year_Week__c</fullName>
    <description>Year week in the form of YYYYWW, example 202305 (fifth week of 2023)</description>
    <label>Year Week</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/AccountPlanScoreHistorySelector.cls
public with sharing class AccountPlanScoreHistorySelector extends fflib_SObjectSelector {
    /******************************
     *      STATIC METHODS
     ******************************/

    public static AccountPlanScoreHistorySelector newInstance() {
        return (AccountPlanScoreHistorySelector) Application.Selector.newInstance(
            pq_Account_Plan_Score_History__c.SObjectType
        );
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            pq_Account_Plan_Score_History__c.Id,
            pq_Account_Plan_Score_History__c.Account_Plan__c,
            pq_Account_Plan_Score_History__c.Score__c,
            pq_Account_Plan_Score_History__c.Year_Week__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return pq_Account_Plan_Score_History__c.sObjectType;
    }

    public override String getOrderBy() {
        return pq_Account_Plan_Score_History__c.pqcrush__Year_Week__c.getDescribe().getName() + ' ASC';
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<pq_Account_Plan_Score_History__c> selectById(Set<Id> ids) {
        return (List<pq_Account_Plan_Score_History__c>) selectSObjectsById(ids);
    }

    public List<pq_Account_Plan_Score_History__c> selectByYearWeek(Decimal yearWeek) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        return Database.query(queryFactory.setCondition('Year_Week__c = :yearWeek').toSOQL());
    }

    public List<pq_Account_Plan_Score_History__c> selectByAccountPlansAfterDate(Set<Id> accountPlanIds, DateTime dt) {
        fflib_QueryFactory queryFactory = newQueryFactory();

        fflib_SObjectSelector accountPlanSelector = new AccountPlanSelector();
        accountPlanSelector.configureQueryFactoryFields(queryFactory, 'Account_Plan__r');

        return Database.query(
            queryFactory.setCondition('LastModifiedDate > :dt AND pqcrush__Account_Plan__c IN :accountPlanIds').toSOQL()
        );
    }
}