default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/RMChartSettingSelectorTest.cls
@isTest
private class RMChartSettingSelectorTest {
    @isTest
    static void newInstanceTest() {
        RMChartSettingSelector selector = RMChartSettingSelector.newInstance();
        System.assertNotEquals(null, selector);
    }

    @isTest
    static void selectByIdTest() {
        RM_Chart_Setting__c setting1 = TestDataFactory.createRMChartSetting('desc1', true);
        RM_Chart_Setting__c setting2 = TestDataFactory.createRMChartSetting('desc2', true);

        Test.startTest();
        List<RM_Chart_Setting__c> queriedResult = new RMChartSettingSelector()
            .selectById(new Set<Id>{ setting1.Id, setting2.Id });
        Test.stopTest();

        // Then the admin user should get back all three account plans
        System.assertEquals(2, queriedResult.size());
    }

    @isTest
    static void selectByObjectIdTest() {
        Account testAccount = new Account(Name = 'Account 1');
        insert testAccount;
        Account_Plan__c accountPlan1 = TestDataFactory.createAccountPlan('Account Plan 1', testAccount);
        Relationship_Map__c relMap = TestDataFactory.createRelationshipMap('mapname');

        TestDataFactory.createRMChartSetting('desc1', true, accountPlan1.Id, null);
        TestDataFactory.createRMChartSetting('desc2', true, null, relMap.Id);

        Test.startTest();
        List<RM_Chart_Setting__c> queriedResult = new RMChartSettingSelector()
            .selectByObjectId(new Set<Id>{ accountPlan1.Id, relMap.Id });
        Test.stopTest();

        // Then the admin user should get back all three account plans
        System.assertEquals(2, queriedResult.size());
    }
}