default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/CRUSH_Settings_Obj__c/CRUSH_Settings_Obj__c.object-meta.xml
<CustomObject>
    <description>The object that holds the organization wide and user specific settings for CRUSH.</description>
    <label>CRUSH Settings</label>
    <nameField>
        <displayFormat>CRUSH-{0000}</displayFormat>
        <label>CRUSH Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRUSH Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/CRUSH_Settings_Obj__c/fields/Enable_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Enable_Notifications__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Notifications</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Key_Stakeholder__c/Key_Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Key Stakeholder</label>
    <nameField>
        <displayFormat>KS-{0000}</displayFormat>
        <label>Key Stakeholder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Key_Stakeholder__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Key Stakeholders</relationshipLabel>
    <relationshipName>Key_Stakeholders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Key_Stakeholder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Key Stakeholders</relationshipLabel>
    <relationshipName>Key_Stakeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/KeyStakeholders.cls
public with sharing class KeyStakeholders extends AccountPlanChildDomain {
    @TestVisible
    static Boolean bypassEmailTrigger = false;

    public KeyStakeholders(List<Key_Stakeholder__c> sObjectList) {
        super(sObjectList);
    }

    /******************************
     *       STATIC METHODS
     ******************************/

    public static KeyStakeholders newInstance(List<Key_Stakeholder__c> sObjectList) {
        return (KeyStakeholders) Application.Domain.newInstance(sObjectList);
    }

    public static String getUniqueKey(Key_Stakeholder__c stakeholder) {
        return String.valueOf(stakeholder.Account_Plan__c) + String.valueOf(stakeholder.Contact__c);
    }

    /******************************
     *   TRIGGER HANDLER METHODS
     ******************************/

    public override void onValidate() {
        checkDuplicates();
    }

    public override void onValidate(Map<Id, SObject> existingRecords) {
        checkDuplicates();
    }

    public override void onAfterInsert() {
        if (!bypassEmailTrigger && !Application.bypassTrigger) {
            sendEmails();
        }
    }

    public override void onAfterUpdate(Map<Id, SObject> existingRecords) {
        if (!bypassEmailTrigger && !Application.bypassTrigger) {
            sendEmails();
        }
    }

    /******************************
     *      PRIVATE METHODS
     ******************************/

    private void checkDuplicates() {
        for (
            Key_Stakeholder__c duplicateStakeholder : KeyStakeholderSelector.newInstance()
                .selectDuplicatesAsSystem(Records)
        ) {
            duplicateStakeholder.addError(System.Label.error_duplicate_account_plan_key_stakeholder);
        }
    }

    private void sendEmails() {
        CRUSH_Settings_Obj__c settings = SettingService.getOrgSettingsAndCreateIfNeeded();

        if (!settings.Enable_Notifications__c || !settings.Key_Stakeholder_Updated__c) {
            return;
        }

        List<SendEmailNotifications.SendEmailRequest> emailRequests = new List<SendEmailNotifications.SendEmailRequest>();

        for (SObject sobj : Records) {
            Key_Stakeholder__c keyStakeholder = (Key_Stakeholder__c) sobj;

            SendEmailNotifications.SendEmailRequest request = new SendEmailNotifications.SendEmailRequest();
            request.accountPlanId = keyStakeholder.Account_Plan__c;
            request.eventType = 'Key_Stakeholders_Is_Updated';

            emailRequests.add(request);
        }

        try {
            SendEmailNotifications.sendEmails(emailRequests);
        } catch (Exception e) {
            System.debug('Error thrown sending update Emails: ' + e.getMessage()); //NOPMD
        }
    }

    /******************************
     *       INNER CLASSES
     ******************************/

    /**
     * This is a workaround for the lack of reflection in Apex.
     */
    public with sharing class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new KeyStakeholders(sObjectList);
        }
    }
}