default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Anchor__c/RM_Anchor__c.object-meta.xml
<CustomObject>
    <label>RM Anchor</label>
    <nameField>
        <label>RM Anchors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM Anchors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Anchor__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>RM Anchors</relationshipLabel>
    <relationshipName>RM_Anchors</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Anchor__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Anchors</relationshipLabel>
    <relationshipName>RM_Anchors</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/RMAnchorSelectorTest.cls
@isTest
private class RMAnchorSelectorTest {
    @isTest
    static void newInstanceTest() {
        RMAnchorSelector selector = RMAnchorSelector.newInstance();
        System.assertNotEquals(null, selector);
    }

    @isTest
    static void selectByObjectIdTest() {
        Account testAccount = new Account(Name = 'Account 1');
        insert testAccount;
        Account_Plan__c accountPlan1 = TestDataFactory.createAccountPlan('Account Plan 1', testAccount);
        Relationship_Map__c relMap = TestDataFactory.createRelationshipMap('mapname');

        TestDataFactory.createRMAnchor('from1', 'to1', accountPlan1.Id, null);
        TestDataFactory.createRMAnchor('from2', 'to2', null, relMap.Id);

        Test.startTest();
        List<RM_Anchor__c> queriedResult = new RMAnchorSelector()
            .selectByObjectId(new Set<Id>{ accountPlan1.Id, relMap.Id });
        Test.stopTest();

        // Should get 2 anchors back
        System.assertEquals(2, queriedResult.size());
    }

    @isTest
    static void selectByObjectIdAndFromFieldTest1() {
        Account testAccount = new Account(Name = 'Account 1');
        insert testAccount;
        Account_Plan__c accountPlan1 = TestDataFactory.createAccountPlan('Account Plan 1', testAccount);
        TestDataFactory.createRMAnchor('from1', 'to1', accountPlan1.Id, null);

        Test.startTest();
        List<RM_Anchor__c> queriedResult = new RMAnchorSelector()
            .selectByObjectIdAndFromField(accountPlan1.Id, new Set<String>{ 'from1' });
        Test.stopTest();

        // Should get 1 anchor back
        System.assertEquals(1, queriedResult.size());
    }

    @isTest
    static void selectByObjectIdAndFromFieldTest2() {
        Relationship_Map__c relMap = TestDataFactory.createRelationshipMap('mapname');
        TestDataFactory.createRMAnchor('from2', 'to2', null, relMap.Id);

        Test.startTest();
        List<RM_Anchor__c> queriedResult = new RMAnchorSelector()
            .selectByObjectIdAndFromField(relMap.Id, new Set<String>{ 'from2' });
        Test.stopTest();

        // // Should get 1 anchor back
        System.assertEquals(1, queriedResult.size());
    }
}