default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Master_Account_Plan_Associations__c/Master_Account_Plan_Associations__c.object-meta.xml
<CustomObject>
    <label>Master Account Plan Association</label>
    <nameField>
        <displayFormat>MAPS-{0000}</displayFormat>
        <label>Master Account Plan Associations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Account Plan Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Master_Account_Plan_Associations__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Master Account Plan Associations</relationshipLabel>
    <relationshipName>Master_Account_Plan_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Master_Account_Plan_Associations__c/fields/Master_Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Master_Account_Plan__c</fullName>
    <label>Master Account Plan</label>
    <referenceTo>pq_Master_Account_Plan__c</referenceTo>
    <relationshipLabel>Master Account Plan Associations</relationshipLabel>
    <relationshipName>Master_Account_Plan_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/pq_Master_Account_Plan__c/pq_Master_Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Master Account Plan</label>
    <nameField>
        <label>Master Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/classes/MasterAccountPlanAssociationSelectorTest.cls
@isTest
private class MasterAccountPlanAssociationSelectorTest {
    @isTest
    static void selectByMasterAccountPlanIdTest() {
        
        pq_Master_Account_Plan__c m = new pq_Master_Account_Plan__c(Name = 'test');
        insert m;

        Account testAccount = new Account(Name = 'Account 1');
        insert testAccount;

        Account_Plan__c ap1 = TestDataFactory.createAccountPlan('a', testAccount);
 
        Master_Account_Plan_Associations__c mpa = new Master_Account_Plan_Associations__c(
            Master_Account_Plan__c = m.Id,
            Account_Plan__c = ap1.Id
        );

        insert mpa;


        List<Master_Account_Plan_Associations__c> result = MasterAccountPlanAssociationSelector.newInstance().selectByMasterAccountPlanId(new Set<Id>{ m.Id });
        System.assertEquals(1, result.size());
        System.assertEquals(ap1.Id, result[0].Account_Plan__c);
    }
}