default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Key_Stakeholder__c/Key_Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Key Stakeholder</label>
    <nameField>
        <displayFormat>KS-{0000}</displayFormat>
        <label>Key Stakeholder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Key_Stakeholder__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Key Stakeholders</relationshipLabel>
    <relationshipName>Key_Stakeholders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Key_Stakeholder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Key Stakeholders</relationshipLabel>
    <relationshipName>Key_Stakeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Key_Stakeholder__c/fields/Influence__c.field-meta.xml
<CustomField>
    <fullName>Influence__c</fullName>
    <label>Influence (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Key_Stakeholder_Influence</valueSetName>
    </valueSet>
</CustomField>

default/objects/Key_Stakeholder__c/fields/Support__c.field-meta.xml
<CustomField>
    <fullName>Support__c</fullName>
    <label>Support (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Key_Stakeholder_Support</valueSetName>
    </valueSet>
</CustomField>

default/objects/pq_Account_Plan_Matrix_Association__c/pq_Account_Plan_Matrix_Association__c.object-meta.xml
<CustomObject>
    <label>Account Plan that uses this matrix</label>
    <nameField>
        <displayFormat>APMA-{0000}</displayFormat>
        <label>Account Plan Matrix Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans that use this matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Account_Plan_Matrix_Association__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Account Plans that use this matrix</relationshipLabel>
    <relationshipName>Account_Plans_that_use_this_matrix</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/pq_Account_Plan_Matrix_Association__c/fields/Influence_And_Support_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Influence_And_Support_Matrix__c</fullName>
    <label>Influence And Support Matrix</label>
    <referenceTo>pq_Influence_And_Support_Matrix__c</referenceTo>
    <relationshipLabel>Account Plans that use this matrix</relationshipLabel>
    <relationshipName>Account_Plans_that_use_this_matrix</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/pq_Influence__c/pq_Influence__c.object-meta.xml
<CustomObject>
    <label>Influence</label>
    <nameField>
        <label>Influence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Influence_And_Support_Matrix__c/pq_Influence_And_Support_Matrix__c.object-meta.xml
<CustomObject>
    <label>Influence And Support Matrix</label>
    <nameField>
        <label>Influence And Support Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence And Support Matrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Influence_And_Support_Matrix__c/fields/Influence_Label__c.field-meta.xml
<CustomField>
    <fullName>Influence_Label__c</fullName>
    <label>Influence Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/pq_Influence_And_Support_Matrix__c/fields/Support_Label__c.field-meta.xml
<CustomField>
    <fullName>Support_Label__c</fullName>
    <label>Support Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/pq_Influence_Matrix_Association__c/pq_Influence_Matrix_Association__c.object-meta.xml
<CustomObject>
    <label>Influence value for this matrix</label>
    <nameField>
        <displayFormat>pqIM-{0000}</displayFormat>
        <label>Influence Matrix Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influence values for this matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Influence_Matrix_Association__c/fields/Influence__c.field-meta.xml
<CustomField>
    <fullName>Influence__c</fullName>
    <label>Influence</label>
    <referenceTo>pq_Influence__c</referenceTo>
    <relationshipName>Influence_Matrix_Association</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/pq_Influence_Matrix_Association__c/fields/Influence_And_Support_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Influence_And_Support_Matrix__c</fullName>
    <label>Influence And Support Matrix</label>
    <referenceTo>pq_Influence_And_Support_Matrix__c</referenceTo>
    <relationshipName>Influence_Matrix_Association</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/pq_Relationship_Map_Matrix_Association__c/pq_Relationship_Map_Matrix_Association__c.object-meta.xml
<CustomObject>
    <label>Relationship Map that uses this matrix</label>
    <nameField>
        <displayFormat>RMMA-{0000}</displayFormat>
        <label>Relationship Map Matrix Assoc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Maps that use this matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Relationship_Map_Matrix_Association__c/fields/Influence_And_Support_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Influence_And_Support_Matrix__c</fullName>
    <label>Influence And Support Matrix</label>
    <referenceTo>pq_Influence_And_Support_Matrix__c</referenceTo>
    <relationshipLabel>Relationship Maps that use this matrix</relationshipLabel>
    <relationshipName>Relationship_Maps_that_use_this_matrix</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/pq_Relationship_Map_Matrix_Association__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Relationship Maps that use this matrix</relationshipLabel>
    <relationshipName>Relationship_Maps_that_use_this_matrix</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/pq_Support__c/pq_Support__c.object-meta.xml
<CustomObject>
    <label>Support</label>
    <nameField>
        <label>Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Support__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color RGB value in the form of #FF0011</description>
    <inlineHelpText>Enter color RGB value in the form of #FF0011</inlineHelpText>
    <label>Color</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/pq_Support_Matrix_Association__c/pq_Support_Matrix_Association__c.object-meta.xml
<CustomObject>
    <label>Support value for this matrix</label>
    <nameField>
        <displayFormat>pqSM-{0000}</displayFormat>
        <label>Support Matrix Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support values for this matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Support_Matrix_Association__c/fields/Influence_And_Support_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Influence_And_Support_Matrix__c</fullName>
    <label>Influence And Support Matrix</label>
    <referenceTo>pq_Influence_And_Support_Matrix__c</referenceTo>
    <relationshipName>Support_Matrix_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/pq_Support_Matrix_Association__c/fields/Support__c.field-meta.xml
<CustomField>
    <fullName>Support__c</fullName>
    <label>Support</label>
    <referenceTo>pq_Support__c</referenceTo>
    <relationshipName>Support_Matrix_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/fields/pq_AccountPlanId__c.field-meta.xml
<CustomField>
    <fullName>pq_AccountPlanId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>pq_AccountPlanId</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Relationship Maps</relationshipLabel>
    <relationshipName>Relationship_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map_Member__c/Relationship_Map_Member__c.object-meta.xml
<CustomObject>
    <label>Relationship Map Member</label>
    <nameField>
        <displayFormat>CHM-{0000}</displayFormat>
        <label>Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Map Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Relationship_Map_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationship Map Members</relationshipLabel>
    <relationshipName>Hierarchy_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/Influence__c.field-meta.xml
<CustomField>
    <fullName>Influence__c</fullName>
    <label>Influence (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Key_Stakeholder_Influence</valueSetName>
    </valueSet>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/Support__c.field-meta.xml
<CustomField>
    <fullName>Support__c</fullName>
    <label>Support (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Key_Stakeholder_Support</valueSetName>
    </valueSet>
</CustomField>

default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Influence_Support_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Influence_Support_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Global Influence and Support Values</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Reports_To_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Reports_To_Global_Scope__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this option to use the Salesforce &apos;Reports To&apos; field.  Uncheck this and this relationship map will maintain this data locally to the chart.</description>
    <inlineHelpText>Check this option to use the Salesforce &apos;Reports To&apos; field.  Uncheck this and this relationship map will maintain this data locally to the chart.</inlineHelpText>
    <label>Use Global Reports To Field</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/InfluenceSupportMatrixServiceImpl.cls
public with sharing class InfluenceSupportMatrixServiceImpl {
    public Map<Id, pq_Influence_And_Support_Matrix__c> getMatrixesForRelationshipMap(Set<Id> mapIds) {
        Map<Id, pq_Account_Plan_Matrix_Association__c> rmAPXMatrixAssoc = getRMMatrixMapUsingAccountPlan(mapIds);

        Map<Id, RM_Chart_Setting__c> settingsMap = RMChartSettingService.getRelationshipMapSettingForObjects(mapIds);

        // GET ANY MATRIXID THAT IS MAP TO THE RELATIONSHIP MAP
        List<pq_Relationship_Map_Matrix_Association__c> matrixAssocs = RMMatrixAssociationSelector.newInstance()
            .selectByRelationshipMaps(mapIds);

        pq_Influence_And_Support_Matrix__c defaultMatrix = InfluenceSupportMatrixSelector.newInstance().selectDefault();

        Map<Id, pq_Relationship_Map_Matrix_Association__c> mapXmatrixAssoc = new Map<Id, pq_Relationship_Map_Matrix_Association__c>();

        for (pq_Relationship_Map_Matrix_Association__c assoc : matrixAssocs) {
            mapXmatrixAssoc.put(assoc.Relationship_Map__c, assoc);
        }

        Map<Id, pq_Influence_And_Support_Matrix__c> result = new Map<Id, pq_Influence_And_Support_Matrix__c>();

        for (Id mapId : mapIds) {
            // Check to see if its global scope, if yes, returnd default
            RM_Chart_Setting__c setting = settingsMap.get(mapId);
            if (setting.Is_Influence_Support_Global_Scope__c) {
                result.put(mapId, defaultMatrix);
                continue;
            }

            // Check Account Plan Assoc First
            pq_Account_Plan_Matrix_Association__c apAssoc = rmAPXMatrixAssoc.get(mapId);
            if (apAssoc != null) {
                pq_Influence_And_Support_Matrix__c apMatrix = new pq_Influence_And_Support_Matrix__c(
                    Id = apAssoc.Influence_And_Support_Matrix__c,
                    Influence_Label__c = apAssoc.Influence_And_Support_Matrix__r.Influence_Label__c,
                    Support_Label__c = apAssoc.Influence_And_Support_Matrix__r.Support_Label__c
                );

                result.put(mapId, apMatrix);
                continue;
            }

            // Check RM Association
            pq_Relationship_Map_Matrix_Association__c assoc = mapXmatrixAssoc.get(mapId);
            if (assoc != null) {
                pq_Influence_And_Support_Matrix__c matrix = new pq_Influence_And_Support_Matrix__c(
                    Id = assoc.Influence_And_Support_Matrix__c,
                    Influence_Label__c = assoc.Influence_And_Support_Matrix__r.Influence_Label__c,
                    Support_Label__c = assoc.Influence_And_Support_Matrix__r.Support_Label__c
                );

                result.put(mapId, matrix);
                continue;
            }

            // use default if nothings is binded
            result.put(mapId, defaultMatrix);
        }

        return result;
    }

    private Map<Id, pq_Account_Plan_Matrix_Association__c> getRMMatrixMapUsingAccountPlan(Set<Id> mapIds) {
        // Find maps tied to account plans
        List<Relationship_Map__c> maps = RelationshipMapSelector.newInstance().selectByIds(mapIds);
        Map<Id, Id> mapAccountPlan = new Map<Id, Id>();
        Map<Id, pq_Account_Plan_Matrix_Association__c> rmAPXMatrixAssoc = new Map<Id, pq_Account_Plan_Matrix_Association__c>();
        Set<Id> acctPlanIds = new Set<Id>();
        for (Relationship_Map__c rmMap : maps) {
            if (rmMap.pq_AccountPlanId__c != null) {
                mapAccountPlan.put(rmMap.pq_AccountPlanId__c, rmMap.Id);
                acctPlanIds.add(rmMap.pq_AccountPlanId__c);
            }
        }

        if (mapAccountPlan.size() > 0) {
            List<pq_Account_Plan_Matrix_Association__c> apMatrixAssocs = AccountPlanMatrixAssociationSelector.newInstance()
                .selectByAccountPlans(acctPlanIds);

            for (pq_Account_Plan_Matrix_Association__c apMatrixAssoc : apMatrixAssocs) {
                Id rmId = mapAccountPlan.get(apMatrixAssoc.Account_Plan__c);
                rmAPXMatrixAssoc.put(rmId, apMatrixAssoc);
            }
        }

        return rmAPXMatrixAssoc;
    }

    public Map<Id, pq_Influence_And_Support_Matrix__c> getMatrixesForAccountPlan(Set<Id> accountPlanIds) {
        Map<Id, RM_Chart_Setting__c> settingsMap = RMChartSettingService.getRelationshipMapSettingForObjects(
            accountPlanIds
        );

        List<pq_Account_Plan_Matrix_Association__c> matrixAssocs = AccountPlanMatrixAssociationSelector.newInstance()
            .selectByAccountPlans(accountPlanIds);

        pq_Influence_And_Support_Matrix__c defaultMatrix = InfluenceSupportMatrixSelector.newInstance().selectDefault();

        Map<Id, pq_Account_Plan_Matrix_Association__c> accountPlanXmatrixAssoc = new Map<Id, pq_Account_Plan_Matrix_Association__c>();

        for (pq_Account_Plan_Matrix_Association__c assoc : matrixAssocs) {
            accountPlanXmatrixAssoc.put(assoc.Account_Plan__c, assoc);
        }

        Map<Id, pq_Influence_And_Support_Matrix__c> result = new Map<Id, pq_Influence_And_Support_Matrix__c>();

        for (Id accountPlanId : accountPlanIds) {
            pq_Account_Plan_Matrix_Association__c assoc = accountPlanXmatrixAssoc.get(accountPlanId);
            RM_Chart_Setting__c setting = settingsMap.get(accountPlanId);
            if (assoc == null || setting.Is_Influence_Support_Global_Scope__c) {
                result.put(accountPlanId, defaultMatrix);
            } else {
                pq_Influence_And_Support_Matrix__c matrix = new pq_Influence_And_Support_Matrix__c(
                    Id = assoc.Influence_And_Support_Matrix__c,
                    Influence_Label__c = assoc.Influence_And_Support_Matrix__r.Influence_Label__c,
                    Support_Label__c = assoc.Influence_And_Support_Matrix__r.Support_Label__c
                );

                result.put(accountPlanId, matrix);
            }
        }

        return result;
    }

    public List<pq_Influence__c> getInfluencesByMatrixes(Set<Id> matrixIdSet) {
        List<pq_Influence_Matrix_Association__c> influenceAssocs = InfluenceMatrixAssociationSelector.newInstance()
            .selectByMatrixId(matrixIdSet);
        List<pq_Influence__c> result = new List<pq_Influence__c>();

        for (pq_Influence_Matrix_Association__c influenceAssoc : influenceAssocs) {
            result.add(
                new pq_Influence__c(
                    Id = influenceAssoc.Influence__c,
                    Name = influenceAssoc.Influence__r.Name,
                    Label__c = influenceAssoc.Influence__r.Label__c
                )
            );
        }

        return result;
    }

    public List<pq_Support__c> getSupportByMatrixes(Set<Id> matrixIdSet) {
        List<pq_Support_Matrix_Association__c> supportAssocs = SupportMatrixAssociationSelector.newInstance()
            .selectByMatrixId(matrixIdSet);
        List<pq_Support__c> result = new List<pq_Support__c>();

        for (pq_Support_Matrix_Association__c supportAssoc : supportAssocs) {
            result.add(
                new pq_Support__c(
                    Id = supportAssoc.Support__c,
                    Name = supportAssoc.Support__r.Name,
                    Label__c = supportAssoc.Support__r.Label__c,
                    Color__c = supportAssoc.Support__r.Color__c
                )
            );
        }

        return result;
    }

    public MatrixMember buildMatrixMemberForKS(
        Key_Stakeholder__c ks,
        Map<String, FieldMetaData> descFieldMap,
        RM_Chart_Setting__c setting,
        Map<Id, Id> reportsToMap,
        Map<Id, Contact> contactMap
    ) {
        List<MatrixMemberAdditionalField> additionalMemberFields = new List<MatrixMemberAdditionalField>();
        for (String af : descFieldMap.keySet()) {
            additionalMemberFields.add(
                new MatrixMemberAdditionalField(
                    af,
                    descFieldMap.get(af)?.label,
                    descFieldMap.get(af)?.displayType,
                    ks.get(af)
                )
            );
        }

        // Add reports to:
        Contact parent;
        Id reportsToId = null;
        if (setting.Is_Reports_To_Global_Scope__c) {
            Contact c = contactMap.get(ks.Contact__c);
            parent = contactMap.get(c.ReportsToId);
            reportsToId = c?.ReportsToId;
        } else {
            reportsToId = reportsToMap.get(ks.Contact__c);
            parent = contactMap.get(reportsToId);
        }

        // Add reports to field to additional info list
        additionalMemberFields.add(
            new MatrixMemberAdditionalField('reportsto', 'Reports To', 'id', reportsToId, parent?.Name)
        );

        MatrixMember mem = new MatrixMember(ks, additionalMemberFields);
        return mem;
    }

    public MatrixMember buildMatrixMemberForMapMember(
        Relationship_Map_Member__c rmm,
        Map<String, FieldMetaData> descFieldMap,
        RM_Chart_Setting__c setting,
        Map<Id, Id> reportsToMap,
        Map<Id, Contact> contactMap
    ) {
        List<MatrixMemberAdditionalField> additionalMemberFields = new List<MatrixMemberAdditionalField>();
        for (String af : descFieldMap.keySet()) {
            additionalMemberFields.add(
                new MatrixMemberAdditionalField(
                    af,
                    descFieldMap.get(af)?.label,
                    descFieldMap.get(af)?.displayType,
                    rmm.get(af)
                )
            );
        }

        // Add reports to:
        Contact parent;
        Id reportsToId = null;
        if (setting.Is_Reports_To_Global_Scope__c) {
            Contact c = contactMap.get(rmm.Contact__c);
            parent = contactMap.get(c.ReportsToId);
            reportsToId = c?.ReportsToId;
        } else {
            reportsToId = reportsToMap.get(rmm.Contact__c);
            parent = contactMap.get(reportsToId);
        }

        // Add reports to field to additional info list
        additionalMemberFields.add(
            new MatrixMemberAdditionalField('reportsto', 'Reports To', 'id', reportsToId, parent?.Name)
        );

        MatrixMember mem = new MatrixMember(rmm, additionalMemberFields);
        return mem;
    }
}