default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Relationship__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/Contact_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Type</label>
    <referenceTo>Contact_Relationship_Type__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/From_Contact__c.field-meta.xml
<CustomField>
    <fullName>From_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Relationships (From Contact)</relationshipLabel>
    <relationshipName>Contact_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/To_Contact__c.field-meta.xml
<CustomField>
    <fullName>To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Relationships (To Contact)</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship_Type__c/Contact_Relationship_Type__c.object-meta.xml
<CustomObject>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Relationship_Type__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>The color of the Relationship Line in the RGB format #AABBCC</description>
    <inlineHelpText>The color of the Relationship Line in the RGB format #AABBCC</inlineHelpText>
    <label>Line Color</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Contact_Relationship_Type__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Default Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Map_Member_Placeholder__c/Map_Member_Placeholder__c.object-meta.xml
<CustomObject>
    <label>Map Member Placeholder</label>
    <nameField>
        <label>Map Member Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Member Placeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Map Member Placeholders</relationshipLabel>
    <relationshipName>Map_Member_Placeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Map Member Placeholders</relationshipLabel>
    <relationshipName>Map_Member_Placeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/Map_Member_Placeholder_Relationship__c.object-meta.xml
<CustomObject>
    <label>Map Member Placeholder Relationship</label>
    <nameField>
        <label>Map Member Placeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Member Placeholder Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Map Member Placeholder Relationships</relationshipLabel>
    <relationshipName>Map_Member_Placeholder_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Contact_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Type</label>
    <referenceTo>Contact_Relationship_Type__c</referenceTo>
    <relationshipLabel>Map Member Placeholder Relationships</relationshipLabel>
    <relationshipName>Map_Member_Placeholder_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Map Member Placeholder Relationships</relationshipLabel>
    <relationshipName>Map_Member_Placeholder_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group__c/Relationship_Group__c.object-meta.xml
<CustomObject>
    <label>Relationship Group</label>
    <nameField>
        <label>Relationship Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Group__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/RelationshipLineWrapperServiceImpl.cls
public with sharing class RelationshipLineWrapperServiceImpl {
    /******************************
     *      PUBLIC METHODS
     ******************************/

    public Map<Id, String> getNodeNames(
        List<Contact_Relationship__c> contactRelList,
        List<Map_Member_Placeholder_Relationship__c> mapMemberList
    ) {
        Set<Id> idSet = new Set<Id>();

        for (Map_Member_Placeholder_Relationship__c mmpr : mapMemberList) {
            idSet.add((Id) mmpr.To__c);
            idSet.add((Id) mmpr.From__c);
        }

        List<User> users = UsersSelector.newInstance().selectById(idSet);
        List<Lead> leads = LeadSelector.newInstance().selectById(idSet);
        List<Map_Member_Placeholder__c> placeholders = MapMemberPlaceHolderSelector.newInstance().selectById(idSet);
        List<Relationship_Group__c> relGroups = RelationshipGroupSelector.newInstance().selectById(idSet);

        Map<Id, String> mapNodeNames = new Map<Id, String>();
        for (User user : users) {
            mapNodeNames.put(user.Id, user.FirstName + ' ' + user.LastName);
        }
        for (Lead lead : leads) {
            mapNodeNames.put(lead.Id, lead.FirstName + ' ' + lead.LastName);
        }
        for (Map_Member_Placeholder__c placeholder : placeholders) {
            mapNodeNames.put(placeholder.Id, placeholder.Label__c);
        }
        for (Relationship_Group__c relGroup : relGroups) {
            mapNodeNames.put(relGroup.Id, relGroup.Label__c);
        }

        Set<Id> contactIdSet = new Set<Id>();

        for (Contact_Relationship__c cr : contactRelList) {
            contactIdSet.add((Id) cr.To_Contact__c);
            contactIdSet.add((Id) cr.From_Contact__c);
        }

        List<Contact> allContacts = ContactSelector.newInstance().selectById(contactIdSet);
        for (Contact c : allContacts) {
            mapNodeNames.put(c.Id, c.Name);
        }

        return mapNodeNames;
    }

    public Map<String, List<CommonRelationshipLineObject>> organizeMemberList(
        Id contactId,
        List<Map_Member_Placeholder_Relationship__c> mapMemberList,
        List<Contact_Relationship__c> contactRelList
    ) {
        Map<String, List<CommonRelationshipLineObject>> mapByContainerId = new Map<String, List<CommonRelationshipLineObject>>();

        mapByContainerId = processMapMembers(contactId, mapMemberList, mapByContainerId);
        mapByContainerId = processContactRelationships(contactId, contactRelList, mapByContainerId);

        return mapByContainerId;
    }

    private Map<String, List<CommonRelationshipLineObject>> processMapMembers(
        Id contactId,
        List<Map_Member_Placeholder_Relationship__c> mapMemberList,
        Map<String, List<CommonRelationshipLineObject>> mapByContainerId
    ) {
        for (Map_Member_Placeholder_Relationship__c mmpr : mapMemberList) {
            String key;
            String containerName;
            Boolean isGlobal = false;
            if (mmpr.Relationship_Map__c != null) {
                containerName = mmpr.Relationship_Map__r.Name;
                key = mmpr.Relationship_Map__c;
            } else if (mmpr.Account_Plan__c != null) {
                containerName = mmpr.Account_Plan__r.Name;
                key = mmpr.Account_Plan__c;
            } else {
                // Global Relationships
                key = '__global';
                containerName = System.Label.Global_Relationships;
                isGlobal = true;
            }

            Id nodeKey;
            if (mmpr.To__c == contactId && mmpr.From__c != contactId) {
                nodeKey = (Id) mmpr.From__c;
            } else if (mmpr.To__c != contactId && mmpr.From__c == contactId) {
                nodeKey = (Id) mmpr.To__c;
            }

            CommonRelationshipLineObject newCommonRL = new CommonRelationshipLineObject(
                mmpr.Id,
                mmpr.Relationship_Map__c,
                mmpr.Account_Plan__c,
                containerName,
                nodeKey,
                HierarchyHelperService.getLabelForRelationship(mmpr),
                mmpr.Contact_Relationship_Type__r.Color__c,
                isGlobal
            );

            if (mapByContainerId.containsKey(key)) {
                List<CommonRelationshipLineObject> mList = mapByContainerId.get(key);
                mList.add(newCommonRL);
                mapByContainerId.put(key, mList);
            } else {
                mapByContainerId.put(key, new List<CommonRelationshipLineObject>{ newCommonRL });
            }
        }

        return mapByContainerId;
    }

    private Map<String, List<CommonRelationshipLineObject>> processContactRelationships(
        Id contactId,
        List<Contact_Relationship__c> contactRelList,
        Map<String, List<CommonRelationshipLineObject>> mapByContainerId
    ) {
        for (Contact_Relationship__c cr : contactRelList) {
            String key;
            String containerName;
            Boolean isGlobal = false;
            if (cr.Relationship_Map__c != null) {
                key = cr.Relationship_Map__c;
                containerName = cr.Relationship_Map__r.Name;
            } else if (cr.Account_Plan__c != null) {
                key = cr.Account_Plan__c;
                containerName = cr.Account_Plan__r.Name;
            } else {
                key = '__global';
                containerName = System.Label.Global_Relationships;
                isGlobal = true;
            }

            Id nodeKey;
            if (cr.To_Contact__c == contactId && cr.From_Contact__c != contactId) {
                nodeKey = cr.From_Contact__c;
            } else if (cr.To_Contact__c != contactId && cr.From_Contact__c == contactId) {
                nodeKey = cr.To_Contact__c;
            }

            CommonRelationshipLineObject newCommonRL = new CommonRelationshipLineObject(
                cr.Id,
                cr.Relationship_Map__c,
                cr.Account_Plan__c,
                containerName,
                nodeKey,
                HierarchyHelperService.getLabelForRelationship(cr),
                cr.Contact_Relationship_Type__r.Color__c,
                isGlobal
            );

            if (mapByContainerId.containsKey(key)) {
                List<CommonRelationshipLineObject> mList = mapByContainerId.get(key);
                mList.add(newCommonRL);
                mapByContainerId.put(key, mList);
            } else {
                mapByContainerId.put(key, new List<CommonRelationshipLineObject>{ newCommonRL });
            }
        }

        return mapByContainerId;
    }
}