default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder__c/Map_Member_Placeholder__c.object-meta.xml
<CustomObject>
    <label>Map Member Placeholder</label>
    <nameField>
        <label>Map Member Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Member Placeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Map Member Placeholders</relationshipLabel>
    <relationshipName>Map_Member_Placeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Map Member Placeholders</relationshipLabel>
    <relationshipName>Map_Member_Placeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group__c/Relationship_Group__c.object-meta.xml
<CustomObject>
    <label>Relationship Group</label>
    <nameField>
        <label>Relationship Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Group__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group__c/fields/Parent_Relationship_Group__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Relationship Group</label>
    <referenceTo>Relationship_Group__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group_Placeholder_Assoc__c/Relationship_Group_Placeholder_Assoc__c.object-meta.xml
<CustomObject>
    <label>Relationship Group Placeholder Assoc</label>
    <nameField>
        <label>Relationship Group Ph Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Group Placeholder Assocs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Relationship_Group_Placeholder_Assoc__c/fields/Map_Member_Placeholder__c.field-meta.xml
<CustomField>
    <fullName>Map_Member_Placeholder__c</fullName>
    <label>Map Member Placeholder</label>
    <referenceTo>Map_Member_Placeholder__c</referenceTo>
    <relationshipLabel>Relationship Group Placeholder Assocs</relationshipLabel>
    <relationshipName>Relationship_Group_Placeholder_Assocs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Group_Placeholder_Assoc__c/fields/Relationship_Group__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Group__c</fullName>
    <label>Relationship Group</label>
    <referenceTo>Relationship_Group__c</referenceTo>
    <relationshipLabel>Relationship Group Placeholder Assocs</relationshipLabel>
    <relationshipName>Relationship_Group_Placeholder_Assocs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/RelationshipGroupPlaceholderSelector.cls
public with sharing class RelationshipGroupPlaceholderSelector extends fflib_SObjectSelector {
    public static RelationshipGroupPlaceholderSelector newInstance() {
        return (RelationshipGroupPlaceholderSelector) Application.Selector.newInstance(
            Relationship_Group_Placeholder_Assoc__c.SObjectType
        );
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Relationship_Group_Placeholder_Assoc__c.Id,
            Relationship_Group_Placeholder_Assoc__c.Map_Member_Placeholder__c,
            Relationship_Group_Placeholder_Assoc__c.Relationship_Group__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Relationship_Group_Placeholder_Assoc__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<Relationship_Group_Placeholder_Assoc__c> selectById(Set<Id> ids) {
        return (List<Relationship_Group_Placeholder_Assoc__c>) selectSObjectsById(ids);
    }

    public List<Relationship_Group_Placeholder_Assoc__c> selectByPlaceholderIds(Set<String> placeholderIds) {
        fflib_QueryFactory query = newQueryFactory().setCondition('Map_Member_Placeholder__c IN :placeholderIds');
        return Database.query(query.toSOQL());
    }

    public List<Relationship_Group_Placeholder_Assoc__c> selectWithGroupsByPlaceholderIds(Set<String> placeholderIds) {
        Set<String> queryFields = new Set<String>();
        queryFields.add('Relationship_Group__c.Id');
        queryFields.add('Relationship_Group__c.Label__c');
        queryFields.add('Relationship_Group__c.Parent_Relationship_Group__c');

        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Map_Member_Placeholder__c IN :placeholderIds')
            .selectFields(queryFields);

        return Database.query(query.toSOQL());
    }

    public List<Relationship_Group_Placeholder_Assoc__c> selectByPlaceholderIdsForLocalGroup(
        Set<String> placeholderIds,
        Id mapOrAccountPlanId
    ) {
        if (mapOrAccountPlanId == null) {
            return new List<Relationship_Group_Placeholder_Assoc__c>();
        }

        String condition =
            'Map_Member_Placeholder__c IN :placeholderIds AND Relationship_Group__r.' +
            mapOrAccountPlanId.getSobjectType() +
            ' = :mapOrAccountPlanId';

        fflib_QueryFactory query = newQueryFactory().setCondition(condition);

        return Database.query(query.toSOQL());
    }

    public List<Relationship_Group_Placeholder_Assoc__c> selectByPlaceholderIdsForGlobalGroup(
        Set<String> placeholderIds
    ) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition(
                'Map_Member_Placeholder__c IN :placeholderIds AND (Relationship_Group__r.Relationship_Map__c = null AND Relationship_Group__r.Account_Plan__c = null)'
            );

        return Database.query(query.toSOQL());
    }
}