default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Master_Account_Plan_Associations__c/Master_Account_Plan_Associations__c.object-meta.xml
<CustomObject>
    <label>Master Account Plan Association</label>
    <nameField>
        <displayFormat>MAPS-{0000}</displayFormat>
        <label>Master Account Plan Associations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Account Plan Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Master_Account_Plan_Associations__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Master Account Plan Associations</relationshipLabel>
    <relationshipName>Master_Account_Plan_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Master_Account_Plan_Associations__c/fields/Master_Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Master_Account_Plan__c</fullName>
    <label>Master Account Plan</label>
    <referenceTo>pq_Master_Account_Plan__c</referenceTo>
    <relationshipLabel>Master Account Plan Associations</relationshipLabel>
    <relationshipName>Master_Account_Plan_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/MasterAccountPlanAssociationSelector.cls
public with sharing class MasterAccountPlanAssociationSelector extends fflib_SObjectSelector {
    public static MasterAccountPlanAssociationSelector newInstance() {
        return (MasterAccountPlanAssociationSelector) Application.Selector.newInstance(Master_Account_Plan_Associations__c.SObjectType);
    }

    /******************************
     *      QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Master_Account_Plan_Associations__c.Id,
            Master_Account_Plan_Associations__c.Account_Plan__c,
            Master_Account_Plan_Associations__c.Master_Account_Plan__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Master_Account_Plan_Associations__c.sObjectType;
    }

    /******************************
     *      SELECT METHODS
     ******************************/

    public List<Master_Account_Plan_Associations__c> selectByMasterAccountPlanId(Set<Id> ids) {
        fflib_QueryFactory query = newQueryFactory().setCondition('Master_Account_Plan__c in :ids');
        return Database.query(query.toSOQL());
    }
}