default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Svg__c/RM_Svg__c.object-meta.xml
<CustomObject>
    <label>Relationship Map Badge</label>
    <nameField>
        <label>Relationship Map Badge Names</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Map Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Svg__c/fields/For_Automation_Use_Only__c.field-meta.xml
<CustomField>
    <fullName>For_Automation_Use_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box if this badge is used for automation.  It will no appear in the menu for users to select.</description>
    <inlineHelpText>Check this box if this badge is used for automation.  It will no appear in the menu for users to select.</inlineHelpText>
    <label>For Automation Use Only</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Svg_Node_Association__c/RM_Svg_Node_Association__c.object-meta.xml
<CustomObject>
    <label>RM Svg Node Association</label>
    <nameField>
        <label>RM Svg Node Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM Svg Node Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/RM_Svg_Node_Association__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>RM Svg Node Associations</relationshipLabel>
    <relationshipName>RM_Svg_Node_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Svg_Node_Association__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Svg Node Associations</relationshipLabel>
    <relationshipName>RM_Svg_Node_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Svg_Node_Association__c/fields/RM_Svg__c.field-meta.xml
<CustomField>
    <fullName>RM_Svg__c</fullName>
    <label>RM Svg</label>
    <referenceTo>RM_Svg__c</referenceTo>
    <relationshipLabel>RM Svg Node Associations</relationshipLabel>
    <relationshipName>RM_Svg_Node_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/classes/RMSvgNodeAssociationSelector.cls
public with sharing class RMSvgNodeAssociationSelector extends fflib_SObjectSelector {
    public static RMSvgNodeAssociationSelector newInstance() {
        return (RMSvgNodeAssociationSelector) Application.Selector.newInstance(RM_Svg_Node_Association__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            RM_Svg_Node_Association__c.Id,
            RM_Svg_Node_Association__c.Key__c,
            RM_Svg_Node_Association__c.RM_Svg__c,
            RM_Svg_Node_Association__c.Account_Plan__c,
            RM_Svg_Node_Association__c.Relationship_Map__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return RM_Svg_Node_Association__c.sObjectType;
    }

    public override String getOrderBy() {
        return 'pqcrush__RM_Svg__r.pqcrush__Order__c ASC';
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<RM_Svg_Node_Association__c> selectById(Set<Id> ids) {
        return (List<RM_Svg_Node_Association__c>) selectSObjectsById(ids);
    }

    public List<RM_Svg_Node_Association__c> selectByKeysGlobalForSvgs(List<RM_Svg__c> svgs, Set<String> keys) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition(
                'pqcrush__Account_Plan__c = null AND pqcrush__Relationship_Map__c = null AND Key__c in :keys AND pqcrush__RM_Svg__c in : svgs'
            );
        return Database.query(query.toSOQL());
    }

    public List<RM_Svg_Node_Association__c> selectByKeysLocalForSvgs(
        Id mapOrAccountPlanId,
        List<RM_Svg__c> svgs,
        Set<String> keys
    ) {
        if (mapOrAccountPlanId == null) {
            return new List<RM_Svg_Node_Association__c>();
        }

        String condition =
            mapOrAccountPlanId.getSobjectType() +
            ' = :mapOrAccountPlanId AND Key__c in :keys AND pqcrush__RM_Svg__c in : svgs';

        fflib_QueryFactory query = newQueryFactory().setCondition(condition);
        return Database.query(query.toSOQL());
    }

    public List<RM_Svg_Node_Association__c> selectByKeysGlobal(Set<String> keys) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition(
                'pqcrush__Account_Plan__c = null AND pqcrush__Relationship_Map__c = null AND Key__c in :keys'
            );
        return Database.query(query.toSOQL());
    }

    public List<RM_Svg_Node_Association__c> selectByKeysLocal(Id mapOrAccountPlanId, Set<String> keys) {
        if (mapOrAccountPlanId == null) {
            return new List<RM_Svg_Node_Association__c>();
        }

        String condition = mapOrAccountPlanId.getSobjectType() + ' = :mapOrAccountPlanId AND Key__c in :keys';

        fflib_QueryFactory query = newQueryFactory().setCondition(condition);
        return Database.query(query.toSOQL());
    }

    public List<RM_Svg_Node_Association__c> selectByKeysGlobalWithAutomation(Set<String> keys, Boolean automation) {
        fflib_QueryFactory query = newQueryFactory();

        fflib_SObjectSelector rmsvgSelector = new RMSvgSelector();
        rmsvgSelector.configureQueryFactoryFields(query, 'RM_Svg__r');

        return Database.query(
            query.setCondition(
                    '(pqcrush__Account_Plan__c = null AND pqcrush__Relationship_Map__c = null AND Key__c in :keys) AND RM_Svg__r.For_Automation_Use_Only__c = :automation'
                )
                .toSOQL()
        );
    }

    public List<RM_Svg_Node_Association__c> selectByKeysLocalWithAutomation(
        Id mapOrAccountPlanId,
        Set<String> keys,
        Boolean automation
    ) {
        if (mapOrAccountPlanId == null) {
            return new List<RM_Svg_Node_Association__c>();
        }

        String condition = '(' + mapOrAccountPlanId.getSobjectType() + ' = :mapOrAccountPlanId AND Key__c in :keys)';

        fflib_QueryFactory query = newQueryFactory();

        fflib_SObjectSelector rmsvgSelector = new RMSvgSelector();
        rmsvgSelector.configureQueryFactoryFields(query, 'RM_Svg__r');

        return Database.query(
            query.setCondition(condition + ' AND RM_Svg__r.For_Automation_Use_Only__c = :automation').toSOQL()
        );
    }
}