default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Objective_Task_Association__c/Objective_Task_Association__c.object-meta.xml
<CustomObject>
    <label>Objective Task Association</label>
    <nameField>
        <label>Objective Task Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objective Task Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Objective_Task_Association__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Objective Task Associations</relationshipLabel>
    <relationshipName>Objective_Task_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Objective_Task_Association__c/fields/TaskId__c.field-meta.xml
<CustomField>
    <fullName>TaskId__c</fullName>
    <label>TaskId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/ObjectiveTaskAssociationSelectorTest.cls
@isTest
private class ObjectiveTaskAssociationSelectorTest {
    @isTest
    static void newInstanceTest() {
        ObjectiveTaskAssociationSelector selector = ObjectiveTaskAssociationSelector.newInstance();
        System.assertNotEquals(null, selector);
    }

    @isTest
    static void selectByObjectivesTest() {
        Account_Plan__c ap = TestDataFactory.createAccountPlan('my plan');
        Objective__c obj1 = TestDataFactory.createObjective(ap, 'test1', 'test2');

        Task task1 = new Task(Subject = 'This is a task');
        insert task1;
        Task task2 = new Task(Subject = 'This is a another task');
        insert task2;

        Objective_Task_Association__c ota1 = new Objective_Task_Association__c(
            Objective__c = obj1.Id,
            TaskId__c = task1.Id
        );
        insert ota1;
        Objective_Task_Association__c ota2 = new Objective_Task_Association__c(
            Objective__c = obj1.Id,
            TaskId__c = task2.Id
        );
        insert ota2;

        List<Objective_Task_Association__c> result = ObjectiveTaskAssociationSelector.newInstance()
            .selectByObjectives(new Set<Id>{ obj1.Id });

        System.assertEquals(2, result.size());
    }

    @isTest
    static void selectByObjectiveAndTaskTest() {
        Account_Plan__c ap = TestDataFactory.createAccountPlan('my plan');
        Objective__c obj1 = TestDataFactory.createObjective(ap, 'test1', 'test2');

        Task task1 = new Task(Subject = 'This is a task');
        insert task1;
        Task task2 = new Task(Subject = 'This is a another task');
        insert task2;

        Objective_Task_Association__c ota1 = new Objective_Task_Association__c(
            Objective__c = obj1.Id,
            TaskId__c = task1.Id
        );
        insert ota1;
        Objective_Task_Association__c ota2 = new Objective_Task_Association__c(
            Objective__c = obj1.Id,
            TaskId__c = task2.Id
        );
        insert ota2;

        List<Objective_Task_Association__c> result = ObjectiveTaskAssociationSelector.newInstance()
            .selectByObjectiveAndTask(obj1.Id, task1.Id);

        System.assertEquals(1, result.size());
        System.assertEquals(ota1.Id, result[0].Id);
    }
}