default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Key_Stakeholder__c/Key_Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Key Stakeholder</label>
    <nameField>
        <displayFormat>KS-{0000}</displayFormat>
        <label>Key Stakeholder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Key_Stakeholder__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Key Stakeholders</relationshipLabel>
    <relationshipName>Key_Stakeholders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Key_Stakeholder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Key Stakeholders</relationshipLabel>
    <relationshipName>Key_Stakeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Key_Stakeholder__c/fields/InfluenceId__c.field-meta.xml
<CustomField>
    <fullName>InfluenceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This influence value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</description>
    <inlineHelpText>This influence value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</inlineHelpText>
    <label>Local Influence</label>
    <referenceTo>pq_Influence__c</referenceTo>
    <relationshipLabel>Key Stakeholders</relationshipLabel>
    <relationshipName>Key_Stakeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Key_Stakeholder__c/fields/SupportId__c.field-meta.xml
<CustomField>
    <fullName>SupportId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This support value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</description>
    <inlineHelpText>This support value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</inlineHelpText>
    <label>Local Support</label>
    <referenceTo>pq_Support__c</referenceTo>
    <relationshipLabel>Key Stakeholders</relationshipLabel>
    <relationshipName>Key_Stakeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/pq_Influence__c/pq_Influence__c.object-meta.xml
<CustomObject>
    <label>Influence</label>
    <nameField>
        <label>Influence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Support__c/pq_Support__c.object-meta.xml
<CustomObject>
    <label>Support</label>
    <nameField>
        <label>Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Support__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color RGB value in the form of #FF0011</description>
    <inlineHelpText>Enter color RGB value in the form of #FF0011</inlineHelpText>
    <label>Color</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Map_Member__c/Relationship_Map_Member__c.object-meta.xml
<CustomObject>
    <label>Relationship Map Member</label>
    <nameField>
        <displayFormat>CHM-{0000}</displayFormat>
        <label>Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Map Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Relationship_Map_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationship Map Members</relationshipLabel>
    <relationshipName>Hierarchy_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/InfluenceId__c.field-meta.xml
<CustomField>
    <fullName>InfluenceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This influence value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</description>
    <inlineHelpText>This influence value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</inlineHelpText>
    <label>Local Influence</label>
    <referenceTo>pq_Influence__c</referenceTo>
    <relationshipLabel>Relationship Map Members</relationshipLabel>
    <relationshipName>Relationship_Map_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/SupportId__c.field-meta.xml
<CustomField>
    <fullName>SupportId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This support value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</description>
    <inlineHelpText>This support value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</inlineHelpText>
    <label>Local Support</label>
    <referenceTo>pq_Support__c</referenceTo>
    <relationshipLabel>Relationship Map Members</relationshipLabel>
    <relationshipName>Relationship_Map_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/MatrixMember.cls
@SuppressWarnings('PMD.ExcessivePublicCount,PMD.TooManyFields')
public with sharing class MatrixMember {
    @AuraEnabled
    public Id id;

    @AuraEnabled
    public Id personId;

    @AuraEnabled
    public String firstName;

    @AuraEnabled
    public String lastName;

    @AuraEnabled
    public String name;

    @AuraEnabled
    public String influenceLabel;

    @AuraEnabled
    public String supportLabel;

    @AuraEnabled
    public String influenceOverrideValue;

    @AuraEnabled
    public String supportOverrideValue;

    @AuraEnabled
    public String influence;

    @AuraEnabled
    public String support;

    @AuraEnabled
    public String supportColor;

    @AuraEnabled
    public String title;

    @AuraEnabled
    public String containerName;

    @AuraEnabled
    public Id containerId;

    @AuraEnabled
    public Boolean containerIsClosed;

    @AuraEnabled
    public Boolean isUsingGlobalInfluence;

    @AuraEnabled
    public datetime createdDate;

    @AuraEnabled
    public List<MatrixMemberAdditionalField> additionalFields;

    public MatrixMember(Key_Stakeholder__c keyStakeholder) {
        this.id = keyStakeholder.Id;
        this.personId = keyStakeholder.Contact__c;
        this.firstName = keyStakeholder.Contact__r.FirstName;
        this.lastName = keyStakeholder.Contact__r.LastName;
        this.name = keyStakeholder.Contact__r.Name;
        this.influence = keyStakeholder.InfluenceId__r.Name;
        this.support = keyStakeholder.SupportId__r.Name;
        this.supportColor = keyStakeholder.SupportId__r.Color__c;

        Map<String, Object> contactMap = keyStakeholder?.Contact__r?.getPopulatedFieldsAsMap();
        this.title = (String) contactMap?.get('Title');

        this.containerName = keyStakeholder.Account_Plan__r.Name;
        this.containerId = keyStakeholder.Account_Plan__c;
        this.containerIsClosed = keyStakeholder.Account_Plan__r.Status__c == 'Closed';
        this.isUsingGlobalInfluence = false;
    }

    public MatrixMember(Key_Stakeholder__c keyStakeholder, String influence, String support) {
        this(keyStakeholder);
        this.influence = influence;
        this.support = support;
    }

    public MatrixMember(Key_Stakeholder__c keyStakeholder, List<MatrixMemberAdditionalField> additionalFields) {
        this(keyStakeholder);
        this.additionalFields = additionalFields;
    }

    public MatrixMember(
        Key_Stakeholder__c keyStakeholder,
        String influence,
        String support,
        List<MatrixMemberAdditionalField> additionalFields
    ) {
        this(keyStakeholder);
        this.influence = influence;
        this.support = support;
        this.additionalFields = additionalFields;
    }

    public MatrixMember(Relationship_Map_Member__c mapMember) {
        this.id = mapMember.Id;
        this.personId = mapMember.Contact__c;
        this.firstName = mapMember.Contact__r.FirstName;
        this.lastName = mapMember.Contact__r.LastName;
        this.name = mapMember.Contact__r.Name;
        this.influence = mapMember.InfluenceId__r.Name;
        this.support = mapMember.SupportId__r.Name;
        this.influenceOverrideValue = mapMember.InfluenceId__r.Label__c;
        this.supportOverrideValue = mapMember.SupportId__r.Label__c;
        this.supportColor = mapMember.SupportId__r.Color__c;

        Map<String, Object> contactMap = mapMember.Contact__r?.getPopulatedFieldsAsMap();
        this.title = (String) contactMap?.get('Title');

        this.containerName = mapMember.Relationship_Map__r.Name;
        this.containerId = mapMember.Relationship_Map__c;
        this.containerIsClosed = false;
        this.isUsingGlobalInfluence = false;
        this.createdDate = mapMember.CreatedDate;
    }

    public MatrixMember(Relationship_Map_Member__c mapMember, String influence, String support) {
        this(mapMember);
        this.influence = influence;
        this.support = support;
    }

    public MatrixMember(Relationship_Map_Member__c mapMember, List<MatrixMemberAdditionalField> additionalFields) {
        this(mapMember);
        this.additionalFields = additionalFields;
    }

    public MatrixMember(
        Relationship_Map_Member__c mapMember,
        String influence,
        String support,
        List<MatrixMemberAdditionalField> additionalFields
    ) {
        this(mapMember);
        this.influence = influence;
        this.support = support;
        this.additionalFields = additionalFields;
    }
}