default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Opportunity_List_User_Filter__c/Opportunity_List_User_Filter__c.object-meta.xml
<CustomObject>
    <description>Stores the filters for a User&apos;s opportunity list within an account plan</description>
    <label>Opportunity List User Filter</label>
    <nameField>
        <displayFormat>OLUF-{0000}</displayFormat>
        <label>Opportunity List User Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity List User Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Opportunity_List_User_Filter__c/fields/AccountPlan__c.field-meta.xml
<CustomField>
    <fullName>AccountPlan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Opportunity List User Filters</relationshipLabel>
    <relationshipName>Opportunity_List_User_Filters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/Opportunity_List_User_Filter__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_List_User_Filters</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/OpportunityListUserFilterSelectorTest.cls
@isTest
private class OpportunityListUserFilterSelectorTest {
    @isTest
    static void selectByAcountPlanAndUser() {
        // Given
        Id userId = UserInfo.getUserId();
        Account acct = new Account(Name = 'Account 1');
        insert acct;
        Account_Plan__c ap = TestDataFactory.createAccountPlan('planA', acct);

        Opportunity_List_User_Filter__c filter = new Opportunity_List_User_Filter__c(
            User__c = userId,
            AccountPlan__c = ap.id
        );
        insert filter;

        // When
        List<Opportunity_List_User_Filter__c> filters = new OpportunityListUserFilterSelector()
            .selectByAccountPlanAndUser(ap.id, userId);

        System.assertEquals(1, filters.size());
    }
}