default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Relationship_Group__c/Relationship_Group__c.object-meta.xml
<CustomObject>
    <label>Relationship Group</label>
    <nameField>
        <label>Relationship Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Group__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group_Contact_Association__c/Relationship_Group_Contact_Association__c.object-meta.xml
<CustomObject>
    <label>Relationship Group Contact Association</label>
    <nameField>
        <label>Relationship Group Contact Association N</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Group Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Relationship_Group_Contact_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationship Group Contact Associations</relationshipLabel>
    <relationshipName>Relationship_Group_Contact_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group_Contact_Association__c/fields/Relationship_Group__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Group__c</fullName>
    <label>Relationship Group</label>
    <referenceTo>Relationship_Group__c</referenceTo>
    <relationshipLabel>Relationship Group Contact Associations</relationshipLabel>
    <relationshipName>Relationship_Group_Contact_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/RelationshipGroupContactWrapper.cls
public with sharing class RelationshipGroupContactWrapper {
    @AuraEnabled
    public Id id { get; set; }
    @AuraEnabled
    public Id contactId { get; set; }
    @AuraEnabled
    public Id groupId { get; set; }
    @AuraEnabled
    public String groupLabel { get; set; }
    @AuraEnabled
    public Id relationshipMapId { get; set; }
    @AuraEnabled
    public Id accountPlanId { get; set; }
    @AuraEnabled
    public String containerName { get; set; }
    @AuraEnabled
    public Boolean isGlobalGroup { get; set; }

    public RelationshipGroupContactWrapper(
        Id id,
        Id contactId,
        Id groupId,
        String groupLabel,
        Id relationshipMapId,
        Id accountPlanId,
        String containerName,
        Boolean isGlobalGroup
    ) {
        this.id = id;
        this.contactId = contactId;
        this.groupId = groupId;
        this.groupLabel = groupLabel;
        this.relationshipMapId = relationshipMapId;
        this.accountPlanId = accountPlanId;
        this.containerName = containerName;
        this.isGlobalGroup = isGlobalGroup;
    }

    public static List<RelationshipGroupContactWrapper> convert(
        List<Relationship_Group_Contact_Association__c> relList
    ) {
        if (relList == null || relList.size() == 0) {
            return new List<RelationshipGroupContactWrapper>();
        }

        List<RelationshipGroupContactWrapper> result = new List<RelationshipGroupContactWrapper>();
        for (Relationship_Group_Contact_Association__c rgca : relList) {
            String containerName = '';
            if (rgca.Relationship_Group__r?.Relationship_Map__c != null) {
                containerName = rgca.Relationship_Group__r?.Relationship_Map__r.Name;
            } else if (rgca.Relationship_Group__r?.Account_Plan__c != null) {
                containerName = rgca.Relationship_Group__r?.Account_Plan__r.Name;
            }
            Boolean isGlobal =
                rgca.Relationship_Group__r?.Relationship_Map__c == null &&
                rgca.Relationship_Group__r?.Account_Plan__c == null;
            result.add(
                new RelationshipGroupContactWrapper(
                    rgca.Id,
                    rgca.Contact__c,
                    rgca.Relationship_Group__c,
                    rgca.Relationship_Group__r?.Label__c,
                    rgca.Relationship_Group__r?.Relationship_Map__c,
                    rgca.Relationship_Group__r?.Account_Plan__c,
                    containerName,
                    isGlobal
                )
            );
        }

        return result;
    }
}