default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Key_Date__c/Key_Date__c.object-meta.xml
<CustomObject>
    <label>Key Date</label>
    <nameField>
        <label>Key Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Key_Date__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Key Dates</relationshipLabel>
    <relationshipName>Key_Dates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Key_Date__c/fields/Reminder__c.field-meta.xml
<CustomField>
    <fullName>Reminder__c</fullName>
    <label>Reminder</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On the day of</fullName>
            </value>
            <value>
                <fullName>1 day before</fullName>
            </value>
            <value>
                <fullName>2 days before</fullName>
            </value>
            <value>
                <fullName>1 week before</fullName>
            </value>
            <value>
                <fullName>2 weeks before</fullName>
            </value>
            <value>
                <fullName>30 days before</fullName>
            </value>
            <value>
                <fullName>60 days before</fullName>
            </value>
            <value>
                <fullName>90 days before</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/KeyDateSelector.cls
public with sharing class KeyDateSelector extends AccountPlanChildSelector {
    public KeyDateSelector() {
        super(
            false, // Do not include FieldSet fields
            true, // Enforce Object level security
            true
        ); // Enforce Field level security
    }

    /******************************
     *      STATIC METHODS
     ******************************/

    public static KeyDateSelector newInstance() {
        return (KeyDateSelector) Application.Selector.newInstance(Key_Date__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Key_Date__c.Id,
            Key_Date__c.Name,
            Key_Date__c.Account_Plan__c,
            Key_Date__c.Date__c,
            Key_Date__c.Reminder__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Key_Date__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<Key_Date__c> selectById(Set<Id> ids) {
        return (List<Key_Date__c>) selectSObjectsById(ids);
    }

    public List<Key_Date__c> selectWithRemindersBetween(Date fromDate, Date toDate) {
        return Database.query(
            newQueryFactory()
                .setCondition('Reminder__c != NULL AND Date__c >= :fromDate AND Date__c < :toDate')
                .toSOQL()
        );
    }

    public List<Key_Date__c> selectWithRemindersBetweenAsSystem(Date fromDate, Date toDate) {
        return new SystemSelector().selectWithRemindersBetween(this, fromDate, toDate);
    }

    /**
     * Returns a list of Key_Date__c records that correspond to the given
     * set of Account Plan Ids
     * @param accountPlanIds The account plans
     * @return List<Key_Date__c> The key dates
     */
    public List<Key_Date__c> selectByAccountPlanId(Set<Id> accountPlanIds) {
        return Database.query(newQueryFactory().setCondition('Account_Plan__c IN :accountPlanIds').toSOQL());
    }

    /******************************
     *       INNER CLASSES
     ******************************/

    private with sharing class SystemSelector {
        public List<Key_Date__c> selectWithRemindersBetween(KeyDateSelector selector, Date fromDate, Date toDate) {
            return Database.query(
                selector.newQueryFactory(false, false, true)
                    .setCondition('Reminder__c != NULL AND Date__c >= :fromDate AND Date__c < :toDate')
                    .toSOQL()
            );
        }
    }
}