default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/pq_CRUSH_Account_Plan_User_Setting__c/pq_CRUSH_Account_Plan_User_Setting__c.object-meta.xml
<CustomObject>
    <label>CRUSH Account Plan User Setting</label>
    <nameField>
        <displayFormat>APUS-{0000}</displayFormat>
        <label>CRUSH Account Plan User Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRUSH Account Plan User Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_CRUSH_Account_Plan_User_Setting__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>CRUSH Account Plan User Settings</relationshipLabel>
    <relationshipName>CRUSH_Account_Plan_User_Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/pq_CRUSH_Account_Plan_User_Setting__c/fields/Account_Plan_RM_Sort__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_RM_Sort__c</fullName>
    <label>Account Plan RelationShip Maps Sort</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CreatedDate DESC</fullName>
                <label>Created: Newest to Oldest</label>
            </value>
            <value>
                <fullName>CreatedDate ASC</fullName>
                <default>true</default>
                <label>Created: Oldest to Newest</label>
            </value>
            <value>
                <fullName>Name ASC</fullName>
                <label>Name: Alphabetical</label>
            </value>
            <value>
                <fullName>Name DESC</fullName>
                <label>Name: Reverse Alphabetical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/pq_CRUSH_Account_Plan_User_Setting__c/fields/Objective_Overview_Chart_Type__c.field-meta.xml
<CustomField>
    <fullName>Objective_Overview_Chart_Type__c</fullName>
    <label>Objective Overview Chart Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bar</fullName>
                <default>true</default>
                <label>Bar</label>
            </value>
            <value>
                <fullName>Pie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/pq_CRUSH_Account_Plan_User_Setting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CRUSH_Account_Plan_User_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/AccountPlanUserSettingSelector.cls
public with sharing class AccountPlanUserSettingSelector extends fflib_SObjectSelector {
    public static AccountPlanUserSettingSelector newInstance() {
        return (AccountPlanUserSettingSelector) Application.Selector.newInstance(
            pq_CRUSH_Account_Plan_User_Setting__c.SObjectType
        );
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            pq_CRUSH_Account_Plan_User_Setting__c.Id,
            pq_CRUSH_Account_Plan_User_Setting__c.Objective_Overview_Chart_Type__c,
            pq_CRUSH_Account_Plan_User_Setting__c.Account_Plan__c,
            pq_CRUSH_Account_Plan_User_Setting__c.User__c,
            pq_CRUSH_Account_Plan_User_Setting__c.Account_Plan_RM_Sort__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return pq_CRUSH_Account_Plan_User_Setting__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<pq_CRUSH_Account_Plan_User_Setting__c> selectById(Set<Id> ids) {
        return (List<pq_CRUSH_Account_Plan_User_Setting__c>) selectSObjectsById(ids);
    }

    public List<pq_CRUSH_Account_Plan_User_Setting__c> selectByAccountPlans(Set<Id> accountPlanIds, Id userId) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Account_Plan__c IN :accountPlanIds AND User__c = :userId');
        return Database.query(query.toSOQL());
    }

    public List<pq_CRUSH_Account_Plan_User_Setting__c> selectByAccPlanID(Set<Id> accountPlanId) {
        fflib_QueryFactory query = newQueryFactory().setCondition('Account_Plan__c IN :accountPlanId');
        return Database.query(query.toSOQL());
    }
}