default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>White Spaces</relationshipLabel>
    <relationshipName>White_Spaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/WS_User_Setting__c/WS_User_Setting__c.object-meta.xml
<CustomObject>
    <label>WS User Setting</label>
    <nameField>
        <displayFormat>WSUserSetting-{0000}</displayFormat>
        <label>WS User Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WS User Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_User_Setting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>WS_User_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/WS_User_Setting__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>WS User Settings</relationshipLabel>
    <relationshipName>WS_User_Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/classes/WSUserSettingSelectorTest.cls
@isTest
private class WSUserSettingSelectorTest {
    @isTest
    static void selectByIdTest() {
        // Given
        Id userId = UserInfo.getUserId();
        Account acct = new Account(Name = 'Account 1');
        insert acct;
        Account_Plan__c ap = TestDataFactory.createAccountPlan('planA', acct);
        White_Space__c ws = TestDataFactory.createWhiteSpace(ap, 'WS Name');

        WS_User_Setting__c setting = new WS_User_Setting__c(User__c = userId, White_Space__c = ws.Id);
        insert setting;

        // When
        List<WS_User_Setting__c> wsUserSettings = new WSUserSettingSelector().selectById(new Set<Id>{ setting.Id });

        System.assertEquals(setting.Id, wsUserSettings[0].Id);
    }

    @isTest
    static void selectByWhitespaceIdTest() {
        // Given
        Id userId = UserInfo.getUserId();
        Account acct = new Account(Name = 'Account 1');
        insert acct;
        Account_Plan__c ap = TestDataFactory.createAccountPlan('planA', acct);
        White_Space__c ws = TestDataFactory.createWhiteSpace(ap, 'WS Name');

        WS_User_Setting__c setting = new WS_User_Setting__c(User__c = userId, White_Space__c = ws.Id);
        insert setting;

        // When
        List<WS_User_Setting__c> wsUserSettings = new WSUserSettingSelector().selectByWhitespaceId(ws.Id);

        System.assertEquals(setting.Id, wsUserSettings[0].Id);
    }
}