default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Account_Plan_Opportunity__c/Account_Plan_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Account Plan Opportunity</label>
    <nameField>
        <displayFormat>APO-{0000}</displayFormat>
        <label>Account Plan Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Account_Plan_Opportunity__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Account Plan Opportunities</relationshipLabel>
    <relationshipName>Account_Plan_Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/CRUSH_Settings_Obj__c.object-meta.xml
<CustomObject>
    <description>The object that holds the organization wide and user specific settings for CRUSH.</description>
    <label>CRUSH Settings</label>
    <nameField>
        <displayFormat>CRUSH-{0000}</displayFormat>
        <label>CRUSH Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRUSH Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/CRUSH_Settings_Obj__c/fields/Enable_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Enable_Notifications__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Notifications</label>
    <type>Checkbox</type>
</CustomField>

default/classes/AccountPlanOpportunities.cls
@SuppressWarnings('PMD.ApexDangerousMethods')
public with sharing class AccountPlanOpportunities extends fflib_SObjectDomain {
    public AccountPlanOpportunities(List<Account_Plan_Opportunity__c> sObjectList) {
        super(sObjectList);
        this.Configuration.disableTriggerCRUDSecurity();
    }

    /******************************
     *       STATIC METHODS
     ******************************/

    public static AccountPlanOpportunities newInstance(List<Account_Plan_Opportunity__c> sObjectList) {
        return (AccountPlanOpportunities) Application.Domain.newInstance(sObjectList);
    }

    public static String getUniqueKey(Account_Plan_Opportunity__c accountPlanOpportunity) {
        return String.valueOf(accountPlanOpportunity.Account_Plan__c) +
            String.valueOf(accountPlanOpportunity.Opportunity__c);
    }

    /******************************
     *   TRIGGER HANDLER METHODS
     ******************************/

    public override void onValidate() {
        checkDuplicates();
    }

    public override void onValidate(Map<Id, SObject> existingRecords) {
        checkDuplicates();
    }

    public override void onAfterInsert() {
        if (!System.Test.isRunningTest() && !Application.bypassTrigger) {
            sendEmails();
        }
    }

    /******************************
     *      PRIVATE METHODS
     ******************************/

    private void checkDuplicates() {
        for (
            Account_Plan_Opportunity__c duplicateAccountPlanOpportunity : AccountPlanOpportunitySelector.newInstance()
                .selectDuplicatesAsSystem(Records)
        ) {
            duplicateAccountPlanOpportunity.addError(System.Label.error_duplicate_account_plan_opportunity);
        }
    }

    private void sendEmails() {
        CRUSH_Settings_Obj__c settings = SettingService.getOrgSettingsAndCreateIfNeeded();

        if (!settings.Enable_Notifications__c || !settings.Opportunities_Added__c) {
            return;
        }

        List<SendEmailNotifications.SendEmailRequest> emailRequests = new List<SendEmailNotifications.SendEmailRequest>();

        for (SObject sobj : Records) {
            Account_Plan_Opportunity__c opp = (Account_Plan_Opportunity__c) sobj;

            SendEmailNotifications.SendEmailRequest request = new SendEmailNotifications.SendEmailRequest();
            request.accountPlanId = opp.Account_Plan__c;
            request.eventType = 'Opportunities_Are_Added';

            emailRequests.add(request);
        }

        try {
            SendEmailNotifications.sendEmails(emailRequests);
        } catch (Exception e) {
            System.debug('Error thrown sending update Emails: ' + e.getMessage()); //NOPMD
        }
    }

    /******************************
     *       INNER CLASSES
     ******************************/

    /**
     * This is a workaround for the lack of reflection in Apex.
     */
    public with sharing class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new AccountPlanOpportunities(sObjectList);
        }
    }
}