default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/White_Space__c/White_Space__c.object-meta.xml
<CustomObject>
    <label>White Space</label>
    <nameField>
        <label>White Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>White Spaces</relationshipLabel>
    <relationshipName>White_Spaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/WS_Summary_Formula__c/WS_Summary_Formula__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Summary Formula</label>
    <nameField>
        <displayFormat>WSSummaryFormula-{0000}</displayFormat>
        <label>WS Summary Formula Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Summary Formulas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_Summary_Formula__c/fields/Apply_To_All_Cross_Sell_Maps__c.field-meta.xml
<CustomField>
    <fullName>Apply_To_All_Cross_Sell_Maps__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to apply this formula to all Cross-Sell maps</description>
    <inlineHelpText>Check this to apply this formula to all Cross-Sell maps</inlineHelpText>
    <label>Apply To All Cross-Sell Maps</label>
    <type>Checkbox</type>
</CustomField>

default/objects/WS_Summary_Formula__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color RBG in the form of #rrggbb</description>
    <inlineHelpText>Color RBG in the form of #rrggbb</inlineHelpText>
    <label>Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

default/objects/WS_Summary_Formula__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <inlineHelpText>Formulas are comprised of different amount types and math symbols.  The amount type variable is defined by using the name of the amount type surrounded by curly braces.  Example formula: {Amount Type 1} + {Amount Type 2}</inlineHelpText>
    <label>Formula</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/WS_Summary_Formula__c/fields/White_Space__c.field-meta.xml
<CustomField>
    <fullName>White_Space__c</fullName>
    <label>White Space</label>
    <referenceTo>White_Space__c</referenceTo>
    <relationshipLabel>Cross-Sell Summary Formulas</relationshipLabel>
    <relationshipName>Cross_Sell_Summary_Formulas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/WSSummaryFormulaSelectorTest.cls
@isTest
private class WSSummaryFormulaSelectorTest {
    @isTest
    static void selectByIdTest() {
        // Given
        Account testAccount = new Account(Name = 'Account 1');
        insert testAccount;
        Account_Plan__c ap = TestDataFactory.createAccountPlan('PlanA', testAccount);
        White_Space__c ws = TestDataFactory.createWhiteSpace(ap, 'WS Name');

        WS_Summary_Formula__c formula = new WS_Summary_Formula__c(
            Label__c = 'A + B',
            Formula__c = '{A} + {B}',
            Color__c = '#0080ff',
            White_Space__c = ws.Id
        );
        insert formula;

        List<WS_Summary_Formula__c> formulas = new WSSummaryFormulaSelector().selectById(new Set<Id>{ formula.Id });

        // Then
        System.assertEquals(1, formulas.size());
        System.assertEquals(formula.Id, formulas[0].Id);
    }

    @isTest
    static void selectByWhiteSpaceIdTest() {
        // Given
        Account testAccount = new Account(Name = 'Account 1');
        insert testAccount;
        Account_Plan__c ap = TestDataFactory.createAccountPlan('PlanA', testAccount);
        White_Space__c ws = TestDataFactory.createWhiteSpace(ap, 'WS Name');
        White_Space__c ws2 = TestDataFactory.createWhiteSpace(ap, 'WS 2 Name');

        // Formula with WS ID
        WS_Summary_Formula__c formula = new WS_Summary_Formula__c(
            Label__c = 'A + B',
            Formula__c = '{A} + {B}',
            Color__c = '#0080ff',
            White_Space__c = ws.Id
        );
        insert formula;

        // Formula with WS ID
        WS_Summary_Formula__c formula2 = new WS_Summary_Formula__c(
            Label__c = 'C + D',
            Formula__c = '{C} + {D}',
            Color__c = '#0080ff',
            White_Space__c = ws.Id
        );
        insert formula2;

        // Formula with no WS ID but Apply to All True
        WS_Summary_Formula__c formula3 = new WS_Summary_Formula__c(
            Label__c = 'C + D',
            Formula__c = '{C} + {D}',
            Color__c = '#0080ff',
            White_Space__c = ws2.Id,
            Apply_To_All_Cross_Sell_Maps__c = true
        );
        insert formula3;

        // Formula that should not be pulled
        WS_Summary_Formula__c formula4 = new WS_Summary_Formula__c(
            Label__c = 'C + D',
            Formula__c = '{C} + {D}',
            Color__c = '#0080ff',
            White_Space__c = ws2.Id
        );
        insert formula4;

        List<WS_Summary_Formula__c> formulas = new WSSummaryFormulaSelector().selectByWhiteSpaceId(ws.Id);
        Set<Id> ids = new Set<Id>();
        for (WS_Summary_Formula__c form : formulas) {
            ids.add(form.Id);
        }

        // Then
        System.assertEquals(3, formulas.size());
        System.assert(!ids.contains(formula4.Id));
    }
}