default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/SWOT_Analysis__c/SWOT_Analysis__c.object-meta.xml
<CustomObject>
    <label>SWOT Analysis</label>
    <nameField>
        <label>SWOT Analysis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SWOT Analysis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/SWOT_Analysis__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>SWOT Analysis</relationshipLabel>
    <relationshipName>SWOT_Analysis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/SWOT_Analysis__c/fields/Description_Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Description_Rich_Text__c</fullName>
    <label>Description (Rich Text)</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

default/classes/SWOTAnalysisSelector.cls
public with sharing class SWOTAnalysisSelector extends AccountPlanChildSelector {
    /******************************
     *      STATIC METHODS
     ******************************/

    public static SWOTAnalysisSelector newInstance() {
        return (SWOTAnalysisSelector) Application.Selector.newInstance(SWOT_Analysis__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            SWOT_Analysis__c.Id,
            SWOT_Analysis__c.Name,
            SWOT_Analysis__c.Description_Rich_Text__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return SWOT_Analysis__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<SWOT_Analysis__c> selectById(Set<Id> ids) {
        return Database.query(
            newQueryFactory().selectField('RecordType.DeveloperName').setCondition('id in :ids').toSOQL()
        );
    }

    public List<SWOT_Analysis__c> selectByAccountPlanId(Id accountPlanId) {
        return Database.query(
            newQueryFactory()
                .selectField('RecordType.DeveloperName')
                .setCondition('Account_Plan__c = :accountPlanId')
                .toSOQL()
        );
    }
}