default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/pq_Account_Plan_Matrix_Association__c/pq_Account_Plan_Matrix_Association__c.object-meta.xml
<CustomObject>
    <label>Account Plan that uses this matrix</label>
    <nameField>
        <displayFormat>APMA-{0000}</displayFormat>
        <label>Account Plan Matrix Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans that use this matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Account_Plan_Matrix_Association__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Account Plans that use this matrix</relationshipLabel>
    <relationshipName>Account_Plans_that_use_this_matrix</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/pq_Account_Plan_Matrix_Association__c/fields/Influence_And_Support_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Influence_And_Support_Matrix__c</fullName>
    <label>Influence And Support Matrix</label>
    <referenceTo>pq_Influence_And_Support_Matrix__c</referenceTo>
    <relationshipLabel>Account Plans that use this matrix</relationshipLabel>
    <relationshipName>Account_Plans_that_use_this_matrix</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/pq_Influence_And_Support_Matrix__c/pq_Influence_And_Support_Matrix__c.object-meta.xml
<CustomObject>
    <label>Influence And Support Matrix</label>
    <nameField>
        <label>Influence And Support Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence And Support Matrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/AccountPlanMatrixAssociationSelectorTest.cls
@isTest
private class AccountPlanMatrixAssociationSelectorTest {
    @isTest
    static void newInstanceTest() {
        AccountPlanMatrixAssociationSelector selector = AccountPlanMatrixAssociationSelector.newInstance();
        System.assertNotEquals(null, selector);
    }

    @isTest
    static void selectByAccountPlansTest() {
        Account_Plan__c ap = TestDataFactory.createAccountPlan('planA');
        pq_Influence_And_Support_Matrix__c m1 = new pq_Influence_And_Support_Matrix__c(Name = 'one');
        insert m1;
        pq_Account_Plan_Matrix_Association__c input1 = new pq_Account_Plan_Matrix_Association__c(
            Account_Plan__c = ap.Id,
            Influence_And_Support_Matrix__c = m1.Id
        );
        insert input1;

        Set<Id> accountPlanIds = new Set<Id>{ ap.Id };

        Test.startTest();
        List<pq_Account_Plan_Matrix_Association__c> result = new AccountPlanMatrixAssociationSelector()
            .selectByAccountPlans(accountPlanIds);
        Test.stopTest();

        System.assertEquals(1, result.size());
        System.assertEquals(m1.Id, result[0].Influence_And_Support_Matrix__c);
        System.assertEquals(ap.Id, result[0].Account_Plan__c);
    }
}