default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Relationship_Group__c/Relationship_Group__c.object-meta.xml
<CustomObject>
    <label>Relationship Group</label>
    <nameField>
        <label>Relationship Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Group__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group__c/fields/Parent_Relationship_Group__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Relationship Group</label>
    <referenceTo>Relationship_Group__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group_Lead_Association__c/Relationship_Group_Lead_Association__c.object-meta.xml
<CustomObject>
    <label>Relationship Group Lead Association</label>
    <nameField>
        <label>Relationship Group Lead Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Group Lead Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Relationship_Group_Lead_Association__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Relationship Group Lead Associations</relationshipLabel>
    <relationshipName>Relationship_Group_Lead_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group_Lead_Association__c/fields/Relationship_Group__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Group__c</fullName>
    <label>Relationship Group</label>
    <referenceTo>Relationship_Group__c</referenceTo>
    <relationshipLabel>Relationship Group Lead Associations</relationshipLabel>
    <relationshipName>Relationship_Group_Lead_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/RelationshipGroupLeadSelector.cls
// Relationship Group Contact Association Selector

public with sharing class RelationshipGroupLeadSelector extends fflib_SObjectSelector {
    public RelationshipGroupLeadSelector() {
        super(false, true, false);
    }

    public static RelationshipGroupLeadSelector newInstance() {
        return (RelationshipGroupLeadSelector) Application.Selector.newInstance(
            Relationship_Group_Lead_Association__c.SObjectType
        );
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Relationship_Group_Lead_Association__c.Id,
            Relationship_Group_Lead_Association__c.Lead__c,
            Relationship_Group_Lead_Association__c.Relationship_Group__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Relationship_Group_Lead_Association__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<Relationship_Group_Lead_Association__c> selectById(Set<Id> ids) {
        return (List<Relationship_Group_Lead_Association__c>) selectSObjectsById(ids);
    }

    public List<Relationship_Group_Lead_Association__c> selectByLeadIds(Set<String> leadIds) {
        fflib_QueryFactory query = newQueryFactory().setCondition('Lead__c IN :leadIds');
        return Database.query(query.toSOQL());
    }

    public List<Relationship_Group_Lead_Association__c> selectWithGroupsByLeadIds(Set<Id> leadIds) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Lead__c IN :leadIds')
            .selectFields(composeQueryFields());
        return Database.query(query.toSOQL());
    }

    public List<Relationship_Group_Lead_Association__c> selectByLeadIdsForLocalGroup(
        Set<String> leadIds,
        Id mapOrAccountPlanId
    ) {
        if (mapOrAccountPlanId == null) {
            return new List<Relationship_Group_Lead_Association__c>();
        }

        String condition =
            'Lead__c IN :leadIds AND Relationship_Group__r.' +
            mapOrAccountPlanId.getSobjectType() +
            ' = :mapOrAccountPlanId';

        fflib_QueryFactory query = newQueryFactory().setCondition(condition).selectFields(composeQueryFields());

        return Database.query(query.toSOQL());
    }

    public List<Relationship_Group_Lead_Association__c> selectByLeadIdsForGlobalGroup(Set<String> leadIds) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition(
                'Lead__c IN :leadIds AND (Relationship_Group__r.Relationship_Map__c = null AND Relationship_Group__r.Account_Plan__c = null)'
            )
            .selectFields(composeQueryFields());

        return Database.query(query.toSOQL());
    }

    private Set<String> composeQueryFields() {
        Set<String> queryFields = new Set<String>();
        queryFields.add('Relationship_Group__c.Id');
        queryFields.add('Relationship_Group__c.Label__c');
        queryFields.add('Relationship_Group__c.Parent_Relationship_Group__c');
        queryFields.add('Relationship_Group__c.Account_Plan__c');
        queryFields.add('Relationship_Group__c.Relationship_Map__c');

        return queryFields;
    }
}