default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/ObjectiveWrapperListTest.cls
@isTest
private class ObjectiveWrapperListTest {
    @isTest
    static void newInstanceTest() {
        Account_Plan__c ap = TestDataFactory.createAccountPlan('my plan');
        Objective__c obj1 = TestDataFactory.createObjective(ap, 'test1', 'test2');

        ObjectiveWrapper wrapper = new ObjectiveWrapper(obj1, true, true);

        ObjectiveWrapperList objWrapperList = new ObjectiveWrapperList(new List<ObjectiveWrapper>{ wrapper });
        System.assertNotEquals(null, objWrapperList);
        System.assertEquals(1, objWrapperList.objectives.size());
    }
}