default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/Account_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/classes/AccountPlanCloneBatchService.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class AccountPlanCloneBatchService {
    @InvocableMethod(
        label='Batch Clone Account Plans'
        description='Batch Clones a list of account plans based on the data passed in'
    )
    global static void cloneAccountPlans(List<AccountPlanCloneBatchInput> inputs) {
        Set<Id> allPlanIds = new Set<Id>();
        for (AccountPlanCloneBatchInput input : inputs) {
            allPlanIds.addAll(input.planIds);
        }

        Map<Id, Account_Plan__c> accountPlansById = new Map<Id, Account_Plan__c>();
        List<Account_Plan__c> accountPlans = AccountPlanSelector.newInstance().selectByIdAsSystem(allPlanIds);
        for (Account_Plan__c ap : accountPlans) {
            accountPlansById.put(ap.Id, ap);
        }

        List<AccountPlanCloneWrapper> wrappers = new List<AccountPlanCloneWrapper>();
        for (AccountPlanCloneBatchInput input : inputs) {
            for (String planId : input.planIds) {
                Id accountId = input.accountId;
                if (String.isBlank(input.accountId)) {
                    Account_Plan__c ap = accountPlansById.get(planId);
                    accountId = ap.Account__c;
                }
                wrappers.add(
                    new AccountPlanCloneWrapper(planId, input.name, input.ownerId, accountId, input.relationships)
                );
            }
        }
        AccountPlanCloneService.cloneAccountPlans(wrappers);
    }
}