default/objects/pq_Condition__c/pq_Condition__c.object-meta.xml
<CustomObject>
    <label>PQ Condition</label>
    <nameField>
        <displayFormat>Cond-{000000}</displayFormat>
        <label>Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PQ Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Condition__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

default/objects/pq_Condition__c/fields/Parent_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Id__c</fullName>
    <label>Parent Object Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/pq_Condition__c/fields/Parent_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Name__c</fullName>
    <label>Parent Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

default/classes/PqConditionSelector.cls
public with sharing class PqConditionSelector extends fflib_SObjectSelector {
    public static PqConditionSelector newInstance() {
        return (PqConditionSelector) Application.Selector.newInstance(pq_Condition__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            pq_Condition__c.Id,
            pq_Condition__c.Field__c,
            pq_Condition__c.Operator__c,
            pq_Condition__c.Value__c,
            pq_Condition__c.Parent_Object_Name__c,
            pq_Condition__c.Parent_Object_Id__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return pq_Condition__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<pq_Condition__c> selectById(Set<ID> idSet) {
        return (List<pq_Condition__c>) selectSObjectsById(idSet);
    }

    public List<pq_Condition__c> selectByParentObjectId(Set<ID> idSet) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        return Database.query(queryFactory.setCondition('Parent_Object_Id__c IN :idSet').toSOQL());
    }
}