default/objects/CRUSH_Settings__c/CRUSH_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CRUSH Settings</label>
</CustomObject>

default/objects/CRUSH_Settings__c/fields/Account_Plan_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Transfer__c</fullName>
    <defaultValue>&quot;NONE&quot;</defaultValue>
    <label>Account Plan Transfer</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings__c/fields/Account_Plan_Transfer_User__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Transfer_User__c</fullName>
    <label>Account Plan Transfer User</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings__c/fields/Key_Date_Updated__c.field-meta.xml
<CustomField>
    <fullName>Key_Date_Updated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Key Date Updated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings__c/fields/Key_Stakeholder_Updated__c.field-meta.xml
<CustomField>
    <fullName>Key_Stakeholder_Updated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Key Stakeholder Updated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings__c/fields/Objectives_Updated__c.field-meta.xml
<CustomField>
    <fullName>Objectives_Updated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Objectives Updated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings__c/fields/Opportunities_Added__c.field-meta.xml
<CustomField>
    <fullName>Opportunities_Added__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Opportunities Added</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings__c/fields/Org_Chart_Default_Fields__c.field-meta.xml
<CustomField>
    <fullName>Org_Chart_Default_Fields__c</fullName>
    <defaultValue>&quot;Contact.Name.Required,Contact.Title,Contact.Email&quot;</defaultValue>
    <description>Determines the default fields for the Org Chart display</description>
    <label>Org Chart Default Fields</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings__c/fields/Plan_Overview_Updated__c.field-meta.xml
<CustomField>
    <fullName>Plan_Overview_Updated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Plan Overview Updated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings__c/fields/Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status Updated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings__c/fields/SWOT_Analysis_Updated__c.field-meta.xml
<CustomField>
    <fullName>SWOT_Analysis_Updated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>SWOT Analysis Updated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings__c/fields/Team_Member_Added_Removed__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Added_Removed__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Team Member Added/Removed</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/CRUSH_Settings_Obj__c.object-meta.xml
<CustomObject>
    <description>The object that holds the organization wide and user specific settings for CRUSH.</description>
    <label>CRUSH Settings</label>
    <nameField>
        <displayFormat>CRUSH-{0000}</displayFormat>
        <label>CRUSH Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRUSH Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/CRUSH_Settings_Obj__c/fields/Account_Plan_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Transfer__c</fullName>
    <label>Account Plan Transfer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TEAM_MEMBER</fullName>
                <label>Assign to oldest team member</label>
            </value>
            <value>
                <fullName>USER</fullName>
                <label>Assign to specific user</label>
            </value>
            <value>
                <fullName>NONE</fullName>
                <default>true</default>
                <label>Do nothing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Account_Plan_Transfer_User__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Transfer_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan Transfer User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CRUSH_Settings_Plan_Transfer</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Allow_Add_Tasks_From_Objective_Component__c.field-meta.xml
<CustomField>
    <fullName>Allow_Add_Tasks_From_Objective_Component__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to allow users to add tasks from the Objective Component</description>
    <inlineHelpText>Check this box to allow users to add tasks from the Objective Component</inlineHelpText>
    <label>Allow Add Tasks From Objective Component</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Can_Create_Objects_In_Cross_Sell__c.field-meta.xml
<CustomField>
    <fullName>Can_Create_Objects_In_Cross_Sell__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Toggle this to true to give users the option to create new objects in the Cross-Sell map</description>
    <inlineHelpText>Toggle this to true to give users the option to create new objects in the Cross-Sell map</inlineHelpText>
    <label>Can Create Objects In Cross-Sell</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Contacts_Ancestry_Levels__c.field-meta.xml
<CustomField>
    <fullName>Contacts_Ancestry_Levels__c</fullName>
    <defaultValue>2</defaultValue>
    <description>The number of levels to query when displaying the Hierarchy Chart of Contacts</description>
    <label>Contacts Ancestry Levels</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Disabled_Objective_Sort_Button__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Objective_Sort_Button__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to disable Objective Component Sort Button</description>
    <inlineHelpText>Check this box to disable Objective Component Sort Button</inlineHelpText>
    <label>Diable Objective Component Sort Button</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Enable_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Enable_Notifications__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Notifications</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Enable_Objective_Stage_Based_On_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Enable_Objective_Stage_Based_On_Tasks__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to enable objective stage based on tasks</description>
    <inlineHelpText>Check this box to enable objective stage based on tasks</inlineHelpText>
    <label>Enable objective stage based on tasks</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Goal_Updated__c.field-meta.xml
<CustomField>
    <fullName>Goal_Updated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Goal Updated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Org_Chart_Default_Fields__c.field-meta.xml
<CustomField>
    <fullName>Org_Chart_Default_Fields__c</fullName>
    <defaultValue>&quot;Contact.Name.Required,Contact.Title,Contact.Email,Key_Stakeholder__c.Influence__c.Required,Key_Stakeholder__c.Support__c.Required&quot;</defaultValue>
    <description>Determines the default fields for the Org Chart display</description>
    <label>Org Chart Default Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Relationship_Map_Default_Fields__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map_Default_Fields__c</fullName>
    <defaultValue>&quot;Contact.Name.Required,Contact.Title,Contact.Email,Relationship_Map_Member__c.Influence__c.Required,Relationship_Map_Member__c.Support__c.Required&quot;</defaultValue>
    <description>Determines the default fields for the Relationship Map display</description>
    <label>Relationship Map Default Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Team_Member_Permission_Updated__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Permission_Updated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Team Member Permission Updated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Org</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Use_Account_Team_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Use_Account_Team_Permissions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If enabled, will grant Account Plan permissions based on the Account permissions from the Account Team.</description>
    <inlineHelpText>If enabled, will grant Account Plan permissions based on the Account permissions from the Account Team.</inlineHelpText>
    <label>Use Account Team Permissions</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Use_Default_Account_Plan_Score__c.field-meta.xml
<CustomField>
    <fullName>Use_Default_Account_Plan_Score__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Toggle this to false to disable the built in Account Plan Scoring</description>
    <inlineHelpText>Turn off if you want to implement your own scoring to save to the Intermediate_Score__c field on account plan records</inlineHelpText>
    <label>Use Default Account Plan Scoring</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Use_Percentage_Account_Plan_Score__c.field-meta.xml
<CustomField>
    <fullName>Use_Percentage_Account_Plan_Score__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Toggle this to false to use old Account Plan Scoring component</description>
    <inlineHelpText>Turn off if you want to use old Account Plan Scoring component</inlineHelpText>
    <label>Use Percentage Account Plan Scoring</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/Use_System_Create_Task_Modal__c.field-meta.xml
<CustomField>
    <fullName>Use_System_Create_Task_Modal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use the default Saleforce Task modal when adding tasks from the Objective Component</description>
    <inlineHelpText>Check this box to use the default Saleforce Task modal when adding tasks from the Objective Component</inlineHelpText>
    <label>Use System Create Task Modal</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Determines the user these settings are for in the case of user level settings</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CRUSH_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/CRUSH_Settings_Obj__c/fields/WS_Object_Filter__c.field-meta.xml
<CustomField>
    <fullName>WS_Object_Filter__c</fullName>
    <description>A list of the objects that are available to use when creating a cross-sell template.</description>
    <inlineHelpText>You should use the API name for each object and each one should be on its own line</inlineHelpText>
    <label>WS Object Filter</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

default/classes/CrushSettings.cls
@SuppressWarnings('PMD.ExcessivePublicCount,PMD.TooManyFields')
public class CrushSettings {
    private static Map<String, String> labelsForNotifications = new Map<String, String>{
        'Goal_Updated__c' => Label.Goal_Updated,
        'Key_Date_Updated__c' => Label.Key_Dates_Updated,
        'Key_Stakeholder_Updated__c' => Label.Key_Stakeholders_Updated,
        'Objectives_Updated__c' => Label.Objectives_Updated,
        'Opportunities_Added__c' => Label.Opportunities_Updated,
        'Plan_Overview_Updated__c' => Label.Plan_Overview_Updated,
        'Status_Updated__c' => Label.Plan_Status_Updated,
        'SWOT_Analysis_Updated__c' => Label.SWOT_Analysis_Updated,
        'Team_Member_Added_Removed__c' => Label.Team_Members_Added_Or_Removed,
        'Team_Member_Permission_Updated__c' => Label.Team_Member_Roles_Updated
    };

    @AuraEnabled
    public Id id;

    @AuraEnabled
    public String type;

    @AuraEnabled
    public String user;

    @AuraEnabled
    public String accountPlanTransferUser;

    @AuraEnabled
    public String accountPlanTransfer;

    @AuraEnabled
    public Integer contactsAncestryLevels;

    @AuraEnabled
    public Boolean enableNotifications;

    @AuraEnabled
    public List<NotificationSetting> notifications;

    @AuraEnabled
    public Boolean useAccountTeamPermissions;

    @AuraEnabled
    public Boolean canCreateObjectsInCrossSell;

    @AuraEnabled
    public Boolean useDefaultAPScoring;

    @AuraEnabled
    public Boolean usePercentageAPScoring;

    @AuraEnabled
    public Boolean allowAddTaskFromObjectiveComponent;

    @AuraEnabled
    public Boolean allowTasksBasedObjStageFromObjectiveComponent;

    @AuraEnabled
    public Boolean useSystemTaskModalFromObjectiveComponent;

    @AuraEnabled
    public String crossSellObjectFilterString;

    @AuraEnabled
    public Boolean disableObjectComponentSortButton;

    private String orgChartDefaultFields;

    private String relationshipMapDefaultFields;

    public CrushSettings(CRUSH_Settings_Obj__c settings) {
        this.id = settings.Id;
        this.type = settings.Type__c;
        this.user = settings.User__c;
        this.accountPlanTransferUser = settings.Account_Plan_Transfer_User__c;
        this.accountPlanTransfer = settings.Account_Plan_Transfer__c;
        this.contactsAncestryLevels = (Integer) settings.Contacts_Ancestry_Levels__c;
        this.enableNotifications = settings.Enable_Notifications__c;
        this.orgChartDefaultFields = settings.Org_Chart_Default_Fields__c;
        this.relationshipMapDefaultFields = settings.Relationship_Map_Default_Fields__c;
        this.canCreateObjectsInCrossSell = settings.Can_Create_Objects_In_Cross_Sell__c;
        this.useDefaultAPScoring = settings.Use_Default_Account_Plan_Score__c;
        this.usePercentageAPScoring = settings.Use_Percentage_Account_Plan_Score__c;
        this.allowAddTaskFromObjectiveComponent = settings.Allow_Add_Tasks_From_Objective_Component__c;
        this.allowTasksBasedObjStageFromObjectiveComponent = settings.Enable_Objective_Stage_Based_On_Tasks__c;
        this.useSystemTaskModalFromObjectiveComponent = settings.Use_System_Create_Task_Modal__c;
        this.crossSellObjectFilterString = settings.WS_Object_Filter__c;
        this.disableObjectComponentSortButton = settings.Disabled_Objective_Sort_Button__c;
        this.notifications = addNotificationSettings(settings);
        if (AccountTeamService.areAccountTeamsEnabled()) {
            this.useAccountTeamPermissions = settings.Use_Account_Team_Permissions__c;
        }
    }

    public CrushSettings(CRUSH_Settings__c settings) {
        this.id = null;
        this.type = 'Org';
        this.user = null;
        this.accountPlanTransferUser = settings.Account_Plan_Transfer_User__c;
        this.accountPlanTransfer = settings.Account_Plan_Transfer__c;
        this.contactsAncestryLevels = (Integer) settings.Contacts_Ancestry_Levels__c;
        this.enableNotifications = settings.Enable_Notifications__c;
        this.orgChartDefaultFields = settings.Org_Chart_Default_Fields__c;
        this.notifications = addNotificationSettings(settings);
    }

    public CRUSH_Settings_Obj__c toSObject() {
        CRUSH_Settings_Obj__c settings = new CRUSH_Settings_Obj__c();

        settings.Id = this.id;
        settings.Type__c = this.type;
        settings.User__c = this.user;
        settings.Account_Plan_Transfer_User__c = this.accountPlanTransferUser;
        settings.Account_Plan_Transfer__c = this.accountPlanTransfer;
        settings.Contacts_Ancestry_Levels__c = this.contactsAncestryLevels;
        settings.Org_Chart_Default_Fields__c = this.orgChartDefaultFields;
        settings.Enable_Notifications__c = this.enableNotifications;
        settings.WS_Object_Filter__c = this.crossSellObjectFilterString;
        for (NotificationSetting setting : this.notifications) {
            settings.put(setting.name, setting.enabled);
        }
        if (this.useAccountTeamPermissions != null) {
            settings.Use_Account_Team_Permissions__c = this.useAccountTeamPermissions;
        }

        return settings;
    }

    private static List<NotificationSetting> addNotificationSettings(SObject settings) {
        List<NotificationSetting> notificationSettings = new List<NotificationSetting>();
        for (String field : labelsForNotifications.keySet()) {
            NotificationSetting nSetting = new NotificationSetting(
                field,
                labelsForNotifications.get(field),
                (Boolean) settings.get(field)
            );
            notificationSettings.add(nSetting);
        }
        return notificationSettings;
    }

    public class NotificationSetting {
        @AuraEnabled
        public String name { get; set; }

        @AuraEnabled
        public String label { get; set; }

        @AuraEnabled
        public Boolean enabled { get; set; }

        public NotificationSetting(String name, String label, Boolean enabled) {
            this.name = name;
            this.label = label;
            this.enabled = enabled;
            if (enabled == null) {
                this.enabled = false;
            }
        }
    }
}