default/objects/Org_Chart_Field__c/Org_Chart_Field__c.object-meta.xml
<CustomObject>
    <description>Defines a field to display in an Account Plan org chart</description>
    <label>Org Chart Field</label>
    <nameField>
        <label>Org Chart Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Chart Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Org_Chart_Field__c/fields/FieldLabel__c.field-meta.xml
<CustomField>
    <fullName>FieldLabel__c</fullName>
    <label>Field Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <description>Name of the related field</description>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/IsMain__c.field-meta.xml
<CustomField>
    <fullName>IsMain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want the field to show up in the main section of the card.  Otherwise, it will show up in the secondary area, that is hidden until users open the card</description>
    <label>IsMain</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/isRequired__c.field-meta.xml
<CustomField>
    <fullName>isRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether the related field can is allowed to be removed from the org chart display</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/isVisible__c.field-meta.xml
<CustomField>
    <fullName>isVisible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether the related field is visible in the org chart user interface</description>
    <label>Visible</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/Map_Type__c.field-meta.xml
<CustomField>
    <fullName>Map_Type__c</fullName>
    <label>Map Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Map_Type</valueSetName>
    </valueSet>
</CustomField>

default/objects/Org_Chart_Field__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>Name of the related object</description>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <displayFormat>{0000000000}</displayFormat>
    <label>Order</label>
    <type>AutoNumber</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/Related_FieldName__c.field-meta.xml
<CustomField>
    <fullName>Related_FieldName__c</fullName>
    <description>the API Name of the related field</description>
    <label>Related Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/OrgChartFieldSelector.cls
public with sharing class OrgChartFieldSelector extends fflib_SObjectSelector {
    public static OrgChartFieldSelector newInstance() {
        return (OrgChartFieldSelector) Application.Selector.newInstance(Org_Chart_Field__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Org_Chart_Field__c.Id,
            Org_Chart_Field__c.Name,
            Org_Chart_Field__c.ObjectName__c,
            Org_Chart_Field__c.FieldName__c,
            Org_Chart_Field__c.FieldLabel__c,
            Org_Chart_Field__c.isRequired__c,
            Org_Chart_Field__c.isVisible__c,
            Org_Chart_Field__c.Order__c,
            Org_Chart_Field__c.Map_Type__c,
            Org_Chart_Field__c.IsMain__c,
            Org_Chart_Field__c.Related_FieldName__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Org_Chart_Field__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<Org_Chart_Field__c> selectById(Set<Id> ids) {
        return (List<Org_Chart_Field__c>) selectSObjectsById(ids);
    }

    public List<Org_Chart_Field__c> selectByObjectNameAndMapType(String objectName, String mapType) {
        return Database.query(
            newQueryFactory().setCondition('ObjectName__c = :objectName AND Map_Type__c = :mapType').toSOQL()
        );
    }

    public List<Org_Chart_Field__c> selectByMapType(String mapType) {
        String objname ='Account';
        return Database.query(newQueryFactory().setCondition('Map_Type__c = :mapType AND ObjectName__c!=:objname').toSOQL());
    }

    public List<Org_Chart_Field__c> selectAll() {
        return Database.query(newQueryFactory().toSOQL());
    }

    public List<Org_Chart_Field__c> selectVisibleByMapType(String mapType) {
        System.debug('===OrgChartFieldSelector selectVisibleByMapType===');

        System.debug('=====query building===='+newQueryFactory().setCondition('(isRequired__c = true OR isVisible__c = true) AND Map_Type__c = :mapType').toSOQL());
        return Database.query(
            newQueryFactory()
                .setCondition('(isRequired__c = true OR isVisible__c = true) AND Map_Type__c = :mapType')
                .toSOQL()
        );
    }

    public List<Org_Chart_Field__c> selectVisibleByMapTypeAndObjectName(String mapType,Set<String> objectNameSet) {
        System.debug('===OrgChartFieldSelector selectVisibleByMapType===');

        System.debug('=====query building===='+newQueryFactory().setCondition('(isRequired__c = true OR isVisible__c = true) AND Map_Type__c = :mapType').toSOQL());
        if(!objectNameSet.isEmpty()){
            return Database.query(
                newQueryFactory()
                    .setCondition('(isRequired__c = true OR isVisible__c = true) AND Map_Type__c = :mapType AND pqcrush__ObjectName__c IN :objectNameSet')
                    .toSOQL()
            );
        }
        return Database.query(
            newQueryFactory()
                .setCondition('(isRequired__c = true OR isVisible__c = true) AND Map_Type__c = :mapType')
                .toSOQL()
        );
    }

    public List<Org_Chart_Field__c> selectAllVisible() {
        return Database.query(newQueryFactory().setCondition('isRequired__c = true OR isVisible__c = true').toSOQL());
    }
}