default/objects/pq_Influence_And_Support_Matrix__c/pq_Influence_And_Support_Matrix__c.object-meta.xml
<CustomObject>
    <label>Influence And Support Matrix</label>
    <nameField>
        <label>Influence And Support Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence And Support Matrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Support__c/pq_Support__c.object-meta.xml
<CustomObject>
    <label>Support</label>
    <nameField>
        <label>Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Support__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color RGB value in the form of #FF0011</description>
    <inlineHelpText>Enter color RGB value in the form of #FF0011</inlineHelpText>
    <label>Color</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/pq_Support_Matrix_Association__c/pq_Support_Matrix_Association__c.object-meta.xml
<CustomObject>
    <label>Support value for this matrix</label>
    <nameField>
        <displayFormat>pqSM-{0000}</displayFormat>
        <label>Support Matrix Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support values for this matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Support_Matrix_Association__c/fields/Influence_And_Support_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Influence_And_Support_Matrix__c</fullName>
    <label>Influence And Support Matrix</label>
    <referenceTo>pq_Influence_And_Support_Matrix__c</referenceTo>
    <relationshipName>Support_Matrix_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/pq_Support_Matrix_Association__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/pq_Support_Matrix_Association__c/fields/Support__c.field-meta.xml
<CustomField>
    <fullName>Support__c</fullName>
    <label>Support</label>
    <referenceTo>pq_Support__c</referenceTo>
    <relationshipName>Support_Matrix_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/classes/SupportMatrixAssociationSelectorTest.cls
@isTest
private class SupportMatrixAssociationSelectorTest {
    @isTest
    static void newInstanceTest() {
        SupportMatrixAssociationSelector selector = SupportMatrixAssociationSelector.newInstance();
        System.assertNotEquals(null, selector);
    }

    @isTest
    static void selectByMatrixIdTest() {
        pq_Support__c s1 = new pq_Support__c(Name = 'blocker', Label__c = 'blockerlabel', Color__c = '#ff0011');
        insert s1;
        pq_Influence_And_Support_Matrix__c m1 = new pq_Influence_And_Support_Matrix__c(Name = 'one');
        insert m1;
        pq_Support_Matrix_Association__c input1 = new pq_Support_Matrix_Association__c(
            Order__c = 1,
            Support__c = s1.Id,
            Influence_And_Support_Matrix__c = m1.Id
        );
        insert input1;

        Set<Id> inputSet = new Set<Id>{ m1.Id };

        Test.startTest();
        List<pq_Support_Matrix_Association__c> result = new SupportMatrixAssociationSelector()
            .selectByMatrixId(inputSet);
        Test.stopTest();

        System.assertEquals(1, result.size());
        System.assertEquals(m1.Id, result[0].Influence_And_Support_Matrix__c);
        System.assertEquals(s1.Id, result[0].Support__c);
        System.assertEquals('blocker', result[0].Support__r.Name);
        System.assertEquals('blockerlabel', result[0].Support__r.Label__c);
        System.assertEquals('#ff0011', result[0].Support__r.Color__c);
    }
}