default/objects/pq_Influence_And_Support_Matrix__c/pq_Influence_And_Support_Matrix__c.object-meta.xml
<CustomObject>
    <label>Influence And Support Matrix</label>
    <nameField>
        <label>Influence And Support Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence And Support Matrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Relationship_Map_Matrix_Association__c/pq_Relationship_Map_Matrix_Association__c.object-meta.xml
<CustomObject>
    <label>Relationship Map that uses this matrix</label>
    <nameField>
        <displayFormat>RMMA-{0000}</displayFormat>
        <label>Relationship Map Matrix Assoc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Maps that use this matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Relationship_Map_Matrix_Association__c/fields/Influence_And_Support_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Influence_And_Support_Matrix__c</fullName>
    <label>Influence And Support Matrix</label>
    <referenceTo>pq_Influence_And_Support_Matrix__c</referenceTo>
    <relationshipLabel>Relationship Maps that use this matrix</relationshipLabel>
    <relationshipName>Relationship_Maps_that_use_this_matrix</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/pq_Relationship_Map_Matrix_Association__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Relationship Maps that use this matrix</relationshipLabel>
    <relationshipName>Relationship_Maps_that_use_this_matrix</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/RMMatrixAssociationSelectorTest.cls
@isTest
private class RMMatrixAssociationSelectorTest {
    @isTest
    static void newInstanceTest() {
        RMMatrixAssociationSelector selector = RMMatrixAssociationSelector.newInstance();
        System.assertNotEquals(null, selector);
    }

    @isTest
    static void selectByRelationshipMapsTest() {
        Relationship_Map__c map1 = TestDataFactory.createRelationshipMap('map1');
        pq_Influence_And_Support_Matrix__c m1 = new pq_Influence_And_Support_Matrix__c(Name = 'one');
        insert m1;
        pq_Relationship_Map_Matrix_Association__c input1 = new pq_Relationship_Map_Matrix_Association__c(
            Relationship_Map__c = map1.Id,
            Influence_And_Support_Matrix__c = m1.Id
        );
        insert input1;

        Set<Id> mapIds = new Set<Id>{ map1.Id };

        Test.startTest();
        List<pq_Relationship_Map_Matrix_Association__c> result = new RMMatrixAssociationSelector()
            .selectByRelationshipMaps(mapIds);
        Test.stopTest();

        System.assertEquals(1, result.size());
        System.assertEquals(m1.Id, result[0].Influence_And_Support_Matrix__c);
        System.assertEquals(map1.Id, result[0].Relationship_Map__c);
    }
}