default/objects/pq_Influence_And_Support_Matrix__c/pq_Influence_And_Support_Matrix__c.object-meta.xml
<CustomObject>
    <label>Influence And Support Matrix</label>
    <nameField>
        <label>Influence And Support Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence And Support Matrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Influence_And_Support_Matrix__c/fields/Is_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>There should only be one matrix marked as the global default.  If multiple matrices are set as default, the system will select whichever was most recently modified.</description>
    <inlineHelpText>There should only be one matrix marked as the global default.  If multiple matrices are set as default, the system will select whichever was most recently modified.</inlineHelpText>
    <label>Global Default</label>
    <type>Checkbox</type>
</CustomField>

default/classes/MatrixWrapperTest.cls
@isTest
private class MatrixWrapperTest {
    @isTest
    static void initializeTest() {

        pq_Influence_And_Support_Matrix__c ism = new pq_Influence_And_Support_Matrix__c();
        ism.Name = 'Test Matrix For crmmt';
        ism.Is_Default__c = false;
        insert ism;

        InfluenceWrapper iw1 = new InfluenceWrapper('test1');
        InfluenceWrapper iw2 = new InfluenceWrapper('test2');

        List<InfluenceWrapper> influenceList = new List<InfluenceWrapper>{ iw1, iw2 };

        SupportWrapper sw1 = new SupportWrapper('test1');
        SupportWrapper sw2 = new SupportWrapper('test2');

        List<SupportWrapper> supportList = new List<SupportWrapper>{ sw1, sw2 };

        MatrixWrapper result = new MatrixWrapper(ism, influenceList, supportList);
        System.assertEquals(ism.Id, result.id);
        System.assertEquals(iw1.value, result.influenceList[0].value);
        System.assertEquals(iw2.value, result.influenceList[1].value);
        System.assertEquals(sw1.value, result.supportList[0].value);
        System.assertEquals(sw2.value, result.supportList[1].value);
    }

}