default/objects/pq_Influence_And_Support_Matrix__c/pq_Influence_And_Support_Matrix__c.object-meta.xml
<CustomObject>
    <label>Influence And Support Matrix</label>
    <nameField>
        <label>Influence And Support Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence And Support Matrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Influence_And_Support_Matrix__c/fields/Influence_Label__c.field-meta.xml
<CustomField>
    <fullName>Influence_Label__c</fullName>
    <label>Influence Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/pq_Influence_And_Support_Matrix__c/fields/Is_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>There should only be one matrix marked as the global default.  If multiple matrices are set as default, the system will select whichever was most recently modified.</description>
    <inlineHelpText>There should only be one matrix marked as the global default.  If multiple matrices are set as default, the system will select whichever was most recently modified.</inlineHelpText>
    <label>Global Default</label>
    <type>Checkbox</type>
</CustomField>

default/objects/pq_Influence_And_Support_Matrix__c/fields/Support_Label__c.field-meta.xml
<CustomField>
    <fullName>Support_Label__c</fullName>
    <label>Support Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/InfluenceSupportMatrixSelector.cls
public with sharing class InfluenceSupportMatrixSelector extends fflib_SObjectSelector {
    public static InfluenceSupportMatrixSelector newInstance() {
        return (InfluenceSupportMatrixSelector) Application.Selector.newInstance(
            pq_Influence_And_Support_Matrix__c.SObjectType
        );
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            pq_Influence_And_Support_Matrix__c.Id,
            pq_Influence_And_Support_Matrix__c.Name,
            pq_Influence_And_Support_Matrix__c.Is_Default__c,
            pq_Influence_And_Support_Matrix__c.Influence_Label__c,
            pq_Influence_And_Support_Matrix__c.Support_Label__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return pq_Influence_And_Support_Matrix__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<pq_Influence_And_Support_Matrix__c> selectById(Set<Id> ids) {
        return (List<pq_Influence_And_Support_Matrix__c>) selectSObjectsById(ids);
    }

    public pq_Influence_And_Support_Matrix__c selectDefault() {
        fflib_QueryFactory query = newQueryFactory().setCondition('Is_Default__c = true').setLimit(1);
        List<pq_Influence_And_Support_Matrix__c> result = Database.query(query.toSOQL());

        if (result.size() == 1) {
            return result[0];
        }

        return null;
    }
}