default/objects/pq_Master_Account_Plan__c/pq_Master_Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Master Account Plan</label>
    <nameField>
        <label>Master Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default/objects/pq_Master_Account_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Account Plans</relationshipLabel>
    <relationshipName>Master_Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/MasterAccountPlanSelector.cls
public with sharing class MasterAccountPlanSelector extends fflib_SObjectSelector {
    public static MasterAccountPlanSelector newInstance() {
        return (MasterAccountPlanSelector) Application.Selector.newInstance(pq_Master_Account_Plan__c.SObjectType);
    }

    /******************************
     *      QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            pq_Master_Account_Plan__c.Id,
            pq_Master_Account_Plan__c.Account__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return pq_Master_Account_Plan__c.sObjectType;
    }

    /******************************
     *      SELECT METHODS
     ******************************/


    public List<pq_Master_Account_Plan__c> selectById(Set<Id> idSet) {
        return (List<pq_Master_Account_Plan__c>) selectSObjectsById(idSet);
    }
}