default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Relationship__c/fields/Contact_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Type</label>
    <referenceTo>Contact_Relationship_Type__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/From_Contact__c.field-meta.xml
<CustomField>
    <fullName>From_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Relationships (From Contact)</relationshipLabel>
    <relationshipName>Contact_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/To_Contact__c.field-meta.xml
<CustomField>
    <fullName>To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Relationships (To Contact)</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship_Type__c/Contact_Relationship_Type__c.object-meta.xml
<CustomObject>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Relationship_Type__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Default Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/Map_Member_Placeholder_Relationship__c.object-meta.xml
<CustomObject>
    <label>Map Member Placeholder Relationship</label>
    <nameField>
        <label>Map Member Placeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Member Placeholder Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Contact_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Type</label>
    <referenceTo>Contact_Relationship_Type__c</referenceTo>
    <relationshipLabel>Map Member Placeholder Relationships</relationshipLabel>
    <relationshipName>Map_Member_Placeholder_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Is_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Is_Hierarchy__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this is true, then the relationship line is a hierarchy line that identifies that node A reports to node B</description>
    <label>Is_Hierarchy</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/fields/TempId__c.field-meta.xml
<CustomField>
    <fullName>TempId__c</fullName>
    <label>TempId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Is_Relationship_Line_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Relationship_Line_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to use Global Relationship Lines.  Leave this unchecked to create and use lines that are visible only in this Relationship Map</description>
    <inlineHelpText>Check this to use Global Relationship Lines.  Leave this unchecked to create and use lines that are visible only in this Relationship Map</inlineHelpText>
    <label>Use Global Relationship Lines</label>
    <type>Checkbox</type>
</CustomField>

default/classes/ContactRelationshipServiceImpl.cls
public with sharing class ContactRelationshipServiceImpl {
    private static final String PERMISSION_SET_STRATEGY_ADMIN = 'CRUSH_Administrator';
    private static final Integer LABEL_MAX_LENGTH = 255;

    /******************************
     *      PUBLIC METHODS
     ******************************/
    public List<GraphLinkData> getRelationships(Set<Id> contactIds, Id mapId, Boolean hasAccountPlanSetting) {
        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(mapId);

        List<Contact_Relationship__c> relationships;
        if (setting.Is_Relationship_Line_Global_Scope__c) {
            relationships = ContactRelationshipSelector.newInstance()
                .selectGlobalRelationshipsById(contactIds, mapId, hasAccountPlanSetting);
        } else {
            relationships = ContactRelationshipSelector.newInstance()
                .selectLocalRelationshipsById(contactIds, mapId, hasAccountPlanSetting);
        }

        List<GraphLinkData> links = new List<GraphLinkData>();
        for (Contact_Relationship__c rel : relationships) {
            links.add(
                new GraphLinkData(
                    rel.Id,
                    rel.TempId__c,
                    rel.From_Contact__c,
                    true,
                    rel.To_Contact__c,
                    rel.Contact_Relationship_Type__c,
                    HierarchyHelperService.getLabelForRelationship(rel)
                )
            );
        }
        return links;
    }

    public void deleteCustomLinks(List<GraphLinkData> linkData) {
        Set<String> ids = new Set<String>();
        for (GraphLinkData ld : linkData) {
            if (!String.isBlank(ld.Id)) {
                ids.add(ld.Id);
            } else if (!String.isBlank(ld.tempId)) {
                ids.add(ld.tempId);
            }
        }

        List<Contact_Relationship__c> relationshipRecords = ContactRelationshipSelector.newInstance()
            .selectByIdOrTempKey(ids);

        // Placeholder Links
        List<Map_Member_Placeholder_Relationship__c> placeholderRelationshipRecords = MapMemberPlaceholderRelationshipSelector.newInstance()
            .selectByIdOrTempKey(ids);

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        uow.registerDeleted(relationshipRecords);
        uow.registerDeleted(placeholderRelationshipRecords);
        uow.commitWork();
    }

    public void newCustomLinks(List<GraphLinkData> linkData, Id mapOrAccountPlanId) {
        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(mapOrAccountPlanId);

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for (GraphLinkData ld : linkData) {
            if (String.isBlank(ld.category)) {
                continue;
            }
            if (checkForContactToContactLink(ld.fromKey, ld.toKey)) {
                Contact_Relationship__c newRel = new Contact_Relationship__c(
                    From_Contact__c = ld.fromKey,
                    To_Contact__c = ld.toKey,
                    TempId__c = ld.tempId,
                    Label__c = ld.text,
                    Contact_Relationship_Type__c = ld.category
                );
                if (!setting.Is_Relationship_Line_Global_Scope__c) {
                    newRel.put(String.valueOf(mapOrAccountPlanId.getSobjectType()), mapOrAccountPlanId);
                }
                uow.registerNew(newRel);
            } else {
                Map_Member_Placeholder_Relationship__c newPlaceholderRel = new Map_Member_Placeholder_Relationship__c(
                    From__c = ld.fromKey,
                    To__c = ld.toKey,
                    TempId__c = ld.tempId,
                    Type__c = ld.category,
                    Label__c = ld.text,
                    Contact_Relationship_Type__c = ld.category,
                    Is_Hierarchy__c = false
                );
                if (!setting.Is_Relationship_Line_Global_Scope__c) {
                    newPlaceholderRel.put(String.valueOf(mapOrAccountPlanId.getSobjectType()), mapOrAccountPlanId);
                }
                uow.registerNew(newPlaceholderRel);
            }
        }

        uow.commitWork();
    }

    public void updateCustomLinks(List<GraphLinkData> linkData) {
        Map<String, GraphLinkData> ids = new Map<String, GraphLinkData>();
        for (GraphLinkData ld : linkData) {
            if (!String.isBlank(ld.Id) && (ld.Id instanceof Id)) {
                ids.put(ld.Id, ld);
            } else if (!String.isBlank(ld.tempId)) {
                ids.put(ld.tempId, ld);
            }
        }

        updateContactCustomLinks(ids);
        updatePlaceholderCustomLinks(ids);
    }

    private void updateContactCustomLinks(Map<String, GraphLinkData> ids) {
        // Contact Links
        List<Contact_Relationship__c> relationshipRecords = ContactRelationshipSelector.newInstance()
            .selectByIdOrTempKey(ids.keySet());

        List<Map_Member_Placeholder_Relationship__c> placeholderLinksToAdd = new List<Map_Member_Placeholder_Relationship__c>();
        List<Contact_Relationship__c> contactLinksToRemove = new List<Contact_Relationship__c>();
        for (Contact_Relationship__c cr : relationshipRecords) {
            GraphLinkData gld = ids.get(cr.Id);
            if (gld == null) {
                gld = ids.get(cr.TempId__c);
            }

            if (gld == null) {
                continue;
            }

            if (checkForContactToContactLink(gld.fromKey, gld.toKey)) {
                cr.From_Contact__c = gld.fromKey;
                cr.To_Contact__c = gld.toKey;
                cr.Label__c = this.getValidString(gld.text);
            } else {
                placeholderLinksToAdd.add(
                    new Map_Member_Placeholder_Relationship__c(
                        From__c = gld.fromKey,
                        To__c = gld.toKey,
                        Label__c = this.getValidString(gld.text),
                        Type__c = gld.category,
                        pqcrush__Contact_Relationship_Type__c = gld.category
                    )
                );
                contactLinksToRemove.add(cr);
            }
        }

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        uow.registerNew(placeholderLinksToAdd);
        uow.registerDeleted(contactLinksToRemove);
        uow.registerDirty(relationshipRecords);
        uow.commitWork();
    }

    private void updatePlaceholderCustomLinks(Map<String, GraphLinkData> ids) {
        // Placeholder Links
        List<Map_Member_Placeholder_Relationship__c> placeholderRelationshipRecords = MapMemberPlaceholderRelationshipSelector.newInstance()
            .selectByIdOrTempKey(ids.keySet());

        List<Map_Member_Placeholder_Relationship__c> placeholderLinksToRemove = new List<Map_Member_Placeholder_Relationship__c>();
        List<Contact_Relationship__c> contactLinksToAdd = new List<Contact_Relationship__c>();
        for (Map_Member_Placeholder_Relationship__c mmpr : placeholderRelationshipRecords) {
            GraphLinkData gld = ids.get(mmpr.Id);
            if (gld == null) {
                gld = ids.get(mmpr.TempId__c);
            }
            if (gld == null) {
                continue;
            }

            if (!checkForContactToContactLink(gld.fromKey, gld.toKey)) {
                mmpr.From__c = gld.fromKey;
                mmpr.To__c = gld.toKey;
                mmpr.Label__c = this.getValidString(gld.text);
            } else {
                contactLinksToAdd.add(
                    new Contact_Relationship__c(
                        From_Contact__c = gld.fromKey,
                        To_Contact__c = gld.toKey,
                        Label__c = this.getValidString(gld.text),
                        pqcrush__Contact_Relationship_Type__c = gld.category
                    )
                );
                placeholderLinksToRemove.add(mmpr);
            }
        }

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        uow.registerNew(contactLinksToAdd);
        uow.registerDirty(placeholderRelationshipRecords);
        uow.registerDeleted(placeholderLinksToRemove);
        uow.commitWork();
    }

    private String getValidString(String label) {
        if (String.isBlank(label)) {
            return '';
        }

        if (label.length() > LABEL_MAX_LENGTH) {
            return label.left(LABEL_MAX_LENGTH);
        }

        return label;
    }

    private Boolean checkForContactToContactLink(String fromKey, String toKey) {
        Id fromId = Id.valueOf(fromKey);
        Id toId = Id.valueOf(toKey);

        if (fromId == null || toId == null) {
            return false;
        }

        if (fromId.getSobjectType() == Contact.SObjectType && toId.getSobjectType() == Contact.SObjectType) {
            return true;
        }

        return false;
    }
}