default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder_Relationship__c/Map_Member_Placeholder_Relationship__c.object-meta.xml
<CustomObject>
    <label>Map Member Placeholder Relationship</label>
    <nameField>
        <label>Map Member Placeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Member Placeholder Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Is_Relationship_Line_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Relationship_Line_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to use Global Relationship Lines.  Leave this unchecked to create and use lines that are visible only in this Relationship Map</description>
    <inlineHelpText>Check this to use Global Relationship Lines.  Leave this unchecked to create and use lines that are visible only in this Relationship Map</inlineHelpText>
    <label>Use Global Relationship Lines</label>
    <type>Checkbox</type>
</CustomField>

default/classes/MapRelationshipLineContainer.cls
public with sharing class MapRelationshipLineContainer {
    @AuraEnabled
    public Id id;
    @AuraEnabled
    public Id relationshipMapId { get; set; }
    @AuraEnabled
    public Id accountPlanId { get; set; }
    @AuraEnabled
    public String containerName { get; set; }
    @AuraEnabled
    public Boolean isGlobalRelationship { get; set; }
    @AuraEnabled
    public Boolean isUsingGlobalRelationship { get; set; }
    @AuraEnabled
    public List<RelationshipLineWrapper> relationshipLines { get; set; }

    public MapRelationshipLineContainer(
        Id id,
        Id relationshipMapId,
        Id accountPlanId,
        String containerName,
        List<RelationshipLineWrapper> relationshipLines,
        Boolean isGlobalRelationship,
        BOolean isUsingGlobalRelationship
    ) {
        this.id = id;
        this.relationshipMapId = relationshipMapId;
        this.accountPlanId = accountPlanId;
        this.containerName = containerName;
        this.relationshipLines = relationshipLines;
        this.isGlobalRelationship = isGlobalRelationship;
        this.isUsingGlobalRelationship = isUsingGlobalRelationship;
    }

    public static List<MapRelationshipLineContainer> convert(
        Id contactId,
        List<Contact_Relationship__c> contactRelationshipList,
        List<Map_Member_Placeholder_Relationship__c> mapMemberList
    ) {
        if (
            (contactRelationshipList == null || contactRelationshipList.size() == 0) &&
            (mapMemberList == null ||
            mapMemberList.size() == 0)
        ) {
            return new List<MapRelationshipLineContainer>();
        }

        Map<String, List<CommonRelationshipLineObject>> mapByContainerId = RelationshipLineWrapperService.organizeMemberList(
            contactId,
            mapMemberList,
            contactRelationshipList
        );

        Map<Id, String> mapNodeName = RelationshipLineWrapperService.getNodeNames(
            contactRelationshipList,
            mapMemberList
        );

        Set<Id> containerIds = new Set<Id>();
        for (String containerId : mapByContainerId.keySet()) {
            if (containerId instanceof Id) {
                containerIds.add(Id.valueOf(containerId));
            }
        }

        Map<Id, RM_Chart_Setting__c> mapSettings = RMChartSettingService.getRelationshipMapSettingForObjects(
            containerIds
        );

        List<MapRelationshipLineContainer> result = new List<MapRelationshipLineContainer>();

        for (String containerId : mapByContainerId.keySet()) {
            List<CommonRelationshipLineObject> commonLineObjectList = mapByContainerId.get(containerId);

            List<RelationshipLineWrapper> lineWrapperList = new List<RelationshipLineWrapper>();
            for (CommonRelationshipLineObject crlo : commonLineObjectList) {
                lineWrapperList.add(
                    new RelationshipLineWrapper(crlo.Id, crlo.lineLabel, crlo.lineColor, mapNodeName.get(crlo.nodeKey))
                );
            }

            Boolean usingGlobal = false;
            if (containerId instanceof Id) {
                RM_Chart_Setting__c chartSetting = mapSettings.get(containerId);
                usingGlobal = chartSetting?.Is_Relationship_Line_Global_Scope__c;
            }

            result.add(
                new MapRelationshipLineContainer(
                    commonLineObjectList[0].id,
                    commonLineObjectList[0].relationshipMapId,
                    commonLineObjectList[0].accountPlanId,
                    commonLineObjectList[0].containerName,
                    lineWrapperList,
                    commonLineObjectList[0].isGlobalRelationship,
                    usingGlobal
                )
            );
        }

        return result;
    }
}