default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Relationship__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Lead__c/Map_Member_Lead__c.object-meta.xml
<CustomObject>
    <label>Map Member Lead</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Map Member Lead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Member Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Lead__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Map Member Leads</relationshipLabel>
    <relationshipName>Map_Member_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder__c/Map_Member_Placeholder__c.object-meta.xml
<CustomObject>
    <label>Map Member Placeholder</label>
    <nameField>
        <label>Map Member Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Member Placeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Map Member Placeholders</relationshipLabel>
    <relationshipName>Map_Member_Placeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/pq_Relationship_Map_Matrix_Association__c/pq_Relationship_Map_Matrix_Association__c.object-meta.xml
<CustomObject>
    <label>Relationship Map that uses this matrix</label>
    <nameField>
        <displayFormat>RMMA-{0000}</displayFormat>
        <label>Relationship Map Matrix Assoc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Maps that use this matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/pq_Relationship_Map_Matrix_Association__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Relationship Maps that use this matrix</relationshipLabel>
    <relationshipName>Relationship_Maps_that_use_this_matrix</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Group__c/Relationship_Group__c.object-meta.xml
<CustomObject>
    <label>Relationship Group</label>
    <nameField>
        <label>Relationship Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Group__c/fields/Parent_Relationship_Group__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Relationship Group</label>
    <referenceTo>Relationship_Group__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Group__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Relationship Groups</relationshipLabel>
    <relationshipName>Relationship_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Map_Member__c/Relationship_Map_Member__c.object-meta.xml
<CustomObject>
    <label>Relationship Map Member</label>
    <nameField>
        <displayFormat>CHM-{0000}</displayFormat>
        <label>Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Map Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Relationship_Map_Member__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Type_Map_Association__c/Relationship_Type_Map_Association__c.object-meta.xml
<CustomObject>
    <label>Relationship Type Map Association</label>
    <nameField>
        <displayFormat>RTA={0000}</displayFormat>
        <label>Relationship Type Map Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Type Map Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Relationship_Type_Map_Association__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Relationship Type Map Associations</relationshipLabel>
    <relationshipName>Relationship_Type_Map_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/RM_Anchor__c/RM_Anchor__c.object-meta.xml
<CustomObject>
    <label>RM Anchor</label>
    <nameField>
        <label>RM Anchors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM Anchors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Anchor__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Anchors</relationshipLabel>
    <relationshipName>RM_Anchors</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Node_Coordinate__c/RM_Node_Coordinate__c.object-meta.xml
<CustomObject>
    <label>RM Node Coordinate</label>
    <nameField>
        <displayFormat>RMNodeCoordinate-{0000}</displayFormat>
        <label>RM Node Coordinate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Node Coordinates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Node_Coordinate__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Node Coordinates</relationshipLabel>
    <relationshipName>RM_Node_Coordinates</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Svg_Map_Association__c/RM_Svg_Map_Association__c.object-meta.xml
<CustomObject>
    <label>RM Svg Map Association</label>
    <nameField>
        <displayFormat>RMSvgMap-{0000}</displayFormat>
        <label>RM Svg Map Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Svg Map Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/RM_Svg_Map_Association__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Svg Map Associations</relationshipLabel>
    <relationshipName>RM_Svg_Map_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/RM_Svg_Node_Association__c/RM_Svg_Node_Association__c.object-meta.xml
<CustomObject>
    <label>RM Svg Node Association</label>
    <nameField>
        <label>RM Svg Node Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RM Svg Node Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/RM_Svg_Node_Association__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Svg Node Associations</relationshipLabel>
    <relationshipName>RM_Svg_Node_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/RelationshipMapCloneService.cls
@SuppressWarnings('PMD.NcssMethodCount,PMD.AvoidGlobalModifier')
global with sharing class RelationshipMapCloneService {
    public static final String MAP_MEMBER_RELATIONSHIP_NAME = 'pqcrush__Members__r';
    public static final String MAP_MEMBER_LEADS_RELATIONSHIP_NAME = 'pqcrush__Map_Member_Leads__r';
    public static final String CUSTOM_RELATIONSHIP_LINE_RELATIONSHIP_NAME = 'pqcrush__Contact_Relationships__r';
    public static final String PLACEHOLDER_RELATIONSHIP_NAME = 'pqcrush__Map_Member_Placeholders__r';
    public static final String ANCHOR_RELATIONSHIP_NAME = 'pqcrush__RM_Anchors__r';
    public static final String MATRIX_RELATIONSHIP_NAME = 'pqcrush__Relationship_Maps_that_use_this_matrix__r';
    public static final String RM_SETTINGS_RELATIONSHIP_NAME = 'pqcrush__RM_Chart_Settings__r';
    public static final String NODE_COORDINATE_RELATIONSHIP_NAME = 'pqcrush__RM_Node_Coordinates__r';
    public static final String RM_GROUP_RELATIONSHIP_NAME = 'pqcrush__Relationship_Groups__r';
    public static final String RM_BADGE_ACCOUNT_PLAN_ASSOC_NAME = 'pqcrush__RM_Svg_Map_Associations__r';
    public static final String RM_BADGE_NODE_ASSOC_NAME = 'pqcrush__RM_Svg_Node_Associations__r';
    public static final String RELATIONSHIP_TYPE_MAP_ASSOC_NAME = 'pqcrush__Relationship_Type_Map_Associations__r';

    @InvocableMethod(
        label='Clone Relationship Maps'
        description='Clones a list of Relationship Maps based on the data passed in to cloneWrappers'
    )
    global static List<Relationship_Map__c> cloneRelationshipMaps(List<RelationshipMapCloneWrapper> cloneWrappers) {
        return service().cloneRelationshipMaps(cloneWrappers, null, null, true);
    }

    public static List<Relationship_Map__c> cloneRelationshipMaps(
        List<RelationshipMapCloneWrapper> cloneWrappers,
        List<SObject> clonedRelatedObjs,
        Set<Schema.SObjectType> relatedObjectTypes,
        Boolean startBatches
    ) {
        return service().cloneRelationshipMaps(cloneWrappers, clonedRelatedObjs, relatedObjectTypes, startBatches);
    }

    private static RelationshipMapCloneServiceImpl service() {
        return (RelationshipMapCloneServiceImpl) Application.Service.newInstance(RelationshipMapCloneServiceImpl.class);
    }
}