default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Relationship__c/fields/Contact_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Type</label>
    <referenceTo>Contact_Relationship_Type__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/From_Contact__c.field-meta.xml
<CustomField>
    <fullName>From_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Relationships (From Contact)</relationshipLabel>
    <relationshipName>Contact_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/fields/To_Contact__c.field-meta.xml
<CustomField>
    <fullName>To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Relationships (To Contact)</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship_Type__c/Contact_Relationship_Type__c.object-meta.xml
<CustomObject>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Relationship_Type__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Default Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Map_Member_Placeholder__c/Map_Member_Placeholder__c.object-meta.xml
<CustomObject>
    <label>Map Member Placeholder</label>
    <nameField>
        <label>Map Member Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Member Placeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Map Member Placeholders</relationshipLabel>
    <relationshipName>Map_Member_Placeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/Map_Member_Placeholder_Relationship__c.object-meta.xml
<CustomObject>
    <label>Map Member Placeholder Relationship</label>
    <nameField>
        <label>Map Member Placeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Member Placeholder Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Contact_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Type</label>
    <referenceTo>Contact_Relationship_Type__c</referenceTo>
    <relationshipLabel>Map Member Placeholder Relationships</relationshipLabel>
    <relationshipName>Map_Member_Placeholder_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Is_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Is_Hierarchy__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this is true, then the relationship line is a hierarchy line that identifies that node A reports to node B</description>
    <label>Is_Hierarchy</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Map Member Placeholder Relationships</relationshipLabel>
    <relationshipName>Map_Member_Placeholder_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/fields/TempId__c.field-meta.xml
<CustomField>
    <fullName>TempId__c</fullName>
    <label>TempId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Is_Relationship_Line_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Relationship_Line_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to use Global Relationship Lines.  Leave this unchecked to create and use lines that are visible only in this Relationship Map</description>
    <inlineHelpText>Check this to use Global Relationship Lines.  Leave this unchecked to create and use lines that are visible only in this Relationship Map</inlineHelpText>
    <label>Use Global Relationship Lines</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/ContactRelationshipServiceTest.cls
@SuppressWarnings('PMD.NcssMethodCount')
@isTest
private class ContactRelationshipServiceTest {
    /*----------------------------------------------------------------------------------------------
    getRelationshipsTest
    -----------------------------------------------------------------------------------------------*/
    @isTest
    static void getRelationshipsLocalTest() {
        // Mocks
        TestMockData md = new TestMockData();
        ContactRelationshipSelector mockSelector = md.mockContactRelationshipSelector;
        RMChartSettingServiceImpl mockRMChartSettingService = md.mockRMChartSettingService;

        // Given
        Contact jody = new Contact(LastName = 'jody');
        insert jody;
        Contact neil = new Contact(ReportsToId = jody.Id, LastName = 'neil');
        insert neil;
        Contact terry = new Contact(ReportsToId = neil.Id, LastName = 'terry');
        insert terry;
        Contact ant = new Contact(ReportsToId = terry.Id, LastName = 'ant');
        Contact cj = new Contact(ReportsToId = terry.Id, LastName = 'cj');
        Contact dame = new Contact(ReportsToId = terry.Id, LastName = 'dame');
        Contact nas = new Contact(ReportsToId = terry.Id, LastName = 'nas');
        insert ant;
        insert cj;
        insert dame;
        insert nas;

        Contact_Relationship__c c1 = new Contact_Relationship__c(From_Contact__c = jody.Id, To_Contact__c = neil.Id);
        Contact_Relationship__c c2 = new Contact_Relationship__c(From_Contact__c = neil.Id, To_Contact__c = terry.Id);
        Contact_Relationship__c c3 = new Contact_Relationship__c(From_Contact__c = terry.Id, To_Contact__c = dame.Id);
        Contact_Relationship__c c4 = new Contact_Relationship__c(From_Contact__c = terry.Id, To_Contact__c = cj.Id);
        Contact_Relationship__c c5 = new Contact_Relationship__c(From_Contact__c = terry.Id, To_Contact__c = ant.Id);
        Contact_Relationship__c c6 = new Contact_Relationship__c(From_Contact__c = terry.Id, To_Contact__c = nas.Id);

        List<Contact_Relationship__c> contactRelationships = new List<Contact_Relationship__c>{
            c1,
            c2,
            c3,
            c4,
            c5,
            c6
        };
        Set<Id> contactIds = new Set<Id>{ jody.Id, neil.Id, terry.Id, ant.Id, dame.Id, cj.Id, nas.Id };

        RM_Chart_Setting__c setting = new RM_Chart_Setting__c(
            Id = fflib_IDGenerator.generate(RM_Chart_Setting__c.SObjectType),
            Is_Relationship_Line_Global_Scope__c = false
        );

        md.mocks.startStubbing();
        md.mocks.when(mockRMChartSettingService.getRelationshipMapSettingForObject(md.mockRelationshipMapId))
            .thenReturn(setting);
        md.mocks.when(mockSelector.selectLocalRelationshipsById(contactIds, md.mockRelationshipMapId, false))
            .thenReturn(contactRelationships);
        md.mocks.stopStubbing();

        // When
        Test.startTest();
        List<GraphLinkData> linkData = ContactRelationshipService.getRelationships(
            contactIds,
            md.mockRelationshipMapId,
            false
        );
        Test.stopTest();

        // Then
        System.assertEquals(6, linkData.size());
    }

    @isTest
    static void getRelationshipsGlobalTest() {
        // Mocks
        TestMockData md = new TestMockData();
        ContactRelationshipSelector mockSelector = md.mockContactRelationshipSelector;
        RMChartSettingServiceImpl mockRMChartSettingService = md.mockRMChartSettingService;

        // Given
        Contact jody = new Contact(LastName = 'jody');
        insert jody;
        Contact neil = new Contact(ReportsToId = jody.Id, LastName = 'neil');
        insert neil;
        Contact terry = new Contact(ReportsToId = neil.Id, LastName = 'terry');
        insert terry;
        Contact ant = new Contact(ReportsToId = terry.Id, LastName = 'ant');
        Contact cj = new Contact(ReportsToId = terry.Id, LastName = 'cj');
        Contact dame = new Contact(ReportsToId = terry.Id, LastName = 'dame');
        Contact nas = new Contact(ReportsToId = terry.Id, LastName = 'nas');
        insert ant;
        insert cj;
        insert dame;
        insert nas;

        Contact_Relationship__c c1 = new Contact_Relationship__c(From_Contact__c = jody.Id, To_Contact__c = neil.Id);
        Contact_Relationship__c c2 = new Contact_Relationship__c(From_Contact__c = neil.Id, To_Contact__c = terry.Id);
        Contact_Relationship__c c3 = new Contact_Relationship__c(From_Contact__c = terry.Id, To_Contact__c = dame.Id);
        Contact_Relationship__c c4 = new Contact_Relationship__c(From_Contact__c = terry.Id, To_Contact__c = cj.Id);
        Contact_Relationship__c c5 = new Contact_Relationship__c(From_Contact__c = terry.Id, To_Contact__c = ant.Id);
        Contact_Relationship__c c6 = new Contact_Relationship__c(From_Contact__c = terry.Id, To_Contact__c = nas.Id);

        List<Contact_Relationship__c> contactRelationships = new List<Contact_Relationship__c>{
            c1,
            c2,
            c3,
            c4,
            c5,
            c6
        };
        Set<Id> contactIds = new Set<Id>{ jody.Id, neil.Id, terry.Id, ant.Id, dame.Id, cj.Id, nas.Id };

        RM_Chart_Setting__c setting = new RM_Chart_Setting__c(
            Id = fflib_IDGenerator.generate(RM_Chart_Setting__c.SObjectType),
            Is_Relationship_Line_Global_Scope__c = true
        );

        md.mocks.startStubbing();
        md.mocks.when(mockRMChartSettingService.getRelationshipMapSettingForObject(md.mockRelationshipMapId))
            .thenReturn(setting);
        md.mocks.when(mockSelector.selectGlobalRelationshipsById(contactIds, md.mockRelationshipMapId, false))
            .thenReturn(contactRelationships);
        md.mocks.stopStubbing();

        // When
        Test.startTest();
        List<GraphLinkData> linkData = ContactRelationshipService.getRelationships(
            contactIds,
            md.mockRelationshipMapId,
            false
        );
        Test.stopTest();

        // Then
        System.assertEquals(6, linkData.size());
    }

    /*----------------------------------------------------------------------------------------------
    deleteCustomLinks
    -----------------------------------------------------------------------------------------------*/
    @isTest
    static void deleteCustomLinksTest() {
        // Mocks
        TestMockData md = new TestMockData();
        ContactRelationshipSelector mockSelector = md.mockContactRelationshipSelector;
        MapMemberPlaceholderRelationshipSelector mockMapMemberPlaceholderRelationshipSelector = md.mockMapMemberPlaceholderRelationshipSelector;
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;

        // Given
        List<GraphLinkData> linkDataArray = new List<GraphLinkData>();
        linkDataArray.add(
            new GraphLinkData(
                fflib_IDGenerator.generate(Contact_Relationship__c.SObjectType),
                '',
                '',
                false,
                '',
                '',
                ''
            )
        );
        linkDataArray.add(new GraphLinkData('', 'abc', '', false, '', '', ''));

        Contact_Relationship__c c1 = new Contact_Relationship__c(
            Id = fflib_IDGenerator.generate(Contact_Relationship__c.SObjectType),
            TempId__c = 'a'
        );
        Map_Member_Placeholder_Relationship__c c2 = new Map_Member_Placeholder_Relationship__c(
            Id = fflib_IDGenerator.generate(Map_Member_Placeholder_Relationship__c.SObjectType),
            TempId__c = 'b'
        );

        Set<String> ids = new Set<String>{ linkDataArray[0].id, linkDataArray[1].tempId };

        md.mocks.startStubbing();
        md.mocks.when(mockSelector.selectByIdOrTempKey(ids)).thenReturn(new List<Contact_Relationship__c>{ c1 });
        md.mocks.when(mockMapMemberPlaceholderRelationshipSelector.selectByIdOrTempKey(ids))
            .thenReturn(new List<Map_Member_Placeholder_Relationship__c>{ c2 });
        md.mocks.stopStubbing();

        // When
        Test.startTest();
        ContactRelationshipService.deleteCustomLinks(linkDataArray);
        Test.stopTest();

        //Then
        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 2))
            .registerDeleted((List<Contact_Relationship__c>) fflib_Match.anyList());
        System.assert(true, 'Assert verified by mocks');
    }

    /*----------------------------------------------------------------------------------------------
    newCustomLinks
    -----------------------------------------------------------------------------------------------*/
    @isTest
    static void newCustomLinksTest() {
        // Mocks
        TestMockData md = new TestMockData();
        ContactRelationshipSelector mockSelector = md.mockContactRelationshipSelector; //NOPMD - Needs to be called in order for it to be mocked in the test
        MapMemberPlaceholderRelationshipSelector mockMapMemberPlaceholderRelationshipSelector = md.mockMapMemberPlaceholderRelationshipSelector; //NOPMD - Needs to be called in order for it to be mocked in the test
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;

        // Given
        List<GraphLinkData> linkDataArray = new List<GraphLinkData>();
        String fromKey = fflib_IDGenerator.generate(Contact.SObjectType);
        String toKey = fflib_IDGenerator.generate(Contact.SObjectType);

        String fromKey2 = fflib_IDGenerator.generate(Map_Member_Placeholder__c.SObjectType);
        String toKey2 = fflib_IDGenerator.generate(Map_Member_Placeholder__c.SObjectType);

        Contact_Relationship_Type__c relType = TestDataFactory.createContactRelationshipType(
            '#ff0022',
            'label',
            true,
            true
        );

        linkDataArray.add(new GraphLinkData('', 'tempIdabc', fromKey, false, toKey, relType.Id, 'label'));

        linkDataArray.add(new GraphLinkData('', 'tempIdabc', fromKey2, false, toKey2, relType.Id, 'label'));

        // When
        Test.startTest();
        ContactRelationshipService.newCustomLinks(linkDataArray, md.mockRelationshipMapId);
        Test.stopTest();

        //Then
        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1))
            .registerNew(
                new Contact_Relationship__c(
                    From_Contact__c = fromKey,
                    To_Contact__c = toKey,
                    TempId__c = 'tempIdabc',
                    Contact_Relationship_Type__c = relType.Id,
                    Label__c = 'label',
                    Relationship_Map__c = md.mockRelationshipMapId
                )
            );
        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1))
            .registerNew(
                new Map_Member_Placeholder_Relationship__c(
                    From__c = fromKey2,
                    To__c = toKey2,
                    TempId__c = 'tempIdabc',
                    Type__c = relType.Id,
                    Label__c = 'label',
                    Contact_Relationship_Type__c = relType.Id,
                    Relationship_Map__c = md.mockRelationshipMapId,
                    Is_Hierarchy__c = false
                )
            );
        System.assert(true, 'Assert by mock verify');
    }

    /*----------------------------------------------------------------------------------------------
    updateCustomLinks
    -----------------------------------------------------------------------------------------------*/
    @isTest
    static void updateCustomLinksTest() {
        // Mocks
        TestMockData md = new TestMockData();
        ContactRelationshipSelector mockSelector = md.mockContactRelationshipSelector;
        MapMemberPlaceholderRelationshipSelector mockMapMemberPlaceholderRelationshipSelector = md.mockMapMemberPlaceholderRelationshipSelector;
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;

        // Given
        List<GraphLinkData> linkDataArray = new List<GraphLinkData>();
        Id from1 = fflib_IDGenerator.generate(Contact.SObjectType);
        Id to1 = fflib_IDGenerator.generate(Contact.SObjectType);
        Id from2 = fflib_IDGenerator.generate(Map_Member_Placeholder__c.SObjectType);
        Id to2 = fflib_IDGenerator.generate(Map_Member_Placeholder__c.SObjectType);
        linkDataArray.add(
            new GraphLinkData(
                fflib_IDGenerator.generate(Contact_Relationship__c.SObjectType),
                'tempId',
                from1,
                false,
                to1,
                'Custom',
                'Label'
            )
        );
        linkDataArray.add(new GraphLinkData('', 'tempId2', from2, false, to2, 'Custom', 'Label'));

        Contact_Relationship__c c1 = new Contact_Relationship__c(
            Id = fflib_IDGenerator.generate(Contact_Relationship__c.SObjectType),
            TempId__c = 'a'
        );
        Map_Member_Placeholder_Relationship__c c2 = new Map_Member_Placeholder_Relationship__c(
            Id = fflib_IDGenerator.generate(Map_Member_Placeholder_Relationship__c.SObjectType),
            TempId__c = 'b'
        );

        Set<String> ids = new Set<String>{ linkDataArray[0].id, linkDataArray[1].tempId };

        md.mocks.startStubbing();
        md.mocks.when(mockSelector.selectByIdOrTempKey(ids)).thenReturn(new List<Contact_Relationship__c>{ c1 });
        md.mocks.when(mockMapMemberPlaceholderRelationshipSelector.selectByIdOrTempKey(ids))
            .thenReturn(new List<Map_Member_Placeholder_Relationship__c>{ c2 });
        md.mocks.stopStubbing();

        // When
        Test.startTest();
        ContactRelationshipService.updateCustomLinks(linkDataArray);
        Test.stopTest();

        //Then
        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 2))
            .registerDirty((List<Contact_Relationship__c>) fflib_Match.anyList());
        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 2))
            .registerNew((List<Contact_Relationship__c>) fflib_Match.anyList());
        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 2))
            .registerDeleted((List<Contact_Relationship__c>) fflib_Match.anyList());
        System.assert(true, 'Assert by mock verify');
    }
}