default/objects/Contact_Extended_Field__c/Contact_Extended_Field__c.object-meta.xml
<CustomObject>
    <label>Contact Extended Field</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contact Extended Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Extended Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Extended_Field__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Extended Fields</relationshipLabel>
    <relationshipName>Contact_Extended_Fields</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Extended_Field__c/fields/Influence__c.field-meta.xml
<CustomField>
    <fullName>Influence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Influence</label>
    <referenceTo>pq_Influence__c</referenceTo>
    <relationshipLabel>Contact Extended Fields</relationshipLabel>
    <relationshipName>Contact_Extended_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Extended_Field__c/fields/Support__c.field-meta.xml
<CustomField>
    <fullName>Support__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support</label>
    <referenceTo>pq_Support__c</referenceTo>
    <relationshipLabel>Contact Extended Fields</relationshipLabel>
    <relationshipName>Contact_Extended_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/pq_Influence__c/pq_Influence__c.object-meta.xml
<CustomObject>
    <label>Influence</label>
    <nameField>
        <label>Influence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Influence_And_Support_Matrix__c/pq_Influence_And_Support_Matrix__c.object-meta.xml
<CustomObject>
    <label>Influence And Support Matrix</label>
    <nameField>
        <label>Influence And Support Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence And Support Matrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Support__c/pq_Support__c.object-meta.xml
<CustomObject>
    <label>Support</label>
    <nameField>
        <label>Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Map_Member__c/Relationship_Map_Member__c.object-meta.xml
<CustomObject>
    <label>Relationship Map Member</label>
    <nameField>
        <displayFormat>CHM-{0000}</displayFormat>
        <label>Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Map Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Relationship_Map_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationship Map Members</relationshipLabel>
    <relationshipName>Hierarchy_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/Influence__c.field-meta.xml
<CustomField>
    <fullName>Influence__c</fullName>
    <label>Influence (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Key_Stakeholder_Influence</valueSetName>
    </valueSet>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/InfluenceId__c.field-meta.xml
<CustomField>
    <fullName>InfluenceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This influence value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</description>
    <inlineHelpText>This influence value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</inlineHelpText>
    <label>Local Influence</label>
    <referenceTo>pq_Influence__c</referenceTo>
    <relationshipLabel>Relationship Map Members</relationshipLabel>
    <relationshipName>Relationship_Map_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/Support__c.field-meta.xml
<CustomField>
    <fullName>Support__c</fullName>
    <label>Support (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Key_Stakeholder_Support</valueSetName>
    </valueSet>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/SupportId__c.field-meta.xml
<CustomField>
    <fullName>SupportId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This support value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</description>
    <inlineHelpText>This support value is local to the map.  it is used when the chart setting &quot;Use Global Influence and Support Values.&quot; is unchecked.</inlineHelpText>
    <label>Local Support</label>
    <referenceTo>pq_Support__c</referenceTo>
    <relationshipLabel>Relationship Map Members</relationshipLabel>
    <relationshipName>Relationship_Map_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Is_Influence_Support_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Influence_Support_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Global Influence and Support Values</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Is_Reports_To_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Reports_To_Global_Scope__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this option to use the Salesforce &apos;Reports To&apos; field.  Uncheck this and this relationship map will maintain this data locally to the chart.</description>
    <inlineHelpText>Check this option to use the Salesforce &apos;Reports To&apos; field.  Uncheck this and this relationship map will maintain this data locally to the chart.</inlineHelpText>
    <label>Use Global Reports To Field</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Show_Empty_Fields__c.field-meta.xml
<CustomField>
    <fullName>Show_Empty_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want fields that have no value to show up.  For example, if users don&apos;t have an email it will show [email].  Uncheck this if you want fields that have no value to not show up.</description>
    <label>Show Empty Fields</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Show_Parents__c.field-meta.xml
<CustomField>
    <fullName>Show_Parents__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this to include a node&apos;s parent node (if they have a parent)</description>
    <inlineHelpText>Check this to include a node&apos;s parent node (if they have a parent)</inlineHelpText>
    <label>Show Parents</label>
    <type>Checkbox</type>
</CustomField>

default/classes/RelationshipMapMemberHelper.cls
@SuppressWarnings('PMD.ExcessivePublicCount,PMD.NcssMethodCount')
public with sharing class RelationshipMapMemberHelper {
    
    public static MatrixMember convertToMatrixMember(List<Relationship_Map_Member__c> mapMembers) {
        if (mapMembers == null || mapmembers.size() <= 0) {
            return null;
        }

        // Future convert the whole list and return a map
        Relationship_Map_Member__c mapMember = mapMembers[0];

        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(
            mapMember.Relationship_Map__c
        );

        if (!setting.Is_Influence_Support_Global_Scope__c) {
            return new MatrixMember(mapMember);
        }

        List<Contact_Extended_Field__c> contactExtFields = ContactExtendedFieldSelector.newInstance()
            .selectByContactId(new Set<Id>{ mapMember.Contact__c });
        if (contactExtFields.size() == 1) {
            return new MatrixMember(
                mapMember,
                contactExtFields[0].Influence__r.Name,
                contactExtFields[0].Support__r.Name
            );
        }
        return new MatrixMember(mapMember, null, null);
    }
	public static GraphData addContactToRelationshipMap(Id relationshipMapId, String graphDataJsonString) {
           GraphData gd = (GraphData) JSON.deserialize(graphDataJsonString, GraphData.class);

        if (relationshipMapId == null || gd == null || gd.nodeDataArray == null) {
            return new GraphData();
        }

        RelationshipMapMemberController.setMapType(relationshipMapId);

        Set<Id> contactIdSet = new Set<Id>();
        for (GraphNodeData node : gd.nodeDataArray) {
            contactIdSet.add(node.key);
        }
        List<Relationship_Map_Member__c> mapMembers = RelationshipMapService.addContactToRelationshipMap(
            relationshipMapId,
            contactIdSet
        );
        List<RelationshipMapMemberWrapper> wrapperList = new List<RelationshipMapMemberWrapper>();
        for (Relationship_Map_Member__c member : mapMembers) {
            RelationshipMapMemberWrapper wrapper = new RelationshipMapMemberWrapper(member);
            wrapperList.add(wrapper);
        }

        RMNodeCoordinateService.updateNodeCoordinates(relationshipMapId, gd.nodeDataArray);

        RM_Chart_Setting__C setting = RMChartSettingService.getRelationshipMapSettingForObject(relationshipMapId);
        setting.Show_Parents__c = false;
        setting.Show_Empty_Fields__c = true;

        List<pq_Influence_And_Support_Matrix__c> matrixes = RelationshipMapMemberController.getMatrixes(new Set<Id>{ relationshipMapId });
        return GraphDataService.generateGraphData(
            wrapperList,
            setting,
            RelationshipMapMemberController.getMapInfluence(matrixes),
            RelationshipMapMemberController.getMapSupport(matrixes),
            RelationshipMapMemberController.mapMembersAndContactFields.get('contacts'),
            RelationshipMapMemberController.orgChartfields,
            relationshipMapId
        );
	}
    public static List<MatrixMember> getMapMembersByMapId(Id mapId) {
        if (mapId == null) {
            return new List<MatrixMember>();
        }
        RelationshipMapMemberController.setMapType(mapId);
        List<Relationship_Map_Member__c> rmmList = RelationshipMapMemberSelector.newInstance()
            .selectByRelationshipMapIdsAndSelectFieldsWithYourContacts(
                new Set<Id>{ mapId },
                RelationshipMapMemberController.mapMembersAndContactFields.get('members'),
                RelationshipMapMemberController.mapMembersAndContactFields.get('contacts')
            );

        Set<Id> contactIds = new Set<Id>();
        Map<Id, Contact_Extended_Field__c> contactExtMap = new Map<Id, Contact_Extended_Field__c>();
        for (Relationship_Map_Member__c rmm : rmmList) {
            contactIds.add(rmm.Contact__c);
        }
        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(mapId);
        if (setting.Is_Influence_Support_Global_Scope__c) {
            List<Contact_Extended_Field__c> contactExtFields = ContactExtendedFieldSelector.newInstance()
                .selectByContactId(contactIds);
            for (Contact_Extended_Field__c cef : contactExtFields) {
                contactExtMap.put(cef.Contact__c, cef);
            }
            List<MatrixMember> matrixMemberList = new List<MatrixMember>();
            for (Relationship_Map_Member__c rmm : rmmList) {
                Contact_Extended_Field__c contactExtField = contactExtMap.get(rmm.Contact__c);
                matrixMemberList.add(
                    new MatrixMember(rmm, contactExtField?.Influence__r?.Name, contactExtField?.Support__r?.Name)
                );
            }
            return matrixMemberList;
        }

        List<MatrixMember> resultForNonGlobal = new List<MatrixMember>();
        for (Relationship_Map_Member__c rmm : rmmList) {
            resultForNonGlobal.add(new MatrixMember(rmm));
        }
        return resultForNonGlobal;
    }
    public static MatrixMember upsertMapMember(Id memberId, String influence, String support) {
        if (memberId == null) {
            return null;
        }

        List<pq_Influence__c> influenceList = InfluenceSelector.newInstance()
            .selectByName(new Set<String>{ influence });
        List<pq_Support__c> supportList = SupportSelector.newInstance().selectByName(new Set<String>{ support });

        Id influenceId = null;
        Id supportId = null;

        String influenceName = '';
        String supportName = '';

        if (influenceList.size() > 0) {
            influenceId = influenceList[0].Id;
            influenceName = influenceList[0].Name;
        }
        if (supportList.size() > 0) {
            supportId = supportList[0].Id;
            supportName = supportList[0].Name;
        }

        Relationship_Map_Member__c mapMember = RelationshipMapMemberController.getMapMemberById(memberId);
        // GET SETTING, CHECK TO SEE IF LOCAL INFLUENCE SUPPORT OR GLOBAL
        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(
            mapMember.Relationship_Map__c
        );

        if (setting.Is_Influence_Support_Global_Scope__c) {
            ContactExtendedFieldService.updateInfluenceSupport(mapMember.Contact__c, influenceId, supportId);
            return new MatrixMember(mapMember, influenceName, supportName);
        } else {
            fflib_ISObjectUnitOfWork unitOfWork = Application.UnitOfWork.newInstance();

            RelationshipMapMembers mapMemberRecords = RelationshipMapMembers.newInstance(
                new List<Relationship_Map_Member__c>{ mapMember }
            );

            mapMemberRecords.updateField(Schema.Relationship_Map_Member__c.InfluenceId__c, influenceId, unitOfWork);
            mapMemberRecords.updateField(Schema.Relationship_Map_Member__c.SupportId__c, supportId, unitOfWork);

            unitOfWork.commitWork();

            Relationship_Map_Member__c result = RelationshipMapMemberController.getMapMemberById(memberId);
            return new MatrixMember(result);
        }
    }
    public static GraphData getUserGraphDataForHierarchyId(Id hierarchyId) {
        if (hierarchyId == null || hierarchyId.getSobjectType() != pqcrush__Relationship_Map__c.sObjectType) {
            return new GraphData();
        }

        // Get map instance
        List<Relationship_Map__c> maps = RelationshipMapSelector.newInstance().selectByIds(new Set<Id>{ hierarchyId });
        if (maps.size() == 0) {
            throw Application.createAuraHandledException(
                String.format(System.label.error_insufficient_access, new List<String>{ String.valueOf(hierarchyId) })
            );
        }
        RelationshipMapMemberController.setMapType(hierarchyId);

        // Convert any Leads (that were converted to contacts) to Map Members
        MapMemberLeadService.convertLeadsToMapMembers(hierarchyId);

        // GET ALL KeyStakeholders/MapMembers
        List<Relationship_Map_Member__c> members = RelationshipMapMemberSelector.newInstance()
            .selectByRelationshipMapIdsAndSelectFieldsWithYourContacts(
                new Set<Id>{ hierarchyId },
                RelationshipMapMemberController.mapMembersAndContactFields.get('members'),
                RelationshipMapMemberController.mapMembersAndContactFields.get('contacts')
            );

        // Wrap MapMembers into helper
        Set<String> contactIdSet = new Set<String>();
        List<RelationshipMapMemberWrapper> wrapperList = new List<RelationshipMapMemberWrapper>();
        for (Relationship_Map_Member__c member : members) {
            contactIdSet.add(member.Contact__c);
            RelationshipMapMemberWrapper wrapper = new RelationshipMapMemberWrapper(member);
            wrapperList.add(wrapper);
        }

        // Get Map Settings
        RM_Chart_Setting__C mapSetting = RMChartSettingService.getRelationshipMapSettingForObject(hierarchyId);
        List<pq_Influence_And_Support_Matrix__c> matrixes = RelationshipMapMemberController.getMatrixes(new Set<Id>{ hierarchyId });

        Map<String, String> infl = RelationshipMapMemberController.getMapInfluence(matrixes);
        Map<String, String> supp = RelationshipMapMemberController.getMapSupport(matrixes);

        // Get the KeyStakeholder nodes
        GraphData gd = GraphDataService.generateGraphData(
            wrapperList,
            mapSetting,
            infl,
            supp,
            RelationshipMapMemberController.mapMembersAndContactFields.get('contacts'),
            RelationshipMapMemberController.orgChartfields,
            hierarchyId
        );

        // Add in Placeholder nodes
        gd = GraphDataService.getAndInjectPlaceholderNodes(gd, hierarchyId);

        // Add in Map Member User nodes
        gd = MapMemberUserService.getAndInjectMapMemberUserNodes(gd, hierarchyId);

        // Add in Map Member Lead nodes
        gd = MapMemberLeadService.getAndInjectMapMemberLeadNodes(gd, hierarchyId, infl, supp);

        // Add in registered coordinates for ALL nodes
        gd = GraphDataService.getAndInjectNodeCoordinates(gd, hierarchyId);

        // Add in group links
        gd = GraphDataService.getAndInjectCustomLinks(gd, hierarchyId);

        // Add in badges
        gd = RMSvgService.injectBadges(hierarchyId, gd, mapSetting);

        // Add in local hierarchy links for contacts
        if (!mapSetting.Is_Reports_To_Global_Scope__c) {
            gd = GraphDataService.getAndInjectLocalHierarchyLinksForContacts(hierarchyId, gd, contactIdSet);
        }
        return gd;
    }

}