default/objects/Contact_Extended_Field__c/Contact_Extended_Field__c.object-meta.xml
<CustomObject>
    <label>Contact Extended Field</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contact Extended Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Extended Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Extended_Field__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Extended Fields</relationshipLabel>
    <relationshipName>Contact_Extended_Fields</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Extended_Field__c/fields/Influence__c.field-meta.xml
<CustomField>
    <fullName>Influence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Influence</label>
    <referenceTo>pq_Influence__c</referenceTo>
    <relationshipLabel>Contact Extended Fields</relationshipLabel>
    <relationshipName>Contact_Extended_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Extended_Field__c/fields/Support__c.field-meta.xml
<CustomField>
    <fullName>Support__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support</label>
    <referenceTo>pq_Support__c</referenceTo>
    <relationshipLabel>Contact Extended Fields</relationshipLabel>
    <relationshipName>Contact_Extended_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Contact_Relationship__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Key_Stakeholder__c/Key_Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Key Stakeholder</label>
    <nameField>
        <displayFormat>KS-{0000}</displayFormat>
        <label>Key Stakeholder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Key_Stakeholder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Key Stakeholders</relationshipLabel>
    <relationshipName>Key_Stakeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Key_Stakeholder__c/fields/Influence__c.field-meta.xml
<CustomField>
    <fullName>Influence__c</fullName>
    <label>Influence (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Key_Stakeholder_Influence</valueSetName>
    </valueSet>
</CustomField>

default/objects/Key_Stakeholder__c/fields/Support__c.field-meta.xml
<CustomField>
    <fullName>Support__c</fullName>
    <label>Support (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Key_Stakeholder_Support</valueSetName>
    </valueSet>
</CustomField>

default/objects/Map_Member_Placeholder_Relationship__c/Map_Member_Placeholder_Relationship__c.object-meta.xml
<CustomObject>
    <label>Map Member Placeholder Relationship</label>
    <nameField>
        <label>Map Member Placeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Member Placeholder Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_Placeholder_Relationship__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Map Member Placeholder Relationships</relationshipLabel>
    <relationshipName>Map_Member_Placeholder_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/pq_Influence__c/pq_Influence__c.object-meta.xml
<CustomObject>
    <label>Influence</label>
    <nameField>
        <label>Influence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Influence_And_Support_Matrix__c/pq_Influence_And_Support_Matrix__c.object-meta.xml
<CustomObject>
    <label>Influence And Support Matrix</label>
    <nameField>
        <label>Influence And Support Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influence And Support Matrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_Influence_And_Support_Matrix__c/fields/Influence_Label__c.field-meta.xml
<CustomField>
    <fullName>Influence_Label__c</fullName>
    <label>Influence Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/pq_Influence_And_Support_Matrix__c/fields/Support_Label__c.field-meta.xml
<CustomField>
    <fullName>Support_Label__c</fullName>
    <label>Support Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/pq_Support__c/pq_Support__c.object-meta.xml
<CustomObject>
    <label>Support</label>
    <nameField>
        <label>Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Map_Member__c/Relationship_Map_Member__c.object-meta.xml
<CustomObject>
    <label>Relationship Map Member</label>
    <nameField>
        <displayFormat>CHM-{0000}</displayFormat>
        <label>Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Map Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Relationship_Map_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationship Map Members</relationshipLabel>
    <relationshipName>Hierarchy_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/Influence__c.field-meta.xml
<CustomField>
    <fullName>Influence__c</fullName>
    <label>Influence (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Key_Stakeholder_Influence</valueSetName>
    </valueSet>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Relationship_Map_Member__c/fields/Support__c.field-meta.xml
<CustomField>
    <fullName>Support__c</fullName>
    <label>Support (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Key_Stakeholder_Support</valueSetName>
    </valueSet>
</CustomField>

default/objects/RM_Chart_Setting__c/RM_Chart_Setting__c.object-meta.xml
<CustomObject>
    <label>RM Chart Setting</label>
    <nameField>
        <displayFormat>RM-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Relationship Map Individual Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RM Chart Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/RM_Chart_Setting__c/fields/Is_Influence_Support_Global_Scope__c.field-meta.xml
<CustomField>
    <fullName>Is_Influence_Support_Global_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Global Influence and Support Values</label>
    <type>Checkbox</type>
</CustomField>

default/objects/RM_Chart_Setting__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>RM Chart Settings</relationshipLabel>
    <relationshipName>RM_Chart_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/OmniViewerController.cls
public with sharing class OmniViewerController {
    // ---------------------------------------------------

    @TestVisible
    private static Set<String> contactFields {
        get {
            if (contactFields != null) {
                return contactFields;
            }

            contactFields = new Set<String>();

            List<String> objectList = new List<String>{ Contact.sObjectType.getDescribe().getName() };
            List<Schema.DescribeSObjectResult> objectDescriptions = Schema.describeSObjects(objectList);

            for (Schema.DescribeSObjectResult obj : objectDescriptions) {
                Map<String, Schema.SObjectField> fieldMap = obj.fields.getMap();
                List<Schema.SObjectField> fieldValues = fieldMap.values();

                for (Schema.SObjectField field : fieldValues) {
                    // If field is a reference type and not a ref used for a cross-object query,
                    // then add relationship Name with dot notation to final field name (ex: "Account.Name")
                    Schema.DescribeFieldResult dfr = field.getDescribe();

                    if (!dfr.isAccessible()) {
                        continue;
                    }

                    String fieldName = dfr.getName();
                    List<Schema.sObjectType> refObjectList = dfr.getReferenceTo();

                    if (dfr.getRelationshipName() != null && refObjectList != new List<Schema.sObjectType>()) {
                        String refObject = String.valueOf(UtilityForList.first(refObjectList));
                        if (String.isBlank(refObject)) {
                            continue;
                        }
                        String nameField = UTIL_Describe.getNameField(refObject);
                        if (String.isBlank(nameField)) {
                            continue;
                        }
                        contactFields.add(fieldName + '.' + nameField);
                    } else {
                        contactFields.add(fieldName);
                    }
                }
            }

            return contactFields;
        }
        set;
    }

    // ---------------------------------------------------

    @TestVisible
    private static Map<String, Set<String>> mapMembersOmniViewerFields {
        get {
            if (mapMembersOmniViewerFields != null) {
                return mapMembersOmniViewerFields;
            }

            Set<String> keyStakeholderFields = new Set<String>();
            keyStakeholderFields.add('pqcrush__Relationship_Map__r.Name');

            mapMembersOmniViewerFields = new Map<String, Set<String>>();
            mapMembersOmniViewerFields.put('contacts', contactFields);
            mapMembersOmniViewerFields.put('members', keyStakeholderFields);

            return mapMembersOmniViewerFields;
        }
        set;
    }

    @TestVisible
    private static Map<String, Set<String>> keyStakeholderOmniViewerFields {
        get {
            if (keyStakeholderOmniViewerFields != null) {
                return keyStakeholderOmniViewerFields;
            }

            Set<String> keyStakeholderFields = new Set<String>();
            keyStakeholderFields.add('pqcrush__Account_Plan__r.Name');

            keyStakeholderOmniViewerFields = new Map<String, Set<String>>();
            keyStakeholderOmniViewerFields.put('contacts', contactFields);
            keyStakeholderOmniViewerFields.put('keystakeholders', keyStakeholderFields);

            return keyStakeholderOmniViewerFields;
        }
        set;
    }

    // ---------------------------------------------------

    @AuraEnabled
    public static Contact getContactById(Id contactId) {
        List<Contact> contacts = ContactSelector.newInstance()
            .selectByIdAndSelectFields(new Set<Id>{ contactId }, contactFields);

        if (contacts == null || contacts.isEmpty()) {
            return null;
        }

        return contacts.get(0);
    }

    @AuraEnabled
    public static Relationship_Map_Member__c getMapMemberByIdORContactId(Id objectId, Id mapId) {
        List<Relationship_Map_Member__c> members = RelationshipMapMemberSelector.newInstance()
            .selectByIdOrContactIdAndMapId(
                new Set<Id>{ objectId },
                mapId,
                mapMembersOmniViewerFields.get('members'),
                new Set<String>{ 'Id' }
            );

        if (members == null || members.isEmpty()) {
            return null;
        }

        return members.get(0);
    }

    @AuraEnabled
    public static Key_Stakeholder__c getKeyStakeholderByIdORContactId(Id objectId, Id planId) {
        List<Key_Stakeholder__c> keyStakeholders = KeyStakeholderSelector.newInstance()
            .selectByIdOrContactIdAndPlanId(
                new Set<Id>{ objectId },
                planId,
                keyStakeholderOmniViewerFields.get('keystakeholders'),
                new Set<String>{ 'Id' }
            );

        if (keyStakeholders == null || keyStakeholders.isEmpty()) {
            return null;
        }

        return keyStakeholders.get(0);
    }

    @AuraEnabled
    public static Map<Id, Contact_Extended_Field__c> getContactExtendedFields(Id contactId) {
        List<Contact_Extended_Field__c> extendedFields = ContactExtendedFieldSelector.newInstance()
            .selectByContactId(new Set<Id>{ contactId });

        Map<Id, Contact_Extended_Field__c> mapContactExtendedFields = new Map<Id, Contact_Extended_Field__c>();

        for (Contact_Extended_Field__c extendedField : extendedFields) {
            mapContactExtendedFields.put(extendedField.Contact__c, extendedField);
        }

        return mapContactExtendedFields;
    }

    @AuraEnabled
    public static MatrixMember getMatrixMemberById(Id memberId) {
        List<Relationship_Map_Member__c> members = RelationshipMapMemberSelector.newInstance()
            .selectById(new Set<Id>{ memberId });
        Relationship_Map_Member__c mapMember = (Relationship_Map_Member__c) UtilityForList.first(members);

        RM_Chart_Setting__c setting = RMChartSettingService.getRelationshipMapSettingForObject(
            mapMember.Relationship_Map__c
        );

        if (setting != null && !setting.Is_Influence_Support_Global_Scope__c) {
            return new MatrixMember(mapMember);
        }
        if (mapMember.Contact__c != null) {
        List<Contact_Extended_Field__c> contactExtFields = ContactExtendedFieldSelector.newInstance()
            .selectByContactId(new Set<Id>{ mapMember.Contact__c });

        if (contactExtFields.size() == 1) {
            Contact_Extended_Field__c contactExtField = contactExtFields[0];
            return new MatrixMember(
                mapMember,
                contactExtField.Influence__r != null ? contactExtField.Influence__r.Name : null,
                contactExtField.Support__r != null ? contactExtField.Support__r.Name : null
            );
        }
        }

        return new MatrixMember(mapMember, null, null);
    }

    @AuraEnabled
    public static List<MatrixMember> getMatrixMembersByContactId(Id contactId) {
        List<Relationship_Map_Member__c> members = new List<Relationship_Map_Member__c>();

        Map<Id, Id> memberIdxMapId = new Map<Id, Id>();

        if (Relationship_Map_Member__c.getSObjectType().getDescribe().isAccessible()) {
            members = RelationshipMapMemberSelector.newInstance().selectByContactId(new Set<Id>{ contactId });
        }

        List<MatrixMember> result = new List<MatrixMember>();

        Set<Id> mapOrAccountPlanIds = new Set<Id>();

        for (Relationship_Map_Member__c mem : members) {
            result.add(new MatrixMember(mem));
            mapOrAccountPlanIds.add(mem.Relationship_Map__c);
            memberIdxMapId.put(mem.Id, mem.Relationship_Map__c);
        }
        Map<Id, pq_Influence_And_Support_Matrix__c> matrixesForMap = new Map<Id, pq_Influence_And_Support_Matrix__c>();
        if (!memberIdxMapId.isEmpty()) {
            matrixesForMap = InfluenceSupportMatrixService.getMatrixesForRelationshipMap(
            new Set<Id>(memberIdxMapId.values())
            );
        }
        Map<Id, RM_Chart_Setting__c> settings = new Map<Id, RM_Chart_Setting__c>();
        if (!mapOrAccountPlanIds.isEmpty()) {
            settings = RMChartSettingService.getRelationshipMapSettingForObjects(mapOrAccountPlanIds);
        }

        for (MatrixMember m : result) {
            RM_Chart_Setting__c s = settings.get(m.containerId);
            if (s != null && s.Is_Influence_Support_Global_Scope__c) {
                m.isUsingGlobalInfluence = true;
            }
            pq_Influence_And_Support_Matrix__c matrix = matrixesForMap.get(m.containerId);
            if (matrix != null) {
                m.influenceLabel = String.isBlank(matrix?.Influence_Label__c)
                    ? Label.pqcrush.Influence
                    : matrix?.Influence_Label__c;
                m.supportLabel = String.isBlank(matrix?.Support_Label__c)
                    ? Label.pqcrush.Support
                    : matrix?.Support_Label__c;
            }
        }

        return result;
    }

    @AuraEnabled
    public static List<ReportStructureWrapper> getReportingStructureForContact(Id contactId) {
        List<ReportStructureWrapper> result = new List<ReportStructureWrapper>();

        // Query salesforce Reports To Data for Contact
        Contact thisContact = ContactSelector.newInstance()
            .selectByIdAndSelectFields(new Set<Id>{ contactId }, new Set<String>{ 'ReportsTo.Name' })
            .get(0);

        List<Contact> peopleTheyManage = ContactSelector.newInstance()
            .selectByReportsToId(new Set<Id>{ contactId }, new Set<String>());

        ReportStructureWrapper globalReportsToData = ReportStructureWrapper.convert(thisContact, peopleTheyManage);

        result.add(globalReportsToData);

        // Query Relationship Map Reports To Data
        List<Map_Member_Placeholder_Relationship__c> localReportsToLinks = MapMemberPlaceholderRelationshipSelector.newInstance()
            .selectHierarchyLinksByContactId(new Set<String>{ contactId });

        List<ReportStructureWrapper> localReportsToData = ReportStructureWrapper.convert(
            contactId,
            localReportsToLinks
        );
        result.addAll(localReportsToData);

        return result;
    }

    @AuraEnabled
    public static List<MapRelationshipLineContainer> getRelationshipsForContact(Id contactId) {
        List<Contact_Relationship__c> contactRels = ContactRelationshipSelector.newInstance()
            .selectActiveCustomRelsByToOrFrom(new Set<String>{ contactId });
        List<Map_Member_Placeholder_Relationship__c> customLinks = MapMemberPlaceholderRelationshipSelector.newInstance()
            .selectActiveCustomRelsByToOrFrom(new Set<String>{ contactId });
        List<MapRelationshipLineContainer> result = MapRelationshipLineContainer.convert(
            contactId,
            contactRels,
            customLinks
        );
        return result;
    }
    // ---------------------------------------------------
}