default/objects/WS_Data_Type__c/WS_Data_Type__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Data Type</label>
    <nameField>
        <displayFormat>WSDT-{0000}</displayFormat>
        <label>WS Data Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Data Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/WS_Data_Type_Association__c/WS_Data_Type_Association__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Data Type Association</label>
    <nameField>
        <displayFormat>WSDTA-{0000}</displayFormat>
        <label>Cross-Sell Data Type Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Data Type Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_Data_Type_Association__c/fields/WS_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>WS_Data_Type__c</fullName>
    <label>WS Data Type</label>
    <referenceTo>WS_Data_Type__c</referenceTo>
    <relationshipLabel>Cross-Sell Data Type Associations</relationshipLabel>
    <relationshipName>Cross_Sell_Data_Type_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/classes/WSDataTypeService.cls
public with sharing class WSDataTypeService {
    public static List<WS_Data_Type__c> getDataTypes(Id whiteSpaceId) {
        return service().getDataTypes(whiteSpaceId);
    }

    public static Id saveDataForCell(Id cellId, Id dataTypeId, String value) {
        return service().saveDataForCell(cellId, dataTypeId, value);
    }

    public static List<WS_Data_Type_Association__c> getDataTypeDataForCell(Id cellId) {
        return service().getDataTypeDataForCell(cellId);
    }

    /******************************
     *      PRIVATE METHODS
     ******************************/

    private static WSDataTypeServiceImpl service() {
        return (WSDataTypeServiceImpl) Application.Service.newInstance(WSDataTypeServiceImpl.class);
    }
}