default/objects/PQ_AP_Score__mdt/PQ_AP_Score__mdt.object-meta.xml
<CustomObject>
    <description>Settings used in the formulas used to calculate a score for an account plan</description>
    <label>Account Plan Score Settings</label>
    <pluralLabel>AP Score Settings</pluralLabel>
</CustomObject>

default/objects/PQ_AP_Score__mdt/fields/Category_Point_Total__c.field-meta.xml
<CustomField>
    <fullName>Category_Point_Total__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Category Point Total used in percent based component</description>
    <label>Category Point Total</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Count_BP_High__c.field-meta.xml
<CustomField>
    <fullName>Count_BP_High__c</fullName>
    <defaultValue>5</defaultValue>
    <description>The high breakpoint for the number of objects when calculating the score</description>
    <inlineHelpText>If the count is above this value it will have the high breakpoint score value for the score</inlineHelpText>
    <label>Count Breakpoint High</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Count_BP_Low__c.field-meta.xml
<CustomField>
    <fullName>Count_BP_Low__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The low breakpoint for the number of objects when calculating the score</description>
    <inlineHelpText>If the count is below this value it will have zero points for the score</inlineHelpText>
    <label>Count Breakpoint Low</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Count_BP_Mid__c.field-meta.xml
<CustomField>
    <fullName>Count_BP_Mid__c</fullName>
    <defaultValue>3</defaultValue>
    <description>The middle breakpoint for the number of objects when calculating the score</description>
    <inlineHelpText>If the count is below this value but above the low value the low breakpoint score will be used, if above this value but below the high value the mid breakpoint score will be used</inlineHelpText>
    <label>Count Breakpoint Mid</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Date_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Date_Field_API_Name__c</fullName>
    <description>The field on the account plan that holds the date value that is used for time decay of the score this metadata record represents</description>
    <inlineHelpText>If this field is not set or if &apos;Use Time Decay&apos; is not checked then time decay will not be used for the scoring of this object.  Time decay will also not work if the field entered is invalid or not a date or date time field on the Account Plan object.</inlineHelpText>
    <label>Date Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Score_BP_High__c.field-meta.xml
<CustomField>
    <fullName>Score_BP_High__c</fullName>
    <defaultValue>10</defaultValue>
    <description>The score used if the count is equal to or greater than the high breakpoint value</description>
    <label>Count Breakpoint Score High</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Score_BP_Low__c.field-meta.xml
<CustomField>
    <fullName>Score_BP_Low__c</fullName>
    <defaultValue>3</defaultValue>
    <description>The score used if the count is equal to the low breakpoint or between the low and mid breakpoint values</description>
    <label>Count Breakpoint Score Low</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Score_BP_Mid__c.field-meta.xml
<CustomField>
    <fullName>Score_BP_Mid__c</fullName>
    <defaultValue>5</defaultValue>
    <description>The score used if the count is equal to the middle breakpoint or between the middle and high breakpoint values</description>
    <label>Count Breakpoint Score Mid</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Score_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Score_Field_API_Name__c</fullName>
    <description>The field on the account plan that holds the score value that this metadata record represents</description>
    <inlineHelpText>This must be a field on the pqcrush__Account_Plan__c object and must be the API name.  Please make sure it&apos;s a valid API name for a field.</inlineHelpText>
    <label>Score Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Score_Label__c.field-meta.xml
<CustomField>
    <fullName>Score_Label__c</fullName>
    <description>The label to show in the individual score breakdown, see help text for additional info</description>
    <inlineHelpText>Please note - You can use this field to overwrite the label on packaged scores but it is recommended to edit the custom labels for those instead.  For admin created scores if this field is left blank it will instead display the metadata record name for the score</inlineHelpText>
    <label>Score Label</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Score_Object__c.field-meta.xml
<CustomField>
    <fullName>Score_Object__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, this objects score is included in the overall Account Plan Score</description>
    <label>Score Object</label>
    <type>Checkbox</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Threshold_Limit__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Limit__c</fullName>
    <defaultValue>10</defaultValue>
    <description>The threshold Limit used to set a value that sets a limit or boundary</description>
    <label>Threshold Limit</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_High__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_High__c</fullName>
    <defaultValue>90</defaultValue>
    <description>The number of days used for the upper time breakpoint since any records of this type have been modified</description>
    <inlineHelpText>This is the final breakpoint for time decayed scoring</inlineHelpText>
    <label>Time Breakpoint High</label>
    <precision>7</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_Low__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_Low__c</fullName>
    <defaultValue>7</defaultValue>
    <description>The number of days used for the lower time breakpoint since any records of this type have been modified</description>
    <inlineHelpText>This is the first breakpoint after 0 days</inlineHelpText>
    <label>Time Breakpoint Low</label>
    <precision>7</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_Mid__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_Mid__c</fullName>
    <defaultValue>30</defaultValue>
    <description>The number of days used for the middle time breakpoint since any records of this type have been modified</description>
    <inlineHelpText>This is the second breakpoint in days that time decay can hit</inlineHelpText>
    <label>Time Breakpoint Mid</label>
    <precision>7</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_Mult_High__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_Mult_High__c</fullName>
    <defaultValue>0.25</defaultValue>
    <description>The multiplier if the number of days since any record was updated is greater than or equal to the high time breakpoint</description>
    <inlineHelpText>This value should be between 0.00 and 1.00</inlineHelpText>
    <label>Time Breakpoint Multiplier High</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_Mult_Low__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_Mult_Low__c</fullName>
    <defaultValue>0.75</defaultValue>
    <description>The multiplier if the number of days since any record was updated is greater than or equal to the low time breakpoint but less than the middle time breakpoint</description>
    <inlineHelpText>This value should be between 0.00 and 1.00</inlineHelpText>
    <label>Time Breakpoint Multiplier Low</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Time_BP_Mult_Mid__c.field-meta.xml
<CustomField>
    <fullName>Time_BP_Mult_Mid__c</fullName>
    <defaultValue>0.50</defaultValue>
    <description>The multiplier if the number of days since any record was updated is greater than or equal to the Middle time breakpoint but less than the high time breakpoint</description>
    <inlineHelpText>This value should be between 0.00 and 1.00</inlineHelpText>
    <label>Time Breakpoint Multiplier Mid</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/PQ_AP_Score__mdt/fields/Use_Time_Decay__c.field-meta.xml
<CustomField>
    <fullName>Use_Time_Decay__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If set then score will decrease by a multiplier based on how long since any records were modified</description>
    <inlineHelpText>This is only available for packaged score objects</inlineHelpText>
    <label>Use Time Decay</label>
    <type>Checkbox</type>
</CustomField>

default/classes/HealthScoreMetadataSelector.cls
public with sharing class HealthScoreMetadataSelector extends fflib_SObjectSelector {
    public HealthScoreMetadataSelector() {
        super(false, true, false);
    }

    public static HealthScoreMetadataSelector newInstance() {
        return (HealthScoreMetadataSelector) Application.Selector.newInstance(PQ_AP_Score__mdt.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            PQ_AP_Score__mdt.Id,
            PQ_AP_Score__mdt.Count_BP_Low__c,
            PQ_AP_Score__mdt.Count_BP_Mid__c,
            PQ_AP_Score__mdt.Count_BP_High__c,
            PQ_AP_Score__mdt.Date_Field_API_Name__c,
            PQ_AP_Score__mdt.DeveloperName,
            PQ_AP_Score__mdt.Label,
            PQ_AP_Score__mdt.Score_Field_API_Name__c,
            PQ_AP_Score__mdt.Score_Label__c,
            PQ_AP_Score__mdt.Score_Object__c,
            PQ_AP_Score__mdt.Score_BP_Low__c,
            PQ_AP_Score__mdt.Score_BP_Mid__c,
            PQ_AP_Score__mdt.Score_BP_High__c,
            PQ_AP_Score__mdt.Time_BP_Low__c,
            PQ_AP_Score__mdt.Time_BP_Mid__c,
            PQ_AP_Score__mdt.Time_BP_High__c,
            PQ_AP_Score__mdt.Time_BP_Mult_Low__c,
            PQ_AP_Score__mdt.Time_BP_Mult_Mid__c,
            PQ_AP_Score__mdt.Time_BP_Mult_High__c,
            PQ_AP_Score__mdt.Threshold_Limit__c,
            PQ_AP_Score__mdt.Category_Point_Total__c,
            PQ_AP_Score__mdt.Use_Time_Decay__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return PQ_AP_Score__mdt.sObjectType;
    }

    public List<PQ_AP_Score__mdt> selectEnabled() {
        fflib_QueryFactory query = newQueryFactory().setCondition('Score_Object__c = true');
        return Database.query(query.toSOQL());
    }
}