default/objects/White_Space_Amount_Type__c/White_Space_Amount_Type__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Amount Type</label>
    <nameField>
        <label>Cross-Sell Amount Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Amount Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/White_Space_Amount_Type__c/fields/Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Abbreviation__c</fullName>
    <label>Abbreviation</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Amount_Type__c/fields/Color_RGB__c.field-meta.xml
<CustomField>
    <fullName>Color_RGB__c</fullName>
    <description>The color RGB value in the form of #RRGGBB</description>
    <inlineHelpText>The color RGB value in the form of #RRGGBB (Red Green Blue Values)</inlineHelpText>
    <label>Color RGB</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/White_Space_Amount_Type__c/fields/Display_Type__c.field-meta.xml
<CustomField>
    <fullName>Display_Type__c</fullName>
    <description>The way the data is displayed for this type</description>
    <label>Display Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Field_Types</valueSetName>
    </valueSet>
</CustomField>

default/objects/White_Space_Amount_Type__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Controls whether this record shows up in white space reports</description>
    <inlineHelpText>Active records will be displayed in associated white space reports. Inactive records will be hidden from associated white space reports.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

default/classes/WhiteSpaceAmountTypeSelector.cls
public with sharing class WhiteSpaceAmountTypeSelector extends fflib_SObjectSelector {
    public static WhiteSpaceAmountTypeSelector newInstance() {
        return (WhiteSpaceAmountTypeSelector) Application.Selector.newInstance(White_Space_Amount_Type__c.SObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            White_Space_Amount_Type__c.Id,
            White_Space_Amount_Type__c.Name,
            White_Space_Amount_Type__c.Abbreviation__c,
            White_Space_Amount_Type__c.Color_RGB__c,
            White_Space_Amount_Type__c.Order__c,
            White_Space_Amount_Type__c.Display_Type__c,
            White_Space_Amount_Type__c.IsActive__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return White_Space_Amount_Type__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<White_Space_Amount_Type__c> selectAll() {
        return Database.query(newQueryFactory().setCondition('IsActive__c = true').toSOQL());
    }

    public List<White_Space_Amount_Type__c> selectInactive() {
        return Database.query(newQueryFactory().setCondition('IsActive__c = false').toSOQL());
    }

    public List<White_Space_Amount_Type__c> selectById(Set<ID> idSet) {
        return Database.query(newQueryFactory().setCondition('id in :idSet and IsActive__c = true').toSOQL());
    }
}