default/objects/White_Space_Amount_Type__c/White_Space_Amount_Type__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Amount Type</label>
    <nameField>
        <label>Cross-Sell Amount Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross-Sell Amount Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/White_Space_Amount_Type_Association__c/White_Space_Amount_Type_Association__c.object-meta.xml
<CustomObject>
    <label>White Space Amount Type Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>White Space Amount Type Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>White Space Amount Type Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/White_Space_Amount_Type_Association__c/fields/White_Space_Amount_Type__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Amount_Type__c</fullName>
    <label>Cross-Sell Amount Type</label>
    <referenceTo>White_Space_Amount_Type__c</referenceTo>
    <relationshipLabel>White Space Amount Type Associations</relationshipLabel>
    <relationshipName>White_Space_Amount_Type_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/White_Space_Amount_Type_Association__c/fields/White_Space_Cell__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Cell__c</fullName>
    <label>White Space Cell</label>
    <referenceTo>White_Space_Cell__c</referenceTo>
    <relationshipLabel>White Space Amount Type Associations</relationshipLabel>
    <relationshipName>White_Space_Amount_Type_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/White_Space_Cell__c/White_Space_Cell__c.object-meta.xml
<CustomObject>
    <label>White Space Cell</label>
    <nameField>
        <label>White Space Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Space Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_Data_Type__c/WS_Data_Type__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Data Type</label>
    <nameField>
        <displayFormat>WSDT-{0000}</displayFormat>
        <label>WS Data Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Data Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/WhiteSpaceCellBuilderLegacy.cls
public with sharing class WhiteSpaceCellBuilderLegacy extends WhiteSpaceCellBuilderAbstract {
    public WhiteSpaceCellBuilderLegacy(
        List<WhiteSpaceCollectionWrapper> columns,
        List<WhiteSpaceCollectionWrapper> rows,
        List<White_Space_Cell__c> cells,
        List<White_Space_Amount_Type__c> amountTypes,
        List<WS_Data_Type__c> dataTypes,
        List<WhiteSpaceTemplateCellFieldWrapper> relatedFields,
        List<WSRelatedObjectWrapper> relatedObjects,
        Map<String, Map<String, List<SObject>>> fieldDataByRelatedIds
    ) {
        super(columns, rows, cells, amountTypes, dataTypes, relatedFields, relatedObjects, fieldDataByRelatedIds);
    }

    @testVisible
    protected override Map<String, List<WhiteSpaceTileWrapper>> populateDisplayTileMap() {
        Map<String, List<WhiteSpaceTileWrapper>> tilesByRowColumnIds = new Map<String, List<WhiteSpaceTileWrapper>>();
        for (String key : cellMap.keySet()) {
            List<White_Space_Cell__c> cells = cellMap.get(key);
            List<WhiteSpaceTileWrapper> tiles = new List<WhiteSpaceTileWrapper>();
            for (White_Space_Cell__c cell : cells) {
                WhiteSpaceTileWrapper newTile = WhiteSpaceTileWrapper.createFor(
                    cell,
                    this.amountTypes,
                    this.dataTypes,
                    this.fieldDataByRelatedIds.get(cell.id),
                    cell.White_Space_Amount_Type_Associations__r,
                    this.relatedFields,
                    this.relatedObjects
                );
                tiles.add(newTile);
            }
            tilesByRowColumnIds.put(key, tiles);
        }
        return tilesByRowColumnIds;
    }
}