default/objects/Map_Member_User__c/Map_Member_User__c.object-meta.xml
<CustomObject>
    <label>Map Member User</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Map Member User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Member Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Map_Member_User__c/fields/Relationship_Map__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Map</label>
    <referenceTo>Relationship_Map__c</referenceTo>
    <relationshipLabel>Map Member Users</relationshipLabel>
    <relationshipName>Map_Member_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Map_Member_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Map Member Users</relationshipLabel>
    <relationshipName>Map_Member_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/MapMemberUsers.cls
@SuppressWarnings('PMD.ApexDangerousMethods')
public with sharing class MapMemberUsers extends fflib_SObjectDomain {
    public MapMemberUsers(List<Map_Member_User__c> sObjectList) {
        super(sObjectList);
        this.Configuration.disableTriggerCRUDSecurity();
    }

    /******************************
     *       STATIC METHODS
     ******************************/

    public static MapMemberUsers newInstance(List<Map_Member_User__c> sObjectList) {
        return (MapMemberUsers) Application.Domain.newInstance(sObjectList);
    }

    public static String getUniqueKey(Map_Member_User__c member) {
        return String.valueOf(member.Relationship_Map__c) + String.valueOf(member.User__c);
    }

    /******************************
     *   TRIGGER HANDLER METHODS
     ******************************/

    public override void onValidate() {
        checkDuplicates();
    }

    public override void onValidate(Map<Id, SObject> existingRecords) {
        checkDuplicates();
    }

    /******************************
     *      PRIVATE METHODS
     ******************************/

    private void checkDuplicates() {
        for (
            Map_Member_User__c duplicateMember : MapMemberUserSelector.newInstance().selectDuplicatesAsSystem(Records)
        ) {
            duplicateMember.addError(System.Label.error_duplicate_hierarchy_member);
        }
    }

    /******************************
     *       INNER CLASSES
     ******************************/

    /**
     * This is a workaround for the lack of reflection in Apex.
     */
    public with sharing class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new MapMemberUsers(sObjectList);
        }
    }
}