default/objects/pq_CRUSH_User_Setting__c/pq_CRUSH_User_Setting__c.object-meta.xml
<CustomObject>
    <description>User Settings</description>
    <label>CRUSH User Setting</label>
    <nameField>
        <label>CRUSH User Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRUSH User Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_CRUSH_User_Setting__c/fields/Account_Plan_Sort__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Sort__c</fullName>
    <label>Account Plan Sort</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CreatedDate DESC</fullName>
                <default>true</default>
                <label>Created: Newest to Oldest</label>
            </value>
            <value>
                <fullName>CreatedDate ASC</fullName>
                <label>Created: Oldest to Newest</label>
            </value>
            <value>
                <fullName>Name ASC</fullName>
                <label>Name: Alphabetical</label>
            </value>
            <value>
                <fullName>Name DESC</fullName>
                <label>Name: Reverse Alphabetical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/pq_CRUSH_User_Setting__c/fields/Account_Plan_Task_Filter__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Task_Filter__c</fullName>
    <description>Save filters for account plans</description>
    <inlineHelpText>Save filters for account plans</inlineHelpText>
    <label>Account Plan Task Filter</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_CRUSH_User_Setting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CRUSH_User_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/CrushUserSettingServiceTest.cls
@isTest
private class CrushUserSettingServiceTest {
    @isTest
    static void getSettingTest1() {
        TestMockData md = new TestMockData();
        CrushUserSettingSelector mockCrushUserSettingSelector = md.mockCrushUserSettingSelector;

        md.mocks.startStubbing();
        md.mocks.when(mockCrushUserSettingSelector.selectForCurrentUser())
            .thenReturn(new List<pq_Crush_User_Setting__c>());
        md.mocks.stopStubbing();

        pq_Crush_User_Setting__c result = CrushUserSettingService.getSetting();
        System.assertNotEquals(null, result);
    }

    @isTest
    static void getSettingTest2() {
        TestMockData md = new TestMockData();
        CrushUserSettingSelector mockCrushUserSettingSelector = md.mockCrushUserSettingSelector;

        md.mocks.startStubbing();
        md.mocks.when(mockCrushUserSettingSelector.selectForCurrentUser())
            .thenReturn(
                new List<pq_Crush_User_Setting__c>{ new pq_Crush_User_Setting__c(User__c = UserInfo.getUserId()) }
            );
        md.mocks.stopStubbing();

        pq_Crush_User_Setting__c result = CrushUserSettingService.getSetting();
        System.assertNotEquals(null, result);
    }

    // Testing updating where setting doesn't exists
    @isTest
    static void updateTaskFilterTest1() {
        TestMockData md = new TestMockData();
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;
        CrushUserSettingSelector mockCrushUserSettingSelector = md.mockCrushUserSettingSelector;

        md.mocks.startStubbing();
        md.mocks.when(mockCrushUserSettingSelector.selectForCurrentUser())
            .thenReturn(new List<pq_Crush_User_Setting__c>());
        md.mocks.stopStubbing();

        String input = 'abc';

        CrushUserSettingService.updateTaskFilter(input);

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1))
            .registerNew(
                new pq_Crush_User_Setting__c(Account_Plan_Task_Filter__c = input, User__c = UserInfo.getUserId())
            );
        System.assert(true, 'Assert from mock verify');
    }

    // Testing updating where setting already exists
    @isTest
    static void updateTaskFilterTest2() {
        TestMockData md = new TestMockData();
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;
        CrushUserSettingSelector mockCrushUserSettingSelector = md.mockCrushUserSettingSelector;

        pq_Crush_User_Setting__c setting1 = new pq_Crush_User_Setting__c(
            Account_Plan_Task_Filter__c = 'abc1',
            User__c = UserInfo.getUserId()
        );
        pq_Crush_User_Setting__c setting2 = new pq_Crush_User_Setting__c(
            Account_Plan_Task_Filter__c = 'abc2',
            User__c = UserInfo.getUserId()
        );
        pq_Crush_User_Setting__c setting3 = new pq_Crush_User_Setting__c(
            Account_Plan_Task_Filter__c = 'abc3',
            User__c = UserInfo.getUserId()
        );

        List<pq_Crush_User_Setting__c> settingsList = new List<pq_Crush_User_Setting__c>{
            setting1,
            setting2,
            setting3
        };

        md.mocks.startStubbing();
        md.mocks.when(mockCrushUserSettingSelector.selectForCurrentUser()).thenReturn(settingsList);
        md.mocks.stopStubbing();

        String input = 'abc';

        CrushUserSettingService.updateTaskFilter(input);

        setting1.Account_Plan_Task_Filter__c = input;
        List<pq_Crush_User_Setting__c> settingsToDelete = new List<pq_Crush_User_Setting__c>{ setting2, setting3 };

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDirty(setting1);
        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDeleted(settingsToDelete);
        System.assert(true, 'Assert from mock verify');
    }

    @isTest
    static void updateAccountPlanSortTest1() {
        TestMockData md = new TestMockData();
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;
        CrushUserSettingSelector mockCrushUserSettingSelector = md.mockCrushUserSettingSelector;

        md.mocks.startStubbing();
        md.mocks.when(mockCrushUserSettingSelector.selectForCurrentUser())
            .thenReturn(new List<pq_Crush_User_Setting__c>());
        md.mocks.stopStubbing();

        String input = 'CreatedDate DESC';

        CrushUserSettingService.updateAccountPlanSort(input);

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1))
            .registerNew(
                new pq_Crush_User_Setting__c(Account_Plan_Sort__c = input, User__c = UserInfo.getUserId())
            );
        System.assert(true, 'Assert from mock verify');
    }

    @isTest
    static void updateAccountPlanSortTest2() {
        TestMockData md = new TestMockData();
        fflib_ISObjectUnitOfWork mockUow = md.mockUow;
        CrushUserSettingSelector mockCrushUserSettingSelector = md.mockCrushUserSettingSelector;

        pq_Crush_User_Setting__c setting1 = new pq_Crush_User_Setting__c(
            Account_Plan_Sort__c = 'CreatedDate DESC',
            User__c = UserInfo.getUserId()
        );
        pq_Crush_User_Setting__c setting2 = new pq_Crush_User_Setting__c(
            Account_Plan_Sort__c = 'CreatedDate ASC',
            User__c = UserInfo.getUserId()
        );
        pq_Crush_User_Setting__c setting3 = new pq_Crush_User_Setting__c(
            Account_Plan_Sort__c = 'Name ASC',
            User__c = UserInfo.getUserId()
        );

        List<pq_Crush_User_Setting__c> settingsList = new List<pq_Crush_User_Setting__c>{
            setting1,
            setting2,
            setting3
        };

        md.mocks.startStubbing();
        md.mocks.when(mockCrushUserSettingSelector.selectForCurrentUser()).thenReturn(settingsList);
        md.mocks.stopStubbing();

        String input = 'CreatedDate DESC';

        CrushUserSettingService.updateAccountPlanSort(input);

        setting1.Account_Plan_Task_Filter__c = input;
        List<pq_Crush_User_Setting__c> settingsToDelete = new List<pq_Crush_User_Setting__c>{ setting2, setting3 };

        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDirty(setting1);
        ((fflib_ISObjectUnitOfWork) md.mocks.verify(mockUow, 1)).registerDeleted(settingsToDelete);
        System.assert(true, 'Assert from mock verify');
    }
}