default/objects/pq_CRUSH_User_Setting__c/pq_CRUSH_User_Setting__c.object-meta.xml
<CustomObject>
    <description>User Settings</description>
    <label>CRUSH User Setting</label>
    <nameField>
        <label>CRUSH User Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRUSH User Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/pq_CRUSH_User_Setting__c/fields/Account_Plan_Task_Filter__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Task_Filter__c</fullName>
    <description>Save filters for account plans</description>
    <inlineHelpText>Save filters for account plans</inlineHelpText>
    <label>Account Plan Task Filter</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/pq_CRUSH_User_Setting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CRUSH_User_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/CrushUserSettingSelector.cls
public with sharing class CrushUserSettingSelector extends fflib_SObjectSelector {
    public static CrushUserSettingSelector newInstance() {
        return (CrushUserSettingSelector) Application.Selector.newInstance(pq_Crush_User_Setting__c.sObjectType);
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            pq_Crush_User_Setting__c.Id,
            pq_Crush_User_Setting__c.Name,
            pq_Crush_User_Setting__c.Account_Plan_Task_Filter__c,
            pq_Crush_User_Setting__c.pqcrush__Account_Plan_Sort__c,
            pq_Crush_User_Setting__c.pqcrush__Objective_Task_Sort_Ascending__c,
            pq_Crush_User_Setting__c.pqcrush__Objective_Task_Sort_Field__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return pq_Crush_User_Setting__c.sObjectType;
    }

    public override String getOrderBy() {
        return pq_Crush_User_Setting__c.LastModifiedDate.getDescribe().getName() + ' DESC';
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<pq_Crush_User_Setting__c> selectForCurrentUser() {
        Id userId = UserInfo.getUserId(); //NOPMD
        return Database.query(newQueryFactory().setCondition('User__c = :userId').toSOQL());
    }
}