default/objects/White_Space_Cell__c/White_Space_Cell__c.object-meta.xml
<CustomObject>
    <label>White Space Cell</label>
    <nameField>
        <label>White Space Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>White Space Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_Data_Type__c/WS_Data_Type__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Data Type</label>
    <nameField>
        <displayFormat>WSDT-{0000}</displayFormat>
        <label>WS Data Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Data Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/WS_Data_Type_Association__c/WS_Data_Type_Association__c.object-meta.xml
<CustomObject>
    <label>Cross-Sell Data Type Association</label>
    <nameField>
        <displayFormat>WSDTA-{0000}</displayFormat>
        <label>Cross-Sell Data Type Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross-Sell Data Type Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/WS_Data_Type_Association__c/fields/White_Space_Cell__c.field-meta.xml
<CustomField>
    <fullName>White_Space_Cell__c</fullName>
    <label>White Space Cell</label>
    <referenceTo>White_Space_Cell__c</referenceTo>
    <relationshipLabel>Cross-Sell Data Type Associations</relationshipLabel>
    <relationshipName>Cross_Sell_Data_Type_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/WS_Data_Type_Association__c/fields/WS_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>WS_Data_Type__c</fullName>
    <label>WS Data Type</label>
    <referenceTo>WS_Data_Type__c</referenceTo>
    <relationshipLabel>Cross-Sell Data Type Associations</relationshipLabel>
    <relationshipName>Cross_Sell_Data_Type_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/WS_Data_Type_Association__c/fields/WS_Data_Value__c.field-meta.xml
<CustomField>
    <fullName>WS_Data_Value__c</fullName>
    <label>WS Data Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/classes/WSDataTypeServiceImpl.cls
public with sharing class WSDataTypeServiceImpl {
    public List<WS_Data_Type__c> getDataTypes(Id whiteSpaceId) {
        return WSDataTypeSelector.newInstance().selectByWhiteSpaceId(whiteSpaceId);
    }

    public Id saveDataForCell(Id cellId, Id dataTypeId, String value) {
        List<WS_Data_Type_Association__c> associations = WSDataTypeAssociationSelector.newInstance()
            .selectByCellAndDataType(cellId, dataTypeId);

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        WS_Data_Type_Association__c assoc;

        if (associations != null && associations.size() > 0) {
            // Should only be 1
            assoc = associations[0];
            assoc.WS_Data_Value__c = value;
            uow.registerDirty(assoc);
        } else {
            assoc = new WS_Data_Type_Association__c(
                White_Space_Cell__c = cellId,
                WS_Data_Type__c = dataTypeId,
                WS_Data_Value__c = value
            );
            uow.registerNew(assoc);
        }
        uow.commitWork();
        return assoc.Id;
    }

    public List<WS_Data_Type_Association__c> getDataTypeDataForCell(Id cellId) {
        return WSDataTypeAssociationSelector.newInstance().selectByCellId(cellId);
    }
}