default/objects/Opportunity_List_User_Filter__c/Opportunity_List_User_Filter__c.object-meta.xml
<CustomObject>
    <description>Stores the filters for a User&apos;s opportunity list within an account plan</description>
    <label>Opportunity List User Filter</label>
    <nameField>
        <displayFormat>OLUF-{0000}</displayFormat>
        <label>Opportunity List User Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity List User Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Opportunity_List_User_Filter__c/fields/AccountPlan__c.field-meta.xml
<CustomField>
    <fullName>AccountPlan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Opportunity List User Filters</relationshipLabel>
    <relationshipName>Opportunity_List_User_Filters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

default/objects/Opportunity_List_User_Filter__c/fields/Filters__c.field-meta.xml
<CustomField>
    <fullName>Filters__c</fullName>
    <defaultValue>&quot;{}&quot;</defaultValue>
    <description>Stores filters as a json string</description>
    <label>Filters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Opportunity_List_User_Filter__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_List_User_Filters</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/OpportunityListUserFilterSelector.cls
public with sharing class OpportunityListUserFilterSelector extends fflib_SObjectSelector {
    public static OpportunityListUserFilterSelector newInstance() {
        return (OpportunityListUserFilterSelector) Application.Selector.newInstance(
            Opportunity_List_User_Filter__c.SObjectType
        );
    }

    /******************************
     *    QUERY CONFIGURATION
     ******************************/

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Opportunity_List_User_Filter__c.Id,
            Opportunity_List_User_Filter__c.User__c,
            Opportunity_List_User_Filter__c.AccountPlan__c,
            Opportunity_List_User_Filter__c.Filters__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Opportunity_List_User_Filter__c.sObjectType;
    }

    /******************************
     *        SELECT METHODS
     ******************************/

    public List<Opportunity_List_User_Filter__c> selectByAccountPlanAndUser(Id accountPlanId, Id userId) {
        fflib_QueryFactory query = newQueryFactory();
        return Database.query(query.setCondition('AccountPlan__c = :accountPlanId AND User__c = :userId').toSOQL());
    }
}