default/objects/PQ_Opportunity_Plan__c/PQ_Opportunity_Plan__c.object-meta.xml
<CustomObject>
    <label>Opportunity Plan</label>
    <nameField>
        <label>Opportunity Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/Relationship_Map__c.object-meta.xml
<CustomObject>
    <label>Relationship Map</label>
    <nameField>
        <label>Relationship Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Relationship_Map__c/fields/pq_Opportunity_Plan__c.field-meta.xml
<CustomField>
    <fullName>pq_Opportunity_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An optional relationship to an Opportunity Plan record</description>
    <label>Opportunity Plan</label>
    <referenceTo>PQ_Opportunity_Plan__c</referenceTo>
    <relationshipLabel>Relationship Maps</relationshipLabel>
    <relationshipName>Relationship_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/OpportunityPlanService.cls
public with sharing class OpportunityPlanService {
    public static Query getQueryForOpportunitiesWithoutPlans() {
        return service().getQueryForOpportunitiesWithoutPlans();
    }

    public static List<PQ_Opportunity_Plan__c> createOpportunityPlans(List<Opportunity> opportunities) {
        return service().createOpportunityPlans(opportunities);
    }

    public static List<Relationship_Map__c> getRelationshipMapsForOppPlanId(Id oppPlanId, Boolean createIfNeeded) {
        return service().getRelationshipMapsForOppPlanId(oppPlanId, createIfNeeded);
    }

    public static Relationship_Map__c createRelationshipMapForOppPlanId(Id oppPlanId) {
        return service().createRelationshipMapForOppPlanId(oppPlanId);
    }

    public static Id getAccountIdForOppPlanId(Id oppPlanId) {
        return service().getAccountIdForOppPlanId(oppPlanId);
    }

    public static Boolean hasOpportunityPlanSetting(Id mapId) {
        return service().hasOpportunityPlanSetting(mapId);
    }

    private static OpportunityPlanServiceImpl service() {
        return (OpportunityPlanServiceImpl) Application.Service.newInstance(OpportunityPlanServiceImpl.class);
    }
}