default/objects/Key_Stakeholder__c/Key_Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Key Stakeholder</label>
    <nameField>
        <displayFormat>KS-{0000}</displayFormat>
        <label>Key Stakeholder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Org_Chart_Field__c/Org_Chart_Field__c.object-meta.xml
<CustomObject>
    <description>Defines a field to display in an Account Plan org chart</description>
    <label>Org Chart Field</label>
    <nameField>
        <label>Org Chart Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Chart Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Org_Chart_Field__c/fields/FieldLabel__c.field-meta.xml
<CustomField>
    <fullName>FieldLabel__c</fullName>
    <label>Field Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <description>Name of the related field</description>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/IsMain__c.field-meta.xml
<CustomField>
    <fullName>IsMain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if you want the field to show up in the main section of the card.  Otherwise, it will show up in the secondary area, that is hidden until users open the card</description>
    <label>IsMain</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/isRequired__c.field-meta.xml
<CustomField>
    <fullName>isRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether the related field can is allowed to be removed from the org chart display</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/isVisible__c.field-meta.xml
<CustomField>
    <fullName>isVisible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether the related field is visible in the org chart user interface</description>
    <label>Visible</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Org_Chart_Field__c/fields/Map_Type__c.field-meta.xml
<CustomField>
    <fullName>Map_Type__c</fullName>
    <label>Map Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Map_Type</valueSetName>
    </valueSet>
</CustomField>

default/objects/Org_Chart_Field__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>Name of the related object</description>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/OrgChartFieldWrapperTest.cls
@isTest
private class OrgChartFieldWrapperTest {
    @isTest
    static void newInstanceTest() {
        // Given
        Org_Chart_Field__c ocf = new Org_Chart_Field__c(
            Id = fflib_IDGenerator.generate(Org_Chart_Field__c.SObjectType),
            Name = 'name',
            ObjectName__c = 'Contact',
            FieldName__c = 'Title',
            FieldLabel__c = 'P Title',
            isRequired__c = true,
            isVisible__c = true,
            Map_Type__c = 'Relationship Map',
            IsMain__c = false
        );

        OrgChartFieldWrapper wrapper = new OrgChartFieldWrapper(ocf);

        // Then
        system.assertEquals(ocf.Id, wrapper.id);
        system.assertEquals(ocf.Name, wrapper.name);
        system.assertEquals(ocf.ObjectName__c, wrapper.objectName);
        system.assertEquals(ocf.FieldName__c, wrapper.fieldName);
        system.assertEquals(ocf.FieldLabel__c, wrapper.fieldLabel);
        system.assertEquals(ocf.isRequired__c, wrapper.isRequired);
        system.assertEquals(ocf.isVisible__c, wrapper.isVisible);
        system.assertEquals(ocf.Map_Type__c, wrapper.mapType);
        system.assertEquals(true, wrapper.isMain);
        system.assertEquals(false, wrapper.isEditable);
    }

    @isTest
    static void newInstanceTest2() {
        // Given
        Org_Chart_Field__c ocf = new Org_Chart_Field__c(
            Id = fflib_IDGenerator.generate(Org_Chart_Field__c.SObjectType),
            Name = 'name',
            ObjectName__c = 'Key_Stakeholder__c',
            FieldName__c = 'pqcrush__Influence__c',
            FieldLabel__c = 'Influence',
            isRequired__c = true,
            isVisible__c = true,
            Map_Type__c = 'Relationship Map',
            IsMain__c = false
        );

        OrgChartFieldWrapper wrapper = new OrgChartFieldWrapper(ocf);

        // Then
        system.assertEquals(ocf.Id, wrapper.id);
        system.assertEquals(ocf.Name, wrapper.name);
        system.assertEquals(ocf.ObjectName__c, wrapper.objectName);
        system.assertEquals(ocf.FieldName__c, wrapper.fieldName);
        system.assertEquals(ocf.FieldLabel__c, wrapper.fieldLabel);
        system.assertEquals(ocf.isRequired__c, wrapper.isRequired);
        system.assertEquals(ocf.isVisible__c, wrapper.isVisible);
        system.assertEquals(ocf.Map_Type__c, wrapper.mapType);
        system.assertEquals(true, wrapper.isMain);
        system.assertEquals(false, wrapper.isEditable);
    }

    @isTest
    static void toSObjectTest() {
        // Given
        Org_Chart_Field__c ocf = new Org_Chart_Field__c(
            Id = fflib_IDGenerator.generate(Org_Chart_Field__c.SObjectType),
            Name = 'name',
            ObjectName__c = 'Key_Stakeholder__c',
            FieldName__c = 'pqcrush__Influence__c',
            FieldLabel__c = 'Influence',
            isRequired__c = true,
            isVisible__c = true,
            Map_Type__c = 'Relationship Map',
            IsMain__c = false
        );

        OrgChartFieldWrapper wrapper = new OrgChartFieldWrapper(ocf);
        Org_Chart_Field__c result = wrapper.toSObject();

        // Then
        system.assertEquals(ocf.Id, result.Id);
        system.assertEquals(ocf.Name, result.Name);
        system.assertEquals(ocf.ObjectName__c, result.ObjectName__c);
        system.assertEquals(ocf.FieldName__c, result.FieldName__c);
        system.assertEquals(ocf.FieldLabel__c, result.FieldLabel__c);
        system.assertEquals(ocf.isRequired__c, result.isRequired__c);
        system.assertEquals(ocf.isVisible__c, result.isVisible__c);
        system.assertEquals(ocf.Map_Type__c, result.Map_Type__c);
    }

    @isTest
    static void toSObjectListTest() {
        // Given
        List<OrgChartFieldWrapper> wrapperList = new List<OrgChartFieldWrapper>();
        List<Org_Chart_Field__c> result = OrgChartFieldWrapper.toSObjectList(wrapperList);

        // Then
        system.assertEquals(0, result.size());
    }

    @isTest
    static void toSObjectListTest2() {
        // Given
        Org_Chart_Field__c ocf = new Org_Chart_Field__c(
            Id = fflib_IDGenerator.generate(Org_Chart_Field__c.SObjectType),
            Name = 'name',
            ObjectName__c = 'Key_Stakeholder__c',
            FieldName__c = 'pqcrush__Influence__c',
            FieldLabel__c = 'Influence',
            isRequired__c = true,
            isVisible__c = true,
            Map_Type__c = 'Relationship Map',
            IsMain__c = false
        );

        OrgChartFieldWrapper wrapper = new OrgChartFieldWrapper(ocf);
        List<OrgChartFieldWrapper> wrapperList = new List<OrgChartFieldWrapper>{ wrapper };
        List<Org_Chart_Field__c> result = OrgChartFieldWrapper.toSObjectList(wrapperList);

        // Then
        system.assertEquals(1, result.size());
    }
}